// File generated from our OpenAPI spec by Stainless.

package com.hubspot.models.marketing.emails

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.hubspot.core.JsonValue
import com.hubspot.core.jsonMapper
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class PublicEmailStyleSettingsTest {

    @Test
    fun create() {
        val publicEmailStyleSettings =
            PublicEmailStyleSettings.builder()
                .backgroundColor("backgroundColor")
                .backgroundImage("backgroundImage")
                .backgroundImageType(PublicEmailStyleSettings.BackgroundImageType.REPEAT)
                .bodyBorderColor("bodyBorderColor")
                .bodyBorderColorChoice("bodyBorderColorChoice")
                .bodyBorderWidth(0.0)
                .bodyColor("bodyColor")
                .buttonStyleSettings(
                    PublicButtonStyleSettings.builder()
                        .backgroundColor(JsonValue.from(mapOf<String, Any>()))
                        .cornerRadius(0)
                        .fontStyle(
                            PublicFontStyle.builder()
                                .bold(true)
                                .color("color")
                                .font("font")
                                .italic(true)
                                .size(0)
                                .underline(true)
                                .build()
                        )
                        .build()
                )
                .colorPickerFavorite1("colorPickerFavorite1")
                .colorPickerFavorite2("colorPickerFavorite2")
                .colorPickerFavorite3("colorPickerFavorite3")
                .colorPickerFavorite4("colorPickerFavorite4")
                .colorPickerFavorite5("colorPickerFavorite5")
                .colorPickerFavorite6("colorPickerFavorite6")
                .dividerStyleSettings(
                    PublicDividerStyleSettings.builder()
                        .color(JsonValue.from(mapOf<String, Any>()))
                        .height(0)
                        .lineType("lineType")
                        .build()
                )
                .emailBodyPadding("emailBodyPadding")
                .emailBodyWidth("emailBodyWidth")
                .headingOneFont(
                    PublicFontStyle.builder()
                        .bold(true)
                        .color("color")
                        .font("font")
                        .italic(true)
                        .size(0)
                        .underline(true)
                        .build()
                )
                .headingTwoFont(
                    PublicFontStyle.builder()
                        .bold(true)
                        .color("color")
                        .font("font")
                        .italic(true)
                        .size(0)
                        .underline(true)
                        .build()
                )
                .linksFont(
                    PublicFontStyle.builder()
                        .bold(true)
                        .color("color")
                        .font("font")
                        .italic(true)
                        .size(0)
                        .underline(true)
                        .build()
                )
                .primaryAccentColor("primaryAccentColor")
                .primaryFont("primaryFont")
                .primaryFontColor("primaryFontColor")
                .primaryFontLineHeight("primaryFontLineHeight")
                .primaryFontSize(0.0)
                .secondaryAccentColor("secondaryAccentColor")
                .secondaryFont("secondaryFont")
                .secondaryFontColor("secondaryFontColor")
                .secondaryFontLineHeight("secondaryFontLineHeight")
                .secondaryFontSize(0.0)
                .build()

        assertThat(publicEmailStyleSettings.backgroundColor()).contains("backgroundColor")
        assertThat(publicEmailStyleSettings.backgroundImage()).contains("backgroundImage")
        assertThat(publicEmailStyleSettings.backgroundImageType())
            .contains(PublicEmailStyleSettings.BackgroundImageType.REPEAT)
        assertThat(publicEmailStyleSettings.bodyBorderColor()).contains("bodyBorderColor")
        assertThat(publicEmailStyleSettings.bodyBorderColorChoice())
            .contains("bodyBorderColorChoice")
        assertThat(publicEmailStyleSettings.bodyBorderWidth()).contains(0.0)
        assertThat(publicEmailStyleSettings.bodyColor()).contains("bodyColor")
        assertThat(publicEmailStyleSettings.buttonStyleSettings())
            .contains(
                PublicButtonStyleSettings.builder()
                    .backgroundColor(JsonValue.from(mapOf<String, Any>()))
                    .cornerRadius(0)
                    .fontStyle(
                        PublicFontStyle.builder()
                            .bold(true)
                            .color("color")
                            .font("font")
                            .italic(true)
                            .size(0)
                            .underline(true)
                            .build()
                    )
                    .build()
            )
        assertThat(publicEmailStyleSettings.colorPickerFavorite1()).contains("colorPickerFavorite1")
        assertThat(publicEmailStyleSettings.colorPickerFavorite2()).contains("colorPickerFavorite2")
        assertThat(publicEmailStyleSettings.colorPickerFavorite3()).contains("colorPickerFavorite3")
        assertThat(publicEmailStyleSettings.colorPickerFavorite4()).contains("colorPickerFavorite4")
        assertThat(publicEmailStyleSettings.colorPickerFavorite5()).contains("colorPickerFavorite5")
        assertThat(publicEmailStyleSettings.colorPickerFavorite6()).contains("colorPickerFavorite6")
        assertThat(publicEmailStyleSettings.dividerStyleSettings())
            .contains(
                PublicDividerStyleSettings.builder()
                    .color(JsonValue.from(mapOf<String, Any>()))
                    .height(0)
                    .lineType("lineType")
                    .build()
            )
        assertThat(publicEmailStyleSettings.emailBodyPadding()).contains("emailBodyPadding")
        assertThat(publicEmailStyleSettings.emailBodyWidth()).contains("emailBodyWidth")
        assertThat(publicEmailStyleSettings.headingOneFont())
            .contains(
                PublicFontStyle.builder()
                    .bold(true)
                    .color("color")
                    .font("font")
                    .italic(true)
                    .size(0)
                    .underline(true)
                    .build()
            )
        assertThat(publicEmailStyleSettings.headingTwoFont())
            .contains(
                PublicFontStyle.builder()
                    .bold(true)
                    .color("color")
                    .font("font")
                    .italic(true)
                    .size(0)
                    .underline(true)
                    .build()
            )
        assertThat(publicEmailStyleSettings.linksFont())
            .contains(
                PublicFontStyle.builder()
                    .bold(true)
                    .color("color")
                    .font("font")
                    .italic(true)
                    .size(0)
                    .underline(true)
                    .build()
            )
        assertThat(publicEmailStyleSettings.primaryAccentColor()).contains("primaryAccentColor")
        assertThat(publicEmailStyleSettings.primaryFont()).contains("primaryFont")
        assertThat(publicEmailStyleSettings.primaryFontColor()).contains("primaryFontColor")
        assertThat(publicEmailStyleSettings.primaryFontLineHeight())
            .contains("primaryFontLineHeight")
        assertThat(publicEmailStyleSettings.primaryFontSize()).contains(0.0)
        assertThat(publicEmailStyleSettings.secondaryAccentColor()).contains("secondaryAccentColor")
        assertThat(publicEmailStyleSettings.secondaryFont()).contains("secondaryFont")
        assertThat(publicEmailStyleSettings.secondaryFontColor()).contains("secondaryFontColor")
        assertThat(publicEmailStyleSettings.secondaryFontLineHeight())
            .contains("secondaryFontLineHeight")
        assertThat(publicEmailStyleSettings.secondaryFontSize()).contains(0.0)
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val publicEmailStyleSettings =
            PublicEmailStyleSettings.builder()
                .backgroundColor("backgroundColor")
                .backgroundImage("backgroundImage")
                .backgroundImageType(PublicEmailStyleSettings.BackgroundImageType.REPEAT)
                .bodyBorderColor("bodyBorderColor")
                .bodyBorderColorChoice("bodyBorderColorChoice")
                .bodyBorderWidth(0.0)
                .bodyColor("bodyColor")
                .buttonStyleSettings(
                    PublicButtonStyleSettings.builder()
                        .backgroundColor(JsonValue.from(mapOf<String, Any>()))
                        .cornerRadius(0)
                        .fontStyle(
                            PublicFontStyle.builder()
                                .bold(true)
                                .color("color")
                                .font("font")
                                .italic(true)
                                .size(0)
                                .underline(true)
                                .build()
                        )
                        .build()
                )
                .colorPickerFavorite1("colorPickerFavorite1")
                .colorPickerFavorite2("colorPickerFavorite2")
                .colorPickerFavorite3("colorPickerFavorite3")
                .colorPickerFavorite4("colorPickerFavorite4")
                .colorPickerFavorite5("colorPickerFavorite5")
                .colorPickerFavorite6("colorPickerFavorite6")
                .dividerStyleSettings(
                    PublicDividerStyleSettings.builder()
                        .color(JsonValue.from(mapOf<String, Any>()))
                        .height(0)
                        .lineType("lineType")
                        .build()
                )
                .emailBodyPadding("emailBodyPadding")
                .emailBodyWidth("emailBodyWidth")
                .headingOneFont(
                    PublicFontStyle.builder()
                        .bold(true)
                        .color("color")
                        .font("font")
                        .italic(true)
                        .size(0)
                        .underline(true)
                        .build()
                )
                .headingTwoFont(
                    PublicFontStyle.builder()
                        .bold(true)
                        .color("color")
                        .font("font")
                        .italic(true)
                        .size(0)
                        .underline(true)
                        .build()
                )
                .linksFont(
                    PublicFontStyle.builder()
                        .bold(true)
                        .color("color")
                        .font("font")
                        .italic(true)
                        .size(0)
                        .underline(true)
                        .build()
                )
                .primaryAccentColor("primaryAccentColor")
                .primaryFont("primaryFont")
                .primaryFontColor("primaryFontColor")
                .primaryFontLineHeight("primaryFontLineHeight")
                .primaryFontSize(0.0)
                .secondaryAccentColor("secondaryAccentColor")
                .secondaryFont("secondaryFont")
                .secondaryFontColor("secondaryFontColor")
                .secondaryFontLineHeight("secondaryFontLineHeight")
                .secondaryFontSize(0.0)
                .build()

        val roundtrippedPublicEmailStyleSettings =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(publicEmailStyleSettings),
                jacksonTypeRef<PublicEmailStyleSettings>(),
            )

        assertThat(roundtrippedPublicEmailStyleSettings).isEqualTo(publicEmailStyleSettings)
    }
}
