// File generated from our OpenAPI spec by Stainless.

package com.hubspot_sdk.api.models.cms.mediabridge

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.hubspot_sdk.api.core.jsonMapper
import com.hubspot_sdk.api.models.Option
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class PropertyTest {

    @Test
    fun create() {
        val property =
            Property.builder()
                .addAllowedObjectType(ObjectTypeIdProto.builder().innerId(0).metaTypeId(0).build())
                .calculated(true)
                .canArchive(true)
                .canRestore(true)
                .createdAt(0L)
                .createdUserId(0L)
                .currencyPropertyName("currencyPropertyName")
                .dataSensitivity(Property.DataSensitivity.HIGH)
                .dateDisplayHint(Property.DateDisplayHint.ABSOLUTE)
                .deleted(true)
                .description("description")
                .displayMode(Property.DisplayMode.ALL_UNIQUE_VERSIONS)
                .displayOrder(0)
                .enforceMultivalueUniqueness(true)
                .externalOptions(true)
                .externalOptionsReferenceType("externalOptionsReferenceType")
                .favorited(true)
                .favoritedOrder(0)
                .fieldType("fieldType")
                .formField(true)
                .fromUserId(0L)
                .groupName("groupName")
                .hasUniqueValue(true)
                .hidden(true)
                .hubspotDefined(true)
                .isCustomizedDefault(true)
                .isMultiValued(true)
                .isPartial(true)
                .label("label")
                .mutableDefinitionNotDeletable(true)
                .name("name")
                .numberDisplayHint(Property.NumberDisplayHint.CURRENCY)
                .addOption(
                    Option.builder()
                        .hidden(false)
                        .label("Option A")
                        .value("A")
                        .description("Choice number one")
                        .displayOrder(1)
                        .build()
                )
                .optionsAreMutable(true)
                .optionSortStrategy(Property.OptionSortStrategy.ALPHABETICAL)
                .owningAppId(0L)
                .portalId(0L)
                .readOnlyDefinition(true)
                .readOnlyValue(true)
                .referencedObjectType(Property.ReferencedObjectType.ABANDONED_CART)
                .searchableInGlobalSearch(true)
                .searchTextAnalysisMode(Property.SearchTextAnalysisMode.NONE)
                .addSensitiveDataCategory("string")
                .showCurrencySymbol(true)
                .textDisplayHint(Property.TextDisplayHint.DOMAIN_NAME)
                .type(Property.Type.BOOL)
                .updatedAt(0L)
                .build()

        assertThat(property.allowedObjectTypes())
            .containsExactly(ObjectTypeIdProto.builder().innerId(0).metaTypeId(0).build())
        assertThat(property.calculated()).isEqualTo(true)
        assertThat(property.canArchive()).isEqualTo(true)
        assertThat(property.canRestore()).isEqualTo(true)
        assertThat(property.createdAt()).isEqualTo(0L)
        assertThat(property.createdUserId()).isEqualTo(0L)
        assertThat(property.currencyPropertyName()).isEqualTo("currencyPropertyName")
        assertThat(property.dataSensitivity()).isEqualTo(Property.DataSensitivity.HIGH)
        assertThat(property.dateDisplayHint()).isEqualTo(Property.DateDisplayHint.ABSOLUTE)
        assertThat(property.deleted()).isEqualTo(true)
        assertThat(property.description()).isEqualTo("description")
        assertThat(property.displayMode()).isEqualTo(Property.DisplayMode.ALL_UNIQUE_VERSIONS)
        assertThat(property.displayOrder()).isEqualTo(0)
        assertThat(property.enforceMultivalueUniqueness()).isEqualTo(true)
        assertThat(property.externalOptions()).isEqualTo(true)
        assertThat(property.externalOptionsReferenceType())
            .isEqualTo("externalOptionsReferenceType")
        assertThat(property.favorited()).isEqualTo(true)
        assertThat(property.favoritedOrder()).isEqualTo(0)
        assertThat(property.fieldType()).isEqualTo("fieldType")
        assertThat(property.formField()).isEqualTo(true)
        assertThat(property.fromUserId()).isEqualTo(0L)
        assertThat(property.groupName()).isEqualTo("groupName")
        assertThat(property.hasUniqueValue()).isEqualTo(true)
        assertThat(property.hidden()).isEqualTo(true)
        assertThat(property.hubspotDefined()).isEqualTo(true)
        assertThat(property.isCustomizedDefault()).isEqualTo(true)
        assertThat(property.isMultiValued()).isEqualTo(true)
        assertThat(property.isPartial()).isEqualTo(true)
        assertThat(property.label()).isEqualTo("label")
        assertThat(property.mutableDefinitionNotDeletable()).isEqualTo(true)
        assertThat(property.name()).isEqualTo("name")
        assertThat(property.numberDisplayHint()).isEqualTo(Property.NumberDisplayHint.CURRENCY)
        assertThat(property.options())
            .containsExactly(
                Option.builder()
                    .hidden(false)
                    .label("Option A")
                    .value("A")
                    .description("Choice number one")
                    .displayOrder(1)
                    .build()
            )
        assertThat(property.optionsAreMutable()).isEqualTo(true)
        assertThat(property.optionSortStrategy())
            .isEqualTo(Property.OptionSortStrategy.ALPHABETICAL)
        assertThat(property.owningAppId()).isEqualTo(0L)
        assertThat(property.portalId()).isEqualTo(0L)
        assertThat(property.readOnlyDefinition()).isEqualTo(true)
        assertThat(property.readOnlyValue()).isEqualTo(true)
        assertThat(property.referencedObjectType())
            .isEqualTo(Property.ReferencedObjectType.ABANDONED_CART)
        assertThat(property.searchableInGlobalSearch()).isEqualTo(true)
        assertThat(property.searchTextAnalysisMode())
            .isEqualTo(Property.SearchTextAnalysisMode.NONE)
        assertThat(property.sensitiveDataCategories()).containsExactly("string")
        assertThat(property.showCurrencySymbol()).isEqualTo(true)
        assertThat(property.textDisplayHint()).isEqualTo(Property.TextDisplayHint.DOMAIN_NAME)
        assertThat(property.type()).isEqualTo(Property.Type.BOOL)
        assertThat(property.updatedAt()).isEqualTo(0L)
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val property =
            Property.builder()
                .addAllowedObjectType(ObjectTypeIdProto.builder().innerId(0).metaTypeId(0).build())
                .calculated(true)
                .canArchive(true)
                .canRestore(true)
                .createdAt(0L)
                .createdUserId(0L)
                .currencyPropertyName("currencyPropertyName")
                .dataSensitivity(Property.DataSensitivity.HIGH)
                .dateDisplayHint(Property.DateDisplayHint.ABSOLUTE)
                .deleted(true)
                .description("description")
                .displayMode(Property.DisplayMode.ALL_UNIQUE_VERSIONS)
                .displayOrder(0)
                .enforceMultivalueUniqueness(true)
                .externalOptions(true)
                .externalOptionsReferenceType("externalOptionsReferenceType")
                .favorited(true)
                .favoritedOrder(0)
                .fieldType("fieldType")
                .formField(true)
                .fromUserId(0L)
                .groupName("groupName")
                .hasUniqueValue(true)
                .hidden(true)
                .hubspotDefined(true)
                .isCustomizedDefault(true)
                .isMultiValued(true)
                .isPartial(true)
                .label("label")
                .mutableDefinitionNotDeletable(true)
                .name("name")
                .numberDisplayHint(Property.NumberDisplayHint.CURRENCY)
                .addOption(
                    Option.builder()
                        .hidden(false)
                        .label("Option A")
                        .value("A")
                        .description("Choice number one")
                        .displayOrder(1)
                        .build()
                )
                .optionsAreMutable(true)
                .optionSortStrategy(Property.OptionSortStrategy.ALPHABETICAL)
                .owningAppId(0L)
                .portalId(0L)
                .readOnlyDefinition(true)
                .readOnlyValue(true)
                .referencedObjectType(Property.ReferencedObjectType.ABANDONED_CART)
                .searchableInGlobalSearch(true)
                .searchTextAnalysisMode(Property.SearchTextAnalysisMode.NONE)
                .addSensitiveDataCategory("string")
                .showCurrencySymbol(true)
                .textDisplayHint(Property.TextDisplayHint.DOMAIN_NAME)
                .type(Property.Type.BOOL)
                .updatedAt(0L)
                .build()

        val roundtrippedProperty =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(property),
                jacksonTypeRef<Property>(),
            )

        assertThat(roundtrippedProperty).isEqualTo(property)
    }
}
