// File generated from our OpenAPI spec by Stainless.

package com.hubspot_sdk.api.models.cms.mediabridge

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.hubspot_sdk.api.core.jsonMapper
import com.hubspot_sdk.api.models.Option
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class PropertyTest {

    @Test
    fun create() {
        val property =
            Property.builder()
                .addAllowedObjectType(ObjectTypeIdProto.builder().innerId(0).metaTypeId(0).build())
                .calculated(false)
                .canArchive(true)
                .canRestore(true)
                .createdAt(0L)
                .createdUserId(0L)
                .currencyPropertyName("")
                .dataSensitivity(Property.DataSensitivity.NONE)
                .dateDisplayHint(Property.DateDisplayHint.ABSOLUTE)
                .deleted(false)
                .description("")
                .displayMode(Property.DisplayMode.CURRENT_VALUE)
                .displayOrder(0)
                .enforceMultivalueUniqueness(true)
                .externalOptions(false)
                .externalOptionsReferenceType("")
                .favorited(false)
                .favoritedOrder(0)
                .fieldType("")
                .formField(false)
                .fromUserId(0L)
                .groupName("")
                .hasUniqueValue(false)
                .hidden(false)
                .hubspotDefined(false)
                .isCustomizedDefault(false)
                .isMultiValued(false)
                .isPartial(false)
                .label("")
                .mutableDefinitionNotDeletable(false)
                .name("")
                .numberDisplayHint(Property.NumberDisplayHint.UNFORMATTED)
                .addOption(
                    Option.builder()
                        .hidden(false)
                        .label("Option A")
                        .value("A")
                        .description("Choice number one")
                        .displayOrder(1)
                        .build()
                )
                .optionsAreMutable(false)
                .optionSortStrategy(Property.OptionSortStrategy.DISPLAY_ORDER)
                .owningAppId(0L)
                .portalId(0L)
                .readOnlyDefinition(false)
                .readOnlyValue(false)
                .referencedObjectType(Property.ReferencedObjectType.CONTACT)
                .searchableInGlobalSearch(false)
                .searchTextAnalysisMode(Property.SearchTextAnalysisMode.NONE)
                .addSensitiveDataCategory("string")
                .showCurrencySymbol(false)
                .textDisplayHint(Property.TextDisplayHint.UNFORMATTED_SINGLE_LINE)
                .type(Property.Type.STRING)
                .updatedAt(0L)
                .build()

        assertThat(property.allowedObjectTypes())
            .containsExactly(ObjectTypeIdProto.builder().innerId(0).metaTypeId(0).build())
        assertThat(property.calculated()).isEqualTo(false)
        assertThat(property.canArchive()).isEqualTo(true)
        assertThat(property.canRestore()).isEqualTo(true)
        assertThat(property.createdAt()).isEqualTo(0L)
        assertThat(property.createdUserId()).isEqualTo(0L)
        assertThat(property.currencyPropertyName()).isEqualTo("")
        assertThat(property.dataSensitivity()).isEqualTo(Property.DataSensitivity.NONE)
        assertThat(property.dateDisplayHint()).isEqualTo(Property.DateDisplayHint.ABSOLUTE)
        assertThat(property.deleted()).isEqualTo(false)
        assertThat(property.description()).isEqualTo("")
        assertThat(property.displayMode()).isEqualTo(Property.DisplayMode.CURRENT_VALUE)
        assertThat(property.displayOrder()).isEqualTo(0)
        assertThat(property.enforceMultivalueUniqueness()).isEqualTo(true)
        assertThat(property.externalOptions()).isEqualTo(false)
        assertThat(property.externalOptionsReferenceType()).isEqualTo("")
        assertThat(property.favorited()).isEqualTo(false)
        assertThat(property.favoritedOrder()).isEqualTo(0)
        assertThat(property.fieldType()).isEqualTo("")
        assertThat(property.formField()).isEqualTo(false)
        assertThat(property.fromUserId()).isEqualTo(0L)
        assertThat(property.groupName()).isEqualTo("")
        assertThat(property.hasUniqueValue()).isEqualTo(false)
        assertThat(property.hidden()).isEqualTo(false)
        assertThat(property.hubspotDefined()).isEqualTo(false)
        assertThat(property.isCustomizedDefault()).isEqualTo(false)
        assertThat(property.isMultiValued()).isEqualTo(false)
        assertThat(property.isPartial()).isEqualTo(false)
        assertThat(property.label()).isEqualTo("")
        assertThat(property.mutableDefinitionNotDeletable()).isEqualTo(false)
        assertThat(property.name()).isEqualTo("")
        assertThat(property.numberDisplayHint()).isEqualTo(Property.NumberDisplayHint.UNFORMATTED)
        assertThat(property.options())
            .containsExactly(
                Option.builder()
                    .hidden(false)
                    .label("Option A")
                    .value("A")
                    .description("Choice number one")
                    .displayOrder(1)
                    .build()
            )
        assertThat(property.optionsAreMutable()).isEqualTo(false)
        assertThat(property.optionSortStrategy())
            .isEqualTo(Property.OptionSortStrategy.DISPLAY_ORDER)
        assertThat(property.owningAppId()).isEqualTo(0L)
        assertThat(property.portalId()).isEqualTo(0L)
        assertThat(property.readOnlyDefinition()).isEqualTo(false)
        assertThat(property.readOnlyValue()).isEqualTo(false)
        assertThat(property.referencedObjectType()).isEqualTo(Property.ReferencedObjectType.CONTACT)
        assertThat(property.searchableInGlobalSearch()).isEqualTo(false)
        assertThat(property.searchTextAnalysisMode())
            .isEqualTo(Property.SearchTextAnalysisMode.NONE)
        assertThat(property.sensitiveDataCategories()).containsExactly("string")
        assertThat(property.showCurrencySymbol()).isEqualTo(false)
        assertThat(property.textDisplayHint())
            .isEqualTo(Property.TextDisplayHint.UNFORMATTED_SINGLE_LINE)
        assertThat(property.type()).isEqualTo(Property.Type.STRING)
        assertThat(property.updatedAt()).isEqualTo(0L)
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val property =
            Property.builder()
                .addAllowedObjectType(ObjectTypeIdProto.builder().innerId(0).metaTypeId(0).build())
                .calculated(false)
                .canArchive(true)
                .canRestore(true)
                .createdAt(0L)
                .createdUserId(0L)
                .currencyPropertyName("")
                .dataSensitivity(Property.DataSensitivity.NONE)
                .dateDisplayHint(Property.DateDisplayHint.ABSOLUTE)
                .deleted(false)
                .description("")
                .displayMode(Property.DisplayMode.CURRENT_VALUE)
                .displayOrder(0)
                .enforceMultivalueUniqueness(true)
                .externalOptions(false)
                .externalOptionsReferenceType("")
                .favorited(false)
                .favoritedOrder(0)
                .fieldType("")
                .formField(false)
                .fromUserId(0L)
                .groupName("")
                .hasUniqueValue(false)
                .hidden(false)
                .hubspotDefined(false)
                .isCustomizedDefault(false)
                .isMultiValued(false)
                .isPartial(false)
                .label("")
                .mutableDefinitionNotDeletable(false)
                .name("")
                .numberDisplayHint(Property.NumberDisplayHint.UNFORMATTED)
                .addOption(
                    Option.builder()
                        .hidden(false)
                        .label("Option A")
                        .value("A")
                        .description("Choice number one")
                        .displayOrder(1)
                        .build()
                )
                .optionsAreMutable(false)
                .optionSortStrategy(Property.OptionSortStrategy.DISPLAY_ORDER)
                .owningAppId(0L)
                .portalId(0L)
                .readOnlyDefinition(false)
                .readOnlyValue(false)
                .referencedObjectType(Property.ReferencedObjectType.CONTACT)
                .searchableInGlobalSearch(false)
                .searchTextAnalysisMode(Property.SearchTextAnalysisMode.NONE)
                .addSensitiveDataCategory("string")
                .showCurrencySymbol(false)
                .textDisplayHint(Property.TextDisplayHint.UNFORMATTED_SINGLE_LINE)
                .type(Property.Type.STRING)
                .updatedAt(0L)
                .build()

        val roundtrippedProperty =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(property),
                jacksonTypeRef<Property>(),
            )

        assertThat(roundtrippedProperty).isEqualTo(property)
    }
}
