// File generated from our OpenAPI spec by Stainless.

package com.hubspot_sdk.api.models.marketing.emails

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.hubspot_sdk.api.core.JsonValue
import com.hubspot_sdk.api.core.jsonMapper
import com.hubspot_sdk.api.models.VersionUser
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class VersionPublicEmailTest {

    @Test
    fun create() {
        val versionPublicEmail =
            VersionPublicEmail.builder()
                .id("id")
                .object_(
                    PublicEmail.builder()
                        .id("38175169118")
                        .content(
                            PublicEmailContent.builder()
                                .flexAreas(
                                    PublicEmailContent.FlexAreas.builder()
                                        .putAdditionalProperty(
                                            "main",
                                            JsonValue.from(mapOf<String, Any>()),
                                        )
                                        .build()
                                )
                                .plainTextVersion(
                                    "This is custom! View in browser ({{view_as_page_url}})\n\nHello {{ contact.firstname }},\n\nPlain text emails have minimal formatting so your reader can really focus on what you have to say. Introduce yourself and explain why you’re reaching out.\n\nEvery email should try to lead the reader to some kind of action. Use this space to describe why the reader should want to click on the link below. Put the link on its own line to really draw their eye to it.\n\nLink text\n\nNow it’s time to wrap up your email. Before your signature, thank the recipient for reading. You can also invite them to send this email to any of their colleagues who might be interested.\n\nAll the best,\n\nYour full name\n\nYour job title\n\nOther contact information\n\n{{site_settings.company_name}}, {{site_settings.company_street_address_1}}, {{site_settings.company_street_address_2}}, {{site_settings.company_city}}, {{site_settings.company_state}} {{site_settings.company_zip}}, {{site_settings.company_country}}, {{site_settings.company_phone}}\n\nUnsubscribe ({{unsubscribe_link_all}})\n\nManage preferences ({{unsubscribe_link}})"
                                )
                                .smartFields(
                                    PublicEmailContent.SmartFields.builder()
                                        .putAdditionalProperty(
                                            "foo",
                                            JsonValue.from(mapOf<String, Any>()),
                                        )
                                        .build()
                                )
                                .styleSettings(
                                    PublicEmailStyleSettings.builder()
                                        .backgroundColor("backgroundColor")
                                        .backgroundImage("backgroundImage")
                                        .backgroundImageType("backgroundImageType")
                                        .bodyBorderColor("bodyBorderColor")
                                        .bodyBorderColorChoice("bodyBorderColorChoice")
                                        .bodyBorderWidth(0.0)
                                        .bodyColor("bodyColor")
                                        .buttonStyleSettings(
                                            PublicButtonStyleSettings.builder()
                                                .backgroundColor(
                                                    JsonValue.from(mapOf<String, Any>())
                                                )
                                                .cornerRadius(0)
                                                .fontStyle(
                                                    PublicFontStyle.builder()
                                                        .bold(true)
                                                        .color("color")
                                                        .font("font")
                                                        .italic(true)
                                                        .size(0)
                                                        .underline(true)
                                                        .build()
                                                )
                                                .build()
                                        )
                                        .colorPickerFavorite1("colorPickerFavorite1")
                                        .colorPickerFavorite2("colorPickerFavorite2")
                                        .colorPickerFavorite3("colorPickerFavorite3")
                                        .colorPickerFavorite4("colorPickerFavorite4")
                                        .colorPickerFavorite5("colorPickerFavorite5")
                                        .colorPickerFavorite6("colorPickerFavorite6")
                                        .dividerStyleSettings(
                                            PublicDividerStyleSettings.builder()
                                                .color(JsonValue.from(mapOf<String, Any>()))
                                                .height(0)
                                                .lineType("lineType")
                                                .build()
                                        )
                                        .emailBodyPadding("emailBodyPadding")
                                        .emailBodyWidth("emailBodyWidth")
                                        .headingOneFont(
                                            PublicFontStyle.builder()
                                                .bold(true)
                                                .color("color")
                                                .font("font")
                                                .italic(true)
                                                .size(0)
                                                .underline(true)
                                                .build()
                                        )
                                        .headingTwoFont(
                                            PublicFontStyle.builder()
                                                .bold(true)
                                                .color("color")
                                                .font("font")
                                                .italic(true)
                                                .size(0)
                                                .underline(true)
                                                .build()
                                        )
                                        .linksFont(
                                            PublicFontStyle.builder()
                                                .bold(true)
                                                .color("color")
                                                .font("font")
                                                .italic(true)
                                                .size(0)
                                                .underline(true)
                                                .build()
                                        )
                                        .primaryAccentColor("primaryAccentColor")
                                        .primaryFont("primaryFont")
                                        .primaryFontColor("primaryFontColor")
                                        .primaryFontLineHeight("primaryFontLineHeight")
                                        .primaryFontSize(0.0)
                                        .secondaryAccentColor("secondaryAccentColor")
                                        .secondaryFont("secondaryFont")
                                        .secondaryFontColor("secondaryFontColor")
                                        .secondaryFontLineHeight("secondaryFontLineHeight")
                                        .secondaryFontSize(0.0)
                                        .build()
                                )
                                .templatePath("@hubspot/email/dnd/plain_text.html")
                                .themeSettingsValues(
                                    PublicEmailContent.ThemeSettingsValues.builder()
                                        .putAdditionalProperty(
                                            "foo",
                                            JsonValue.from(mapOf<String, Any>()),
                                        )
                                        .build()
                                )
                                .widgetContainers(
                                    PublicEmailContent.WidgetContainers.builder()
                                        .putAdditionalProperty(
                                            "foo",
                                            JsonValue.from(mapOf<String, Any>()),
                                        )
                                        .build()
                                )
                                .widgets(
                                    PublicEmailContent.Widgets.builder()
                                        .putAdditionalProperty(
                                            "module-0-1-1",
                                            JsonValue.from(mapOf<String, Any>()),
                                        )
                                        .putAdditionalProperty(
                                            "module-1-1-1",
                                            JsonValue.from(mapOf<String, Any>()),
                                        )
                                        .putAdditionalProperty(
                                            "module_160676180617911",
                                            JsonValue.from(mapOf<String, Any>()),
                                        )
                                        .putAdditionalProperty(
                                            "preview_text",
                                            JsonValue.from(mapOf<String, Any>()),
                                        )
                                        .build()
                                )
                                .build()
                        )
                        .from(
                            PublicEmailFromDetails.builder()
                                .customReplyTo("customReplyTo")
                                .fromName("Bruce Wayne")
                                .replyTo("test@hubspot.com")
                                .build()
                        )
                        .name("My subject")
                        .sendOnPublish(true)
                        .state(PublicEmail.State.DRAFT)
                        .subcategory("batch")
                        .subject("My subject")
                        .to(
                            PublicEmailToDetails.builder()
                                .contactIds(
                                    PublicEmailRecipients.builder()
                                        .addExclude("string")
                                        .addInclude("string")
                                        .build()
                                )
                                .contactIlsLists(
                                    PublicEmailRecipients.builder()
                                        .addExclude("string")
                                        .addInclude("string")
                                        .build()
                                )
                                .contactLists(
                                    PublicEmailRecipients.builder()
                                        .addExclude("string")
                                        .addInclude("string")
                                        .build()
                                )
                                .limitSendFrequency(true)
                                .suppressGraymail(true)
                                .build()
                        )
                        .activeDomain("test.hs-sites.com")
                        .addAllEmailCampaignId("string")
                        .archived(false)
                        .businessUnitId("businessUnitId")
                        .campaign("1b7f51a6-33c1-44d6-ba28-fe81f655dced")
                        .campaignName("campaignName")
                        .campaignUtm("campaignUtm")
                        .clonedFrom("3817552341")
                        .createdAt(OffsetDateTime.parse("2020-11-30T18:43:17.136Z"))
                        .createdById("createdById")
                        .deletedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .emailCampaignGroupId("emailCampaignGroupId")
                        .emailTemplateMode(PublicEmail.EmailTemplateMode.DESIGN_MANAGER)
                        .feedbackSurveyId("feedbackSurveyId")
                        .folderId(0L)
                        .folderIdV2(0L)
                        .isAb(true)
                        .isPublished(false)
                        .isTransactional(false)
                        .jitterSendTime(true)
                        .language(PublicEmail.Language.EN)
                        .previewKey("previewKey")
                        .primaryEmailCampaignId("primaryEmailCampaignId")
                        .publishDate(OffsetDateTime.parse("2020-11-30T18:44:20.387Z"))
                        .publishedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .publishedByEmail("publishedByEmail")
                        .publishedById("publishedById")
                        .publishedByName("publishedByName")
                        .rssData(
                            PublicRssEmailDetails.builder()
                                .blogEmailType("blogEmailType")
                                .blogImageMaxWidth(0)
                                .blogLayout("blogLayout")
                                .hubspotBlogId("hubspotBlogId")
                                .maxEntries(0)
                                .rssEntryTemplate("rssEntryTemplate")
                                .timing(
                                    PublicRssEmailDetails.Timing.builder()
                                        .putAdditionalProperty(
                                            "foo",
                                            JsonValue.from(mapOf<String, Any>()),
                                        )
                                        .build()
                                )
                                .url("url")
                                .useHeadlineAsSubject(true)
                                .build()
                        )
                        .stats(
                            EmailStatisticsData.builder()
                                .counters(
                                    EmailStatisticsData.Counters.builder()
                                        .putAdditionalProperty("foo", JsonValue.from(0))
                                        .build()
                                )
                                .deviceBreakdown(
                                    EmailStatisticsData.DeviceBreakdown.builder()
                                        .putAdditionalProperty(
                                            "foo",
                                            JsonValue.from(mapOf("foo" to 0)),
                                        )
                                        .build()
                                )
                                .qualifierStats(
                                    EmailStatisticsData.QualifierStats.builder()
                                        .putAdditionalProperty(
                                            "foo",
                                            JsonValue.from(mapOf("foo" to 0)),
                                        )
                                        .build()
                                )
                                .ratios(
                                    EmailStatisticsData.Ratios.builder()
                                        .putAdditionalProperty("foo", JsonValue.from(0))
                                        .build()
                                )
                                .build()
                        )
                        .subscriptionDetails(
                            PublicEmailSubscriptionDetails.builder()
                                .officeLocationId("5449392956")
                                .preferencesGroupId("preferencesGroupId")
                                .subscriptionId("subscriptionId")
                                .subscriptionName("subscriptionName")
                                .build()
                        )
                        .addTeamsWithAccess("string")
                        .testing(
                            PublicEmailTestingDetails.builder()
                                .abSampleSizeDefault(
                                    PublicEmailTestingDetails.AbSampleSizeDefault.MASTER
                                )
                                .abSamplingDefault(
                                    PublicEmailTestingDetails.AbSamplingDefault.MASTER
                                )
                                .abStatus(PublicEmailTestingDetails.AbStatus.MASTER)
                                .abSuccessMetric(
                                    PublicEmailTestingDetails.AbSuccessMetric.CLICKS_BY_OPENS
                                )
                                .abTestPercentage(0)
                                .hoursToWait(0)
                                .isAbVariation(true)
                                .testId("testId")
                                .build()
                        )
                        .type(PublicEmail.Type.BATCH_EMAIL)
                        .unpublishedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .updatedAt(OffsetDateTime.parse("2020-11-30T18:44:20.384Z"))
                        .updatedById("updatedById")
                        .addUsersWithAccess("string")
                        .webversion(
                            PublicWebversionDetails.builder()
                                .domain("domain")
                                .enabled(true)
                                .expiresAt(OffsetDateTime.parse("2020-11-30T18:44:20.387Z"))
                                .isPageRedirected(true)
                                .metaDescription("")
                                .pageExpiryEnabled(true)
                                .redirectToPageId("redirectToPageId")
                                .redirectToUrl("http://www.example.org")
                                .slug("slug")
                                .title("title")
                                .url("url")
                                .build()
                        )
                        .addWorkflowName("string")
                        .build()
                )
                .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .user(VersionUser.builder().id("id").email("email").fullName("fullName").build())
                .build()

        assertThat(versionPublicEmail.id()).isEqualTo("id")
        assertThat(versionPublicEmail.object_())
            .isEqualTo(
                PublicEmail.builder()
                    .id("38175169118")
                    .content(
                        PublicEmailContent.builder()
                            .flexAreas(
                                PublicEmailContent.FlexAreas.builder()
                                    .putAdditionalProperty(
                                        "main",
                                        JsonValue.from(mapOf<String, Any>()),
                                    )
                                    .build()
                            )
                            .plainTextVersion(
                                "This is custom! View in browser ({{view_as_page_url}})\n\nHello {{ contact.firstname }},\n\nPlain text emails have minimal formatting so your reader can really focus on what you have to say. Introduce yourself and explain why you’re reaching out.\n\nEvery email should try to lead the reader to some kind of action. Use this space to describe why the reader should want to click on the link below. Put the link on its own line to really draw their eye to it.\n\nLink text\n\nNow it’s time to wrap up your email. Before your signature, thank the recipient for reading. You can also invite them to send this email to any of their colleagues who might be interested.\n\nAll the best,\n\nYour full name\n\nYour job title\n\nOther contact information\n\n{{site_settings.company_name}}, {{site_settings.company_street_address_1}}, {{site_settings.company_street_address_2}}, {{site_settings.company_city}}, {{site_settings.company_state}} {{site_settings.company_zip}}, {{site_settings.company_country}}, {{site_settings.company_phone}}\n\nUnsubscribe ({{unsubscribe_link_all}})\n\nManage preferences ({{unsubscribe_link}})"
                            )
                            .smartFields(
                                PublicEmailContent.SmartFields.builder()
                                    .putAdditionalProperty(
                                        "foo",
                                        JsonValue.from(mapOf<String, Any>()),
                                    )
                                    .build()
                            )
                            .styleSettings(
                                PublicEmailStyleSettings.builder()
                                    .backgroundColor("backgroundColor")
                                    .backgroundImage("backgroundImage")
                                    .backgroundImageType("backgroundImageType")
                                    .bodyBorderColor("bodyBorderColor")
                                    .bodyBorderColorChoice("bodyBorderColorChoice")
                                    .bodyBorderWidth(0.0)
                                    .bodyColor("bodyColor")
                                    .buttonStyleSettings(
                                        PublicButtonStyleSettings.builder()
                                            .backgroundColor(JsonValue.from(mapOf<String, Any>()))
                                            .cornerRadius(0)
                                            .fontStyle(
                                                PublicFontStyle.builder()
                                                    .bold(true)
                                                    .color("color")
                                                    .font("font")
                                                    .italic(true)
                                                    .size(0)
                                                    .underline(true)
                                                    .build()
                                            )
                                            .build()
                                    )
                                    .colorPickerFavorite1("colorPickerFavorite1")
                                    .colorPickerFavorite2("colorPickerFavorite2")
                                    .colorPickerFavorite3("colorPickerFavorite3")
                                    .colorPickerFavorite4("colorPickerFavorite4")
                                    .colorPickerFavorite5("colorPickerFavorite5")
                                    .colorPickerFavorite6("colorPickerFavorite6")
                                    .dividerStyleSettings(
                                        PublicDividerStyleSettings.builder()
                                            .color(JsonValue.from(mapOf<String, Any>()))
                                            .height(0)
                                            .lineType("lineType")
                                            .build()
                                    )
                                    .emailBodyPadding("emailBodyPadding")
                                    .emailBodyWidth("emailBodyWidth")
                                    .headingOneFont(
                                        PublicFontStyle.builder()
                                            .bold(true)
                                            .color("color")
                                            .font("font")
                                            .italic(true)
                                            .size(0)
                                            .underline(true)
                                            .build()
                                    )
                                    .headingTwoFont(
                                        PublicFontStyle.builder()
                                            .bold(true)
                                            .color("color")
                                            .font("font")
                                            .italic(true)
                                            .size(0)
                                            .underline(true)
                                            .build()
                                    )
                                    .linksFont(
                                        PublicFontStyle.builder()
                                            .bold(true)
                                            .color("color")
                                            .font("font")
                                            .italic(true)
                                            .size(0)
                                            .underline(true)
                                            .build()
                                    )
                                    .primaryAccentColor("primaryAccentColor")
                                    .primaryFont("primaryFont")
                                    .primaryFontColor("primaryFontColor")
                                    .primaryFontLineHeight("primaryFontLineHeight")
                                    .primaryFontSize(0.0)
                                    .secondaryAccentColor("secondaryAccentColor")
                                    .secondaryFont("secondaryFont")
                                    .secondaryFontColor("secondaryFontColor")
                                    .secondaryFontLineHeight("secondaryFontLineHeight")
                                    .secondaryFontSize(0.0)
                                    .build()
                            )
                            .templatePath("@hubspot/email/dnd/plain_text.html")
                            .themeSettingsValues(
                                PublicEmailContent.ThemeSettingsValues.builder()
                                    .putAdditionalProperty(
                                        "foo",
                                        JsonValue.from(mapOf<String, Any>()),
                                    )
                                    .build()
                            )
                            .widgetContainers(
                                PublicEmailContent.WidgetContainers.builder()
                                    .putAdditionalProperty(
                                        "foo",
                                        JsonValue.from(mapOf<String, Any>()),
                                    )
                                    .build()
                            )
                            .widgets(
                                PublicEmailContent.Widgets.builder()
                                    .putAdditionalProperty(
                                        "module-0-1-1",
                                        JsonValue.from(mapOf<String, Any>()),
                                    )
                                    .putAdditionalProperty(
                                        "module-1-1-1",
                                        JsonValue.from(mapOf<String, Any>()),
                                    )
                                    .putAdditionalProperty(
                                        "module_160676180617911",
                                        JsonValue.from(mapOf<String, Any>()),
                                    )
                                    .putAdditionalProperty(
                                        "preview_text",
                                        JsonValue.from(mapOf<String, Any>()),
                                    )
                                    .build()
                            )
                            .build()
                    )
                    .from(
                        PublicEmailFromDetails.builder()
                            .customReplyTo("customReplyTo")
                            .fromName("Bruce Wayne")
                            .replyTo("test@hubspot.com")
                            .build()
                    )
                    .name("My subject")
                    .sendOnPublish(true)
                    .state(PublicEmail.State.DRAFT)
                    .subcategory("batch")
                    .subject("My subject")
                    .to(
                        PublicEmailToDetails.builder()
                            .contactIds(
                                PublicEmailRecipients.builder()
                                    .addExclude("string")
                                    .addInclude("string")
                                    .build()
                            )
                            .contactIlsLists(
                                PublicEmailRecipients.builder()
                                    .addExclude("string")
                                    .addInclude("string")
                                    .build()
                            )
                            .contactLists(
                                PublicEmailRecipients.builder()
                                    .addExclude("string")
                                    .addInclude("string")
                                    .build()
                            )
                            .limitSendFrequency(true)
                            .suppressGraymail(true)
                            .build()
                    )
                    .activeDomain("test.hs-sites.com")
                    .addAllEmailCampaignId("string")
                    .archived(false)
                    .businessUnitId("businessUnitId")
                    .campaign("1b7f51a6-33c1-44d6-ba28-fe81f655dced")
                    .campaignName("campaignName")
                    .campaignUtm("campaignUtm")
                    .clonedFrom("3817552341")
                    .createdAt(OffsetDateTime.parse("2020-11-30T18:43:17.136Z"))
                    .createdById("createdById")
                    .deletedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .emailCampaignGroupId("emailCampaignGroupId")
                    .emailTemplateMode(PublicEmail.EmailTemplateMode.DESIGN_MANAGER)
                    .feedbackSurveyId("feedbackSurveyId")
                    .folderId(0L)
                    .folderIdV2(0L)
                    .isAb(true)
                    .isPublished(false)
                    .isTransactional(false)
                    .jitterSendTime(true)
                    .language(PublicEmail.Language.EN)
                    .previewKey("previewKey")
                    .primaryEmailCampaignId("primaryEmailCampaignId")
                    .publishDate(OffsetDateTime.parse("2020-11-30T18:44:20.387Z"))
                    .publishedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .publishedByEmail("publishedByEmail")
                    .publishedById("publishedById")
                    .publishedByName("publishedByName")
                    .rssData(
                        PublicRssEmailDetails.builder()
                            .blogEmailType("blogEmailType")
                            .blogImageMaxWidth(0)
                            .blogLayout("blogLayout")
                            .hubspotBlogId("hubspotBlogId")
                            .maxEntries(0)
                            .rssEntryTemplate("rssEntryTemplate")
                            .timing(
                                PublicRssEmailDetails.Timing.builder()
                                    .putAdditionalProperty(
                                        "foo",
                                        JsonValue.from(mapOf<String, Any>()),
                                    )
                                    .build()
                            )
                            .url("url")
                            .useHeadlineAsSubject(true)
                            .build()
                    )
                    .stats(
                        EmailStatisticsData.builder()
                            .counters(
                                EmailStatisticsData.Counters.builder()
                                    .putAdditionalProperty("foo", JsonValue.from(0))
                                    .build()
                            )
                            .deviceBreakdown(
                                EmailStatisticsData.DeviceBreakdown.builder()
                                    .putAdditionalProperty("foo", JsonValue.from(mapOf("foo" to 0)))
                                    .build()
                            )
                            .qualifierStats(
                                EmailStatisticsData.QualifierStats.builder()
                                    .putAdditionalProperty("foo", JsonValue.from(mapOf("foo" to 0)))
                                    .build()
                            )
                            .ratios(
                                EmailStatisticsData.Ratios.builder()
                                    .putAdditionalProperty("foo", JsonValue.from(0))
                                    .build()
                            )
                            .build()
                    )
                    .subscriptionDetails(
                        PublicEmailSubscriptionDetails.builder()
                            .officeLocationId("5449392956")
                            .preferencesGroupId("preferencesGroupId")
                            .subscriptionId("subscriptionId")
                            .subscriptionName("subscriptionName")
                            .build()
                    )
                    .addTeamsWithAccess("string")
                    .testing(
                        PublicEmailTestingDetails.builder()
                            .abSampleSizeDefault(
                                PublicEmailTestingDetails.AbSampleSizeDefault.MASTER
                            )
                            .abSamplingDefault(PublicEmailTestingDetails.AbSamplingDefault.MASTER)
                            .abStatus(PublicEmailTestingDetails.AbStatus.MASTER)
                            .abSuccessMetric(
                                PublicEmailTestingDetails.AbSuccessMetric.CLICKS_BY_OPENS
                            )
                            .abTestPercentage(0)
                            .hoursToWait(0)
                            .isAbVariation(true)
                            .testId("testId")
                            .build()
                    )
                    .type(PublicEmail.Type.BATCH_EMAIL)
                    .unpublishedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .updatedAt(OffsetDateTime.parse("2020-11-30T18:44:20.384Z"))
                    .updatedById("updatedById")
                    .addUsersWithAccess("string")
                    .webversion(
                        PublicWebversionDetails.builder()
                            .domain("domain")
                            .enabled(true)
                            .expiresAt(OffsetDateTime.parse("2020-11-30T18:44:20.387Z"))
                            .isPageRedirected(true)
                            .metaDescription("")
                            .pageExpiryEnabled(true)
                            .redirectToPageId("redirectToPageId")
                            .redirectToUrl("http://www.example.org")
                            .slug("slug")
                            .title("title")
                            .url("url")
                            .build()
                    )
                    .addWorkflowName("string")
                    .build()
            )
        assertThat(versionPublicEmail.updatedAt())
            .isEqualTo(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
        assertThat(versionPublicEmail.user())
            .isEqualTo(VersionUser.builder().id("id").email("email").fullName("fullName").build())
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val versionPublicEmail =
            VersionPublicEmail.builder()
                .id("id")
                .object_(
                    PublicEmail.builder()
                        .id("38175169118")
                        .content(
                            PublicEmailContent.builder()
                                .flexAreas(
                                    PublicEmailContent.FlexAreas.builder()
                                        .putAdditionalProperty(
                                            "main",
                                            JsonValue.from(mapOf<String, Any>()),
                                        )
                                        .build()
                                )
                                .plainTextVersion(
                                    "This is custom! View in browser ({{view_as_page_url}})\n\nHello {{ contact.firstname }},\n\nPlain text emails have minimal formatting so your reader can really focus on what you have to say. Introduce yourself and explain why you’re reaching out.\n\nEvery email should try to lead the reader to some kind of action. Use this space to describe why the reader should want to click on the link below. Put the link on its own line to really draw their eye to it.\n\nLink text\n\nNow it’s time to wrap up your email. Before your signature, thank the recipient for reading. You can also invite them to send this email to any of their colleagues who might be interested.\n\nAll the best,\n\nYour full name\n\nYour job title\n\nOther contact information\n\n{{site_settings.company_name}}, {{site_settings.company_street_address_1}}, {{site_settings.company_street_address_2}}, {{site_settings.company_city}}, {{site_settings.company_state}} {{site_settings.company_zip}}, {{site_settings.company_country}}, {{site_settings.company_phone}}\n\nUnsubscribe ({{unsubscribe_link_all}})\n\nManage preferences ({{unsubscribe_link}})"
                                )
                                .smartFields(
                                    PublicEmailContent.SmartFields.builder()
                                        .putAdditionalProperty(
                                            "foo",
                                            JsonValue.from(mapOf<String, Any>()),
                                        )
                                        .build()
                                )
                                .styleSettings(
                                    PublicEmailStyleSettings.builder()
                                        .backgroundColor("backgroundColor")
                                        .backgroundImage("backgroundImage")
                                        .backgroundImageType("backgroundImageType")
                                        .bodyBorderColor("bodyBorderColor")
                                        .bodyBorderColorChoice("bodyBorderColorChoice")
                                        .bodyBorderWidth(0.0)
                                        .bodyColor("bodyColor")
                                        .buttonStyleSettings(
                                            PublicButtonStyleSettings.builder()
                                                .backgroundColor(
                                                    JsonValue.from(mapOf<String, Any>())
                                                )
                                                .cornerRadius(0)
                                                .fontStyle(
                                                    PublicFontStyle.builder()
                                                        .bold(true)
                                                        .color("color")
                                                        .font("font")
                                                        .italic(true)
                                                        .size(0)
                                                        .underline(true)
                                                        .build()
                                                )
                                                .build()
                                        )
                                        .colorPickerFavorite1("colorPickerFavorite1")
                                        .colorPickerFavorite2("colorPickerFavorite2")
                                        .colorPickerFavorite3("colorPickerFavorite3")
                                        .colorPickerFavorite4("colorPickerFavorite4")
                                        .colorPickerFavorite5("colorPickerFavorite5")
                                        .colorPickerFavorite6("colorPickerFavorite6")
                                        .dividerStyleSettings(
                                            PublicDividerStyleSettings.builder()
                                                .color(JsonValue.from(mapOf<String, Any>()))
                                                .height(0)
                                                .lineType("lineType")
                                                .build()
                                        )
                                        .emailBodyPadding("emailBodyPadding")
                                        .emailBodyWidth("emailBodyWidth")
                                        .headingOneFont(
                                            PublicFontStyle.builder()
                                                .bold(true)
                                                .color("color")
                                                .font("font")
                                                .italic(true)
                                                .size(0)
                                                .underline(true)
                                                .build()
                                        )
                                        .headingTwoFont(
                                            PublicFontStyle.builder()
                                                .bold(true)
                                                .color("color")
                                                .font("font")
                                                .italic(true)
                                                .size(0)
                                                .underline(true)
                                                .build()
                                        )
                                        .linksFont(
                                            PublicFontStyle.builder()
                                                .bold(true)
                                                .color("color")
                                                .font("font")
                                                .italic(true)
                                                .size(0)
                                                .underline(true)
                                                .build()
                                        )
                                        .primaryAccentColor("primaryAccentColor")
                                        .primaryFont("primaryFont")
                                        .primaryFontColor("primaryFontColor")
                                        .primaryFontLineHeight("primaryFontLineHeight")
                                        .primaryFontSize(0.0)
                                        .secondaryAccentColor("secondaryAccentColor")
                                        .secondaryFont("secondaryFont")
                                        .secondaryFontColor("secondaryFontColor")
                                        .secondaryFontLineHeight("secondaryFontLineHeight")
                                        .secondaryFontSize(0.0)
                                        .build()
                                )
                                .templatePath("@hubspot/email/dnd/plain_text.html")
                                .themeSettingsValues(
                                    PublicEmailContent.ThemeSettingsValues.builder()
                                        .putAdditionalProperty(
                                            "foo",
                                            JsonValue.from(mapOf<String, Any>()),
                                        )
                                        .build()
                                )
                                .widgetContainers(
                                    PublicEmailContent.WidgetContainers.builder()
                                        .putAdditionalProperty(
                                            "foo",
                                            JsonValue.from(mapOf<String, Any>()),
                                        )
                                        .build()
                                )
                                .widgets(
                                    PublicEmailContent.Widgets.builder()
                                        .putAdditionalProperty(
                                            "module-0-1-1",
                                            JsonValue.from(mapOf<String, Any>()),
                                        )
                                        .putAdditionalProperty(
                                            "module-1-1-1",
                                            JsonValue.from(mapOf<String, Any>()),
                                        )
                                        .putAdditionalProperty(
                                            "module_160676180617911",
                                            JsonValue.from(mapOf<String, Any>()),
                                        )
                                        .putAdditionalProperty(
                                            "preview_text",
                                            JsonValue.from(mapOf<String, Any>()),
                                        )
                                        .build()
                                )
                                .build()
                        )
                        .from(
                            PublicEmailFromDetails.builder()
                                .customReplyTo("customReplyTo")
                                .fromName("Bruce Wayne")
                                .replyTo("test@hubspot.com")
                                .build()
                        )
                        .name("My subject")
                        .sendOnPublish(true)
                        .state(PublicEmail.State.DRAFT)
                        .subcategory("batch")
                        .subject("My subject")
                        .to(
                            PublicEmailToDetails.builder()
                                .contactIds(
                                    PublicEmailRecipients.builder()
                                        .addExclude("string")
                                        .addInclude("string")
                                        .build()
                                )
                                .contactIlsLists(
                                    PublicEmailRecipients.builder()
                                        .addExclude("string")
                                        .addInclude("string")
                                        .build()
                                )
                                .contactLists(
                                    PublicEmailRecipients.builder()
                                        .addExclude("string")
                                        .addInclude("string")
                                        .build()
                                )
                                .limitSendFrequency(true)
                                .suppressGraymail(true)
                                .build()
                        )
                        .activeDomain("test.hs-sites.com")
                        .addAllEmailCampaignId("string")
                        .archived(false)
                        .businessUnitId("businessUnitId")
                        .campaign("1b7f51a6-33c1-44d6-ba28-fe81f655dced")
                        .campaignName("campaignName")
                        .campaignUtm("campaignUtm")
                        .clonedFrom("3817552341")
                        .createdAt(OffsetDateTime.parse("2020-11-30T18:43:17.136Z"))
                        .createdById("createdById")
                        .deletedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .emailCampaignGroupId("emailCampaignGroupId")
                        .emailTemplateMode(PublicEmail.EmailTemplateMode.DESIGN_MANAGER)
                        .feedbackSurveyId("feedbackSurveyId")
                        .folderId(0L)
                        .folderIdV2(0L)
                        .isAb(true)
                        .isPublished(false)
                        .isTransactional(false)
                        .jitterSendTime(true)
                        .language(PublicEmail.Language.EN)
                        .previewKey("previewKey")
                        .primaryEmailCampaignId("primaryEmailCampaignId")
                        .publishDate(OffsetDateTime.parse("2020-11-30T18:44:20.387Z"))
                        .publishedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .publishedByEmail("publishedByEmail")
                        .publishedById("publishedById")
                        .publishedByName("publishedByName")
                        .rssData(
                            PublicRssEmailDetails.builder()
                                .blogEmailType("blogEmailType")
                                .blogImageMaxWidth(0)
                                .blogLayout("blogLayout")
                                .hubspotBlogId("hubspotBlogId")
                                .maxEntries(0)
                                .rssEntryTemplate("rssEntryTemplate")
                                .timing(
                                    PublicRssEmailDetails.Timing.builder()
                                        .putAdditionalProperty(
                                            "foo",
                                            JsonValue.from(mapOf<String, Any>()),
                                        )
                                        .build()
                                )
                                .url("url")
                                .useHeadlineAsSubject(true)
                                .build()
                        )
                        .stats(
                            EmailStatisticsData.builder()
                                .counters(
                                    EmailStatisticsData.Counters.builder()
                                        .putAdditionalProperty("foo", JsonValue.from(0))
                                        .build()
                                )
                                .deviceBreakdown(
                                    EmailStatisticsData.DeviceBreakdown.builder()
                                        .putAdditionalProperty(
                                            "foo",
                                            JsonValue.from(mapOf("foo" to 0)),
                                        )
                                        .build()
                                )
                                .qualifierStats(
                                    EmailStatisticsData.QualifierStats.builder()
                                        .putAdditionalProperty(
                                            "foo",
                                            JsonValue.from(mapOf("foo" to 0)),
                                        )
                                        .build()
                                )
                                .ratios(
                                    EmailStatisticsData.Ratios.builder()
                                        .putAdditionalProperty("foo", JsonValue.from(0))
                                        .build()
                                )
                                .build()
                        )
                        .subscriptionDetails(
                            PublicEmailSubscriptionDetails.builder()
                                .officeLocationId("5449392956")
                                .preferencesGroupId("preferencesGroupId")
                                .subscriptionId("subscriptionId")
                                .subscriptionName("subscriptionName")
                                .build()
                        )
                        .addTeamsWithAccess("string")
                        .testing(
                            PublicEmailTestingDetails.builder()
                                .abSampleSizeDefault(
                                    PublicEmailTestingDetails.AbSampleSizeDefault.MASTER
                                )
                                .abSamplingDefault(
                                    PublicEmailTestingDetails.AbSamplingDefault.MASTER
                                )
                                .abStatus(PublicEmailTestingDetails.AbStatus.MASTER)
                                .abSuccessMetric(
                                    PublicEmailTestingDetails.AbSuccessMetric.CLICKS_BY_OPENS
                                )
                                .abTestPercentage(0)
                                .hoursToWait(0)
                                .isAbVariation(true)
                                .testId("testId")
                                .build()
                        )
                        .type(PublicEmail.Type.BATCH_EMAIL)
                        .unpublishedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .updatedAt(OffsetDateTime.parse("2020-11-30T18:44:20.384Z"))
                        .updatedById("updatedById")
                        .addUsersWithAccess("string")
                        .webversion(
                            PublicWebversionDetails.builder()
                                .domain("domain")
                                .enabled(true)
                                .expiresAt(OffsetDateTime.parse("2020-11-30T18:44:20.387Z"))
                                .isPageRedirected(true)
                                .metaDescription("")
                                .pageExpiryEnabled(true)
                                .redirectToPageId("redirectToPageId")
                                .redirectToUrl("http://www.example.org")
                                .slug("slug")
                                .title("title")
                                .url("url")
                                .build()
                        )
                        .addWorkflowName("string")
                        .build()
                )
                .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .user(VersionUser.builder().id("id").email("email").fullName("fullName").build())
                .build()

        val roundtrippedVersionPublicEmail =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(versionPublicEmail),
                jacksonTypeRef<VersionPublicEmail>(),
            )

        assertThat(roundtrippedVersionPublicEmail).isEqualTo(versionPublicEmail)
    }
}
