// File generated from our OpenAPI spec by Stainless.

package com.hubspot_sdk.api.models.crm.lists

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.hubspot_sdk.api.core.jsonMapper
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class PublicRestrictedFilterBranchTest {

    @Test
    fun create() {
        val publicRestrictedFilterBranch =
            PublicRestrictedFilterBranch.builder()
                .addFilterBranch(
                    PublicOrFilterBranch.builder()
                        .addFilterBranch(
                            PublicAndFilterBranch.builder()
                                .addFilterBranch(
                                    PublicNotAllFilterBranch.builder()
                                        .addFilterBranch(
                                            PublicNotAnyFilterBranch.builder()
                                                .addFilterBranch(
                                                    PublicUnifiedEventsFilterBranch.builder()
                                                        .eventTypeId("eventTypeId")
                                                        .addFilterBranch(
                                                            PublicPropertyAssociationFilterBranch
                                                                .builder()
                                                                .addFilterBranch(
                                                                    PublicAssociationFilterBranch
                                                                        .builder()
                                                                        .associationCategory(
                                                                            "associationCategory"
                                                                        )
                                                                        .associationTypeId(0)
                                                                        .addFilterBranch(
                                                                            PublicOrFilterBranch
                                                                                .builder()
                                                                                .filterBranches(
                                                                                    listOf()
                                                                                )
                                                                                .filterBranchOperator(
                                                                                    "filterBranchOperator"
                                                                                )
                                                                                .filterBranchType(
                                                                                    PublicOrFilterBranch
                                                                                        .FilterBranchType
                                                                                        .OR
                                                                                )
                                                                                .addFilter(
                                                                                    PublicPropertyFilter
                                                                                        .builder()
                                                                                        .filterType(
                                                                                            PublicPropertyFilter
                                                                                                .FilterType
                                                                                                .PROPERTY
                                                                                        )
                                                                                        .operation(
                                                                                            PublicBoolPropertyOperation
                                                                                                .builder()
                                                                                                .includeObjectsWithNoValueSet(
                                                                                                    true
                                                                                                )
                                                                                                .operationType(
                                                                                                    PublicBoolPropertyOperation
                                                                                                        .OperationType
                                                                                                        .BOOL
                                                                                                )
                                                                                                .operator(
                                                                                                    "operator"
                                                                                                )
                                                                                                .value(
                                                                                                    true
                                                                                                )
                                                                                                .build()
                                                                                        )
                                                                                        .property(
                                                                                            "property"
                                                                                        )
                                                                                        .build()
                                                                                )
                                                                                .build()
                                                                        )
                                                                        .filterBranchOperator(
                                                                            "filterBranchOperator"
                                                                        )
                                                                        .filterBranchType(
                                                                            PublicAssociationFilterBranch
                                                                                .FilterBranchType
                                                                                .ASSOCIATION
                                                                        )
                                                                        .addFilter(
                                                                            PublicPropertyFilter
                                                                                .builder()
                                                                                .filterType(
                                                                                    PublicPropertyFilter
                                                                                        .FilterType
                                                                                        .PROPERTY
                                                                                )
                                                                                .operation(
                                                                                    PublicBoolPropertyOperation
                                                                                        .builder()
                                                                                        .includeObjectsWithNoValueSet(
                                                                                            true
                                                                                        )
                                                                                        .operationType(
                                                                                            PublicBoolPropertyOperation
                                                                                                .OperationType
                                                                                                .BOOL
                                                                                        )
                                                                                        .operator(
                                                                                            "operator"
                                                                                        )
                                                                                        .value(true)
                                                                                        .build()
                                                                                )
                                                                                .property(
                                                                                    "property"
                                                                                )
                                                                                .build()
                                                                        )
                                                                        .objectTypeId(
                                                                            "objectTypeId"
                                                                        )
                                                                        .operator("operator")
                                                                        .build()
                                                                )
                                                                .filterBranchOperator(
                                                                    "filterBranchOperator"
                                                                )
                                                                .filterBranchType(
                                                                    PublicPropertyAssociationFilterBranch
                                                                        .FilterBranchType
                                                                        .PROPERTY_ASSOCIATION
                                                                )
                                                                .addFilter(
                                                                    PublicPropertyFilter.builder()
                                                                        .filterType(
                                                                            PublicPropertyFilter
                                                                                .FilterType
                                                                                .PROPERTY
                                                                        )
                                                                        .operation(
                                                                            PublicBoolPropertyOperation
                                                                                .builder()
                                                                                .includeObjectsWithNoValueSet(
                                                                                    true
                                                                                )
                                                                                .operationType(
                                                                                    PublicBoolPropertyOperation
                                                                                        .OperationType
                                                                                        .BOOL
                                                                                )
                                                                                .operator(
                                                                                    "operator"
                                                                                )
                                                                                .value(true)
                                                                                .build()
                                                                        )
                                                                        .property("property")
                                                                        .build()
                                                                )
                                                                .objectTypeId("objectTypeId")
                                                                .operator("operator")
                                                                .propertyWithObjectId(
                                                                    "propertyWithObjectId"
                                                                )
                                                                .build()
                                                        )
                                                        .filterBranchOperator(
                                                            "filterBranchOperator"
                                                        )
                                                        .filterBranchType(
                                                            PublicUnifiedEventsFilterBranch
                                                                .FilterBranchType
                                                                .UNIFIED_EVENTS
                                                        )
                                                        .addFilter(
                                                            PublicPropertyFilter.builder()
                                                                .filterType(
                                                                    PublicPropertyFilter.FilterType
                                                                        .PROPERTY
                                                                )
                                                                .operation(
                                                                    PublicBoolPropertyOperation
                                                                        .builder()
                                                                        .includeObjectsWithNoValueSet(
                                                                            true
                                                                        )
                                                                        .operationType(
                                                                            PublicBoolPropertyOperation
                                                                                .OperationType
                                                                                .BOOL
                                                                        )
                                                                        .operator("operator")
                                                                        .value(true)
                                                                        .build()
                                                                )
                                                                .property("property")
                                                                .build()
                                                        )
                                                        .operator(
                                                            PublicUnifiedEventsFilterBranch.Operator
                                                                .HAS_COMPLETED
                                                        )
                                                        .coalescingRefineBy(
                                                            PublicNumOccurrencesRefineBy.builder()
                                                                .type(
                                                                    PublicNumOccurrencesRefineBy
                                                                        .Type
                                                                        .NUM_OCCURRENCES
                                                                )
                                                                .maxOccurrences(0)
                                                                .minOccurrences(0)
                                                                .build()
                                                        )
                                                        .pruningRefineBy(
                                                            PublicNumOccurrencesRefineBy.builder()
                                                                .type(
                                                                    PublicNumOccurrencesRefineBy
                                                                        .Type
                                                                        .NUM_OCCURRENCES
                                                                )
                                                                .maxOccurrences(0)
                                                                .minOccurrences(0)
                                                                .build()
                                                        )
                                                        .build()
                                                )
                                                .filterBranchOperator("filterBranchOperator")
                                                .filterBranchType(
                                                    PublicNotAnyFilterBranch.FilterBranchType
                                                        .NOT_ANY
                                                )
                                                .addFilter(
                                                    PublicPropertyFilter.builder()
                                                        .filterType(
                                                            PublicPropertyFilter.FilterType.PROPERTY
                                                        )
                                                        .operation(
                                                            PublicBoolPropertyOperation.builder()
                                                                .includeObjectsWithNoValueSet(true)
                                                                .operationType(
                                                                    PublicBoolPropertyOperation
                                                                        .OperationType
                                                                        .BOOL
                                                                )
                                                                .operator("operator")
                                                                .value(true)
                                                                .build()
                                                        )
                                                        .property("property")
                                                        .build()
                                                )
                                                .build()
                                        )
                                        .filterBranchOperator("filterBranchOperator")
                                        .filterBranchType(
                                            PublicNotAllFilterBranch.FilterBranchType.NOT_ALL
                                        )
                                        .addFilter(
                                            PublicPropertyFilter.builder()
                                                .filterType(
                                                    PublicPropertyFilter.FilterType.PROPERTY
                                                )
                                                .operation(
                                                    PublicBoolPropertyOperation.builder()
                                                        .includeObjectsWithNoValueSet(true)
                                                        .operationType(
                                                            PublicBoolPropertyOperation
                                                                .OperationType
                                                                .BOOL
                                                        )
                                                        .operator("operator")
                                                        .value(true)
                                                        .build()
                                                )
                                                .property("property")
                                                .build()
                                        )
                                        .build()
                                )
                                .filterBranchOperator("filterBranchOperator")
                                .filterBranchType(PublicAndFilterBranch.FilterBranchType.AND)
                                .addFilter(
                                    PublicPropertyFilter.builder()
                                        .filterType(PublicPropertyFilter.FilterType.PROPERTY)
                                        .operation(
                                            PublicBoolPropertyOperation.builder()
                                                .includeObjectsWithNoValueSet(true)
                                                .operationType(
                                                    PublicBoolPropertyOperation.OperationType.BOOL
                                                )
                                                .operator("operator")
                                                .value(true)
                                                .build()
                                        )
                                        .property("property")
                                        .build()
                                )
                                .build()
                        )
                        .filterBranchOperator("filterBranchOperator")
                        .filterBranchType(PublicOrFilterBranch.FilterBranchType.OR)
                        .addFilter(
                            PublicPropertyFilter.builder()
                                .filterType(PublicPropertyFilter.FilterType.PROPERTY)
                                .operation(
                                    PublicBoolPropertyOperation.builder()
                                        .includeObjectsWithNoValueSet(true)
                                        .operationType(
                                            PublicBoolPropertyOperation.OperationType.BOOL
                                        )
                                        .operator("operator")
                                        .value(true)
                                        .build()
                                )
                                .property("property")
                                .build()
                        )
                        .build()
                )
                .filterBranchOperator("filterBranchOperator")
                .filterBranchType(PublicRestrictedFilterBranch.FilterBranchType.RESTRICTED)
                .addFilter(
                    PublicPropertyFilter.builder()
                        .filterType(PublicPropertyFilter.FilterType.PROPERTY)
                        .operation(
                            PublicBoolPropertyOperation.builder()
                                .includeObjectsWithNoValueSet(true)
                                .operationType(PublicBoolPropertyOperation.OperationType.BOOL)
                                .operator("operator")
                                .value(true)
                                .build()
                        )
                        .property("property")
                        .build()
                )
                .build()

        assertThat(publicRestrictedFilterBranch.filterBranches())
            .containsExactly(
                PublicRestrictedFilterBranch.FilterBranch.ofOr(
                    PublicOrFilterBranch.builder()
                        .addFilterBranch(
                            PublicAndFilterBranch.builder()
                                .addFilterBranch(
                                    PublicNotAllFilterBranch.builder()
                                        .addFilterBranch(
                                            PublicNotAnyFilterBranch.builder()
                                                .addFilterBranch(
                                                    PublicUnifiedEventsFilterBranch.builder()
                                                        .eventTypeId("eventTypeId")
                                                        .addFilterBranch(
                                                            PublicPropertyAssociationFilterBranch
                                                                .builder()
                                                                .addFilterBranch(
                                                                    PublicAssociationFilterBranch
                                                                        .builder()
                                                                        .associationCategory(
                                                                            "associationCategory"
                                                                        )
                                                                        .associationTypeId(0)
                                                                        .addFilterBranch(
                                                                            PublicOrFilterBranch
                                                                                .builder()
                                                                                .filterBranches(
                                                                                    listOf()
                                                                                )
                                                                                .filterBranchOperator(
                                                                                    "filterBranchOperator"
                                                                                )
                                                                                .filterBranchType(
                                                                                    PublicOrFilterBranch
                                                                                        .FilterBranchType
                                                                                        .OR
                                                                                )
                                                                                .addFilter(
                                                                                    PublicPropertyFilter
                                                                                        .builder()
                                                                                        .filterType(
                                                                                            PublicPropertyFilter
                                                                                                .FilterType
                                                                                                .PROPERTY
                                                                                        )
                                                                                        .operation(
                                                                                            PublicBoolPropertyOperation
                                                                                                .builder()
                                                                                                .includeObjectsWithNoValueSet(
                                                                                                    true
                                                                                                )
                                                                                                .operationType(
                                                                                                    PublicBoolPropertyOperation
                                                                                                        .OperationType
                                                                                                        .BOOL
                                                                                                )
                                                                                                .operator(
                                                                                                    "operator"
                                                                                                )
                                                                                                .value(
                                                                                                    true
                                                                                                )
                                                                                                .build()
                                                                                        )
                                                                                        .property(
                                                                                            "property"
                                                                                        )
                                                                                        .build()
                                                                                )
                                                                                .build()
                                                                        )
                                                                        .filterBranchOperator(
                                                                            "filterBranchOperator"
                                                                        )
                                                                        .filterBranchType(
                                                                            PublicAssociationFilterBranch
                                                                                .FilterBranchType
                                                                                .ASSOCIATION
                                                                        )
                                                                        .addFilter(
                                                                            PublicPropertyFilter
                                                                                .builder()
                                                                                .filterType(
                                                                                    PublicPropertyFilter
                                                                                        .FilterType
                                                                                        .PROPERTY
                                                                                )
                                                                                .operation(
                                                                                    PublicBoolPropertyOperation
                                                                                        .builder()
                                                                                        .includeObjectsWithNoValueSet(
                                                                                            true
                                                                                        )
                                                                                        .operationType(
                                                                                            PublicBoolPropertyOperation
                                                                                                .OperationType
                                                                                                .BOOL
                                                                                        )
                                                                                        .operator(
                                                                                            "operator"
                                                                                        )
                                                                                        .value(true)
                                                                                        .build()
                                                                                )
                                                                                .property(
                                                                                    "property"
                                                                                )
                                                                                .build()
                                                                        )
                                                                        .objectTypeId(
                                                                            "objectTypeId"
                                                                        )
                                                                        .operator("operator")
                                                                        .build()
                                                                )
                                                                .filterBranchOperator(
                                                                    "filterBranchOperator"
                                                                )
                                                                .filterBranchType(
                                                                    PublicPropertyAssociationFilterBranch
                                                                        .FilterBranchType
                                                                        .PROPERTY_ASSOCIATION
                                                                )
                                                                .addFilter(
                                                                    PublicPropertyFilter.builder()
                                                                        .filterType(
                                                                            PublicPropertyFilter
                                                                                .FilterType
                                                                                .PROPERTY
                                                                        )
                                                                        .operation(
                                                                            PublicBoolPropertyOperation
                                                                                .builder()
                                                                                .includeObjectsWithNoValueSet(
                                                                                    true
                                                                                )
                                                                                .operationType(
                                                                                    PublicBoolPropertyOperation
                                                                                        .OperationType
                                                                                        .BOOL
                                                                                )
                                                                                .operator(
                                                                                    "operator"
                                                                                )
                                                                                .value(true)
                                                                                .build()
                                                                        )
                                                                        .property("property")
                                                                        .build()
                                                                )
                                                                .objectTypeId("objectTypeId")
                                                                .operator("operator")
                                                                .propertyWithObjectId(
                                                                    "propertyWithObjectId"
                                                                )
                                                                .build()
                                                        )
                                                        .filterBranchOperator(
                                                            "filterBranchOperator"
                                                        )
                                                        .filterBranchType(
                                                            PublicUnifiedEventsFilterBranch
                                                                .FilterBranchType
                                                                .UNIFIED_EVENTS
                                                        )
                                                        .addFilter(
                                                            PublicPropertyFilter.builder()
                                                                .filterType(
                                                                    PublicPropertyFilter.FilterType
                                                                        .PROPERTY
                                                                )
                                                                .operation(
                                                                    PublicBoolPropertyOperation
                                                                        .builder()
                                                                        .includeObjectsWithNoValueSet(
                                                                            true
                                                                        )
                                                                        .operationType(
                                                                            PublicBoolPropertyOperation
                                                                                .OperationType
                                                                                .BOOL
                                                                        )
                                                                        .operator("operator")
                                                                        .value(true)
                                                                        .build()
                                                                )
                                                                .property("property")
                                                                .build()
                                                        )
                                                        .operator(
                                                            PublicUnifiedEventsFilterBranch.Operator
                                                                .HAS_COMPLETED
                                                        )
                                                        .coalescingRefineBy(
                                                            PublicNumOccurrencesRefineBy.builder()
                                                                .type(
                                                                    PublicNumOccurrencesRefineBy
                                                                        .Type
                                                                        .NUM_OCCURRENCES
                                                                )
                                                                .maxOccurrences(0)
                                                                .minOccurrences(0)
                                                                .build()
                                                        )
                                                        .pruningRefineBy(
                                                            PublicNumOccurrencesRefineBy.builder()
                                                                .type(
                                                                    PublicNumOccurrencesRefineBy
                                                                        .Type
                                                                        .NUM_OCCURRENCES
                                                                )
                                                                .maxOccurrences(0)
                                                                .minOccurrences(0)
                                                                .build()
                                                        )
                                                        .build()
                                                )
                                                .filterBranchOperator("filterBranchOperator")
                                                .filterBranchType(
                                                    PublicNotAnyFilterBranch.FilterBranchType
                                                        .NOT_ANY
                                                )
                                                .addFilter(
                                                    PublicPropertyFilter.builder()
                                                        .filterType(
                                                            PublicPropertyFilter.FilterType.PROPERTY
                                                        )
                                                        .operation(
                                                            PublicBoolPropertyOperation.builder()
                                                                .includeObjectsWithNoValueSet(true)
                                                                .operationType(
                                                                    PublicBoolPropertyOperation
                                                                        .OperationType
                                                                        .BOOL
                                                                )
                                                                .operator("operator")
                                                                .value(true)
                                                                .build()
                                                        )
                                                        .property("property")
                                                        .build()
                                                )
                                                .build()
                                        )
                                        .filterBranchOperator("filterBranchOperator")
                                        .filterBranchType(
                                            PublicNotAllFilterBranch.FilterBranchType.NOT_ALL
                                        )
                                        .addFilter(
                                            PublicPropertyFilter.builder()
                                                .filterType(
                                                    PublicPropertyFilter.FilterType.PROPERTY
                                                )
                                                .operation(
                                                    PublicBoolPropertyOperation.builder()
                                                        .includeObjectsWithNoValueSet(true)
                                                        .operationType(
                                                            PublicBoolPropertyOperation
                                                                .OperationType
                                                                .BOOL
                                                        )
                                                        .operator("operator")
                                                        .value(true)
                                                        .build()
                                                )
                                                .property("property")
                                                .build()
                                        )
                                        .build()
                                )
                                .filterBranchOperator("filterBranchOperator")
                                .filterBranchType(PublicAndFilterBranch.FilterBranchType.AND)
                                .addFilter(
                                    PublicPropertyFilter.builder()
                                        .filterType(PublicPropertyFilter.FilterType.PROPERTY)
                                        .operation(
                                            PublicBoolPropertyOperation.builder()
                                                .includeObjectsWithNoValueSet(true)
                                                .operationType(
                                                    PublicBoolPropertyOperation.OperationType.BOOL
                                                )
                                                .operator("operator")
                                                .value(true)
                                                .build()
                                        )
                                        .property("property")
                                        .build()
                                )
                                .build()
                        )
                        .filterBranchOperator("filterBranchOperator")
                        .filterBranchType(PublicOrFilterBranch.FilterBranchType.OR)
                        .addFilter(
                            PublicPropertyFilter.builder()
                                .filterType(PublicPropertyFilter.FilterType.PROPERTY)
                                .operation(
                                    PublicBoolPropertyOperation.builder()
                                        .includeObjectsWithNoValueSet(true)
                                        .operationType(
                                            PublicBoolPropertyOperation.OperationType.BOOL
                                        )
                                        .operator("operator")
                                        .value(true)
                                        .build()
                                )
                                .property("property")
                                .build()
                        )
                        .build()
                )
            )
        assertThat(publicRestrictedFilterBranch.filterBranchOperator())
            .isEqualTo("filterBranchOperator")
        assertThat(publicRestrictedFilterBranch.filterBranchType())
            .isEqualTo(PublicRestrictedFilterBranch.FilterBranchType.RESTRICTED)
        assertThat(publicRestrictedFilterBranch.filters())
            .containsExactly(
                PublicRestrictedFilterBranch.Filter.ofProperty(
                    PublicPropertyFilter.builder()
                        .filterType(PublicPropertyFilter.FilterType.PROPERTY)
                        .operation(
                            PublicBoolPropertyOperation.builder()
                                .includeObjectsWithNoValueSet(true)
                                .operationType(PublicBoolPropertyOperation.OperationType.BOOL)
                                .operator("operator")
                                .value(true)
                                .build()
                        )
                        .property("property")
                        .build()
                )
            )
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val publicRestrictedFilterBranch =
            PublicRestrictedFilterBranch.builder()
                .addFilterBranch(
                    PublicOrFilterBranch.builder()
                        .addFilterBranch(
                            PublicAndFilterBranch.builder()
                                .addFilterBranch(
                                    PublicNotAllFilterBranch.builder()
                                        .addFilterBranch(
                                            PublicNotAnyFilterBranch.builder()
                                                .addFilterBranch(
                                                    PublicUnifiedEventsFilterBranch.builder()
                                                        .eventTypeId("eventTypeId")
                                                        .addFilterBranch(
                                                            PublicPropertyAssociationFilterBranch
                                                                .builder()
                                                                .addFilterBranch(
                                                                    PublicAssociationFilterBranch
                                                                        .builder()
                                                                        .associationCategory(
                                                                            "associationCategory"
                                                                        )
                                                                        .associationTypeId(0)
                                                                        .addFilterBranch(
                                                                            PublicOrFilterBranch
                                                                                .builder()
                                                                                .filterBranches(
                                                                                    listOf()
                                                                                )
                                                                                .filterBranchOperator(
                                                                                    "filterBranchOperator"
                                                                                )
                                                                                .filterBranchType(
                                                                                    PublicOrFilterBranch
                                                                                        .FilterBranchType
                                                                                        .OR
                                                                                )
                                                                                .addFilter(
                                                                                    PublicPropertyFilter
                                                                                        .builder()
                                                                                        .filterType(
                                                                                            PublicPropertyFilter
                                                                                                .FilterType
                                                                                                .PROPERTY
                                                                                        )
                                                                                        .operation(
                                                                                            PublicBoolPropertyOperation
                                                                                                .builder()
                                                                                                .includeObjectsWithNoValueSet(
                                                                                                    true
                                                                                                )
                                                                                                .operationType(
                                                                                                    PublicBoolPropertyOperation
                                                                                                        .OperationType
                                                                                                        .BOOL
                                                                                                )
                                                                                                .operator(
                                                                                                    "operator"
                                                                                                )
                                                                                                .value(
                                                                                                    true
                                                                                                )
                                                                                                .build()
                                                                                        )
                                                                                        .property(
                                                                                            "property"
                                                                                        )
                                                                                        .build()
                                                                                )
                                                                                .build()
                                                                        )
                                                                        .filterBranchOperator(
                                                                            "filterBranchOperator"
                                                                        )
                                                                        .filterBranchType(
                                                                            PublicAssociationFilterBranch
                                                                                .FilterBranchType
                                                                                .ASSOCIATION
                                                                        )
                                                                        .addFilter(
                                                                            PublicPropertyFilter
                                                                                .builder()
                                                                                .filterType(
                                                                                    PublicPropertyFilter
                                                                                        .FilterType
                                                                                        .PROPERTY
                                                                                )
                                                                                .operation(
                                                                                    PublicBoolPropertyOperation
                                                                                        .builder()
                                                                                        .includeObjectsWithNoValueSet(
                                                                                            true
                                                                                        )
                                                                                        .operationType(
                                                                                            PublicBoolPropertyOperation
                                                                                                .OperationType
                                                                                                .BOOL
                                                                                        )
                                                                                        .operator(
                                                                                            "operator"
                                                                                        )
                                                                                        .value(true)
                                                                                        .build()
                                                                                )
                                                                                .property(
                                                                                    "property"
                                                                                )
                                                                                .build()
                                                                        )
                                                                        .objectTypeId(
                                                                            "objectTypeId"
                                                                        )
                                                                        .operator("operator")
                                                                        .build()
                                                                )
                                                                .filterBranchOperator(
                                                                    "filterBranchOperator"
                                                                )
                                                                .filterBranchType(
                                                                    PublicPropertyAssociationFilterBranch
                                                                        .FilterBranchType
                                                                        .PROPERTY_ASSOCIATION
                                                                )
                                                                .addFilter(
                                                                    PublicPropertyFilter.builder()
                                                                        .filterType(
                                                                            PublicPropertyFilter
                                                                                .FilterType
                                                                                .PROPERTY
                                                                        )
                                                                        .operation(
                                                                            PublicBoolPropertyOperation
                                                                                .builder()
                                                                                .includeObjectsWithNoValueSet(
                                                                                    true
                                                                                )
                                                                                .operationType(
                                                                                    PublicBoolPropertyOperation
                                                                                        .OperationType
                                                                                        .BOOL
                                                                                )
                                                                                .operator(
                                                                                    "operator"
                                                                                )
                                                                                .value(true)
                                                                                .build()
                                                                        )
                                                                        .property("property")
                                                                        .build()
                                                                )
                                                                .objectTypeId("objectTypeId")
                                                                .operator("operator")
                                                                .propertyWithObjectId(
                                                                    "propertyWithObjectId"
                                                                )
                                                                .build()
                                                        )
                                                        .filterBranchOperator(
                                                            "filterBranchOperator"
                                                        )
                                                        .filterBranchType(
                                                            PublicUnifiedEventsFilterBranch
                                                                .FilterBranchType
                                                                .UNIFIED_EVENTS
                                                        )
                                                        .addFilter(
                                                            PublicPropertyFilter.builder()
                                                                .filterType(
                                                                    PublicPropertyFilter.FilterType
                                                                        .PROPERTY
                                                                )
                                                                .operation(
                                                                    PublicBoolPropertyOperation
                                                                        .builder()
                                                                        .includeObjectsWithNoValueSet(
                                                                            true
                                                                        )
                                                                        .operationType(
                                                                            PublicBoolPropertyOperation
                                                                                .OperationType
                                                                                .BOOL
                                                                        )
                                                                        .operator("operator")
                                                                        .value(true)
                                                                        .build()
                                                                )
                                                                .property("property")
                                                                .build()
                                                        )
                                                        .operator(
                                                            PublicUnifiedEventsFilterBranch.Operator
                                                                .HAS_COMPLETED
                                                        )
                                                        .coalescingRefineBy(
                                                            PublicNumOccurrencesRefineBy.builder()
                                                                .type(
                                                                    PublicNumOccurrencesRefineBy
                                                                        .Type
                                                                        .NUM_OCCURRENCES
                                                                )
                                                                .maxOccurrences(0)
                                                                .minOccurrences(0)
                                                                .build()
                                                        )
                                                        .pruningRefineBy(
                                                            PublicNumOccurrencesRefineBy.builder()
                                                                .type(
                                                                    PublicNumOccurrencesRefineBy
                                                                        .Type
                                                                        .NUM_OCCURRENCES
                                                                )
                                                                .maxOccurrences(0)
                                                                .minOccurrences(0)
                                                                .build()
                                                        )
                                                        .build()
                                                )
                                                .filterBranchOperator("filterBranchOperator")
                                                .filterBranchType(
                                                    PublicNotAnyFilterBranch.FilterBranchType
                                                        .NOT_ANY
                                                )
                                                .addFilter(
                                                    PublicPropertyFilter.builder()
                                                        .filterType(
                                                            PublicPropertyFilter.FilterType.PROPERTY
                                                        )
                                                        .operation(
                                                            PublicBoolPropertyOperation.builder()
                                                                .includeObjectsWithNoValueSet(true)
                                                                .operationType(
                                                                    PublicBoolPropertyOperation
                                                                        .OperationType
                                                                        .BOOL
                                                                )
                                                                .operator("operator")
                                                                .value(true)
                                                                .build()
                                                        )
                                                        .property("property")
                                                        .build()
                                                )
                                                .build()
                                        )
                                        .filterBranchOperator("filterBranchOperator")
                                        .filterBranchType(
                                            PublicNotAllFilterBranch.FilterBranchType.NOT_ALL
                                        )
                                        .addFilter(
                                            PublicPropertyFilter.builder()
                                                .filterType(
                                                    PublicPropertyFilter.FilterType.PROPERTY
                                                )
                                                .operation(
                                                    PublicBoolPropertyOperation.builder()
                                                        .includeObjectsWithNoValueSet(true)
                                                        .operationType(
                                                            PublicBoolPropertyOperation
                                                                .OperationType
                                                                .BOOL
                                                        )
                                                        .operator("operator")
                                                        .value(true)
                                                        .build()
                                                )
                                                .property("property")
                                                .build()
                                        )
                                        .build()
                                )
                                .filterBranchOperator("filterBranchOperator")
                                .filterBranchType(PublicAndFilterBranch.FilterBranchType.AND)
                                .addFilter(
                                    PublicPropertyFilter.builder()
                                        .filterType(PublicPropertyFilter.FilterType.PROPERTY)
                                        .operation(
                                            PublicBoolPropertyOperation.builder()
                                                .includeObjectsWithNoValueSet(true)
                                                .operationType(
                                                    PublicBoolPropertyOperation.OperationType.BOOL
                                                )
                                                .operator("operator")
                                                .value(true)
                                                .build()
                                        )
                                        .property("property")
                                        .build()
                                )
                                .build()
                        )
                        .filterBranchOperator("filterBranchOperator")
                        .filterBranchType(PublicOrFilterBranch.FilterBranchType.OR)
                        .addFilter(
                            PublicPropertyFilter.builder()
                                .filterType(PublicPropertyFilter.FilterType.PROPERTY)
                                .operation(
                                    PublicBoolPropertyOperation.builder()
                                        .includeObjectsWithNoValueSet(true)
                                        .operationType(
                                            PublicBoolPropertyOperation.OperationType.BOOL
                                        )
                                        .operator("operator")
                                        .value(true)
                                        .build()
                                )
                                .property("property")
                                .build()
                        )
                        .build()
                )
                .filterBranchOperator("filterBranchOperator")
                .filterBranchType(PublicRestrictedFilterBranch.FilterBranchType.RESTRICTED)
                .addFilter(
                    PublicPropertyFilter.builder()
                        .filterType(PublicPropertyFilter.FilterType.PROPERTY)
                        .operation(
                            PublicBoolPropertyOperation.builder()
                                .includeObjectsWithNoValueSet(true)
                                .operationType(PublicBoolPropertyOperation.OperationType.BOOL)
                                .operator("operator")
                                .value(true)
                                .build()
                        )
                        .property("property")
                        .build()
                )
                .build()

        val roundtrippedPublicRestrictedFilterBranch =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(publicRestrictedFilterBranch),
                jacksonTypeRef<PublicRestrictedFilterBranch>(),
            )

        assertThat(roundtrippedPublicRestrictedFilterBranch).isEqualTo(publicRestrictedFilterBranch)
    }
}
