// File generated from our OpenAPI spec by Stainless.

package com.hubspot.models.cms.hubdb

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.hubspot.core.JsonValue
import com.hubspot.core.jsonMapper
import com.hubspot.models.NextPage
import com.hubspot.models.Paging
import com.hubspot.models.PreviousPage
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class CollectionResponseWithTotalHubDbTableV3Test {

    @Test
    fun create() {
        val collectionResponseWithTotalHubDbTableV3 =
            CollectionResponseWithTotalHubDbTableV3.builder()
                .addResult(
                    HubDbTableV3.builder()
                        .id("id")
                        .allowChildTables(true)
                        .allowPublicApiAccess(true)
                        .columnCount(0)
                        .addColumn(
                            Column.builder()
                                .id("id")
                                .deleted(true)
                                .description("description")
                                .label("label")
                                .name("name")
                                .type(Column.Type.BOOLEAN)
                                .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .createdBy(
                                    SimpleUser.builder()
                                        .id("id")
                                        .email("email")
                                        .firstName("firstName")
                                        .lastName("lastName")
                                        .build()
                                )
                                .createdByUserId(0)
                                .foreignColumnId(0)
                                .addForeignId(
                                    ForeignId.builder().id("id").name("name").type("type").build()
                                )
                                .foreignIdsById(
                                    Column.ForeignIdsById.builder()
                                        .putAdditionalProperty(
                                            "foo",
                                            JsonValue.from(
                                                mapOf(
                                                    "id" to "id",
                                                    "name" to "name",
                                                    "type" to "type",
                                                )
                                            ),
                                        )
                                        .build()
                                )
                                .foreignIdsByName(
                                    Column.ForeignIdsByName.builder()
                                        .putAdditionalProperty(
                                            "foo",
                                            JsonValue.from(
                                                mapOf(
                                                    "id" to "id",
                                                    "name" to "name",
                                                    "type" to "type",
                                                )
                                            ),
                                        )
                                        .build()
                                )
                                .foreignTableId(0L)
                                .optionCount(0)
                                .addOption(
                                    Option.builder()
                                        .id("id")
                                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                        .label("label")
                                        .name("name")
                                        .order(0)
                                        .type("type")
                                        .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                        .createdBy(
                                            SimpleUser.builder()
                                                .id("id")
                                                .email("email")
                                                .firstName("firstName")
                                                .lastName("lastName")
                                                .build()
                                        )
                                        .createdByUserId(0)
                                        .updatedBy(
                                            SimpleUser.builder()
                                                .id("id")
                                                .email("email")
                                                .firstName("firstName")
                                                .lastName("lastName")
                                                .build()
                                        )
                                        .updatedByUserId(0)
                                        .build()
                                )
                                .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .updatedBy(
                                    SimpleUser.builder()
                                        .id("id")
                                        .email("email")
                                        .firstName("firstName")
                                        .lastName("lastName")
                                        .build()
                                )
                                .updatedByUserId(0)
                                .width(0)
                                .build()
                        )
                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .deleted(true)
                        .deletedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .dynamicMetaTags(
                            HubDbTableV3.DynamicMetaTags.builder()
                                .putAdditionalProperty("foo", JsonValue.from(0))
                                .build()
                        )
                        .enableChildTablePages(true)
                        .label("label")
                        .name("name")
                        .published(true)
                        .publishedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .rowCount(0)
                        .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .useForPages(true)
                        .createdBy(
                            SimpleUser.builder()
                                .id("id")
                                .email("email")
                                .firstName("firstName")
                                .lastName("lastName")
                                .build()
                        )
                        .isOrderedManually(true)
                        .updatedBy(
                            SimpleUser.builder()
                                .id("id")
                                .email("email")
                                .firstName("firstName")
                                .lastName("lastName")
                                .build()
                        )
                        .build()
                )
                .total(0)
                .paging(
                    Paging.builder()
                        .next(NextPage.builder().after("after").link("link").build())
                        .prev(PreviousPage.builder().before("before").link("link").build())
                        .build()
                )
                .build()

        assertThat(collectionResponseWithTotalHubDbTableV3.results())
            .containsExactly(
                HubDbTableV3.builder()
                    .id("id")
                    .allowChildTables(true)
                    .allowPublicApiAccess(true)
                    .columnCount(0)
                    .addColumn(
                        Column.builder()
                            .id("id")
                            .deleted(true)
                            .description("description")
                            .label("label")
                            .name("name")
                            .type(Column.Type.BOOLEAN)
                            .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .createdBy(
                                SimpleUser.builder()
                                    .id("id")
                                    .email("email")
                                    .firstName("firstName")
                                    .lastName("lastName")
                                    .build()
                            )
                            .createdByUserId(0)
                            .foreignColumnId(0)
                            .addForeignId(
                                ForeignId.builder().id("id").name("name").type("type").build()
                            )
                            .foreignIdsById(
                                Column.ForeignIdsById.builder()
                                    .putAdditionalProperty(
                                        "foo",
                                        JsonValue.from(
                                            mapOf("id" to "id", "name" to "name", "type" to "type")
                                        ),
                                    )
                                    .build()
                            )
                            .foreignIdsByName(
                                Column.ForeignIdsByName.builder()
                                    .putAdditionalProperty(
                                        "foo",
                                        JsonValue.from(
                                            mapOf("id" to "id", "name" to "name", "type" to "type")
                                        ),
                                    )
                                    .build()
                            )
                            .foreignTableId(0L)
                            .optionCount(0)
                            .addOption(
                                Option.builder()
                                    .id("id")
                                    .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .label("label")
                                    .name("name")
                                    .order(0)
                                    .type("type")
                                    .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .createdBy(
                                        SimpleUser.builder()
                                            .id("id")
                                            .email("email")
                                            .firstName("firstName")
                                            .lastName("lastName")
                                            .build()
                                    )
                                    .createdByUserId(0)
                                    .updatedBy(
                                        SimpleUser.builder()
                                            .id("id")
                                            .email("email")
                                            .firstName("firstName")
                                            .lastName("lastName")
                                            .build()
                                    )
                                    .updatedByUserId(0)
                                    .build()
                            )
                            .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .updatedBy(
                                SimpleUser.builder()
                                    .id("id")
                                    .email("email")
                                    .firstName("firstName")
                                    .lastName("lastName")
                                    .build()
                            )
                            .updatedByUserId(0)
                            .width(0)
                            .build()
                    )
                    .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .deleted(true)
                    .deletedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .dynamicMetaTags(
                        HubDbTableV3.DynamicMetaTags.builder()
                            .putAdditionalProperty("foo", JsonValue.from(0))
                            .build()
                    )
                    .enableChildTablePages(true)
                    .label("label")
                    .name("name")
                    .published(true)
                    .publishedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .rowCount(0)
                    .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .useForPages(true)
                    .createdBy(
                        SimpleUser.builder()
                            .id("id")
                            .email("email")
                            .firstName("firstName")
                            .lastName("lastName")
                            .build()
                    )
                    .isOrderedManually(true)
                    .updatedBy(
                        SimpleUser.builder()
                            .id("id")
                            .email("email")
                            .firstName("firstName")
                            .lastName("lastName")
                            .build()
                    )
                    .build()
            )
        assertThat(collectionResponseWithTotalHubDbTableV3.total()).isEqualTo(0)
        assertThat(collectionResponseWithTotalHubDbTableV3.paging())
            .contains(
                Paging.builder()
                    .next(NextPage.builder().after("after").link("link").build())
                    .prev(PreviousPage.builder().before("before").link("link").build())
                    .build()
            )
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val collectionResponseWithTotalHubDbTableV3 =
            CollectionResponseWithTotalHubDbTableV3.builder()
                .addResult(
                    HubDbTableV3.builder()
                        .id("id")
                        .allowChildTables(true)
                        .allowPublicApiAccess(true)
                        .columnCount(0)
                        .addColumn(
                            Column.builder()
                                .id("id")
                                .deleted(true)
                                .description("description")
                                .label("label")
                                .name("name")
                                .type(Column.Type.BOOLEAN)
                                .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .createdBy(
                                    SimpleUser.builder()
                                        .id("id")
                                        .email("email")
                                        .firstName("firstName")
                                        .lastName("lastName")
                                        .build()
                                )
                                .createdByUserId(0)
                                .foreignColumnId(0)
                                .addForeignId(
                                    ForeignId.builder().id("id").name("name").type("type").build()
                                )
                                .foreignIdsById(
                                    Column.ForeignIdsById.builder()
                                        .putAdditionalProperty(
                                            "foo",
                                            JsonValue.from(
                                                mapOf(
                                                    "id" to "id",
                                                    "name" to "name",
                                                    "type" to "type",
                                                )
                                            ),
                                        )
                                        .build()
                                )
                                .foreignIdsByName(
                                    Column.ForeignIdsByName.builder()
                                        .putAdditionalProperty(
                                            "foo",
                                            JsonValue.from(
                                                mapOf(
                                                    "id" to "id",
                                                    "name" to "name",
                                                    "type" to "type",
                                                )
                                            ),
                                        )
                                        .build()
                                )
                                .foreignTableId(0L)
                                .optionCount(0)
                                .addOption(
                                    Option.builder()
                                        .id("id")
                                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                        .label("label")
                                        .name("name")
                                        .order(0)
                                        .type("type")
                                        .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                        .createdBy(
                                            SimpleUser.builder()
                                                .id("id")
                                                .email("email")
                                                .firstName("firstName")
                                                .lastName("lastName")
                                                .build()
                                        )
                                        .createdByUserId(0)
                                        .updatedBy(
                                            SimpleUser.builder()
                                                .id("id")
                                                .email("email")
                                                .firstName("firstName")
                                                .lastName("lastName")
                                                .build()
                                        )
                                        .updatedByUserId(0)
                                        .build()
                                )
                                .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .updatedBy(
                                    SimpleUser.builder()
                                        .id("id")
                                        .email("email")
                                        .firstName("firstName")
                                        .lastName("lastName")
                                        .build()
                                )
                                .updatedByUserId(0)
                                .width(0)
                                .build()
                        )
                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .deleted(true)
                        .deletedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .dynamicMetaTags(
                            HubDbTableV3.DynamicMetaTags.builder()
                                .putAdditionalProperty("foo", JsonValue.from(0))
                                .build()
                        )
                        .enableChildTablePages(true)
                        .label("label")
                        .name("name")
                        .published(true)
                        .publishedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .rowCount(0)
                        .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .useForPages(true)
                        .createdBy(
                            SimpleUser.builder()
                                .id("id")
                                .email("email")
                                .firstName("firstName")
                                .lastName("lastName")
                                .build()
                        )
                        .isOrderedManually(true)
                        .updatedBy(
                            SimpleUser.builder()
                                .id("id")
                                .email("email")
                                .firstName("firstName")
                                .lastName("lastName")
                                .build()
                        )
                        .build()
                )
                .total(0)
                .paging(
                    Paging.builder()
                        .next(NextPage.builder().after("after").link("link").build())
                        .prev(PreviousPage.builder().before("before").link("link").build())
                        .build()
                )
                .build()

        val roundtrippedCollectionResponseWithTotalHubDbTableV3 =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(collectionResponseWithTotalHubDbTableV3),
                jacksonTypeRef<CollectionResponseWithTotalHubDbTableV3>(),
            )

        assertThat(roundtrippedCollectionResponseWithTotalHubDbTableV3)
            .isEqualTo(collectionResponseWithTotalHubDbTableV3)
    }
}
