// File generated from our OpenAPI spec by Stainless.

package com.hubspot_sdk.api.models.crm.imports

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.hubspot_sdk.api.core.JsonValue
import com.hubspot_sdk.api.core.jsonMapper
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class PublicImportResponseTest {

    @Test
    fun create() {
        val publicImportResponse =
            PublicImportResponse.builder()
                .id("1471")
                .createdAt(OffsetDateTime.parse("2020-01-14T22:45:00.153+00:00"))
                .addMappedObjectTypeId("string")
                .metadata(
                    PublicImportMetadata.builder()
                        .counters(
                            PublicImportMetadata.Counters.builder()
                                .putAdditionalProperty("0", JsonValue.from(0))
                                .putAdditionalProperty("1", JsonValue.from(0))
                                .putAdditionalProperty("2", JsonValue.from(0))
                                .putAdditionalProperty("3", JsonValue.from(0))
                                .putAdditionalProperty("4", JsonValue.from(0))
                                .putAdditionalProperty("5", JsonValue.from(0))
                                .putAdditionalProperty("6", JsonValue.from(0))
                                .putAdditionalProperty("7", JsonValue.from(0))
                                .putAdditionalProperty("8", JsonValue.from(0))
                                .putAdditionalProperty("9", JsonValue.from(0))
                                .putAdditionalProperty("10", JsonValue.from(0))
                                .putAdditionalProperty("11", JsonValue.from(0))
                                .putAdditionalProperty("12", JsonValue.from(0))
                                .putAdditionalProperty("13", JsonValue.from(0))
                                .putAdditionalProperty("14", JsonValue.from(0))
                                .putAdditionalProperty("15", JsonValue.from(0))
                                .putAdditionalProperty("16", JsonValue.from(0))
                                .putAdditionalProperty("17", JsonValue.from(0))
                                .putAdditionalProperty("18", JsonValue.from(0))
                                .putAdditionalProperty("19", JsonValue.from(0))
                                .putAdditionalProperty("20", JsonValue.from(0))
                                .putAdditionalProperty("21", JsonValue.from(0))
                                .putAdditionalProperty("22", JsonValue.from(0))
                                .putAdditionalProperty("23", JsonValue.from(0))
                                .putAdditionalProperty("24", JsonValue.from(0))
                                .putAdditionalProperty("25", JsonValue.from(0))
                                .putAdditionalProperty("26", JsonValue.from(0))
                                .putAdditionalProperty("27", JsonValue.from(0))
                                .putAdditionalProperty("28", JsonValue.from(0))
                                .putAdditionalProperty("29", JsonValue.from(0))
                                .putAdditionalProperty("30", JsonValue.from(0))
                                .putAdditionalProperty("31", JsonValue.from(0))
                                .putAdditionalProperty("32", JsonValue.from(0))
                                .putAdditionalProperty("33", JsonValue.from(0))
                                .putAdditionalProperty("34", JsonValue.from(0))
                                .putAdditionalProperty("35", JsonValue.from(0))
                                .putAdditionalProperty("36", JsonValue.from(0))
                                .putAdditionalProperty("37", JsonValue.from(0))
                                .putAdditionalProperty("38", JsonValue.from(0))
                                .putAdditionalProperty("39", JsonValue.from(0))
                                .putAdditionalProperty("40", JsonValue.from(0))
                                .putAdditionalProperty("41", JsonValue.from(0))
                                .putAdditionalProperty("42", JsonValue.from(0))
                                .putAdditionalProperty("43", JsonValue.from(0))
                                .putAdditionalProperty("44", JsonValue.from(0))
                                .putAdditionalProperty("45", JsonValue.from(0))
                                .putAdditionalProperty("46", JsonValue.from(0))
                                .putAdditionalProperty("47", JsonValue.from(0))
                                .putAdditionalProperty("48", JsonValue.from(0))
                                .putAdditionalProperty("49", JsonValue.from(0))
                                .putAdditionalProperty("50", JsonValue.from(0))
                                .putAdditionalProperty("51", JsonValue.from(0))
                                .putAdditionalProperty("52", JsonValue.from(0))
                                .putAdditionalProperty("53", JsonValue.from(0))
                                .putAdditionalProperty("54", JsonValue.from(0))
                                .putAdditionalProperty("55", JsonValue.from(0))
                                .putAdditionalProperty("56", JsonValue.from(0))
                                .putAdditionalProperty("57", JsonValue.from(0))
                                .putAdditionalProperty("58", JsonValue.from(0))
                                .putAdditionalProperty("59", JsonValue.from(0))
                                .putAdditionalProperty("60", JsonValue.from(0))
                                .putAdditionalProperty("61", JsonValue.from(0))
                                .putAdditionalProperty("62", JsonValue.from(0))
                                .putAdditionalProperty("63", JsonValue.from(0))
                                .putAdditionalProperty("64", JsonValue.from(0))
                                .putAdditionalProperty("65", JsonValue.from(0))
                                .putAdditionalProperty("66", JsonValue.from(0))
                                .putAdditionalProperty("67", JsonValue.from(0))
                                .putAdditionalProperty("68", JsonValue.from(0))
                                .putAdditionalProperty("69", JsonValue.from(0))
                                .putAdditionalProperty("70", JsonValue.from(0))
                                .putAdditionalProperty("71", JsonValue.from(0))
                                .putAdditionalProperty("72", JsonValue.from(0))
                                .putAdditionalProperty("73", JsonValue.from(0))
                                .putAdditionalProperty("74", JsonValue.from(0))
                                .putAdditionalProperty("75", JsonValue.from(0))
                                .putAdditionalProperty("76", JsonValue.from(0))
                                .putAdditionalProperty("77", JsonValue.from(0))
                                .putAdditionalProperty("78", JsonValue.from(0))
                                .putAdditionalProperty("79", JsonValue.from(0))
                                .putAdditionalProperty("80", JsonValue.from(0))
                                .putAdditionalProperty("81", JsonValue.from(0))
                                .putAdditionalProperty("82", JsonValue.from(0))
                                .putAdditionalProperty("83", JsonValue.from(0))
                                .putAdditionalProperty("84", JsonValue.from(0))
                                .putAdditionalProperty("85", JsonValue.from(0))
                                .putAdditionalProperty("86", JsonValue.from(0))
                                .putAdditionalProperty("87", JsonValue.from(0))
                                .putAdditionalProperty("88", JsonValue.from(0))
                                .putAdditionalProperty("89", JsonValue.from(0))
                                .putAdditionalProperty("90", JsonValue.from(0))
                                .putAdditionalProperty("91", JsonValue.from(0))
                                .putAdditionalProperty("92", JsonValue.from(0))
                                .putAdditionalProperty("93", JsonValue.from(0))
                                .putAdditionalProperty("94", JsonValue.from(0))
                                .putAdditionalProperty("95", JsonValue.from(0))
                                .putAdditionalProperty("96", JsonValue.from(0))
                                .putAdditionalProperty("97", JsonValue.from(0))
                                .putAdditionalProperty("98", JsonValue.from(0))
                                .putAdditionalProperty("99", JsonValue.from(0))
                                .putAdditionalProperty("100", JsonValue.from(0))
                                .putAdditionalProperty("101", JsonValue.from(0))
                                .putAdditionalProperty("102", JsonValue.from(0))
                                .putAdditionalProperty("103", JsonValue.from(0))
                                .putAdditionalProperty("104", JsonValue.from(0))
                                .putAdditionalProperty("105", JsonValue.from(0))
                                .putAdditionalProperty("106", JsonValue.from(0))
                                .putAdditionalProperty("107", JsonValue.from(0))
                                .putAdditionalProperty("108", JsonValue.from(0))
                                .putAdditionalProperty("109", JsonValue.from(0))
                                .putAdditionalProperty("110", JsonValue.from(0))
                                .build()
                        )
                        .addFileId("string")
                        .addObjectList(
                            PublicObjectListRecord.builder()
                                .listId("3")
                                .objectType("contacts")
                                .build()
                        )
                        .build()
                )
                .optOutImport(false)
                .state(PublicImportResponse.State.DONE)
                .updatedAt(OffsetDateTime.parse("2020-01-14T22:45:00.153+00:00"))
                .importName("importName")
                .importRequestJson(JsonValue.from(mapOf<String, Any>()))
                .importSource(PublicImportResponse.ImportSource.API)
                .importTemplate(
                    ImportTemplate.builder()
                        .templateId(0)
                        .templateType(ImportTemplate.TemplateType.ADMIN_DEFINED)
                        .build()
                )
                .build()

        assertThat(publicImportResponse.id()).isEqualTo("1471")
        assertThat(publicImportResponse.createdAt())
            .isEqualTo(OffsetDateTime.parse("2020-01-14T22:45:00.153+00:00"))
        assertThat(publicImportResponse.mappedObjectTypeIds()).containsExactly("string")
        assertThat(publicImportResponse.metadata())
            .isEqualTo(
                PublicImportMetadata.builder()
                    .counters(
                        PublicImportMetadata.Counters.builder()
                            .putAdditionalProperty("0", JsonValue.from(0))
                            .putAdditionalProperty("1", JsonValue.from(0))
                            .putAdditionalProperty("2", JsonValue.from(0))
                            .putAdditionalProperty("3", JsonValue.from(0))
                            .putAdditionalProperty("4", JsonValue.from(0))
                            .putAdditionalProperty("5", JsonValue.from(0))
                            .putAdditionalProperty("6", JsonValue.from(0))
                            .putAdditionalProperty("7", JsonValue.from(0))
                            .putAdditionalProperty("8", JsonValue.from(0))
                            .putAdditionalProperty("9", JsonValue.from(0))
                            .putAdditionalProperty("10", JsonValue.from(0))
                            .putAdditionalProperty("11", JsonValue.from(0))
                            .putAdditionalProperty("12", JsonValue.from(0))
                            .putAdditionalProperty("13", JsonValue.from(0))
                            .putAdditionalProperty("14", JsonValue.from(0))
                            .putAdditionalProperty("15", JsonValue.from(0))
                            .putAdditionalProperty("16", JsonValue.from(0))
                            .putAdditionalProperty("17", JsonValue.from(0))
                            .putAdditionalProperty("18", JsonValue.from(0))
                            .putAdditionalProperty("19", JsonValue.from(0))
                            .putAdditionalProperty("20", JsonValue.from(0))
                            .putAdditionalProperty("21", JsonValue.from(0))
                            .putAdditionalProperty("22", JsonValue.from(0))
                            .putAdditionalProperty("23", JsonValue.from(0))
                            .putAdditionalProperty("24", JsonValue.from(0))
                            .putAdditionalProperty("25", JsonValue.from(0))
                            .putAdditionalProperty("26", JsonValue.from(0))
                            .putAdditionalProperty("27", JsonValue.from(0))
                            .putAdditionalProperty("28", JsonValue.from(0))
                            .putAdditionalProperty("29", JsonValue.from(0))
                            .putAdditionalProperty("30", JsonValue.from(0))
                            .putAdditionalProperty("31", JsonValue.from(0))
                            .putAdditionalProperty("32", JsonValue.from(0))
                            .putAdditionalProperty("33", JsonValue.from(0))
                            .putAdditionalProperty("34", JsonValue.from(0))
                            .putAdditionalProperty("35", JsonValue.from(0))
                            .putAdditionalProperty("36", JsonValue.from(0))
                            .putAdditionalProperty("37", JsonValue.from(0))
                            .putAdditionalProperty("38", JsonValue.from(0))
                            .putAdditionalProperty("39", JsonValue.from(0))
                            .putAdditionalProperty("40", JsonValue.from(0))
                            .putAdditionalProperty("41", JsonValue.from(0))
                            .putAdditionalProperty("42", JsonValue.from(0))
                            .putAdditionalProperty("43", JsonValue.from(0))
                            .putAdditionalProperty("44", JsonValue.from(0))
                            .putAdditionalProperty("45", JsonValue.from(0))
                            .putAdditionalProperty("46", JsonValue.from(0))
                            .putAdditionalProperty("47", JsonValue.from(0))
                            .putAdditionalProperty("48", JsonValue.from(0))
                            .putAdditionalProperty("49", JsonValue.from(0))
                            .putAdditionalProperty("50", JsonValue.from(0))
                            .putAdditionalProperty("51", JsonValue.from(0))
                            .putAdditionalProperty("52", JsonValue.from(0))
                            .putAdditionalProperty("53", JsonValue.from(0))
                            .putAdditionalProperty("54", JsonValue.from(0))
                            .putAdditionalProperty("55", JsonValue.from(0))
                            .putAdditionalProperty("56", JsonValue.from(0))
                            .putAdditionalProperty("57", JsonValue.from(0))
                            .putAdditionalProperty("58", JsonValue.from(0))
                            .putAdditionalProperty("59", JsonValue.from(0))
                            .putAdditionalProperty("60", JsonValue.from(0))
                            .putAdditionalProperty("61", JsonValue.from(0))
                            .putAdditionalProperty("62", JsonValue.from(0))
                            .putAdditionalProperty("63", JsonValue.from(0))
                            .putAdditionalProperty("64", JsonValue.from(0))
                            .putAdditionalProperty("65", JsonValue.from(0))
                            .putAdditionalProperty("66", JsonValue.from(0))
                            .putAdditionalProperty("67", JsonValue.from(0))
                            .putAdditionalProperty("68", JsonValue.from(0))
                            .putAdditionalProperty("69", JsonValue.from(0))
                            .putAdditionalProperty("70", JsonValue.from(0))
                            .putAdditionalProperty("71", JsonValue.from(0))
                            .putAdditionalProperty("72", JsonValue.from(0))
                            .putAdditionalProperty("73", JsonValue.from(0))
                            .putAdditionalProperty("74", JsonValue.from(0))
                            .putAdditionalProperty("75", JsonValue.from(0))
                            .putAdditionalProperty("76", JsonValue.from(0))
                            .putAdditionalProperty("77", JsonValue.from(0))
                            .putAdditionalProperty("78", JsonValue.from(0))
                            .putAdditionalProperty("79", JsonValue.from(0))
                            .putAdditionalProperty("80", JsonValue.from(0))
                            .putAdditionalProperty("81", JsonValue.from(0))
                            .putAdditionalProperty("82", JsonValue.from(0))
                            .putAdditionalProperty("83", JsonValue.from(0))
                            .putAdditionalProperty("84", JsonValue.from(0))
                            .putAdditionalProperty("85", JsonValue.from(0))
                            .putAdditionalProperty("86", JsonValue.from(0))
                            .putAdditionalProperty("87", JsonValue.from(0))
                            .putAdditionalProperty("88", JsonValue.from(0))
                            .putAdditionalProperty("89", JsonValue.from(0))
                            .putAdditionalProperty("90", JsonValue.from(0))
                            .putAdditionalProperty("91", JsonValue.from(0))
                            .putAdditionalProperty("92", JsonValue.from(0))
                            .putAdditionalProperty("93", JsonValue.from(0))
                            .putAdditionalProperty("94", JsonValue.from(0))
                            .putAdditionalProperty("95", JsonValue.from(0))
                            .putAdditionalProperty("96", JsonValue.from(0))
                            .putAdditionalProperty("97", JsonValue.from(0))
                            .putAdditionalProperty("98", JsonValue.from(0))
                            .putAdditionalProperty("99", JsonValue.from(0))
                            .putAdditionalProperty("100", JsonValue.from(0))
                            .putAdditionalProperty("101", JsonValue.from(0))
                            .putAdditionalProperty("102", JsonValue.from(0))
                            .putAdditionalProperty("103", JsonValue.from(0))
                            .putAdditionalProperty("104", JsonValue.from(0))
                            .putAdditionalProperty("105", JsonValue.from(0))
                            .putAdditionalProperty("106", JsonValue.from(0))
                            .putAdditionalProperty("107", JsonValue.from(0))
                            .putAdditionalProperty("108", JsonValue.from(0))
                            .putAdditionalProperty("109", JsonValue.from(0))
                            .putAdditionalProperty("110", JsonValue.from(0))
                            .build()
                    )
                    .addFileId("string")
                    .addObjectList(
                        PublicObjectListRecord.builder().listId("3").objectType("contacts").build()
                    )
                    .build()
            )
        assertThat(publicImportResponse.optOutImport()).isEqualTo(false)
        assertThat(publicImportResponse.state()).isEqualTo(PublicImportResponse.State.DONE)
        assertThat(publicImportResponse.updatedAt())
            .isEqualTo(OffsetDateTime.parse("2020-01-14T22:45:00.153+00:00"))
        assertThat(publicImportResponse.importName()).contains("importName")
        assertThat(publicImportResponse._importRequestJson())
            .isEqualTo(JsonValue.from(mapOf<String, Any>()))
        assertThat(publicImportResponse.importSource())
            .contains(PublicImportResponse.ImportSource.API)
        assertThat(publicImportResponse.importTemplate())
            .contains(
                ImportTemplate.builder()
                    .templateId(0)
                    .templateType(ImportTemplate.TemplateType.ADMIN_DEFINED)
                    .build()
            )
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val publicImportResponse =
            PublicImportResponse.builder()
                .id("1471")
                .createdAt(OffsetDateTime.parse("2020-01-14T22:45:00.153+00:00"))
                .addMappedObjectTypeId("string")
                .metadata(
                    PublicImportMetadata.builder()
                        .counters(
                            PublicImportMetadata.Counters.builder()
                                .putAdditionalProperty("0", JsonValue.from(0))
                                .putAdditionalProperty("1", JsonValue.from(0))
                                .putAdditionalProperty("2", JsonValue.from(0))
                                .putAdditionalProperty("3", JsonValue.from(0))
                                .putAdditionalProperty("4", JsonValue.from(0))
                                .putAdditionalProperty("5", JsonValue.from(0))
                                .putAdditionalProperty("6", JsonValue.from(0))
                                .putAdditionalProperty("7", JsonValue.from(0))
                                .putAdditionalProperty("8", JsonValue.from(0))
                                .putAdditionalProperty("9", JsonValue.from(0))
                                .putAdditionalProperty("10", JsonValue.from(0))
                                .putAdditionalProperty("11", JsonValue.from(0))
                                .putAdditionalProperty("12", JsonValue.from(0))
                                .putAdditionalProperty("13", JsonValue.from(0))
                                .putAdditionalProperty("14", JsonValue.from(0))
                                .putAdditionalProperty("15", JsonValue.from(0))
                                .putAdditionalProperty("16", JsonValue.from(0))
                                .putAdditionalProperty("17", JsonValue.from(0))
                                .putAdditionalProperty("18", JsonValue.from(0))
                                .putAdditionalProperty("19", JsonValue.from(0))
                                .putAdditionalProperty("20", JsonValue.from(0))
                                .putAdditionalProperty("21", JsonValue.from(0))
                                .putAdditionalProperty("22", JsonValue.from(0))
                                .putAdditionalProperty("23", JsonValue.from(0))
                                .putAdditionalProperty("24", JsonValue.from(0))
                                .putAdditionalProperty("25", JsonValue.from(0))
                                .putAdditionalProperty("26", JsonValue.from(0))
                                .putAdditionalProperty("27", JsonValue.from(0))
                                .putAdditionalProperty("28", JsonValue.from(0))
                                .putAdditionalProperty("29", JsonValue.from(0))
                                .putAdditionalProperty("30", JsonValue.from(0))
                                .putAdditionalProperty("31", JsonValue.from(0))
                                .putAdditionalProperty("32", JsonValue.from(0))
                                .putAdditionalProperty("33", JsonValue.from(0))
                                .putAdditionalProperty("34", JsonValue.from(0))
                                .putAdditionalProperty("35", JsonValue.from(0))
                                .putAdditionalProperty("36", JsonValue.from(0))
                                .putAdditionalProperty("37", JsonValue.from(0))
                                .putAdditionalProperty("38", JsonValue.from(0))
                                .putAdditionalProperty("39", JsonValue.from(0))
                                .putAdditionalProperty("40", JsonValue.from(0))
                                .putAdditionalProperty("41", JsonValue.from(0))
                                .putAdditionalProperty("42", JsonValue.from(0))
                                .putAdditionalProperty("43", JsonValue.from(0))
                                .putAdditionalProperty("44", JsonValue.from(0))
                                .putAdditionalProperty("45", JsonValue.from(0))
                                .putAdditionalProperty("46", JsonValue.from(0))
                                .putAdditionalProperty("47", JsonValue.from(0))
                                .putAdditionalProperty("48", JsonValue.from(0))
                                .putAdditionalProperty("49", JsonValue.from(0))
                                .putAdditionalProperty("50", JsonValue.from(0))
                                .putAdditionalProperty("51", JsonValue.from(0))
                                .putAdditionalProperty("52", JsonValue.from(0))
                                .putAdditionalProperty("53", JsonValue.from(0))
                                .putAdditionalProperty("54", JsonValue.from(0))
                                .putAdditionalProperty("55", JsonValue.from(0))
                                .putAdditionalProperty("56", JsonValue.from(0))
                                .putAdditionalProperty("57", JsonValue.from(0))
                                .putAdditionalProperty("58", JsonValue.from(0))
                                .putAdditionalProperty("59", JsonValue.from(0))
                                .putAdditionalProperty("60", JsonValue.from(0))
                                .putAdditionalProperty("61", JsonValue.from(0))
                                .putAdditionalProperty("62", JsonValue.from(0))
                                .putAdditionalProperty("63", JsonValue.from(0))
                                .putAdditionalProperty("64", JsonValue.from(0))
                                .putAdditionalProperty("65", JsonValue.from(0))
                                .putAdditionalProperty("66", JsonValue.from(0))
                                .putAdditionalProperty("67", JsonValue.from(0))
                                .putAdditionalProperty("68", JsonValue.from(0))
                                .putAdditionalProperty("69", JsonValue.from(0))
                                .putAdditionalProperty("70", JsonValue.from(0))
                                .putAdditionalProperty("71", JsonValue.from(0))
                                .putAdditionalProperty("72", JsonValue.from(0))
                                .putAdditionalProperty("73", JsonValue.from(0))
                                .putAdditionalProperty("74", JsonValue.from(0))
                                .putAdditionalProperty("75", JsonValue.from(0))
                                .putAdditionalProperty("76", JsonValue.from(0))
                                .putAdditionalProperty("77", JsonValue.from(0))
                                .putAdditionalProperty("78", JsonValue.from(0))
                                .putAdditionalProperty("79", JsonValue.from(0))
                                .putAdditionalProperty("80", JsonValue.from(0))
                                .putAdditionalProperty("81", JsonValue.from(0))
                                .putAdditionalProperty("82", JsonValue.from(0))
                                .putAdditionalProperty("83", JsonValue.from(0))
                                .putAdditionalProperty("84", JsonValue.from(0))
                                .putAdditionalProperty("85", JsonValue.from(0))
                                .putAdditionalProperty("86", JsonValue.from(0))
                                .putAdditionalProperty("87", JsonValue.from(0))
                                .putAdditionalProperty("88", JsonValue.from(0))
                                .putAdditionalProperty("89", JsonValue.from(0))
                                .putAdditionalProperty("90", JsonValue.from(0))
                                .putAdditionalProperty("91", JsonValue.from(0))
                                .putAdditionalProperty("92", JsonValue.from(0))
                                .putAdditionalProperty("93", JsonValue.from(0))
                                .putAdditionalProperty("94", JsonValue.from(0))
                                .putAdditionalProperty("95", JsonValue.from(0))
                                .putAdditionalProperty("96", JsonValue.from(0))
                                .putAdditionalProperty("97", JsonValue.from(0))
                                .putAdditionalProperty("98", JsonValue.from(0))
                                .putAdditionalProperty("99", JsonValue.from(0))
                                .putAdditionalProperty("100", JsonValue.from(0))
                                .putAdditionalProperty("101", JsonValue.from(0))
                                .putAdditionalProperty("102", JsonValue.from(0))
                                .putAdditionalProperty("103", JsonValue.from(0))
                                .putAdditionalProperty("104", JsonValue.from(0))
                                .putAdditionalProperty("105", JsonValue.from(0))
                                .putAdditionalProperty("106", JsonValue.from(0))
                                .putAdditionalProperty("107", JsonValue.from(0))
                                .putAdditionalProperty("108", JsonValue.from(0))
                                .putAdditionalProperty("109", JsonValue.from(0))
                                .putAdditionalProperty("110", JsonValue.from(0))
                                .build()
                        )
                        .addFileId("string")
                        .addObjectList(
                            PublicObjectListRecord.builder()
                                .listId("3")
                                .objectType("contacts")
                                .build()
                        )
                        .build()
                )
                .optOutImport(false)
                .state(PublicImportResponse.State.DONE)
                .updatedAt(OffsetDateTime.parse("2020-01-14T22:45:00.153+00:00"))
                .importName("importName")
                .importRequestJson(JsonValue.from(mapOf<String, Any>()))
                .importSource(PublicImportResponse.ImportSource.API)
                .importTemplate(
                    ImportTemplate.builder()
                        .templateId(0)
                        .templateType(ImportTemplate.TemplateType.ADMIN_DEFINED)
                        .build()
                )
                .build()

        val roundtrippedPublicImportResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(publicImportResponse),
                jacksonTypeRef<PublicImportResponse>(),
            )

        assertThat(roundtrippedPublicImportResponse).isEqualTo(publicImportResponse)
    }
}
