// File generated from our OpenAPI spec by Stainless.

package com.hubspot.sdk.models.cms.mediabridge

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.hubspot.sdk.core.JsonValue
import com.hubspot.sdk.core.jsonMapper
import com.hubspot.sdk.models.AutomationActionsOption
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class BatchResponsePropertyTest {

    @Test
    fun create() {
        val batchResponseProperty =
            BatchResponseProperty.builder()
                .completedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .addResult(
                    Property.builder()
                        .addAllowedObjectType(
                            ObjectTypeIdProto.builder().innerId(0).metaTypeId(0).build()
                        )
                        .calculated(true)
                        .canArchive(true)
                        .canRestore(true)
                        .createdAt(0L)
                        .createdUserId(0L)
                        .currencyPropertyName("currencyPropertyName")
                        .dataSensitivity(Property.DataSensitivity.HIGH)
                        .dateDisplayHint(Property.DateDisplayHint.ABSOLUTE)
                        .deleted(true)
                        .description("description")
                        .displayMode(Property.DisplayMode.ALL_UNIQUE_VERSIONS)
                        .displayOrder(0)
                        .enforceMultivalueUniqueness(true)
                        .externalOptions(true)
                        .externalOptionsReferenceType("externalOptionsReferenceType")
                        .favorited(true)
                        .favoritedOrder(0)
                        .fieldType("fieldType")
                        .formField(true)
                        .fromUserId(0L)
                        .groupName("groupName")
                        .hasUniqueValue(true)
                        .hidden(false)
                        .hubSpotDefined(true)
                        .isCustomizedDefault(true)
                        .isMultiValued(true)
                        .isPartial(true)
                        .label("label")
                        .mutableDefinitionNotDeletable(true)
                        .name("name")
                        .numberDisplayHint(Property.NumberDisplayHint.CURRENCY)
                        .addOption(
                            AutomationActionsOption.builder()
                                .description("description")
                                .displayOrder(0)
                                .doubleData(0.0)
                                .hidden(true)
                                .label("label")
                                .readOnly(true)
                                .value("value")
                                .build()
                        )
                        .optionsAreMutable(true)
                        .optionSortStrategy(Property.OptionSortStrategy.ALPHABETICAL)
                        .owningAppId(0L)
                        .portalId(0L)
                        .readOnlyDefinition(true)
                        .readOnlyValue(true)
                        .referencedObjectType(Property.ReferencedObjectType.ABANDONED_CART)
                        .searchableInGlobalSearch(true)
                        .searchTextAnalysisMode(Property.SearchTextAnalysisMode.NONE)
                        .addSensitiveDataCategory("string")
                        .showCurrencySymbol(true)
                        .textDisplayHint(Property.TextDisplayHint.DOMAIN_NAME)
                        .type(Property.Type.BOOL)
                        .updatedAt(0L)
                        .build()
                )
                .startedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .status(BatchResponseProperty.Status.CANCELED)
                .links(
                    BatchResponseProperty.Links.builder()
                        .putAdditionalProperty("foo", JsonValue.from("string"))
                        .build()
                )
                .requestedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .build()

        assertThat(batchResponseProperty.completedAt())
            .isEqualTo(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
        assertThat(batchResponseProperty.results())
            .containsExactly(
                Property.builder()
                    .addAllowedObjectType(
                        ObjectTypeIdProto.builder().innerId(0).metaTypeId(0).build()
                    )
                    .calculated(true)
                    .canArchive(true)
                    .canRestore(true)
                    .createdAt(0L)
                    .createdUserId(0L)
                    .currencyPropertyName("currencyPropertyName")
                    .dataSensitivity(Property.DataSensitivity.HIGH)
                    .dateDisplayHint(Property.DateDisplayHint.ABSOLUTE)
                    .deleted(true)
                    .description("description")
                    .displayMode(Property.DisplayMode.ALL_UNIQUE_VERSIONS)
                    .displayOrder(0)
                    .enforceMultivalueUniqueness(true)
                    .externalOptions(true)
                    .externalOptionsReferenceType("externalOptionsReferenceType")
                    .favorited(true)
                    .favoritedOrder(0)
                    .fieldType("fieldType")
                    .formField(true)
                    .fromUserId(0L)
                    .groupName("groupName")
                    .hasUniqueValue(true)
                    .hidden(false)
                    .hubSpotDefined(true)
                    .isCustomizedDefault(true)
                    .isMultiValued(true)
                    .isPartial(true)
                    .label("label")
                    .mutableDefinitionNotDeletable(true)
                    .name("name")
                    .numberDisplayHint(Property.NumberDisplayHint.CURRENCY)
                    .addOption(
                        AutomationActionsOption.builder()
                            .description("description")
                            .displayOrder(0)
                            .doubleData(0.0)
                            .hidden(true)
                            .label("label")
                            .readOnly(true)
                            .value("value")
                            .build()
                    )
                    .optionsAreMutable(true)
                    .optionSortStrategy(Property.OptionSortStrategy.ALPHABETICAL)
                    .owningAppId(0L)
                    .portalId(0L)
                    .readOnlyDefinition(true)
                    .readOnlyValue(true)
                    .referencedObjectType(Property.ReferencedObjectType.ABANDONED_CART)
                    .searchableInGlobalSearch(true)
                    .searchTextAnalysisMode(Property.SearchTextAnalysisMode.NONE)
                    .addSensitiveDataCategory("string")
                    .showCurrencySymbol(true)
                    .textDisplayHint(Property.TextDisplayHint.DOMAIN_NAME)
                    .type(Property.Type.BOOL)
                    .updatedAt(0L)
                    .build()
            )
        assertThat(batchResponseProperty.startedAt())
            .isEqualTo(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
        assertThat(batchResponseProperty.status()).isEqualTo(BatchResponseProperty.Status.CANCELED)
        assertThat(batchResponseProperty.links())
            .contains(
                BatchResponseProperty.Links.builder()
                    .putAdditionalProperty("foo", JsonValue.from("string"))
                    .build()
            )
        assertThat(batchResponseProperty.requestedAt())
            .contains(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val batchResponseProperty =
            BatchResponseProperty.builder()
                .completedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .addResult(
                    Property.builder()
                        .addAllowedObjectType(
                            ObjectTypeIdProto.builder().innerId(0).metaTypeId(0).build()
                        )
                        .calculated(true)
                        .canArchive(true)
                        .canRestore(true)
                        .createdAt(0L)
                        .createdUserId(0L)
                        .currencyPropertyName("currencyPropertyName")
                        .dataSensitivity(Property.DataSensitivity.HIGH)
                        .dateDisplayHint(Property.DateDisplayHint.ABSOLUTE)
                        .deleted(true)
                        .description("description")
                        .displayMode(Property.DisplayMode.ALL_UNIQUE_VERSIONS)
                        .displayOrder(0)
                        .enforceMultivalueUniqueness(true)
                        .externalOptions(true)
                        .externalOptionsReferenceType("externalOptionsReferenceType")
                        .favorited(true)
                        .favoritedOrder(0)
                        .fieldType("fieldType")
                        .formField(true)
                        .fromUserId(0L)
                        .groupName("groupName")
                        .hasUniqueValue(true)
                        .hidden(false)
                        .hubSpotDefined(true)
                        .isCustomizedDefault(true)
                        .isMultiValued(true)
                        .isPartial(true)
                        .label("label")
                        .mutableDefinitionNotDeletable(true)
                        .name("name")
                        .numberDisplayHint(Property.NumberDisplayHint.CURRENCY)
                        .addOption(
                            AutomationActionsOption.builder()
                                .description("description")
                                .displayOrder(0)
                                .doubleData(0.0)
                                .hidden(true)
                                .label("label")
                                .readOnly(true)
                                .value("value")
                                .build()
                        )
                        .optionsAreMutable(true)
                        .optionSortStrategy(Property.OptionSortStrategy.ALPHABETICAL)
                        .owningAppId(0L)
                        .portalId(0L)
                        .readOnlyDefinition(true)
                        .readOnlyValue(true)
                        .referencedObjectType(Property.ReferencedObjectType.ABANDONED_CART)
                        .searchableInGlobalSearch(true)
                        .searchTextAnalysisMode(Property.SearchTextAnalysisMode.NONE)
                        .addSensitiveDataCategory("string")
                        .showCurrencySymbol(true)
                        .textDisplayHint(Property.TextDisplayHint.DOMAIN_NAME)
                        .type(Property.Type.BOOL)
                        .updatedAt(0L)
                        .build()
                )
                .startedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .status(BatchResponseProperty.Status.CANCELED)
                .links(
                    BatchResponseProperty.Links.builder()
                        .putAdditionalProperty("foo", JsonValue.from("string"))
                        .build()
                )
                .requestedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .build()

        val roundtrippedBatchResponseProperty =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(batchResponseProperty),
                jacksonTypeRef<BatchResponseProperty>(),
            )

        assertThat(roundtrippedBatchResponseProperty).isEqualTo(batchResponseProperty)
    }
}
