// File generated from our OpenAPI spec by Stainless.

package com.hubspot.sdk.models.cms.mediabridge

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.hubspot.sdk.core.jsonMapper
import com.hubspot.sdk.models.AutomationActionsOption
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class MediaBridgePropertyTest {

    @Test
    fun create() {
        val mediaBridgeProperty =
            MediaBridgeProperty.builder()
                .addAllowedObjectType(ObjectTypeIdProto.builder().innerId(0).metaTypeId(0).build())
                .calculated(true)
                .canArchive(true)
                .canRestore(true)
                .createdAt(0L)
                .createdUserId(0L)
                .currencyPropertyName("currencyPropertyName")
                .dataSensitivity(MediaBridgeProperty.DataSensitivity.HIGH)
                .dateDisplayHint(MediaBridgeProperty.DateDisplayHint.ABSOLUTE)
                .deleted(true)
                .description("description")
                .displayMode(MediaBridgeProperty.DisplayMode.ALL_UNIQUE_VERSIONS)
                .displayOrder(0)
                .enforceMultivalueUniqueness(true)
                .externalOptions(true)
                .externalOptionsReferenceType("externalOptionsReferenceType")
                .favorited(true)
                .favoritedOrder(0)
                .fieldType("fieldType")
                .formField(true)
                .fromUserId(0L)
                .groupName("groupName")
                .hasUniqueValue(true)
                .hidden(false)
                .hubSpotDefined(true)
                .isCustomizedDefault(true)
                .isMultiValued(true)
                .isPartial(true)
                .label("label")
                .mutableDefinitionNotDeletable(true)
                .name("name")
                .numberDisplayHint(MediaBridgeProperty.NumberDisplayHint.CURRENCY)
                .addOption(
                    AutomationActionsOption.builder()
                        .description("description")
                        .displayOrder(0)
                        .doubleData(0.0)
                        .hidden(true)
                        .label("label")
                        .readOnly(true)
                        .value("value")
                        .build()
                )
                .optionsAreMutable(true)
                .optionSortStrategy(MediaBridgeProperty.OptionSortStrategy.ALPHABETICAL)
                .owningAppId(0L)
                .portalId(0L)
                .readOnlyDefinition(true)
                .readOnlyValue(true)
                .referencedObjectType(MediaBridgeProperty.ReferencedObjectType.ABANDONED_CART)
                .searchableInGlobalSearch(true)
                .searchTextAnalysisMode(MediaBridgeProperty.SearchTextAnalysisMode.NONE)
                .addSensitiveDataCategory("string")
                .showCurrencySymbol(true)
                .textDisplayHint(MediaBridgeProperty.TextDisplayHint.DOMAIN_NAME)
                .type(MediaBridgeProperty.Type.BOOL)
                .updatedAt(0L)
                .build()

        assertThat(mediaBridgeProperty.allowedObjectTypes())
            .containsExactly(ObjectTypeIdProto.builder().innerId(0).metaTypeId(0).build())
        assertThat(mediaBridgeProperty.calculated()).isEqualTo(true)
        assertThat(mediaBridgeProperty.canArchive()).isEqualTo(true)
        assertThat(mediaBridgeProperty.canRestore()).isEqualTo(true)
        assertThat(mediaBridgeProperty.createdAt()).isEqualTo(0L)
        assertThat(mediaBridgeProperty.createdUserId()).isEqualTo(0L)
        assertThat(mediaBridgeProperty.currencyPropertyName()).isEqualTo("currencyPropertyName")
        assertThat(mediaBridgeProperty.dataSensitivity())
            .isEqualTo(MediaBridgeProperty.DataSensitivity.HIGH)
        assertThat(mediaBridgeProperty.dateDisplayHint())
            .isEqualTo(MediaBridgeProperty.DateDisplayHint.ABSOLUTE)
        assertThat(mediaBridgeProperty.deleted()).isEqualTo(true)
        assertThat(mediaBridgeProperty.description()).isEqualTo("description")
        assertThat(mediaBridgeProperty.displayMode())
            .isEqualTo(MediaBridgeProperty.DisplayMode.ALL_UNIQUE_VERSIONS)
        assertThat(mediaBridgeProperty.displayOrder()).isEqualTo(0)
        assertThat(mediaBridgeProperty.enforceMultivalueUniqueness()).isEqualTo(true)
        assertThat(mediaBridgeProperty.externalOptions()).isEqualTo(true)
        assertThat(mediaBridgeProperty.externalOptionsReferenceType())
            .isEqualTo("externalOptionsReferenceType")
        assertThat(mediaBridgeProperty.favorited()).isEqualTo(true)
        assertThat(mediaBridgeProperty.favoritedOrder()).isEqualTo(0)
        assertThat(mediaBridgeProperty.fieldType()).isEqualTo("fieldType")
        assertThat(mediaBridgeProperty.formField()).isEqualTo(true)
        assertThat(mediaBridgeProperty.fromUserId()).isEqualTo(0L)
        assertThat(mediaBridgeProperty.groupName()).isEqualTo("groupName")
        assertThat(mediaBridgeProperty.hasUniqueValue()).isEqualTo(true)
        assertThat(mediaBridgeProperty.hidden()).isEqualTo(false)
        assertThat(mediaBridgeProperty.hubSpotDefined()).isEqualTo(true)
        assertThat(mediaBridgeProperty.isCustomizedDefault()).isEqualTo(true)
        assertThat(mediaBridgeProperty.isMultiValued()).isEqualTo(true)
        assertThat(mediaBridgeProperty.isPartial()).isEqualTo(true)
        assertThat(mediaBridgeProperty.label()).isEqualTo("label")
        assertThat(mediaBridgeProperty.mutableDefinitionNotDeletable()).isEqualTo(true)
        assertThat(mediaBridgeProperty.name()).isEqualTo("name")
        assertThat(mediaBridgeProperty.numberDisplayHint())
            .isEqualTo(MediaBridgeProperty.NumberDisplayHint.CURRENCY)
        assertThat(mediaBridgeProperty.options())
            .containsExactly(
                AutomationActionsOption.builder()
                    .description("description")
                    .displayOrder(0)
                    .doubleData(0.0)
                    .hidden(true)
                    .label("label")
                    .readOnly(true)
                    .value("value")
                    .build()
            )
        assertThat(mediaBridgeProperty.optionsAreMutable()).isEqualTo(true)
        assertThat(mediaBridgeProperty.optionSortStrategy())
            .isEqualTo(MediaBridgeProperty.OptionSortStrategy.ALPHABETICAL)
        assertThat(mediaBridgeProperty.owningAppId()).isEqualTo(0L)
        assertThat(mediaBridgeProperty.portalId()).isEqualTo(0L)
        assertThat(mediaBridgeProperty.readOnlyDefinition()).isEqualTo(true)
        assertThat(mediaBridgeProperty.readOnlyValue()).isEqualTo(true)
        assertThat(mediaBridgeProperty.referencedObjectType())
            .isEqualTo(MediaBridgeProperty.ReferencedObjectType.ABANDONED_CART)
        assertThat(mediaBridgeProperty.searchableInGlobalSearch()).isEqualTo(true)
        assertThat(mediaBridgeProperty.searchTextAnalysisMode())
            .isEqualTo(MediaBridgeProperty.SearchTextAnalysisMode.NONE)
        assertThat(mediaBridgeProperty.sensitiveDataCategories()).containsExactly("string")
        assertThat(mediaBridgeProperty.showCurrencySymbol()).isEqualTo(true)
        assertThat(mediaBridgeProperty.textDisplayHint())
            .isEqualTo(MediaBridgeProperty.TextDisplayHint.DOMAIN_NAME)
        assertThat(mediaBridgeProperty.type()).isEqualTo(MediaBridgeProperty.Type.BOOL)
        assertThat(mediaBridgeProperty.updatedAt()).isEqualTo(0L)
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val mediaBridgeProperty =
            MediaBridgeProperty.builder()
                .addAllowedObjectType(ObjectTypeIdProto.builder().innerId(0).metaTypeId(0).build())
                .calculated(true)
                .canArchive(true)
                .canRestore(true)
                .createdAt(0L)
                .createdUserId(0L)
                .currencyPropertyName("currencyPropertyName")
                .dataSensitivity(MediaBridgeProperty.DataSensitivity.HIGH)
                .dateDisplayHint(MediaBridgeProperty.DateDisplayHint.ABSOLUTE)
                .deleted(true)
                .description("description")
                .displayMode(MediaBridgeProperty.DisplayMode.ALL_UNIQUE_VERSIONS)
                .displayOrder(0)
                .enforceMultivalueUniqueness(true)
                .externalOptions(true)
                .externalOptionsReferenceType("externalOptionsReferenceType")
                .favorited(true)
                .favoritedOrder(0)
                .fieldType("fieldType")
                .formField(true)
                .fromUserId(0L)
                .groupName("groupName")
                .hasUniqueValue(true)
                .hidden(false)
                .hubSpotDefined(true)
                .isCustomizedDefault(true)
                .isMultiValued(true)
                .isPartial(true)
                .label("label")
                .mutableDefinitionNotDeletable(true)
                .name("name")
                .numberDisplayHint(MediaBridgeProperty.NumberDisplayHint.CURRENCY)
                .addOption(
                    AutomationActionsOption.builder()
                        .description("description")
                        .displayOrder(0)
                        .doubleData(0.0)
                        .hidden(true)
                        .label("label")
                        .readOnly(true)
                        .value("value")
                        .build()
                )
                .optionsAreMutable(true)
                .optionSortStrategy(MediaBridgeProperty.OptionSortStrategy.ALPHABETICAL)
                .owningAppId(0L)
                .portalId(0L)
                .readOnlyDefinition(true)
                .readOnlyValue(true)
                .referencedObjectType(MediaBridgeProperty.ReferencedObjectType.ABANDONED_CART)
                .searchableInGlobalSearch(true)
                .searchTextAnalysisMode(MediaBridgeProperty.SearchTextAnalysisMode.NONE)
                .addSensitiveDataCategory("string")
                .showCurrencySymbol(true)
                .textDisplayHint(MediaBridgeProperty.TextDisplayHint.DOMAIN_NAME)
                .type(MediaBridgeProperty.Type.BOOL)
                .updatedAt(0L)
                .build()

        val roundtrippedMediaBridgeProperty =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(mediaBridgeProperty),
                jacksonTypeRef<MediaBridgeProperty>(),
            )

        assertThat(roundtrippedMediaBridgeProperty).isEqualTo(mediaBridgeProperty)
    }
}
