// File generated from our OpenAPI spec by Stainless.

package com.hubspot.sdk.models.cms.mediabridge

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.hubspot.sdk.core.JsonValue
import com.hubspot.sdk.core.jsonMapper
import com.hubspot.sdk.models.AssociationSpec
import com.hubspot.sdk.models.AutomationActionsOption
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class PropertyDefinitionTest {

    @Test
    fun create() {
        val propertyDefinition =
            PropertyDefinition.builder()
                .objectTypeId("objectTypeId")
                .property(
                    MediaBridgeProperty.builder()
                        .addAllowedObjectType(
                            ObjectTypeIdProto.builder().innerId(0).metaTypeId(0).build()
                        )
                        .calculated(true)
                        .canArchive(true)
                        .canRestore(true)
                        .createdAt(0L)
                        .createdUserId(0L)
                        .currencyPropertyName("currencyPropertyName")
                        .dataSensitivity(MediaBridgeProperty.DataSensitivity.HIGH)
                        .dateDisplayHint(MediaBridgeProperty.DateDisplayHint.ABSOLUTE)
                        .deleted(true)
                        .description("description")
                        .displayMode(MediaBridgeProperty.DisplayMode.ALL_UNIQUE_VERSIONS)
                        .displayOrder(0)
                        .enforceMultivalueUniqueness(true)
                        .externalOptions(true)
                        .externalOptionsReferenceType("externalOptionsReferenceType")
                        .favorited(true)
                        .favoritedOrder(0)
                        .fieldType("fieldType")
                        .formField(true)
                        .fromUserId(0L)
                        .groupName("groupName")
                        .hasUniqueValue(true)
                        .hidden(false)
                        .hubSpotDefined(true)
                        .isCustomizedDefault(true)
                        .isMultiValued(true)
                        .isPartial(true)
                        .label("label")
                        .mutableDefinitionNotDeletable(true)
                        .name("name")
                        .numberDisplayHint(MediaBridgeProperty.NumberDisplayHint.CURRENCY)
                        .addOption(
                            AutomationActionsOption.builder()
                                .description("description")
                                .displayOrder(0)
                                .doubleData(0.0)
                                .hidden(true)
                                .label("label")
                                .readOnly(true)
                                .value("value")
                                .build()
                        )
                        .optionsAreMutable(true)
                        .optionSortStrategy(MediaBridgeProperty.OptionSortStrategy.ALPHABETICAL)
                        .owningAppId(0L)
                        .portalId(0L)
                        .readOnlyDefinition(true)
                        .readOnlyValue(true)
                        .referencedObjectType(
                            MediaBridgeProperty.ReferencedObjectType.ABANDONED_CART
                        )
                        .searchableInGlobalSearch(true)
                        .searchTextAnalysisMode(MediaBridgeProperty.SearchTextAnalysisMode.NONE)
                        .addSensitiveDataCategory("string")
                        .showCurrencySymbol(true)
                        .textDisplayHint(MediaBridgeProperty.TextDisplayHint.DOMAIN_NAME)
                        .type(MediaBridgeProperty.Type.BOOL)
                        .updatedAt(0L)
                        .build()
                )
                .calculationExpression(JsonValue.from(mapOf<String, Any>()))
                .calculationFormula("calculationFormula")
                .definitionSource(
                    PropertyDefinitionSource.builder()
                        .type(PropertyDefinitionSource.Type.GLOBAL)
                        .name("name")
                        .build()
                )
                .extensionData(
                    ExtensionData.builder()
                        .extensionStatusMap(
                            ExtensionData.ExtensionStatusMap.builder()
                                .putAdditionalProperty("foo", JsonValue.from("OK"))
                                .build()
                        )
                        .addTag("string")
                        .caseChangeTestExtensionData(
                            CaseChangeTestExtensionData.builder()
                                .mood(CaseChangeTestExtensionData.Mood.ANGRY)
                                .build()
                        )
                        .optionDecoratorsExtensionData(
                            OptionDecoratorsExtensionData.builder()
                                .optionDecorators(
                                    OptionDecoratorsExtensionData.OptionDecorators.builder()
                                        .putAdditionalProperty(
                                            "foo",
                                            JsonValue.from(mapOf("color" to "BLACK")),
                                        )
                                        .build()
                                )
                                .optionDecoratorStyle(
                                    OptionDecoratorsExtensionData.OptionDecoratorStyle.LABEL_ONLY
                                )
                                .build()
                        )
                        .requiredPropertiesExtensionData(
                            RequiredPropertiesExtensionData.builder()
                                .isRequiredProperty(true)
                                .build()
                        )
                        .softRequiredPropertiesExtensionData(
                            SoftRequiredPropertiesExtensionData.builder()
                                .isSoftRequiredProperty(true)
                                .build()
                        )
                        .build()
                )
                .externalOptionsMetaData(
                    ExternalOptionsMetaData.builder()
                        .filter(
                            FilteringMetaData.builder()
                                .includeHelpdeskRoutableTeamsOnly(true)
                                .includeUnconfirmedUsers(true)
                                .addListProcessingType("string")
                                .addPipelineId("string")
                                .build()
                        )
                        .relatedObjectTypeId("relatedObjectTypeId")
                        .build()
                )
                .fulcrumPortalId(0)
                .fulcrumTimestamp(0L)
                .janusGroup("janusGroup")
                .lookupAssociationSpec(
                    LookupAssociationSpec.builder()
                        .associationSpec(
                            AssociationSpec.builder()
                                .associationCategory(
                                    AssociationSpec.AssociationCategory.HUBSPOT_DEFINED
                                )
                                .associationTypeId(0)
                                .build()
                        )
                        .cardinality(LookupAssociationSpec.Cardinality.ONE_TO_MANY)
                        .maxToObjectIds(0)
                        .toObjectTypeId("toObjectTypeId")
                        .build()
                )
                .permission(FieldLevelPermission.builder().accessLevel("accessLevel").build())
                .propertyDefinitionSource(
                    DefinitionSource.builder()
                        .type(DefinitionSource.Type.GLOBAL)
                        .name("name")
                        .build()
                )
                .propertyRequirements(
                    DefaultRequirements.builder()
                        .addGate("string")
                        .operator(DefaultRequirements.Operator.AND)
                        .addScopeName("string")
                        .addSetting("string")
                        .build()
                )
                .rollupExpression(
                    RollupExpression.builder()
                        .addAssociationType(
                            AssociationSpec.builder()
                                .associationCategory(
                                    AssociationSpec.AssociationCategory.HUBSPOT_DEFINED
                                )
                                .associationTypeId(0)
                                .build()
                        )
                        .rollupOperator(RollupExpression.RollupOperator.AVERAGE)
                        .sourceObjectTypeId("sourceObjectTypeId")
                        .sourcePropertyName("sourcePropertyName")
                        .conditionalExpression(JsonValue.from(mapOf<String, Any>()))
                        .conditionalFormula("conditionalFormula")
                        .emptyRollupValue("emptyRollupValue")
                        .sourceCompareByPropertyName("sourceCompareByPropertyName")
                        .build()
                )
                .build()

        assertThat(propertyDefinition.objectTypeId()).isEqualTo("objectTypeId")
        assertThat(propertyDefinition.property())
            .isEqualTo(
                MediaBridgeProperty.builder()
                    .addAllowedObjectType(
                        ObjectTypeIdProto.builder().innerId(0).metaTypeId(0).build()
                    )
                    .calculated(true)
                    .canArchive(true)
                    .canRestore(true)
                    .createdAt(0L)
                    .createdUserId(0L)
                    .currencyPropertyName("currencyPropertyName")
                    .dataSensitivity(MediaBridgeProperty.DataSensitivity.HIGH)
                    .dateDisplayHint(MediaBridgeProperty.DateDisplayHint.ABSOLUTE)
                    .deleted(true)
                    .description("description")
                    .displayMode(MediaBridgeProperty.DisplayMode.ALL_UNIQUE_VERSIONS)
                    .displayOrder(0)
                    .enforceMultivalueUniqueness(true)
                    .externalOptions(true)
                    .externalOptionsReferenceType("externalOptionsReferenceType")
                    .favorited(true)
                    .favoritedOrder(0)
                    .fieldType("fieldType")
                    .formField(true)
                    .fromUserId(0L)
                    .groupName("groupName")
                    .hasUniqueValue(true)
                    .hidden(false)
                    .hubSpotDefined(true)
                    .isCustomizedDefault(true)
                    .isMultiValued(true)
                    .isPartial(true)
                    .label("label")
                    .mutableDefinitionNotDeletable(true)
                    .name("name")
                    .numberDisplayHint(MediaBridgeProperty.NumberDisplayHint.CURRENCY)
                    .addOption(
                        AutomationActionsOption.builder()
                            .description("description")
                            .displayOrder(0)
                            .doubleData(0.0)
                            .hidden(true)
                            .label("label")
                            .readOnly(true)
                            .value("value")
                            .build()
                    )
                    .optionsAreMutable(true)
                    .optionSortStrategy(MediaBridgeProperty.OptionSortStrategy.ALPHABETICAL)
                    .owningAppId(0L)
                    .portalId(0L)
                    .readOnlyDefinition(true)
                    .readOnlyValue(true)
                    .referencedObjectType(MediaBridgeProperty.ReferencedObjectType.ABANDONED_CART)
                    .searchableInGlobalSearch(true)
                    .searchTextAnalysisMode(MediaBridgeProperty.SearchTextAnalysisMode.NONE)
                    .addSensitiveDataCategory("string")
                    .showCurrencySymbol(true)
                    .textDisplayHint(MediaBridgeProperty.TextDisplayHint.DOMAIN_NAME)
                    .type(MediaBridgeProperty.Type.BOOL)
                    .updatedAt(0L)
                    .build()
            )
        assertThat(propertyDefinition._calculationExpression())
            .isEqualTo(JsonValue.from(mapOf<String, Any>()))
        assertThat(propertyDefinition.calculationFormula()).contains("calculationFormula")
        assertThat(propertyDefinition.definitionSource())
            .contains(
                PropertyDefinitionSource.builder()
                    .type(PropertyDefinitionSource.Type.GLOBAL)
                    .name("name")
                    .build()
            )
        assertThat(propertyDefinition.extensionData())
            .contains(
                ExtensionData.builder()
                    .extensionStatusMap(
                        ExtensionData.ExtensionStatusMap.builder()
                            .putAdditionalProperty("foo", JsonValue.from("OK"))
                            .build()
                    )
                    .addTag("string")
                    .caseChangeTestExtensionData(
                        CaseChangeTestExtensionData.builder()
                            .mood(CaseChangeTestExtensionData.Mood.ANGRY)
                            .build()
                    )
                    .optionDecoratorsExtensionData(
                        OptionDecoratorsExtensionData.builder()
                            .optionDecorators(
                                OptionDecoratorsExtensionData.OptionDecorators.builder()
                                    .putAdditionalProperty(
                                        "foo",
                                        JsonValue.from(mapOf("color" to "BLACK")),
                                    )
                                    .build()
                            )
                            .optionDecoratorStyle(
                                OptionDecoratorsExtensionData.OptionDecoratorStyle.LABEL_ONLY
                            )
                            .build()
                    )
                    .requiredPropertiesExtensionData(
                        RequiredPropertiesExtensionData.builder().isRequiredProperty(true).build()
                    )
                    .softRequiredPropertiesExtensionData(
                        SoftRequiredPropertiesExtensionData.builder()
                            .isSoftRequiredProperty(true)
                            .build()
                    )
                    .build()
            )
        assertThat(propertyDefinition.externalOptionsMetaData())
            .contains(
                ExternalOptionsMetaData.builder()
                    .filter(
                        FilteringMetaData.builder()
                            .includeHelpdeskRoutableTeamsOnly(true)
                            .includeUnconfirmedUsers(true)
                            .addListProcessingType("string")
                            .addPipelineId("string")
                            .build()
                    )
                    .relatedObjectTypeId("relatedObjectTypeId")
                    .build()
            )
        assertThat(propertyDefinition.fulcrumPortalId()).contains(0)
        assertThat(propertyDefinition.fulcrumTimestamp()).contains(0L)
        assertThat(propertyDefinition.janusGroup()).contains("janusGroup")
        assertThat(propertyDefinition.lookupAssociationSpec())
            .contains(
                LookupAssociationSpec.builder()
                    .associationSpec(
                        AssociationSpec.builder()
                            .associationCategory(
                                AssociationSpec.AssociationCategory.HUBSPOT_DEFINED
                            )
                            .associationTypeId(0)
                            .build()
                    )
                    .cardinality(LookupAssociationSpec.Cardinality.ONE_TO_MANY)
                    .maxToObjectIds(0)
                    .toObjectTypeId("toObjectTypeId")
                    .build()
            )
        assertThat(propertyDefinition.permission())
            .contains(FieldLevelPermission.builder().accessLevel("accessLevel").build())
        assertThat(propertyDefinition.propertyDefinitionSource())
            .contains(
                DefinitionSource.builder().type(DefinitionSource.Type.GLOBAL).name("name").build()
            )
        assertThat(propertyDefinition.propertyRequirements())
            .contains(
                DefaultRequirements.builder()
                    .addGate("string")
                    .operator(DefaultRequirements.Operator.AND)
                    .addScopeName("string")
                    .addSetting("string")
                    .build()
            )
        assertThat(propertyDefinition.rollupExpression())
            .contains(
                RollupExpression.builder()
                    .addAssociationType(
                        AssociationSpec.builder()
                            .associationCategory(
                                AssociationSpec.AssociationCategory.HUBSPOT_DEFINED
                            )
                            .associationTypeId(0)
                            .build()
                    )
                    .rollupOperator(RollupExpression.RollupOperator.AVERAGE)
                    .sourceObjectTypeId("sourceObjectTypeId")
                    .sourcePropertyName("sourcePropertyName")
                    .conditionalExpression(JsonValue.from(mapOf<String, Any>()))
                    .conditionalFormula("conditionalFormula")
                    .emptyRollupValue("emptyRollupValue")
                    .sourceCompareByPropertyName("sourceCompareByPropertyName")
                    .build()
            )
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val propertyDefinition =
            PropertyDefinition.builder()
                .objectTypeId("objectTypeId")
                .property(
                    MediaBridgeProperty.builder()
                        .addAllowedObjectType(
                            ObjectTypeIdProto.builder().innerId(0).metaTypeId(0).build()
                        )
                        .calculated(true)
                        .canArchive(true)
                        .canRestore(true)
                        .createdAt(0L)
                        .createdUserId(0L)
                        .currencyPropertyName("currencyPropertyName")
                        .dataSensitivity(MediaBridgeProperty.DataSensitivity.HIGH)
                        .dateDisplayHint(MediaBridgeProperty.DateDisplayHint.ABSOLUTE)
                        .deleted(true)
                        .description("description")
                        .displayMode(MediaBridgeProperty.DisplayMode.ALL_UNIQUE_VERSIONS)
                        .displayOrder(0)
                        .enforceMultivalueUniqueness(true)
                        .externalOptions(true)
                        .externalOptionsReferenceType("externalOptionsReferenceType")
                        .favorited(true)
                        .favoritedOrder(0)
                        .fieldType("fieldType")
                        .formField(true)
                        .fromUserId(0L)
                        .groupName("groupName")
                        .hasUniqueValue(true)
                        .hidden(false)
                        .hubSpotDefined(true)
                        .isCustomizedDefault(true)
                        .isMultiValued(true)
                        .isPartial(true)
                        .label("label")
                        .mutableDefinitionNotDeletable(true)
                        .name("name")
                        .numberDisplayHint(MediaBridgeProperty.NumberDisplayHint.CURRENCY)
                        .addOption(
                            AutomationActionsOption.builder()
                                .description("description")
                                .displayOrder(0)
                                .doubleData(0.0)
                                .hidden(true)
                                .label("label")
                                .readOnly(true)
                                .value("value")
                                .build()
                        )
                        .optionsAreMutable(true)
                        .optionSortStrategy(MediaBridgeProperty.OptionSortStrategy.ALPHABETICAL)
                        .owningAppId(0L)
                        .portalId(0L)
                        .readOnlyDefinition(true)
                        .readOnlyValue(true)
                        .referencedObjectType(
                            MediaBridgeProperty.ReferencedObjectType.ABANDONED_CART
                        )
                        .searchableInGlobalSearch(true)
                        .searchTextAnalysisMode(MediaBridgeProperty.SearchTextAnalysisMode.NONE)
                        .addSensitiveDataCategory("string")
                        .showCurrencySymbol(true)
                        .textDisplayHint(MediaBridgeProperty.TextDisplayHint.DOMAIN_NAME)
                        .type(MediaBridgeProperty.Type.BOOL)
                        .updatedAt(0L)
                        .build()
                )
                .calculationExpression(JsonValue.from(mapOf<String, Any>()))
                .calculationFormula("calculationFormula")
                .definitionSource(
                    PropertyDefinitionSource.builder()
                        .type(PropertyDefinitionSource.Type.GLOBAL)
                        .name("name")
                        .build()
                )
                .extensionData(
                    ExtensionData.builder()
                        .extensionStatusMap(
                            ExtensionData.ExtensionStatusMap.builder()
                                .putAdditionalProperty("foo", JsonValue.from("OK"))
                                .build()
                        )
                        .addTag("string")
                        .caseChangeTestExtensionData(
                            CaseChangeTestExtensionData.builder()
                                .mood(CaseChangeTestExtensionData.Mood.ANGRY)
                                .build()
                        )
                        .optionDecoratorsExtensionData(
                            OptionDecoratorsExtensionData.builder()
                                .optionDecorators(
                                    OptionDecoratorsExtensionData.OptionDecorators.builder()
                                        .putAdditionalProperty(
                                            "foo",
                                            JsonValue.from(mapOf("color" to "BLACK")),
                                        )
                                        .build()
                                )
                                .optionDecoratorStyle(
                                    OptionDecoratorsExtensionData.OptionDecoratorStyle.LABEL_ONLY
                                )
                                .build()
                        )
                        .requiredPropertiesExtensionData(
                            RequiredPropertiesExtensionData.builder()
                                .isRequiredProperty(true)
                                .build()
                        )
                        .softRequiredPropertiesExtensionData(
                            SoftRequiredPropertiesExtensionData.builder()
                                .isSoftRequiredProperty(true)
                                .build()
                        )
                        .build()
                )
                .externalOptionsMetaData(
                    ExternalOptionsMetaData.builder()
                        .filter(
                            FilteringMetaData.builder()
                                .includeHelpdeskRoutableTeamsOnly(true)
                                .includeUnconfirmedUsers(true)
                                .addListProcessingType("string")
                                .addPipelineId("string")
                                .build()
                        )
                        .relatedObjectTypeId("relatedObjectTypeId")
                        .build()
                )
                .fulcrumPortalId(0)
                .fulcrumTimestamp(0L)
                .janusGroup("janusGroup")
                .lookupAssociationSpec(
                    LookupAssociationSpec.builder()
                        .associationSpec(
                            AssociationSpec.builder()
                                .associationCategory(
                                    AssociationSpec.AssociationCategory.HUBSPOT_DEFINED
                                )
                                .associationTypeId(0)
                                .build()
                        )
                        .cardinality(LookupAssociationSpec.Cardinality.ONE_TO_MANY)
                        .maxToObjectIds(0)
                        .toObjectTypeId("toObjectTypeId")
                        .build()
                )
                .permission(FieldLevelPermission.builder().accessLevel("accessLevel").build())
                .propertyDefinitionSource(
                    DefinitionSource.builder()
                        .type(DefinitionSource.Type.GLOBAL)
                        .name("name")
                        .build()
                )
                .propertyRequirements(
                    DefaultRequirements.builder()
                        .addGate("string")
                        .operator(DefaultRequirements.Operator.AND)
                        .addScopeName("string")
                        .addSetting("string")
                        .build()
                )
                .rollupExpression(
                    RollupExpression.builder()
                        .addAssociationType(
                            AssociationSpec.builder()
                                .associationCategory(
                                    AssociationSpec.AssociationCategory.HUBSPOT_DEFINED
                                )
                                .associationTypeId(0)
                                .build()
                        )
                        .rollupOperator(RollupExpression.RollupOperator.AVERAGE)
                        .sourceObjectTypeId("sourceObjectTypeId")
                        .sourcePropertyName("sourcePropertyName")
                        .conditionalExpression(JsonValue.from(mapOf<String, Any>()))
                        .conditionalFormula("conditionalFormula")
                        .emptyRollupValue("emptyRollupValue")
                        .sourceCompareByPropertyName("sourceCompareByPropertyName")
                        .build()
                )
                .build()

        val roundtrippedPropertyDefinition =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(propertyDefinition),
                jacksonTypeRef<PropertyDefinition>(),
            )

        assertThat(roundtrippedPropertyDefinition).isEqualTo(propertyDefinition)
    }
}
