// File generated from our OpenAPI spec by Stainless.

package com.hubspot.sdk.models.events.definitions

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.hubspot.sdk.core.jsonMapper
import com.hubspot.sdk.models.BaseOption
import com.hubspot.sdk.models.BaseProperty
import com.hubspot.sdk.models.NextPage
import com.hubspot.sdk.models.Paging
import com.hubspot.sdk.models.PreviousPage
import com.hubspot.sdk.models.PropertyModificationMetadata
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class CollectionResponseWithTotalExternalBehavioralEventTypeDefinitionTest {

    @Test
    fun create() {
        val collectionResponseWithTotalExternalBehavioralEventTypeDefinition =
            CollectionResponseWithTotalExternalBehavioralEventTypeDefinition.builder()
                .addResult(
                    ExternalBehavioralEventTypeDefinition.builder()
                        .id("id")
                        .archived(true)
                        .addAssociation(
                            DefinitionsAssociationDefinition.builder()
                                .id(0)
                                .allowsCustomLabels(true)
                                .cardinality(
                                    DefinitionsAssociationDefinition.Cardinality.ONE_TO_MANY
                                )
                                .category(DefinitionsAssociationDefinition.Category.HUBSPOT_DEFINED)
                                .fromObjectTypeId("fromObjectTypeId")
                                .hasAllAssociatedObjects(true)
                                .hasCascadingDeletes(true)
                                .hasUserEnforcedMaxFromObjectIds(true)
                                .hasUserEnforcedMaxToObjectIds(true)
                                .hidden(true)
                                .inverseAllowsCustomLabels(true)
                                .inverseCardinality(
                                    DefinitionsAssociationDefinition.InverseCardinality.ONE_TO_MANY
                                )
                                .inverseHasAllAssociatedObjects(true)
                                .inverseId(0)
                                .inverseName("inverseName")
                                .isDefault(true)
                                .isInversePrimary(true)
                                .isPrimary(true)
                                .maxFromObjectIds(0)
                                .maxToObjectIds(0)
                                .name("name")
                                .portalUniqueIdentifier("portalUniqueIdentifier")
                                .readOnly(true)
                                .toObjectTypeId("toObjectTypeId")
                                .fromObjectType(
                                    DefinitionsAssociationDefinition.FromObjectType.ABANDONED_CART
                                )
                                .hiddenReason(DefinitionsAssociationDefinition.HiddenReason.DEFAULT)
                                .inverseLabel("inverseLabel")
                                .label("label")
                                .toObjectType(
                                    DefinitionsAssociationDefinition.ToObjectType.ABANDONED_CART
                                )
                                .build()
                        )
                        .fullyQualifiedName("fullyQualifiedName")
                        .labels(
                            BehavioralEventTypeDefinitionLabels.builder()
                                .singular("singular")
                                .plural("plural")
                                .build()
                        )
                        .name("name")
                        .objectTypeId("objectTypeId")
                        .addProperty(
                            BaseProperty.builder()
                                .description("description")
                                .fieldType("fieldType")
                                .groupName("groupName")
                                .label("label")
                                .name("name")
                                .addOption(
                                    BaseOption.builder()
                                        .hidden(true)
                                        .label("label")
                                        .value("value")
                                        .description("description")
                                        .displayOrder(0)
                                        .build()
                                )
                                .type("type")
                                .archived(true)
                                .archivedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .calculated(true)
                                .calculationFormula("calculationFormula")
                                .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .createdUserId("createdUserId")
                                .currencyPropertyName("currencyPropertyName")
                                .dataSensitivity(BaseProperty.DataSensitivity.HIGHLY_SENSITIVE)
                                .dateDisplayHint(BaseProperty.DateDisplayHint.ABSOLUTE)
                                .displayOrder(0)
                                .externalOptions(true)
                                .formField(true)
                                .hasUniqueValue(true)
                                .hidden(false)
                                .hubSpotDefined(true)
                                .modificationMetadata(
                                    PropertyModificationMetadata.builder()
                                        .archivable(true)
                                        .readOnlyDefinition(true)
                                        .readOnlyValue(true)
                                        .readOnlyOptions(true)
                                        .build()
                                )
                                .numberDisplayHint(BaseProperty.NumberDisplayHint.CURRENCY)
                                .referencedObjectType("referencedObjectType")
                                .addSensitiveDataCategory("string")
                                .showCurrencySymbol(true)
                                .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .updatedUserId("updatedUserId")
                                .build()
                        )
                        .comboEventRules(
                            ComboEventRuleBranch.builder()
                                .addComposingRule(
                                    ComboEventRule.builder()
                                        .count(0)
                                        .eventTypeId("eventTypeId")
                                        .addPropertyFilter(
                                            PropertyFilter.builder()
                                                .filterType(PropertyFilter.FilterType.PROPERTY)
                                                .operation(
                                                    BoolPropertyOperation.builder()
                                                        .includeObjectsWithNoValueSet(true)
                                                        .operationType("operationType")
                                                        .operator(
                                                            BoolPropertyOperation.Operator
                                                                .HAS_EVER_BEEN_EQUAL_TO
                                                        )
                                                        .operatorName("operatorName")
                                                        .propertyType(
                                                            BoolPropertyOperation.PropertyType.BOOL
                                                        )
                                                        .value(true)
                                                        .defaultValue("defaultValue")
                                                        .renderSpec("renderSpec")
                                                        .build()
                                                )
                                                .property("property")
                                                .context(
                                                    PropertyFilterContext.builder()
                                                        .objectTypeId("objectTypeId")
                                                        .build()
                                                )
                                                .filterInsightsId(0)
                                                .frameworkFilterId(0L)
                                                .build()
                                        )
                                        .lookbackWindowDays(0)
                                        .build()
                                )
                                .operationType(ComboEventRuleBranch.OperationType.AND)
                                .ruleBranches(listOf())
                                .build()
                        )
                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .createdUserId(0)
                        .customMatchingId(
                            ExternalObjectResolutionMappingResponse.builder()
                                .primaryObjectRule(
                                    ExternalPrimaryObjectResolutionRule.builder()
                                        .eventPropertyName("eventPropertyName")
                                        .targetObjectPropertyName("targetObjectPropertyName")
                                        .build()
                                )
                                .build()
                        )
                        .description("description")
                        .detailTemplate("detailTemplate")
                        .headerTemplate("headerTemplate")
                        .primaryObject("primaryObject")
                        .primaryObjectId("primaryObjectId")
                        .trackingType(ExternalBehavioralEventTypeDefinition.TrackingType.APP_EVENT)
                        .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .updatedUserId(0)
                        .build()
                )
                .total(0)
                .paging(
                    Paging.builder()
                        .next(NextPage.builder().after("after").link("link").build())
                        .prev(PreviousPage.builder().before("before").link("link").build())
                        .build()
                )
                .build()

        assertThat(collectionResponseWithTotalExternalBehavioralEventTypeDefinition.results())
            .containsExactly(
                ExternalBehavioralEventTypeDefinition.builder()
                    .id("id")
                    .archived(true)
                    .addAssociation(
                        DefinitionsAssociationDefinition.builder()
                            .id(0)
                            .allowsCustomLabels(true)
                            .cardinality(DefinitionsAssociationDefinition.Cardinality.ONE_TO_MANY)
                            .category(DefinitionsAssociationDefinition.Category.HUBSPOT_DEFINED)
                            .fromObjectTypeId("fromObjectTypeId")
                            .hasAllAssociatedObjects(true)
                            .hasCascadingDeletes(true)
                            .hasUserEnforcedMaxFromObjectIds(true)
                            .hasUserEnforcedMaxToObjectIds(true)
                            .hidden(true)
                            .inverseAllowsCustomLabels(true)
                            .inverseCardinality(
                                DefinitionsAssociationDefinition.InverseCardinality.ONE_TO_MANY
                            )
                            .inverseHasAllAssociatedObjects(true)
                            .inverseId(0)
                            .inverseName("inverseName")
                            .isDefault(true)
                            .isInversePrimary(true)
                            .isPrimary(true)
                            .maxFromObjectIds(0)
                            .maxToObjectIds(0)
                            .name("name")
                            .portalUniqueIdentifier("portalUniqueIdentifier")
                            .readOnly(true)
                            .toObjectTypeId("toObjectTypeId")
                            .fromObjectType(
                                DefinitionsAssociationDefinition.FromObjectType.ABANDONED_CART
                            )
                            .hiddenReason(DefinitionsAssociationDefinition.HiddenReason.DEFAULT)
                            .inverseLabel("inverseLabel")
                            .label("label")
                            .toObjectType(
                                DefinitionsAssociationDefinition.ToObjectType.ABANDONED_CART
                            )
                            .build()
                    )
                    .fullyQualifiedName("fullyQualifiedName")
                    .labels(
                        BehavioralEventTypeDefinitionLabels.builder()
                            .singular("singular")
                            .plural("plural")
                            .build()
                    )
                    .name("name")
                    .objectTypeId("objectTypeId")
                    .addProperty(
                        BaseProperty.builder()
                            .description("description")
                            .fieldType("fieldType")
                            .groupName("groupName")
                            .label("label")
                            .name("name")
                            .addOption(
                                BaseOption.builder()
                                    .hidden(true)
                                    .label("label")
                                    .value("value")
                                    .description("description")
                                    .displayOrder(0)
                                    .build()
                            )
                            .type("type")
                            .archived(true)
                            .archivedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .calculated(true)
                            .calculationFormula("calculationFormula")
                            .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .createdUserId("createdUserId")
                            .currencyPropertyName("currencyPropertyName")
                            .dataSensitivity(BaseProperty.DataSensitivity.HIGHLY_SENSITIVE)
                            .dateDisplayHint(BaseProperty.DateDisplayHint.ABSOLUTE)
                            .displayOrder(0)
                            .externalOptions(true)
                            .formField(true)
                            .hasUniqueValue(true)
                            .hidden(false)
                            .hubSpotDefined(true)
                            .modificationMetadata(
                                PropertyModificationMetadata.builder()
                                    .archivable(true)
                                    .readOnlyDefinition(true)
                                    .readOnlyValue(true)
                                    .readOnlyOptions(true)
                                    .build()
                            )
                            .numberDisplayHint(BaseProperty.NumberDisplayHint.CURRENCY)
                            .referencedObjectType("referencedObjectType")
                            .addSensitiveDataCategory("string")
                            .showCurrencySymbol(true)
                            .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .updatedUserId("updatedUserId")
                            .build()
                    )
                    .comboEventRules(
                        ComboEventRuleBranch.builder()
                            .addComposingRule(
                                ComboEventRule.builder()
                                    .count(0)
                                    .eventTypeId("eventTypeId")
                                    .addPropertyFilter(
                                        PropertyFilter.builder()
                                            .filterType(PropertyFilter.FilterType.PROPERTY)
                                            .operation(
                                                BoolPropertyOperation.builder()
                                                    .includeObjectsWithNoValueSet(true)
                                                    .operationType("operationType")
                                                    .operator(
                                                        BoolPropertyOperation.Operator
                                                            .HAS_EVER_BEEN_EQUAL_TO
                                                    )
                                                    .operatorName("operatorName")
                                                    .propertyType(
                                                        BoolPropertyOperation.PropertyType.BOOL
                                                    )
                                                    .value(true)
                                                    .defaultValue("defaultValue")
                                                    .renderSpec("renderSpec")
                                                    .build()
                                            )
                                            .property("property")
                                            .context(
                                                PropertyFilterContext.builder()
                                                    .objectTypeId("objectTypeId")
                                                    .build()
                                            )
                                            .filterInsightsId(0)
                                            .frameworkFilterId(0L)
                                            .build()
                                    )
                                    .lookbackWindowDays(0)
                                    .build()
                            )
                            .operationType(ComboEventRuleBranch.OperationType.AND)
                            .ruleBranches(listOf())
                            .build()
                    )
                    .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .createdUserId(0)
                    .customMatchingId(
                        ExternalObjectResolutionMappingResponse.builder()
                            .primaryObjectRule(
                                ExternalPrimaryObjectResolutionRule.builder()
                                    .eventPropertyName("eventPropertyName")
                                    .targetObjectPropertyName("targetObjectPropertyName")
                                    .build()
                            )
                            .build()
                    )
                    .description("description")
                    .detailTemplate("detailTemplate")
                    .headerTemplate("headerTemplate")
                    .primaryObject("primaryObject")
                    .primaryObjectId("primaryObjectId")
                    .trackingType(ExternalBehavioralEventTypeDefinition.TrackingType.APP_EVENT)
                    .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .updatedUserId(0)
                    .build()
            )
        assertThat(collectionResponseWithTotalExternalBehavioralEventTypeDefinition.total())
            .isEqualTo(0)
        assertThat(collectionResponseWithTotalExternalBehavioralEventTypeDefinition.paging())
            .contains(
                Paging.builder()
                    .next(NextPage.builder().after("after").link("link").build())
                    .prev(PreviousPage.builder().before("before").link("link").build())
                    .build()
            )
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val collectionResponseWithTotalExternalBehavioralEventTypeDefinition =
            CollectionResponseWithTotalExternalBehavioralEventTypeDefinition.builder()
                .addResult(
                    ExternalBehavioralEventTypeDefinition.builder()
                        .id("id")
                        .archived(true)
                        .addAssociation(
                            DefinitionsAssociationDefinition.builder()
                                .id(0)
                                .allowsCustomLabels(true)
                                .cardinality(
                                    DefinitionsAssociationDefinition.Cardinality.ONE_TO_MANY
                                )
                                .category(DefinitionsAssociationDefinition.Category.HUBSPOT_DEFINED)
                                .fromObjectTypeId("fromObjectTypeId")
                                .hasAllAssociatedObjects(true)
                                .hasCascadingDeletes(true)
                                .hasUserEnforcedMaxFromObjectIds(true)
                                .hasUserEnforcedMaxToObjectIds(true)
                                .hidden(true)
                                .inverseAllowsCustomLabels(true)
                                .inverseCardinality(
                                    DefinitionsAssociationDefinition.InverseCardinality.ONE_TO_MANY
                                )
                                .inverseHasAllAssociatedObjects(true)
                                .inverseId(0)
                                .inverseName("inverseName")
                                .isDefault(true)
                                .isInversePrimary(true)
                                .isPrimary(true)
                                .maxFromObjectIds(0)
                                .maxToObjectIds(0)
                                .name("name")
                                .portalUniqueIdentifier("portalUniqueIdentifier")
                                .readOnly(true)
                                .toObjectTypeId("toObjectTypeId")
                                .fromObjectType(
                                    DefinitionsAssociationDefinition.FromObjectType.ABANDONED_CART
                                )
                                .hiddenReason(DefinitionsAssociationDefinition.HiddenReason.DEFAULT)
                                .inverseLabel("inverseLabel")
                                .label("label")
                                .toObjectType(
                                    DefinitionsAssociationDefinition.ToObjectType.ABANDONED_CART
                                )
                                .build()
                        )
                        .fullyQualifiedName("fullyQualifiedName")
                        .labels(
                            BehavioralEventTypeDefinitionLabels.builder()
                                .singular("singular")
                                .plural("plural")
                                .build()
                        )
                        .name("name")
                        .objectTypeId("objectTypeId")
                        .addProperty(
                            BaseProperty.builder()
                                .description("description")
                                .fieldType("fieldType")
                                .groupName("groupName")
                                .label("label")
                                .name("name")
                                .addOption(
                                    BaseOption.builder()
                                        .hidden(true)
                                        .label("label")
                                        .value("value")
                                        .description("description")
                                        .displayOrder(0)
                                        .build()
                                )
                                .type("type")
                                .archived(true)
                                .archivedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .calculated(true)
                                .calculationFormula("calculationFormula")
                                .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .createdUserId("createdUserId")
                                .currencyPropertyName("currencyPropertyName")
                                .dataSensitivity(BaseProperty.DataSensitivity.HIGHLY_SENSITIVE)
                                .dateDisplayHint(BaseProperty.DateDisplayHint.ABSOLUTE)
                                .displayOrder(0)
                                .externalOptions(true)
                                .formField(true)
                                .hasUniqueValue(true)
                                .hidden(false)
                                .hubSpotDefined(true)
                                .modificationMetadata(
                                    PropertyModificationMetadata.builder()
                                        .archivable(true)
                                        .readOnlyDefinition(true)
                                        .readOnlyValue(true)
                                        .readOnlyOptions(true)
                                        .build()
                                )
                                .numberDisplayHint(BaseProperty.NumberDisplayHint.CURRENCY)
                                .referencedObjectType("referencedObjectType")
                                .addSensitiveDataCategory("string")
                                .showCurrencySymbol(true)
                                .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .updatedUserId("updatedUserId")
                                .build()
                        )
                        .comboEventRules(
                            ComboEventRuleBranch.builder()
                                .addComposingRule(
                                    ComboEventRule.builder()
                                        .count(0)
                                        .eventTypeId("eventTypeId")
                                        .addPropertyFilter(
                                            PropertyFilter.builder()
                                                .filterType(PropertyFilter.FilterType.PROPERTY)
                                                .operation(
                                                    BoolPropertyOperation.builder()
                                                        .includeObjectsWithNoValueSet(true)
                                                        .operationType("operationType")
                                                        .operator(
                                                            BoolPropertyOperation.Operator
                                                                .HAS_EVER_BEEN_EQUAL_TO
                                                        )
                                                        .operatorName("operatorName")
                                                        .propertyType(
                                                            BoolPropertyOperation.PropertyType.BOOL
                                                        )
                                                        .value(true)
                                                        .defaultValue("defaultValue")
                                                        .renderSpec("renderSpec")
                                                        .build()
                                                )
                                                .property("property")
                                                .context(
                                                    PropertyFilterContext.builder()
                                                        .objectTypeId("objectTypeId")
                                                        .build()
                                                )
                                                .filterInsightsId(0)
                                                .frameworkFilterId(0L)
                                                .build()
                                        )
                                        .lookbackWindowDays(0)
                                        .build()
                                )
                                .operationType(ComboEventRuleBranch.OperationType.AND)
                                .ruleBranches(listOf())
                                .build()
                        )
                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .createdUserId(0)
                        .customMatchingId(
                            ExternalObjectResolutionMappingResponse.builder()
                                .primaryObjectRule(
                                    ExternalPrimaryObjectResolutionRule.builder()
                                        .eventPropertyName("eventPropertyName")
                                        .targetObjectPropertyName("targetObjectPropertyName")
                                        .build()
                                )
                                .build()
                        )
                        .description("description")
                        .detailTemplate("detailTemplate")
                        .headerTemplate("headerTemplate")
                        .primaryObject("primaryObject")
                        .primaryObjectId("primaryObjectId")
                        .trackingType(ExternalBehavioralEventTypeDefinition.TrackingType.APP_EVENT)
                        .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .updatedUserId(0)
                        .build()
                )
                .total(0)
                .paging(
                    Paging.builder()
                        .next(NextPage.builder().after("after").link("link").build())
                        .prev(PreviousPage.builder().before("before").link("link").build())
                        .build()
                )
                .build()

        val roundtrippedCollectionResponseWithTotalExternalBehavioralEventTypeDefinition =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(
                    collectionResponseWithTotalExternalBehavioralEventTypeDefinition
                ),
                jacksonTypeRef<CollectionResponseWithTotalExternalBehavioralEventTypeDefinition>(),
            )

        assertThat(roundtrippedCollectionResponseWithTotalExternalBehavioralEventTypeDefinition)
            .isEqualTo(collectionResponseWithTotalExternalBehavioralEventTypeDefinition)
    }
}
