// File generated from our OpenAPI spec by Stainless.

package com.hubspot.models.crm.lists

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.hubspot.core.JsonValue
import com.hubspot.core.jsonMapper
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class ListCreateRequestTest {

    @Test
    fun create() {
        val listCreateRequest =
            ListCreateRequest.builder()
                .name("name")
                .objectTypeId("objectTypeId")
                .processingType("processingType")
                .customProperties(
                    ListCreateRequest.CustomProperties.builder()
                        .putAdditionalProperty("foo", JsonValue.from("string"))
                        .build()
                )
                .filterBranch(
                    PublicOrFilterBranch.builder()
                        .addFilterBranch(
                            PublicAndFilterBranch.builder()
                                .addFilterBranch(
                                    PublicNotAllFilterBranch.builder()
                                        .addFilterBranch(
                                            PublicNotAnyFilterBranch.builder()
                                                .addFilterBranch(
                                                    PublicRestrictedFilterBranch.builder()
                                                        .addFilterBranch(
                                                            PublicUnifiedEventsFilterBranch
                                                                .builder()
                                                                .eventTypeId("eventTypeId")
                                                                .addFilterBranch(
                                                                    PublicPropertyAssociationFilterBranch
                                                                        .builder()
                                                                        .addFilterBranch(
                                                                            PublicAssociationFilterBranch
                                                                                .builder()
                                                                                .associationCategory(
                                                                                    "associationCategory"
                                                                                )
                                                                                .associationTypeId(
                                                                                    0
                                                                                )
                                                                                .addFilterBranch(
                                                                                    PublicOrFilterBranch
                                                                                        .builder()
                                                                                        .filterBranches(
                                                                                            listOf()
                                                                                        )
                                                                                        .filterBranchOperator(
                                                                                            "filterBranchOperator"
                                                                                        )
                                                                                        .filterBranchType(
                                                                                            PublicOrFilterBranch
                                                                                                .FilterBranchType
                                                                                                .OR
                                                                                        )
                                                                                        .addFilter(
                                                                                            PublicPropertyFilter
                                                                                                .builder()
                                                                                                .filterType(
                                                                                                    PublicPropertyFilter
                                                                                                        .FilterType
                                                                                                        .PROPERTY
                                                                                                )
                                                                                                .operation(
                                                                                                    PublicBoolPropertyOperation
                                                                                                        .builder()
                                                                                                        .includeObjectsWithNoValueSet(
                                                                                                            true
                                                                                                        )
                                                                                                        .operationType(
                                                                                                            PublicBoolPropertyOperation
                                                                                                                .OperationType
                                                                                                                .BOOL
                                                                                                        )
                                                                                                        .operator(
                                                                                                            "operator"
                                                                                                        )
                                                                                                        .value(
                                                                                                            true
                                                                                                        )
                                                                                                        .build()
                                                                                                )
                                                                                                .property(
                                                                                                    "property"
                                                                                                )
                                                                                                .build()
                                                                                        )
                                                                                        .build()
                                                                                )
                                                                                .filterBranchOperator(
                                                                                    "filterBranchOperator"
                                                                                )
                                                                                .filterBranchType(
                                                                                    PublicAssociationFilterBranch
                                                                                        .FilterBranchType
                                                                                        .ASSOCIATION
                                                                                )
                                                                                .addFilter(
                                                                                    PublicPropertyFilter
                                                                                        .builder()
                                                                                        .filterType(
                                                                                            PublicPropertyFilter
                                                                                                .FilterType
                                                                                                .PROPERTY
                                                                                        )
                                                                                        .operation(
                                                                                            PublicBoolPropertyOperation
                                                                                                .builder()
                                                                                                .includeObjectsWithNoValueSet(
                                                                                                    true
                                                                                                )
                                                                                                .operationType(
                                                                                                    PublicBoolPropertyOperation
                                                                                                        .OperationType
                                                                                                        .BOOL
                                                                                                )
                                                                                                .operator(
                                                                                                    "operator"
                                                                                                )
                                                                                                .value(
                                                                                                    true
                                                                                                )
                                                                                                .build()
                                                                                        )
                                                                                        .property(
                                                                                            "property"
                                                                                        )
                                                                                        .build()
                                                                                )
                                                                                .objectTypeId(
                                                                                    "objectTypeId"
                                                                                )
                                                                                .operator(
                                                                                    "operator"
                                                                                )
                                                                                .build()
                                                                        )
                                                                        .filterBranchOperator(
                                                                            "filterBranchOperator"
                                                                        )
                                                                        .filterBranchType(
                                                                            PublicPropertyAssociationFilterBranch
                                                                                .FilterBranchType
                                                                                .PROPERTY_ASSOCIATION
                                                                        )
                                                                        .addFilter(
                                                                            PublicPropertyFilter
                                                                                .builder()
                                                                                .filterType(
                                                                                    PublicPropertyFilter
                                                                                        .FilterType
                                                                                        .PROPERTY
                                                                                )
                                                                                .operation(
                                                                                    PublicBoolPropertyOperation
                                                                                        .builder()
                                                                                        .includeObjectsWithNoValueSet(
                                                                                            true
                                                                                        )
                                                                                        .operationType(
                                                                                            PublicBoolPropertyOperation
                                                                                                .OperationType
                                                                                                .BOOL
                                                                                        )
                                                                                        .operator(
                                                                                            "operator"
                                                                                        )
                                                                                        .value(true)
                                                                                        .build()
                                                                                )
                                                                                .property(
                                                                                    "property"
                                                                                )
                                                                                .build()
                                                                        )
                                                                        .objectTypeId(
                                                                            "objectTypeId"
                                                                        )
                                                                        .operator("operator")
                                                                        .propertyWithObjectId(
                                                                            "propertyWithObjectId"
                                                                        )
                                                                        .build()
                                                                )
                                                                .filterBranchOperator(
                                                                    "filterBranchOperator"
                                                                )
                                                                .filterBranchType(
                                                                    PublicUnifiedEventsFilterBranch
                                                                        .FilterBranchType
                                                                        .UNIFIED_EVENTS
                                                                )
                                                                .addFilter(
                                                                    PublicPropertyFilter.builder()
                                                                        .filterType(
                                                                            PublicPropertyFilter
                                                                                .FilterType
                                                                                .PROPERTY
                                                                        )
                                                                        .operation(
                                                                            PublicBoolPropertyOperation
                                                                                .builder()
                                                                                .includeObjectsWithNoValueSet(
                                                                                    true
                                                                                )
                                                                                .operationType(
                                                                                    PublicBoolPropertyOperation
                                                                                        .OperationType
                                                                                        .BOOL
                                                                                )
                                                                                .operator(
                                                                                    "operator"
                                                                                )
                                                                                .value(true)
                                                                                .build()
                                                                        )
                                                                        .property("property")
                                                                        .build()
                                                                )
                                                                .operator(
                                                                    PublicUnifiedEventsFilterBranch
                                                                        .Operator
                                                                        .HAS_COMPLETED
                                                                )
                                                                .coalescingRefineBy(
                                                                    PublicNumOccurrencesRefineBy
                                                                        .builder()
                                                                        .type(
                                                                            PublicNumOccurrencesRefineBy
                                                                                .Type
                                                                                .NUM_OCCURRENCES
                                                                        )
                                                                        .maxOccurrences(0)
                                                                        .minOccurrences(0)
                                                                        .build()
                                                                )
                                                                .pruningRefineBy(
                                                                    PublicNumOccurrencesRefineBy
                                                                        .builder()
                                                                        .type(
                                                                            PublicNumOccurrencesRefineBy
                                                                                .Type
                                                                                .NUM_OCCURRENCES
                                                                        )
                                                                        .maxOccurrences(0)
                                                                        .minOccurrences(0)
                                                                        .build()
                                                                )
                                                                .build()
                                                        )
                                                        .filterBranchOperator(
                                                            "filterBranchOperator"
                                                        )
                                                        .filterBranchType(
                                                            PublicRestrictedFilterBranch
                                                                .FilterBranchType
                                                                .RESTRICTED
                                                        )
                                                        .addFilter(
                                                            PublicPropertyFilter.builder()
                                                                .filterType(
                                                                    PublicPropertyFilter.FilterType
                                                                        .PROPERTY
                                                                )
                                                                .operation(
                                                                    PublicBoolPropertyOperation
                                                                        .builder()
                                                                        .includeObjectsWithNoValueSet(
                                                                            true
                                                                        )
                                                                        .operationType(
                                                                            PublicBoolPropertyOperation
                                                                                .OperationType
                                                                                .BOOL
                                                                        )
                                                                        .operator("operator")
                                                                        .value(true)
                                                                        .build()
                                                                )
                                                                .property("property")
                                                                .build()
                                                        )
                                                        .build()
                                                )
                                                .filterBranchOperator("filterBranchOperator")
                                                .filterBranchType(
                                                    PublicNotAnyFilterBranch.FilterBranchType
                                                        .NOT_ANY
                                                )
                                                .addFilter(
                                                    PublicPropertyFilter.builder()
                                                        .filterType(
                                                            PublicPropertyFilter.FilterType.PROPERTY
                                                        )
                                                        .operation(
                                                            PublicBoolPropertyOperation.builder()
                                                                .includeObjectsWithNoValueSet(true)
                                                                .operationType(
                                                                    PublicBoolPropertyOperation
                                                                        .OperationType
                                                                        .BOOL
                                                                )
                                                                .operator("operator")
                                                                .value(true)
                                                                .build()
                                                        )
                                                        .property("property")
                                                        .build()
                                                )
                                                .build()
                                        )
                                        .filterBranchOperator("filterBranchOperator")
                                        .filterBranchType(
                                            PublicNotAllFilterBranch.FilterBranchType.NOT_ALL
                                        )
                                        .addFilter(
                                            PublicPropertyFilter.builder()
                                                .filterType(
                                                    PublicPropertyFilter.FilterType.PROPERTY
                                                )
                                                .operation(
                                                    PublicBoolPropertyOperation.builder()
                                                        .includeObjectsWithNoValueSet(true)
                                                        .operationType(
                                                            PublicBoolPropertyOperation
                                                                .OperationType
                                                                .BOOL
                                                        )
                                                        .operator("operator")
                                                        .value(true)
                                                        .build()
                                                )
                                                .property("property")
                                                .build()
                                        )
                                        .build()
                                )
                                .filterBranchOperator("filterBranchOperator")
                                .filterBranchType(PublicAndFilterBranch.FilterBranchType.AND)
                                .addFilter(
                                    PublicPropertyFilter.builder()
                                        .filterType(PublicPropertyFilter.FilterType.PROPERTY)
                                        .operation(
                                            PublicBoolPropertyOperation.builder()
                                                .includeObjectsWithNoValueSet(true)
                                                .operationType(
                                                    PublicBoolPropertyOperation.OperationType.BOOL
                                                )
                                                .operator("operator")
                                                .value(true)
                                                .build()
                                        )
                                        .property("property")
                                        .build()
                                )
                                .build()
                        )
                        .filterBranchOperator("filterBranchOperator")
                        .filterBranchType(PublicOrFilterBranch.FilterBranchType.OR)
                        .addFilter(
                            PublicPropertyFilter.builder()
                                .filterType(PublicPropertyFilter.FilterType.PROPERTY)
                                .operation(
                                    PublicBoolPropertyOperation.builder()
                                        .includeObjectsWithNoValueSet(true)
                                        .operationType(
                                            PublicBoolPropertyOperation.OperationType.BOOL
                                        )
                                        .operator("operator")
                                        .value(true)
                                        .build()
                                )
                                .property("property")
                                .build()
                        )
                        .build()
                )
                .listFolderId(0)
                .listPermissions(
                    PublicListPermissions.builder()
                        .addTeamsWithEditAccess(0)
                        .addUsersWithEditAccess(0)
                        .build()
                )
                .membershipSettings(
                    PublicMembershipSettings.builder()
                        .includeUnassigned(true)
                        .membershipTeamId(0)
                        .build()
                )
                .build()

        assertThat(listCreateRequest.name()).isEqualTo("name")
        assertThat(listCreateRequest.objectTypeId()).isEqualTo("objectTypeId")
        assertThat(listCreateRequest.processingType()).isEqualTo("processingType")
        assertThat(listCreateRequest.customProperties())
            .contains(
                ListCreateRequest.CustomProperties.builder()
                    .putAdditionalProperty("foo", JsonValue.from("string"))
                    .build()
            )
        assertThat(listCreateRequest.filterBranch())
            .contains(
                ListCreateRequest.FilterBranch.ofOr(
                    PublicOrFilterBranch.builder()
                        .addFilterBranch(
                            PublicAndFilterBranch.builder()
                                .addFilterBranch(
                                    PublicNotAllFilterBranch.builder()
                                        .addFilterBranch(
                                            PublicNotAnyFilterBranch.builder()
                                                .addFilterBranch(
                                                    PublicRestrictedFilterBranch.builder()
                                                        .addFilterBranch(
                                                            PublicUnifiedEventsFilterBranch
                                                                .builder()
                                                                .eventTypeId("eventTypeId")
                                                                .addFilterBranch(
                                                                    PublicPropertyAssociationFilterBranch
                                                                        .builder()
                                                                        .addFilterBranch(
                                                                            PublicAssociationFilterBranch
                                                                                .builder()
                                                                                .associationCategory(
                                                                                    "associationCategory"
                                                                                )
                                                                                .associationTypeId(
                                                                                    0
                                                                                )
                                                                                .addFilterBranch(
                                                                                    PublicOrFilterBranch
                                                                                        .builder()
                                                                                        .filterBranches(
                                                                                            listOf()
                                                                                        )
                                                                                        .filterBranchOperator(
                                                                                            "filterBranchOperator"
                                                                                        )
                                                                                        .filterBranchType(
                                                                                            PublicOrFilterBranch
                                                                                                .FilterBranchType
                                                                                                .OR
                                                                                        )
                                                                                        .addFilter(
                                                                                            PublicPropertyFilter
                                                                                                .builder()
                                                                                                .filterType(
                                                                                                    PublicPropertyFilter
                                                                                                        .FilterType
                                                                                                        .PROPERTY
                                                                                                )
                                                                                                .operation(
                                                                                                    PublicBoolPropertyOperation
                                                                                                        .builder()
                                                                                                        .includeObjectsWithNoValueSet(
                                                                                                            true
                                                                                                        )
                                                                                                        .operationType(
                                                                                                            PublicBoolPropertyOperation
                                                                                                                .OperationType
                                                                                                                .BOOL
                                                                                                        )
                                                                                                        .operator(
                                                                                                            "operator"
                                                                                                        )
                                                                                                        .value(
                                                                                                            true
                                                                                                        )
                                                                                                        .build()
                                                                                                )
                                                                                                .property(
                                                                                                    "property"
                                                                                                )
                                                                                                .build()
                                                                                        )
                                                                                        .build()
                                                                                )
                                                                                .filterBranchOperator(
                                                                                    "filterBranchOperator"
                                                                                )
                                                                                .filterBranchType(
                                                                                    PublicAssociationFilterBranch
                                                                                        .FilterBranchType
                                                                                        .ASSOCIATION
                                                                                )
                                                                                .addFilter(
                                                                                    PublicPropertyFilter
                                                                                        .builder()
                                                                                        .filterType(
                                                                                            PublicPropertyFilter
                                                                                                .FilterType
                                                                                                .PROPERTY
                                                                                        )
                                                                                        .operation(
                                                                                            PublicBoolPropertyOperation
                                                                                                .builder()
                                                                                                .includeObjectsWithNoValueSet(
                                                                                                    true
                                                                                                )
                                                                                                .operationType(
                                                                                                    PublicBoolPropertyOperation
                                                                                                        .OperationType
                                                                                                        .BOOL
                                                                                                )
                                                                                                .operator(
                                                                                                    "operator"
                                                                                                )
                                                                                                .value(
                                                                                                    true
                                                                                                )
                                                                                                .build()
                                                                                        )
                                                                                        .property(
                                                                                            "property"
                                                                                        )
                                                                                        .build()
                                                                                )
                                                                                .objectTypeId(
                                                                                    "objectTypeId"
                                                                                )
                                                                                .operator(
                                                                                    "operator"
                                                                                )
                                                                                .build()
                                                                        )
                                                                        .filterBranchOperator(
                                                                            "filterBranchOperator"
                                                                        )
                                                                        .filterBranchType(
                                                                            PublicPropertyAssociationFilterBranch
                                                                                .FilterBranchType
                                                                                .PROPERTY_ASSOCIATION
                                                                        )
                                                                        .addFilter(
                                                                            PublicPropertyFilter
                                                                                .builder()
                                                                                .filterType(
                                                                                    PublicPropertyFilter
                                                                                        .FilterType
                                                                                        .PROPERTY
                                                                                )
                                                                                .operation(
                                                                                    PublicBoolPropertyOperation
                                                                                        .builder()
                                                                                        .includeObjectsWithNoValueSet(
                                                                                            true
                                                                                        )
                                                                                        .operationType(
                                                                                            PublicBoolPropertyOperation
                                                                                                .OperationType
                                                                                                .BOOL
                                                                                        )
                                                                                        .operator(
                                                                                            "operator"
                                                                                        )
                                                                                        .value(true)
                                                                                        .build()
                                                                                )
                                                                                .property(
                                                                                    "property"
                                                                                )
                                                                                .build()
                                                                        )
                                                                        .objectTypeId(
                                                                            "objectTypeId"
                                                                        )
                                                                        .operator("operator")
                                                                        .propertyWithObjectId(
                                                                            "propertyWithObjectId"
                                                                        )
                                                                        .build()
                                                                )
                                                                .filterBranchOperator(
                                                                    "filterBranchOperator"
                                                                )
                                                                .filterBranchType(
                                                                    PublicUnifiedEventsFilterBranch
                                                                        .FilterBranchType
                                                                        .UNIFIED_EVENTS
                                                                )
                                                                .addFilter(
                                                                    PublicPropertyFilter.builder()
                                                                        .filterType(
                                                                            PublicPropertyFilter
                                                                                .FilterType
                                                                                .PROPERTY
                                                                        )
                                                                        .operation(
                                                                            PublicBoolPropertyOperation
                                                                                .builder()
                                                                                .includeObjectsWithNoValueSet(
                                                                                    true
                                                                                )
                                                                                .operationType(
                                                                                    PublicBoolPropertyOperation
                                                                                        .OperationType
                                                                                        .BOOL
                                                                                )
                                                                                .operator(
                                                                                    "operator"
                                                                                )
                                                                                .value(true)
                                                                                .build()
                                                                        )
                                                                        .property("property")
                                                                        .build()
                                                                )
                                                                .operator(
                                                                    PublicUnifiedEventsFilterBranch
                                                                        .Operator
                                                                        .HAS_COMPLETED
                                                                )
                                                                .coalescingRefineBy(
                                                                    PublicNumOccurrencesRefineBy
                                                                        .builder()
                                                                        .type(
                                                                            PublicNumOccurrencesRefineBy
                                                                                .Type
                                                                                .NUM_OCCURRENCES
                                                                        )
                                                                        .maxOccurrences(0)
                                                                        .minOccurrences(0)
                                                                        .build()
                                                                )
                                                                .pruningRefineBy(
                                                                    PublicNumOccurrencesRefineBy
                                                                        .builder()
                                                                        .type(
                                                                            PublicNumOccurrencesRefineBy
                                                                                .Type
                                                                                .NUM_OCCURRENCES
                                                                        )
                                                                        .maxOccurrences(0)
                                                                        .minOccurrences(0)
                                                                        .build()
                                                                )
                                                                .build()
                                                        )
                                                        .filterBranchOperator(
                                                            "filterBranchOperator"
                                                        )
                                                        .filterBranchType(
                                                            PublicRestrictedFilterBranch
                                                                .FilterBranchType
                                                                .RESTRICTED
                                                        )
                                                        .addFilter(
                                                            PublicPropertyFilter.builder()
                                                                .filterType(
                                                                    PublicPropertyFilter.FilterType
                                                                        .PROPERTY
                                                                )
                                                                .operation(
                                                                    PublicBoolPropertyOperation
                                                                        .builder()
                                                                        .includeObjectsWithNoValueSet(
                                                                            true
                                                                        )
                                                                        .operationType(
                                                                            PublicBoolPropertyOperation
                                                                                .OperationType
                                                                                .BOOL
                                                                        )
                                                                        .operator("operator")
                                                                        .value(true)
                                                                        .build()
                                                                )
                                                                .property("property")
                                                                .build()
                                                        )
                                                        .build()
                                                )
                                                .filterBranchOperator("filterBranchOperator")
                                                .filterBranchType(
                                                    PublicNotAnyFilterBranch.FilterBranchType
                                                        .NOT_ANY
                                                )
                                                .addFilter(
                                                    PublicPropertyFilter.builder()
                                                        .filterType(
                                                            PublicPropertyFilter.FilterType.PROPERTY
                                                        )
                                                        .operation(
                                                            PublicBoolPropertyOperation.builder()
                                                                .includeObjectsWithNoValueSet(true)
                                                                .operationType(
                                                                    PublicBoolPropertyOperation
                                                                        .OperationType
                                                                        .BOOL
                                                                )
                                                                .operator("operator")
                                                                .value(true)
                                                                .build()
                                                        )
                                                        .property("property")
                                                        .build()
                                                )
                                                .build()
                                        )
                                        .filterBranchOperator("filterBranchOperator")
                                        .filterBranchType(
                                            PublicNotAllFilterBranch.FilterBranchType.NOT_ALL
                                        )
                                        .addFilter(
                                            PublicPropertyFilter.builder()
                                                .filterType(
                                                    PublicPropertyFilter.FilterType.PROPERTY
                                                )
                                                .operation(
                                                    PublicBoolPropertyOperation.builder()
                                                        .includeObjectsWithNoValueSet(true)
                                                        .operationType(
                                                            PublicBoolPropertyOperation
                                                                .OperationType
                                                                .BOOL
                                                        )
                                                        .operator("operator")
                                                        .value(true)
                                                        .build()
                                                )
                                                .property("property")
                                                .build()
                                        )
                                        .build()
                                )
                                .filterBranchOperator("filterBranchOperator")
                                .filterBranchType(PublicAndFilterBranch.FilterBranchType.AND)
                                .addFilter(
                                    PublicPropertyFilter.builder()
                                        .filterType(PublicPropertyFilter.FilterType.PROPERTY)
                                        .operation(
                                            PublicBoolPropertyOperation.builder()
                                                .includeObjectsWithNoValueSet(true)
                                                .operationType(
                                                    PublicBoolPropertyOperation.OperationType.BOOL
                                                )
                                                .operator("operator")
                                                .value(true)
                                                .build()
                                        )
                                        .property("property")
                                        .build()
                                )
                                .build()
                        )
                        .filterBranchOperator("filterBranchOperator")
                        .filterBranchType(PublicOrFilterBranch.FilterBranchType.OR)
                        .addFilter(
                            PublicPropertyFilter.builder()
                                .filterType(PublicPropertyFilter.FilterType.PROPERTY)
                                .operation(
                                    PublicBoolPropertyOperation.builder()
                                        .includeObjectsWithNoValueSet(true)
                                        .operationType(
                                            PublicBoolPropertyOperation.OperationType.BOOL
                                        )
                                        .operator("operator")
                                        .value(true)
                                        .build()
                                )
                                .property("property")
                                .build()
                        )
                        .build()
                )
            )
        assertThat(listCreateRequest.listFolderId()).contains(0)
        assertThat(listCreateRequest.listPermissions())
            .contains(
                PublicListPermissions.builder()
                    .addTeamsWithEditAccess(0)
                    .addUsersWithEditAccess(0)
                    .build()
            )
        assertThat(listCreateRequest.membershipSettings())
            .contains(
                PublicMembershipSettings.builder()
                    .includeUnassigned(true)
                    .membershipTeamId(0)
                    .build()
            )
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val listCreateRequest =
            ListCreateRequest.builder()
                .name("name")
                .objectTypeId("objectTypeId")
                .processingType("processingType")
                .customProperties(
                    ListCreateRequest.CustomProperties.builder()
                        .putAdditionalProperty("foo", JsonValue.from("string"))
                        .build()
                )
                .filterBranch(
                    PublicOrFilterBranch.builder()
                        .addFilterBranch(
                            PublicAndFilterBranch.builder()
                                .addFilterBranch(
                                    PublicNotAllFilterBranch.builder()
                                        .addFilterBranch(
                                            PublicNotAnyFilterBranch.builder()
                                                .addFilterBranch(
                                                    PublicRestrictedFilterBranch.builder()
                                                        .addFilterBranch(
                                                            PublicUnifiedEventsFilterBranch
                                                                .builder()
                                                                .eventTypeId("eventTypeId")
                                                                .addFilterBranch(
                                                                    PublicPropertyAssociationFilterBranch
                                                                        .builder()
                                                                        .addFilterBranch(
                                                                            PublicAssociationFilterBranch
                                                                                .builder()
                                                                                .associationCategory(
                                                                                    "associationCategory"
                                                                                )
                                                                                .associationTypeId(
                                                                                    0
                                                                                )
                                                                                .addFilterBranch(
                                                                                    PublicOrFilterBranch
                                                                                        .builder()
                                                                                        .filterBranches(
                                                                                            listOf()
                                                                                        )
                                                                                        .filterBranchOperator(
                                                                                            "filterBranchOperator"
                                                                                        )
                                                                                        .filterBranchType(
                                                                                            PublicOrFilterBranch
                                                                                                .FilterBranchType
                                                                                                .OR
                                                                                        )
                                                                                        .addFilter(
                                                                                            PublicPropertyFilter
                                                                                                .builder()
                                                                                                .filterType(
                                                                                                    PublicPropertyFilter
                                                                                                        .FilterType
                                                                                                        .PROPERTY
                                                                                                )
                                                                                                .operation(
                                                                                                    PublicBoolPropertyOperation
                                                                                                        .builder()
                                                                                                        .includeObjectsWithNoValueSet(
                                                                                                            true
                                                                                                        )
                                                                                                        .operationType(
                                                                                                            PublicBoolPropertyOperation
                                                                                                                .OperationType
                                                                                                                .BOOL
                                                                                                        )
                                                                                                        .operator(
                                                                                                            "operator"
                                                                                                        )
                                                                                                        .value(
                                                                                                            true
                                                                                                        )
                                                                                                        .build()
                                                                                                )
                                                                                                .property(
                                                                                                    "property"
                                                                                                )
                                                                                                .build()
                                                                                        )
                                                                                        .build()
                                                                                )
                                                                                .filterBranchOperator(
                                                                                    "filterBranchOperator"
                                                                                )
                                                                                .filterBranchType(
                                                                                    PublicAssociationFilterBranch
                                                                                        .FilterBranchType
                                                                                        .ASSOCIATION
                                                                                )
                                                                                .addFilter(
                                                                                    PublicPropertyFilter
                                                                                        .builder()
                                                                                        .filterType(
                                                                                            PublicPropertyFilter
                                                                                                .FilterType
                                                                                                .PROPERTY
                                                                                        )
                                                                                        .operation(
                                                                                            PublicBoolPropertyOperation
                                                                                                .builder()
                                                                                                .includeObjectsWithNoValueSet(
                                                                                                    true
                                                                                                )
                                                                                                .operationType(
                                                                                                    PublicBoolPropertyOperation
                                                                                                        .OperationType
                                                                                                        .BOOL
                                                                                                )
                                                                                                .operator(
                                                                                                    "operator"
                                                                                                )
                                                                                                .value(
                                                                                                    true
                                                                                                )
                                                                                                .build()
                                                                                        )
                                                                                        .property(
                                                                                            "property"
                                                                                        )
                                                                                        .build()
                                                                                )
                                                                                .objectTypeId(
                                                                                    "objectTypeId"
                                                                                )
                                                                                .operator(
                                                                                    "operator"
                                                                                )
                                                                                .build()
                                                                        )
                                                                        .filterBranchOperator(
                                                                            "filterBranchOperator"
                                                                        )
                                                                        .filterBranchType(
                                                                            PublicPropertyAssociationFilterBranch
                                                                                .FilterBranchType
                                                                                .PROPERTY_ASSOCIATION
                                                                        )
                                                                        .addFilter(
                                                                            PublicPropertyFilter
                                                                                .builder()
                                                                                .filterType(
                                                                                    PublicPropertyFilter
                                                                                        .FilterType
                                                                                        .PROPERTY
                                                                                )
                                                                                .operation(
                                                                                    PublicBoolPropertyOperation
                                                                                        .builder()
                                                                                        .includeObjectsWithNoValueSet(
                                                                                            true
                                                                                        )
                                                                                        .operationType(
                                                                                            PublicBoolPropertyOperation
                                                                                                .OperationType
                                                                                                .BOOL
                                                                                        )
                                                                                        .operator(
                                                                                            "operator"
                                                                                        )
                                                                                        .value(true)
                                                                                        .build()
                                                                                )
                                                                                .property(
                                                                                    "property"
                                                                                )
                                                                                .build()
                                                                        )
                                                                        .objectTypeId(
                                                                            "objectTypeId"
                                                                        )
                                                                        .operator("operator")
                                                                        .propertyWithObjectId(
                                                                            "propertyWithObjectId"
                                                                        )
                                                                        .build()
                                                                )
                                                                .filterBranchOperator(
                                                                    "filterBranchOperator"
                                                                )
                                                                .filterBranchType(
                                                                    PublicUnifiedEventsFilterBranch
                                                                        .FilterBranchType
                                                                        .UNIFIED_EVENTS
                                                                )
                                                                .addFilter(
                                                                    PublicPropertyFilter.builder()
                                                                        .filterType(
                                                                            PublicPropertyFilter
                                                                                .FilterType
                                                                                .PROPERTY
                                                                        )
                                                                        .operation(
                                                                            PublicBoolPropertyOperation
                                                                                .builder()
                                                                                .includeObjectsWithNoValueSet(
                                                                                    true
                                                                                )
                                                                                .operationType(
                                                                                    PublicBoolPropertyOperation
                                                                                        .OperationType
                                                                                        .BOOL
                                                                                )
                                                                                .operator(
                                                                                    "operator"
                                                                                )
                                                                                .value(true)
                                                                                .build()
                                                                        )
                                                                        .property("property")
                                                                        .build()
                                                                )
                                                                .operator(
                                                                    PublicUnifiedEventsFilterBranch
                                                                        .Operator
                                                                        .HAS_COMPLETED
                                                                )
                                                                .coalescingRefineBy(
                                                                    PublicNumOccurrencesRefineBy
                                                                        .builder()
                                                                        .type(
                                                                            PublicNumOccurrencesRefineBy
                                                                                .Type
                                                                                .NUM_OCCURRENCES
                                                                        )
                                                                        .maxOccurrences(0)
                                                                        .minOccurrences(0)
                                                                        .build()
                                                                )
                                                                .pruningRefineBy(
                                                                    PublicNumOccurrencesRefineBy
                                                                        .builder()
                                                                        .type(
                                                                            PublicNumOccurrencesRefineBy
                                                                                .Type
                                                                                .NUM_OCCURRENCES
                                                                        )
                                                                        .maxOccurrences(0)
                                                                        .minOccurrences(0)
                                                                        .build()
                                                                )
                                                                .build()
                                                        )
                                                        .filterBranchOperator(
                                                            "filterBranchOperator"
                                                        )
                                                        .filterBranchType(
                                                            PublicRestrictedFilterBranch
                                                                .FilterBranchType
                                                                .RESTRICTED
                                                        )
                                                        .addFilter(
                                                            PublicPropertyFilter.builder()
                                                                .filterType(
                                                                    PublicPropertyFilter.FilterType
                                                                        .PROPERTY
                                                                )
                                                                .operation(
                                                                    PublicBoolPropertyOperation
                                                                        .builder()
                                                                        .includeObjectsWithNoValueSet(
                                                                            true
                                                                        )
                                                                        .operationType(
                                                                            PublicBoolPropertyOperation
                                                                                .OperationType
                                                                                .BOOL
                                                                        )
                                                                        .operator("operator")
                                                                        .value(true)
                                                                        .build()
                                                                )
                                                                .property("property")
                                                                .build()
                                                        )
                                                        .build()
                                                )
                                                .filterBranchOperator("filterBranchOperator")
                                                .filterBranchType(
                                                    PublicNotAnyFilterBranch.FilterBranchType
                                                        .NOT_ANY
                                                )
                                                .addFilter(
                                                    PublicPropertyFilter.builder()
                                                        .filterType(
                                                            PublicPropertyFilter.FilterType.PROPERTY
                                                        )
                                                        .operation(
                                                            PublicBoolPropertyOperation.builder()
                                                                .includeObjectsWithNoValueSet(true)
                                                                .operationType(
                                                                    PublicBoolPropertyOperation
                                                                        .OperationType
                                                                        .BOOL
                                                                )
                                                                .operator("operator")
                                                                .value(true)
                                                                .build()
                                                        )
                                                        .property("property")
                                                        .build()
                                                )
                                                .build()
                                        )
                                        .filterBranchOperator("filterBranchOperator")
                                        .filterBranchType(
                                            PublicNotAllFilterBranch.FilterBranchType.NOT_ALL
                                        )
                                        .addFilter(
                                            PublicPropertyFilter.builder()
                                                .filterType(
                                                    PublicPropertyFilter.FilterType.PROPERTY
                                                )
                                                .operation(
                                                    PublicBoolPropertyOperation.builder()
                                                        .includeObjectsWithNoValueSet(true)
                                                        .operationType(
                                                            PublicBoolPropertyOperation
                                                                .OperationType
                                                                .BOOL
                                                        )
                                                        .operator("operator")
                                                        .value(true)
                                                        .build()
                                                )
                                                .property("property")
                                                .build()
                                        )
                                        .build()
                                )
                                .filterBranchOperator("filterBranchOperator")
                                .filterBranchType(PublicAndFilterBranch.FilterBranchType.AND)
                                .addFilter(
                                    PublicPropertyFilter.builder()
                                        .filterType(PublicPropertyFilter.FilterType.PROPERTY)
                                        .operation(
                                            PublicBoolPropertyOperation.builder()
                                                .includeObjectsWithNoValueSet(true)
                                                .operationType(
                                                    PublicBoolPropertyOperation.OperationType.BOOL
                                                )
                                                .operator("operator")
                                                .value(true)
                                                .build()
                                        )
                                        .property("property")
                                        .build()
                                )
                                .build()
                        )
                        .filterBranchOperator("filterBranchOperator")
                        .filterBranchType(PublicOrFilterBranch.FilterBranchType.OR)
                        .addFilter(
                            PublicPropertyFilter.builder()
                                .filterType(PublicPropertyFilter.FilterType.PROPERTY)
                                .operation(
                                    PublicBoolPropertyOperation.builder()
                                        .includeObjectsWithNoValueSet(true)
                                        .operationType(
                                            PublicBoolPropertyOperation.OperationType.BOOL
                                        )
                                        .operator("operator")
                                        .value(true)
                                        .build()
                                )
                                .property("property")
                                .build()
                        )
                        .build()
                )
                .listFolderId(0)
                .listPermissions(
                    PublicListPermissions.builder()
                        .addTeamsWithEditAccess(0)
                        .addUsersWithEditAccess(0)
                        .build()
                )
                .membershipSettings(
                    PublicMembershipSettings.builder()
                        .includeUnassigned(true)
                        .membershipTeamId(0)
                        .build()
                )
                .build()

        val roundtrippedListCreateRequest =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(listCreateRequest),
                jacksonTypeRef<ListCreateRequest>(),
            )

        assertThat(roundtrippedListCreateRequest).isEqualTo(listCreateRequest)
    }
}
