// File generated from our OpenAPI spec by Stainless.

package com.hubspot_sdk.api.models.events.eventdefinitions

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.hubspot_sdk.api.core.jsonMapper
import com.hubspot_sdk.api.models.ForwardPaging
import com.hubspot_sdk.api.models.NextPage
import com.hubspot_sdk.api.models.Option
import com.hubspot_sdk.api.models.Property
import com.hubspot_sdk.api.models.PropertyModificationMetadata
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class CollectionResponseWithTotalExternalBehavioralEventTypeDefinitionForwardPagingTest {

    @Test
    fun create() {
        val collectionResponseWithTotalExternalBehavioralEventTypeDefinitionForwardPaging =
            CollectionResponseWithTotalExternalBehavioralEventTypeDefinitionForwardPaging.builder()
                .addResult(
                    ExternalBehavioralEventTypeDefinition.builder()
                        .id("id")
                        .archived(true)
                        .addAssociation(
                            AssociationDefinition.builder()
                                .id(0)
                                .allowsCustomLabels(true)
                                .cardinality(AssociationDefinition.Cardinality.ONE_TO_ONE)
                                .category(AssociationDefinition.Category.HUBSPOT_DEFINED)
                                .fromObjectTypeId("fromObjectTypeId")
                                .hasAllAssociatedObjects(true)
                                .hasCascadingDeletes(true)
                                .hasUserEnforcedMaxFromObjectIds(true)
                                .hasUserEnforcedMaxToObjectIds(true)
                                .hidden(true)
                                .inverseAllowsCustomLabels(true)
                                .inverseCardinality(
                                    AssociationDefinition.InverseCardinality.ONE_TO_ONE
                                )
                                .inverseHasAllAssociatedObjects(true)
                                .inverseId(0)
                                .inverseName("inverseName")
                                .isInversePrimary(true)
                                .isPrimary(true)
                                .maxFromObjectIds(0)
                                .maxToObjectIds(0)
                                .name("name")
                                .portalUniqueIdentifier("portalUniqueIdentifier")
                                .toObjectTypeId("toObjectTypeId")
                                .fromObjectType(AssociationDefinition.FromObjectType.CONTACT)
                                .inverseLabel("inverseLabel")
                                .label("label")
                                .toObjectType(AssociationDefinition.ToObjectType.CONTACT)
                                .build()
                        )
                        .fullyQualifiedName("fullyQualifiedName")
                        .labels(
                            BehavioralEventTypeDefinitionLabels.builder()
                                .singular("singular")
                                .plural("plural")
                                .build()
                        )
                        .name("name")
                        .objectTypeId("objectTypeId")
                        .addProperty(
                            Property.builder()
                                .description("description")
                                .fieldType("select")
                                .groupName("my_object_information")
                                .label("My object property")
                                .name("my_object_property")
                                .addOption(
                                    Option.builder()
                                        .hidden(false)
                                        .label("Option A")
                                        .value("A")
                                        .description("Choice number one")
                                        .displayOrder(1)
                                        .build()
                                )
                                .addOption(
                                    Option.builder()
                                        .hidden(false)
                                        .label("Option B")
                                        .value("B")
                                        .description("Choice number two")
                                        .displayOrder(2)
                                        .build()
                                )
                                .type("enumeration")
                                .archived(true)
                                .archivedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .calculated(true)
                                .calculationFormula("calculationFormula")
                                .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .createdUserId("createdUserId")
                                .dataSensitivity(Property.DataSensitivity.NON_SENSITIVE)
                                .displayOrder(2)
                                .externalOptions(true)
                                .formField(true)
                                .hasUniqueValue(false)
                                .hidden(true)
                                .hubspotDefined(true)
                                .modificationMetadata(
                                    PropertyModificationMetadata.builder()
                                        .archivable(true)
                                        .readOnlyDefinition(false)
                                        .readOnlyValue(false)
                                        .readOnlyOptions(false)
                                        .build()
                                )
                                .referencedObjectType("referencedObjectType")
                                .addSensitiveDataCategory("string")
                                .showCurrencySymbol(true)
                                .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .updatedUserId("updatedUserId")
                                .build()
                        )
                        .comboEventRules(
                            ComboEventRuleBranch.builder()
                                .addComposingRule(
                                    ComboEventRule.builder()
                                        .count(0)
                                        .eventTypeId("eventTypeId")
                                        .addPropertyFilter(
                                            PropertyFilter.builder()
                                                .filterType(PropertyFilter.FilterType.PROPERTY)
                                                .operation(
                                                    BoolPropertyOperation.builder()
                                                        .includeObjectsWithNoValueSet(true)
                                                        .operationType("operationType")
                                                        .operator(
                                                            BoolPropertyOperation.Operator
                                                                .IS_EQUAL_TO
                                                        )
                                                        .operatorName("operatorName")
                                                        .propertyType(
                                                            BoolPropertyOperation.PropertyType.BOOL
                                                        )
                                                        .value(true)
                                                        .defaultValue("defaultValue")
                                                        .build()
                                                )
                                                .property("property")
                                                .frameworkFilterId(0L)
                                                .build()
                                        )
                                        .lookbackWindowDays(0)
                                        .build()
                                )
                                .operationType(ComboEventRuleBranch.OperationType.AND)
                                .ruleBranches(listOf())
                                .build()
                        )
                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .createdUserId(0)
                        .description("description")
                        .primaryObject("primaryObject")
                        .primaryObjectId("primaryObjectId")
                        .trackingType(
                            ExternalBehavioralEventTypeDefinition.TrackingType.VISITED_URL
                        )
                        .build()
                )
                .total(0)
                .paging(
                    ForwardPaging.builder()
                        .next(NextPage.builder().after("after").link("link").build())
                        .build()
                )
                .build()

        assertThat(
                collectionResponseWithTotalExternalBehavioralEventTypeDefinitionForwardPaging
                    .results()
            )
            .containsExactly(
                ExternalBehavioralEventTypeDefinition.builder()
                    .id("id")
                    .archived(true)
                    .addAssociation(
                        AssociationDefinition.builder()
                            .id(0)
                            .allowsCustomLabels(true)
                            .cardinality(AssociationDefinition.Cardinality.ONE_TO_ONE)
                            .category(AssociationDefinition.Category.HUBSPOT_DEFINED)
                            .fromObjectTypeId("fromObjectTypeId")
                            .hasAllAssociatedObjects(true)
                            .hasCascadingDeletes(true)
                            .hasUserEnforcedMaxFromObjectIds(true)
                            .hasUserEnforcedMaxToObjectIds(true)
                            .hidden(true)
                            .inverseAllowsCustomLabels(true)
                            .inverseCardinality(AssociationDefinition.InverseCardinality.ONE_TO_ONE)
                            .inverseHasAllAssociatedObjects(true)
                            .inverseId(0)
                            .inverseName("inverseName")
                            .isInversePrimary(true)
                            .isPrimary(true)
                            .maxFromObjectIds(0)
                            .maxToObjectIds(0)
                            .name("name")
                            .portalUniqueIdentifier("portalUniqueIdentifier")
                            .toObjectTypeId("toObjectTypeId")
                            .fromObjectType(AssociationDefinition.FromObjectType.CONTACT)
                            .inverseLabel("inverseLabel")
                            .label("label")
                            .toObjectType(AssociationDefinition.ToObjectType.CONTACT)
                            .build()
                    )
                    .fullyQualifiedName("fullyQualifiedName")
                    .labels(
                        BehavioralEventTypeDefinitionLabels.builder()
                            .singular("singular")
                            .plural("plural")
                            .build()
                    )
                    .name("name")
                    .objectTypeId("objectTypeId")
                    .addProperty(
                        Property.builder()
                            .description("description")
                            .fieldType("select")
                            .groupName("my_object_information")
                            .label("My object property")
                            .name("my_object_property")
                            .addOption(
                                Option.builder()
                                    .hidden(false)
                                    .label("Option A")
                                    .value("A")
                                    .description("Choice number one")
                                    .displayOrder(1)
                                    .build()
                            )
                            .addOption(
                                Option.builder()
                                    .hidden(false)
                                    .label("Option B")
                                    .value("B")
                                    .description("Choice number two")
                                    .displayOrder(2)
                                    .build()
                            )
                            .type("enumeration")
                            .archived(true)
                            .archivedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .calculated(true)
                            .calculationFormula("calculationFormula")
                            .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .createdUserId("createdUserId")
                            .dataSensitivity(Property.DataSensitivity.NON_SENSITIVE)
                            .displayOrder(2)
                            .externalOptions(true)
                            .formField(true)
                            .hasUniqueValue(false)
                            .hidden(true)
                            .hubspotDefined(true)
                            .modificationMetadata(
                                PropertyModificationMetadata.builder()
                                    .archivable(true)
                                    .readOnlyDefinition(false)
                                    .readOnlyValue(false)
                                    .readOnlyOptions(false)
                                    .build()
                            )
                            .referencedObjectType("referencedObjectType")
                            .addSensitiveDataCategory("string")
                            .showCurrencySymbol(true)
                            .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .updatedUserId("updatedUserId")
                            .build()
                    )
                    .comboEventRules(
                        ComboEventRuleBranch.builder()
                            .addComposingRule(
                                ComboEventRule.builder()
                                    .count(0)
                                    .eventTypeId("eventTypeId")
                                    .addPropertyFilter(
                                        PropertyFilter.builder()
                                            .filterType(PropertyFilter.FilterType.PROPERTY)
                                            .operation(
                                                BoolPropertyOperation.builder()
                                                    .includeObjectsWithNoValueSet(true)
                                                    .operationType("operationType")
                                                    .operator(
                                                        BoolPropertyOperation.Operator.IS_EQUAL_TO
                                                    )
                                                    .operatorName("operatorName")
                                                    .propertyType(
                                                        BoolPropertyOperation.PropertyType.BOOL
                                                    )
                                                    .value(true)
                                                    .defaultValue("defaultValue")
                                                    .build()
                                            )
                                            .property("property")
                                            .frameworkFilterId(0L)
                                            .build()
                                    )
                                    .lookbackWindowDays(0)
                                    .build()
                            )
                            .operationType(ComboEventRuleBranch.OperationType.AND)
                            .ruleBranches(listOf())
                            .build()
                    )
                    .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .createdUserId(0)
                    .description("description")
                    .primaryObject("primaryObject")
                    .primaryObjectId("primaryObjectId")
                    .trackingType(ExternalBehavioralEventTypeDefinition.TrackingType.VISITED_URL)
                    .build()
            )
        assertThat(
                collectionResponseWithTotalExternalBehavioralEventTypeDefinitionForwardPaging
                    .total()
            )
            .isEqualTo(0)
        assertThat(
                collectionResponseWithTotalExternalBehavioralEventTypeDefinitionForwardPaging
                    .paging()
            )
            .contains(
                ForwardPaging.builder()
                    .next(NextPage.builder().after("after").link("link").build())
                    .build()
            )
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val collectionResponseWithTotalExternalBehavioralEventTypeDefinitionForwardPaging =
            CollectionResponseWithTotalExternalBehavioralEventTypeDefinitionForwardPaging.builder()
                .addResult(
                    ExternalBehavioralEventTypeDefinition.builder()
                        .id("id")
                        .archived(true)
                        .addAssociation(
                            AssociationDefinition.builder()
                                .id(0)
                                .allowsCustomLabels(true)
                                .cardinality(AssociationDefinition.Cardinality.ONE_TO_ONE)
                                .category(AssociationDefinition.Category.HUBSPOT_DEFINED)
                                .fromObjectTypeId("fromObjectTypeId")
                                .hasAllAssociatedObjects(true)
                                .hasCascadingDeletes(true)
                                .hasUserEnforcedMaxFromObjectIds(true)
                                .hasUserEnforcedMaxToObjectIds(true)
                                .hidden(true)
                                .inverseAllowsCustomLabels(true)
                                .inverseCardinality(
                                    AssociationDefinition.InverseCardinality.ONE_TO_ONE
                                )
                                .inverseHasAllAssociatedObjects(true)
                                .inverseId(0)
                                .inverseName("inverseName")
                                .isInversePrimary(true)
                                .isPrimary(true)
                                .maxFromObjectIds(0)
                                .maxToObjectIds(0)
                                .name("name")
                                .portalUniqueIdentifier("portalUniqueIdentifier")
                                .toObjectTypeId("toObjectTypeId")
                                .fromObjectType(AssociationDefinition.FromObjectType.CONTACT)
                                .inverseLabel("inverseLabel")
                                .label("label")
                                .toObjectType(AssociationDefinition.ToObjectType.CONTACT)
                                .build()
                        )
                        .fullyQualifiedName("fullyQualifiedName")
                        .labels(
                            BehavioralEventTypeDefinitionLabels.builder()
                                .singular("singular")
                                .plural("plural")
                                .build()
                        )
                        .name("name")
                        .objectTypeId("objectTypeId")
                        .addProperty(
                            Property.builder()
                                .description("description")
                                .fieldType("select")
                                .groupName("my_object_information")
                                .label("My object property")
                                .name("my_object_property")
                                .addOption(
                                    Option.builder()
                                        .hidden(false)
                                        .label("Option A")
                                        .value("A")
                                        .description("Choice number one")
                                        .displayOrder(1)
                                        .build()
                                )
                                .addOption(
                                    Option.builder()
                                        .hidden(false)
                                        .label("Option B")
                                        .value("B")
                                        .description("Choice number two")
                                        .displayOrder(2)
                                        .build()
                                )
                                .type("enumeration")
                                .archived(true)
                                .archivedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .calculated(true)
                                .calculationFormula("calculationFormula")
                                .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .createdUserId("createdUserId")
                                .dataSensitivity(Property.DataSensitivity.NON_SENSITIVE)
                                .displayOrder(2)
                                .externalOptions(true)
                                .formField(true)
                                .hasUniqueValue(false)
                                .hidden(true)
                                .hubspotDefined(true)
                                .modificationMetadata(
                                    PropertyModificationMetadata.builder()
                                        .archivable(true)
                                        .readOnlyDefinition(false)
                                        .readOnlyValue(false)
                                        .readOnlyOptions(false)
                                        .build()
                                )
                                .referencedObjectType("referencedObjectType")
                                .addSensitiveDataCategory("string")
                                .showCurrencySymbol(true)
                                .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .updatedUserId("updatedUserId")
                                .build()
                        )
                        .comboEventRules(
                            ComboEventRuleBranch.builder()
                                .addComposingRule(
                                    ComboEventRule.builder()
                                        .count(0)
                                        .eventTypeId("eventTypeId")
                                        .addPropertyFilter(
                                            PropertyFilter.builder()
                                                .filterType(PropertyFilter.FilterType.PROPERTY)
                                                .operation(
                                                    BoolPropertyOperation.builder()
                                                        .includeObjectsWithNoValueSet(true)
                                                        .operationType("operationType")
                                                        .operator(
                                                            BoolPropertyOperation.Operator
                                                                .IS_EQUAL_TO
                                                        )
                                                        .operatorName("operatorName")
                                                        .propertyType(
                                                            BoolPropertyOperation.PropertyType.BOOL
                                                        )
                                                        .value(true)
                                                        .defaultValue("defaultValue")
                                                        .build()
                                                )
                                                .property("property")
                                                .frameworkFilterId(0L)
                                                .build()
                                        )
                                        .lookbackWindowDays(0)
                                        .build()
                                )
                                .operationType(ComboEventRuleBranch.OperationType.AND)
                                .ruleBranches(listOf())
                                .build()
                        )
                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .createdUserId(0)
                        .description("description")
                        .primaryObject("primaryObject")
                        .primaryObjectId("primaryObjectId")
                        .trackingType(
                            ExternalBehavioralEventTypeDefinition.TrackingType.VISITED_URL
                        )
                        .build()
                )
                .total(0)
                .paging(
                    ForwardPaging.builder()
                        .next(NextPage.builder().after("after").link("link").build())
                        .build()
                )
                .build()

        val roundtrippedCollectionResponseWithTotalExternalBehavioralEventTypeDefinitionForwardPaging =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(
                    collectionResponseWithTotalExternalBehavioralEventTypeDefinitionForwardPaging
                ),
                jacksonTypeRef<
                    CollectionResponseWithTotalExternalBehavioralEventTypeDefinitionForwardPaging
                >(),
            )

        assertThat(
                roundtrippedCollectionResponseWithTotalExternalBehavioralEventTypeDefinitionForwardPaging
            )
            .isEqualTo(
                collectionResponseWithTotalExternalBehavioralEventTypeDefinitionForwardPaging
            )
    }
}
