// File generated from our OpenAPI spec by Stainless.

package com.hubspot_sdk.api.models.events.eventdefinitions

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.hubspot_sdk.api.core.JsonValue
import com.hubspot_sdk.api.core.jsonMapper
import com.hubspot_sdk.api.models.Option
import com.hubspot_sdk.api.models.Property
import com.hubspot_sdk.api.models.PropertyModificationMetadata
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class EventDefinitionUpdateResponseTest {

    @Test
    fun create() {
        val eventDefinitionUpdateResponse =
            EventDefinitionUpdateResponse.builder()
                .id("id")
                .archived(true)
                .addAssociation(
                    EventDefinitionUpdateResponse.Association.builder()
                        .id(0)
                        .allowsCustomLabels(false)
                        .cardinality(
                            EventDefinitionUpdateResponse.Association.Cardinality.ONE_TO_ONE
                        )
                        .category(
                            EventDefinitionUpdateResponse.Association.Category.HUBSPOT_DEFINED
                        )
                        .fromObjectTypeId("")
                        .hasAllAssociatedObjects(false)
                        .hasCascadingDeletes(false)
                        .hasUserEnforcedMaxFromObjectIds(false)
                        .hasUserEnforcedMaxToObjectIds(false)
                        .hidden(false)
                        .inverseAllowsCustomLabels(false)
                        .inverseCardinality(
                            EventDefinitionUpdateResponse.Association.InverseCardinality.ONE_TO_ONE
                        )
                        .inverseHasAllAssociatedObjects(false)
                        .inverseId(0)
                        .inverseName("")
                        .isInversePrimary(false)
                        .isPrimary(false)
                        .maxFromObjectIds(0)
                        .maxToObjectIds(0)
                        .name("")
                        .portalUniqueIdentifier("")
                        .toObjectTypeId("")
                        .fromObjectType(
                            EventDefinitionUpdateResponse.Association.FromObjectType.CONTACT
                        )
                        .inverseLabel("")
                        .label("")
                        .toObjectType(
                            EventDefinitionUpdateResponse.Association.ToObjectType.CONTACT
                        )
                        .build()
                )
                .fullyQualifiedName("fullyQualifiedName")
                .labels(
                    EventDefinitionUpdateResponse.Labels.builder()
                        .singular("singular")
                        .plural("plural")
                        .build()
                )
                .name("name")
                .objectTypeId("objectTypeId")
                .addProperty(
                    Property.builder()
                        .description("")
                        .fieldType("select")
                        .groupName("my_object_information")
                        .label("My object property")
                        .name("my_object_property")
                        .addOption(
                            Option.builder()
                                .description("Choice number one")
                                .displayOrder(1)
                                .doubleData(0.0)
                                .hidden(false)
                                .label("Option A")
                                .readOnly(false)
                                .value("A")
                                .build()
                        )
                        .addOption(
                            Option.builder()
                                .description("Choice number two")
                                .displayOrder(2)
                                .doubleData(0.0)
                                .hidden(false)
                                .label("Option B")
                                .readOnly(false)
                                .value("B")
                                .build()
                        )
                        .type("enumeration")
                        .archived(false)
                        .archivedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .calculated(false)
                        .calculationFormula("")
                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .createdUserId("")
                        .dataSensitivity(Property.DataSensitivity.NON_SENSITIVE)
                        .displayOrder(2)
                        .externalOptions(false)
                        .formField(false)
                        .hasUniqueValue(false)
                        .hidden(false)
                        .hubspotDefined(false)
                        .modificationMetadata(
                            PropertyModificationMetadata.builder()
                                .archivable(true)
                                .readOnlyDefinition(false)
                                .readOnlyValue(false)
                                .readOnlyOptions(false)
                                .build()
                        )
                        .referencedObjectType("")
                        .addSensitiveDataCategory("string")
                        .showCurrencySymbol(false)
                        .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .updatedUserId("updatedUserId")
                        .build()
                )
                .comboEventRules(
                    EventDefinitionUpdateResponse.ComboEventRules.builder()
                        .addComposingRule(
                            EventDefinitionUpdateResponse.ComboEventRules.ComposingRule.builder()
                                .count(0)
                                .eventTypeId("eventTypeId")
                                .addPropertyFilter(
                                    EventDefinitionUpdateResponse.ComboEventRules.ComposingRule
                                        .PropertyFilter
                                        .builder()
                                        .filterType(
                                            EventDefinitionUpdateResponse.ComboEventRules
                                                .ComposingRule
                                                .PropertyFilter
                                                .FilterType
                                                .PROPERTY
                                        )
                                        .operation(
                                            EventDefinitionUpdateResponse.ComboEventRules
                                                .ComposingRule
                                                .PropertyFilter
                                                .Operation
                                                .EventsEventdefinitionsBoolPropertyOperation
                                                .builder()
                                                .includeObjectsWithNoValueSet(true)
                                                .operationType("operationType")
                                                .operator(
                                                    EventDefinitionUpdateResponse.ComboEventRules
                                                        .ComposingRule
                                                        .PropertyFilter
                                                        .Operation
                                                        .EventsEventdefinitionsBoolPropertyOperation
                                                        .Operator
                                                        .IS_EQUAL_TO
                                                )
                                                .operatorName("operatorName")
                                                .propertyType(
                                                    EventDefinitionUpdateResponse.ComboEventRules
                                                        .ComposingRule
                                                        .PropertyFilter
                                                        .Operation
                                                        .EventsEventdefinitionsBoolPropertyOperation
                                                        .PropertyType
                                                        .BOOL
                                                )
                                                .value(true)
                                                .defaultValue("defaultValue")
                                                .build()
                                        )
                                        .property("property")
                                        .frameworkFilterId(0L)
                                        .build()
                                )
                                .lookbackWindowDays(0)
                                .build()
                        )
                        .operationType(
                            EventDefinitionUpdateResponse.ComboEventRules.OperationType.AND
                        )
                        .addRuleBranch(JsonValue.from(mapOf<String, Any>()))
                        .build()
                )
                .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .createdUserId(0)
                .description("description")
                .primaryObject("primaryObject")
                .primaryObjectId("primaryObjectId")
                .trackingType(EventDefinitionUpdateResponse.TrackingType.VISITED_URL)
                .build()

        assertThat(eventDefinitionUpdateResponse.id()).isEqualTo("id")
        assertThat(eventDefinitionUpdateResponse.archived()).isEqualTo(true)
        assertThat(eventDefinitionUpdateResponse.associations())
            .containsExactly(
                EventDefinitionUpdateResponse.Association.builder()
                    .id(0)
                    .allowsCustomLabels(false)
                    .cardinality(EventDefinitionUpdateResponse.Association.Cardinality.ONE_TO_ONE)
                    .category(EventDefinitionUpdateResponse.Association.Category.HUBSPOT_DEFINED)
                    .fromObjectTypeId("")
                    .hasAllAssociatedObjects(false)
                    .hasCascadingDeletes(false)
                    .hasUserEnforcedMaxFromObjectIds(false)
                    .hasUserEnforcedMaxToObjectIds(false)
                    .hidden(false)
                    .inverseAllowsCustomLabels(false)
                    .inverseCardinality(
                        EventDefinitionUpdateResponse.Association.InverseCardinality.ONE_TO_ONE
                    )
                    .inverseHasAllAssociatedObjects(false)
                    .inverseId(0)
                    .inverseName("")
                    .isInversePrimary(false)
                    .isPrimary(false)
                    .maxFromObjectIds(0)
                    .maxToObjectIds(0)
                    .name("")
                    .portalUniqueIdentifier("")
                    .toObjectTypeId("")
                    .fromObjectType(
                        EventDefinitionUpdateResponse.Association.FromObjectType.CONTACT
                    )
                    .inverseLabel("")
                    .label("")
                    .toObjectType(EventDefinitionUpdateResponse.Association.ToObjectType.CONTACT)
                    .build()
            )
        assertThat(eventDefinitionUpdateResponse.fullyQualifiedName())
            .isEqualTo("fullyQualifiedName")
        assertThat(eventDefinitionUpdateResponse.labels())
            .isEqualTo(
                EventDefinitionUpdateResponse.Labels.builder()
                    .singular("singular")
                    .plural("plural")
                    .build()
            )
        assertThat(eventDefinitionUpdateResponse.name()).isEqualTo("name")
        assertThat(eventDefinitionUpdateResponse.objectTypeId()).isEqualTo("objectTypeId")
        assertThat(eventDefinitionUpdateResponse.properties())
            .containsExactly(
                Property.builder()
                    .description("")
                    .fieldType("select")
                    .groupName("my_object_information")
                    .label("My object property")
                    .name("my_object_property")
                    .addOption(
                        Option.builder()
                            .description("Choice number one")
                            .displayOrder(1)
                            .doubleData(0.0)
                            .hidden(false)
                            .label("Option A")
                            .readOnly(false)
                            .value("A")
                            .build()
                    )
                    .addOption(
                        Option.builder()
                            .description("Choice number two")
                            .displayOrder(2)
                            .doubleData(0.0)
                            .hidden(false)
                            .label("Option B")
                            .readOnly(false)
                            .value("B")
                            .build()
                    )
                    .type("enumeration")
                    .archived(false)
                    .archivedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .calculated(false)
                    .calculationFormula("")
                    .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .createdUserId("")
                    .dataSensitivity(Property.DataSensitivity.NON_SENSITIVE)
                    .displayOrder(2)
                    .externalOptions(false)
                    .formField(false)
                    .hasUniqueValue(false)
                    .hidden(false)
                    .hubspotDefined(false)
                    .modificationMetadata(
                        PropertyModificationMetadata.builder()
                            .archivable(true)
                            .readOnlyDefinition(false)
                            .readOnlyValue(false)
                            .readOnlyOptions(false)
                            .build()
                    )
                    .referencedObjectType("")
                    .addSensitiveDataCategory("string")
                    .showCurrencySymbol(false)
                    .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .updatedUserId("updatedUserId")
                    .build()
            )
        assertThat(eventDefinitionUpdateResponse.comboEventRules())
            .contains(
                EventDefinitionUpdateResponse.ComboEventRules.builder()
                    .addComposingRule(
                        EventDefinitionUpdateResponse.ComboEventRules.ComposingRule.builder()
                            .count(0)
                            .eventTypeId("eventTypeId")
                            .addPropertyFilter(
                                EventDefinitionUpdateResponse.ComboEventRules.ComposingRule
                                    .PropertyFilter
                                    .builder()
                                    .filterType(
                                        EventDefinitionUpdateResponse.ComboEventRules.ComposingRule
                                            .PropertyFilter
                                            .FilterType
                                            .PROPERTY
                                    )
                                    .operation(
                                        EventDefinitionUpdateResponse.ComboEventRules.ComposingRule
                                            .PropertyFilter
                                            .Operation
                                            .EventsEventdefinitionsBoolPropertyOperation
                                            .builder()
                                            .includeObjectsWithNoValueSet(true)
                                            .operationType("operationType")
                                            .operator(
                                                EventDefinitionUpdateResponse.ComboEventRules
                                                    .ComposingRule
                                                    .PropertyFilter
                                                    .Operation
                                                    .EventsEventdefinitionsBoolPropertyOperation
                                                    .Operator
                                                    .IS_EQUAL_TO
                                            )
                                            .operatorName("operatorName")
                                            .propertyType(
                                                EventDefinitionUpdateResponse.ComboEventRules
                                                    .ComposingRule
                                                    .PropertyFilter
                                                    .Operation
                                                    .EventsEventdefinitionsBoolPropertyOperation
                                                    .PropertyType
                                                    .BOOL
                                            )
                                            .value(true)
                                            .defaultValue("defaultValue")
                                            .build()
                                    )
                                    .property("property")
                                    .frameworkFilterId(0L)
                                    .build()
                            )
                            .lookbackWindowDays(0)
                            .build()
                    )
                    .operationType(EventDefinitionUpdateResponse.ComboEventRules.OperationType.AND)
                    .addRuleBranch(JsonValue.from(mapOf<String, Any>()))
                    .build()
            )
        assertThat(eventDefinitionUpdateResponse.createdAt())
            .contains(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
        assertThat(eventDefinitionUpdateResponse.createdUserId()).contains(0)
        assertThat(eventDefinitionUpdateResponse.description()).contains("description")
        assertThat(eventDefinitionUpdateResponse.primaryObject()).contains("primaryObject")
        assertThat(eventDefinitionUpdateResponse.primaryObjectId()).contains("primaryObjectId")
        assertThat(eventDefinitionUpdateResponse.trackingType())
            .contains(EventDefinitionUpdateResponse.TrackingType.VISITED_URL)
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val eventDefinitionUpdateResponse =
            EventDefinitionUpdateResponse.builder()
                .id("id")
                .archived(true)
                .addAssociation(
                    EventDefinitionUpdateResponse.Association.builder()
                        .id(0)
                        .allowsCustomLabels(false)
                        .cardinality(
                            EventDefinitionUpdateResponse.Association.Cardinality.ONE_TO_ONE
                        )
                        .category(
                            EventDefinitionUpdateResponse.Association.Category.HUBSPOT_DEFINED
                        )
                        .fromObjectTypeId("")
                        .hasAllAssociatedObjects(false)
                        .hasCascadingDeletes(false)
                        .hasUserEnforcedMaxFromObjectIds(false)
                        .hasUserEnforcedMaxToObjectIds(false)
                        .hidden(false)
                        .inverseAllowsCustomLabels(false)
                        .inverseCardinality(
                            EventDefinitionUpdateResponse.Association.InverseCardinality.ONE_TO_ONE
                        )
                        .inverseHasAllAssociatedObjects(false)
                        .inverseId(0)
                        .inverseName("")
                        .isInversePrimary(false)
                        .isPrimary(false)
                        .maxFromObjectIds(0)
                        .maxToObjectIds(0)
                        .name("")
                        .portalUniqueIdentifier("")
                        .toObjectTypeId("")
                        .fromObjectType(
                            EventDefinitionUpdateResponse.Association.FromObjectType.CONTACT
                        )
                        .inverseLabel("")
                        .label("")
                        .toObjectType(
                            EventDefinitionUpdateResponse.Association.ToObjectType.CONTACT
                        )
                        .build()
                )
                .fullyQualifiedName("fullyQualifiedName")
                .labels(
                    EventDefinitionUpdateResponse.Labels.builder()
                        .singular("singular")
                        .plural("plural")
                        .build()
                )
                .name("name")
                .objectTypeId("objectTypeId")
                .addProperty(
                    Property.builder()
                        .description("")
                        .fieldType("select")
                        .groupName("my_object_information")
                        .label("My object property")
                        .name("my_object_property")
                        .addOption(
                            Option.builder()
                                .description("Choice number one")
                                .displayOrder(1)
                                .doubleData(0.0)
                                .hidden(false)
                                .label("Option A")
                                .readOnly(false)
                                .value("A")
                                .build()
                        )
                        .addOption(
                            Option.builder()
                                .description("Choice number two")
                                .displayOrder(2)
                                .doubleData(0.0)
                                .hidden(false)
                                .label("Option B")
                                .readOnly(false)
                                .value("B")
                                .build()
                        )
                        .type("enumeration")
                        .archived(false)
                        .archivedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .calculated(false)
                        .calculationFormula("")
                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .createdUserId("")
                        .dataSensitivity(Property.DataSensitivity.NON_SENSITIVE)
                        .displayOrder(2)
                        .externalOptions(false)
                        .formField(false)
                        .hasUniqueValue(false)
                        .hidden(false)
                        .hubspotDefined(false)
                        .modificationMetadata(
                            PropertyModificationMetadata.builder()
                                .archivable(true)
                                .readOnlyDefinition(false)
                                .readOnlyValue(false)
                                .readOnlyOptions(false)
                                .build()
                        )
                        .referencedObjectType("")
                        .addSensitiveDataCategory("string")
                        .showCurrencySymbol(false)
                        .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .updatedUserId("updatedUserId")
                        .build()
                )
                .comboEventRules(
                    EventDefinitionUpdateResponse.ComboEventRules.builder()
                        .addComposingRule(
                            EventDefinitionUpdateResponse.ComboEventRules.ComposingRule.builder()
                                .count(0)
                                .eventTypeId("eventTypeId")
                                .addPropertyFilter(
                                    EventDefinitionUpdateResponse.ComboEventRules.ComposingRule
                                        .PropertyFilter
                                        .builder()
                                        .filterType(
                                            EventDefinitionUpdateResponse.ComboEventRules
                                                .ComposingRule
                                                .PropertyFilter
                                                .FilterType
                                                .PROPERTY
                                        )
                                        .operation(
                                            EventDefinitionUpdateResponse.ComboEventRules
                                                .ComposingRule
                                                .PropertyFilter
                                                .Operation
                                                .EventsEventdefinitionsBoolPropertyOperation
                                                .builder()
                                                .includeObjectsWithNoValueSet(true)
                                                .operationType("operationType")
                                                .operator(
                                                    EventDefinitionUpdateResponse.ComboEventRules
                                                        .ComposingRule
                                                        .PropertyFilter
                                                        .Operation
                                                        .EventsEventdefinitionsBoolPropertyOperation
                                                        .Operator
                                                        .IS_EQUAL_TO
                                                )
                                                .operatorName("operatorName")
                                                .propertyType(
                                                    EventDefinitionUpdateResponse.ComboEventRules
                                                        .ComposingRule
                                                        .PropertyFilter
                                                        .Operation
                                                        .EventsEventdefinitionsBoolPropertyOperation
                                                        .PropertyType
                                                        .BOOL
                                                )
                                                .value(true)
                                                .defaultValue("defaultValue")
                                                .build()
                                        )
                                        .property("property")
                                        .frameworkFilterId(0L)
                                        .build()
                                )
                                .lookbackWindowDays(0)
                                .build()
                        )
                        .operationType(
                            EventDefinitionUpdateResponse.ComboEventRules.OperationType.AND
                        )
                        .addRuleBranch(JsonValue.from(mapOf<String, Any>()))
                        .build()
                )
                .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .createdUserId(0)
                .description("description")
                .primaryObject("primaryObject")
                .primaryObjectId("primaryObjectId")
                .trackingType(EventDefinitionUpdateResponse.TrackingType.VISITED_URL)
                .build()

        val roundtrippedEventDefinitionUpdateResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(eventDefinitionUpdateResponse),
                jacksonTypeRef<EventDefinitionUpdateResponse>(),
            )

        assertThat(roundtrippedEventDefinitionUpdateResponse)
            .isEqualTo(eventDefinitionUpdateResponse)
    }
}
