// File generated from our OpenAPI spec by Stainless.

package com.hubspot_sdk.api.models.events.eventdefinitions

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.hubspot_sdk.api.core.JsonValue
import com.hubspot_sdk.api.core.jsonMapper
import com.hubspot_sdk.api.models.ForwardPaging
import com.hubspot_sdk.api.models.NextPage
import com.hubspot_sdk.api.models.Option
import com.hubspot_sdk.api.models.Property
import com.hubspot_sdk.api.models.PropertyModificationMetadata
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class EventDefinitionListPageResponseTest {

    @Test
    fun create() {
        val eventDefinitionListPageResponse =
            EventDefinitionListPageResponse.builder()
                .addResult(
                    EventDefinitionListResponse.builder()
                        .id("id")
                        .archived(true)
                        .addAssociation(
                            EventDefinitionListResponse.Association.builder()
                                .id(0)
                                .allowsCustomLabels(false)
                                .cardinality(
                                    EventDefinitionListResponse.Association.Cardinality.ONE_TO_ONE
                                )
                                .category(
                                    EventDefinitionListResponse.Association.Category.HUBSPOT_DEFINED
                                )
                                .fromObjectTypeId("")
                                .hasAllAssociatedObjects(false)
                                .hasCascadingDeletes(false)
                                .hasUserEnforcedMaxFromObjectIds(false)
                                .hasUserEnforcedMaxToObjectIds(false)
                                .hidden(false)
                                .inverseAllowsCustomLabels(false)
                                .inverseCardinality(
                                    EventDefinitionListResponse.Association.InverseCardinality
                                        .ONE_TO_ONE
                                )
                                .inverseHasAllAssociatedObjects(false)
                                .inverseId(0)
                                .inverseName("")
                                .isInversePrimary(false)
                                .isPrimary(false)
                                .maxFromObjectIds(0)
                                .maxToObjectIds(0)
                                .name("")
                                .portalUniqueIdentifier("")
                                .toObjectTypeId("")
                                .fromObjectType(
                                    EventDefinitionListResponse.Association.FromObjectType.CONTACT
                                )
                                .inverseLabel("")
                                .label("")
                                .toObjectType(
                                    EventDefinitionListResponse.Association.ToObjectType.CONTACT
                                )
                                .build()
                        )
                        .fullyQualifiedName("fullyQualifiedName")
                        .labels(
                            EventDefinitionListResponse.Labels.builder()
                                .singular("singular")
                                .plural("plural")
                                .build()
                        )
                        .name("name")
                        .objectTypeId("objectTypeId")
                        .addProperty(
                            Property.builder()
                                .description("")
                                .fieldType("select")
                                .groupName("my_object_information")
                                .label("My object property")
                                .name("my_object_property")
                                .addOption(
                                    Option.builder()
                                        .description("Choice number one")
                                        .displayOrder(1)
                                        .doubleData(0.0)
                                        .hidden(false)
                                        .label("Option A")
                                        .readOnly(false)
                                        .value("A")
                                        .build()
                                )
                                .addOption(
                                    Option.builder()
                                        .description("Choice number two")
                                        .displayOrder(2)
                                        .doubleData(0.0)
                                        .hidden(false)
                                        .label("Option B")
                                        .readOnly(false)
                                        .value("B")
                                        .build()
                                )
                                .type("enumeration")
                                .archived(false)
                                .archivedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .calculated(false)
                                .calculationFormula("")
                                .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .createdUserId("")
                                .dataSensitivity(Property.DataSensitivity.NON_SENSITIVE)
                                .displayOrder(2)
                                .externalOptions(false)
                                .formField(false)
                                .hasUniqueValue(false)
                                .hidden(false)
                                .hubspotDefined(false)
                                .modificationMetadata(
                                    PropertyModificationMetadata.builder()
                                        .archivable(true)
                                        .readOnlyDefinition(false)
                                        .readOnlyValue(false)
                                        .readOnlyOptions(false)
                                        .build()
                                )
                                .referencedObjectType("")
                                .addSensitiveDataCategory("string")
                                .showCurrencySymbol(false)
                                .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .updatedUserId("updatedUserId")
                                .build()
                        )
                        .comboEventRules(
                            EventDefinitionListResponse.ComboEventRules.builder()
                                .addComposingRule(
                                    EventDefinitionListResponse.ComboEventRules.ComposingRule
                                        .builder()
                                        .count(0)
                                        .eventTypeId("eventTypeId")
                                        .addPropertyFilter(
                                            EventDefinitionListResponse.ComboEventRules
                                                .ComposingRule
                                                .PropertyFilter
                                                .builder()
                                                .filterType(
                                                    EventDefinitionListResponse.ComboEventRules
                                                        .ComposingRule
                                                        .PropertyFilter
                                                        .FilterType
                                                        .PROPERTY
                                                )
                                                .operation(
                                                    EventDefinitionListResponse.ComboEventRules
                                                        .ComposingRule
                                                        .PropertyFilter
                                                        .Operation
                                                        .EventsEventdefinitionsBoolPropertyOperation
                                                        .builder()
                                                        .includeObjectsWithNoValueSet(true)
                                                        .operationType("operationType")
                                                        .operator(
                                                            EventDefinitionListResponse
                                                                .ComboEventRules
                                                                .ComposingRule
                                                                .PropertyFilter
                                                                .Operation
                                                                .EventsEventdefinitionsBoolPropertyOperation
                                                                .Operator
                                                                .IS_EQUAL_TO
                                                        )
                                                        .operatorName("operatorName")
                                                        .propertyType(
                                                            EventDefinitionListResponse
                                                                .ComboEventRules
                                                                .ComposingRule
                                                                .PropertyFilter
                                                                .Operation
                                                                .EventsEventdefinitionsBoolPropertyOperation
                                                                .PropertyType
                                                                .BOOL
                                                        )
                                                        .value(true)
                                                        .defaultValue("defaultValue")
                                                        .build()
                                                )
                                                .property("property")
                                                .frameworkFilterId(0L)
                                                .build()
                                        )
                                        .lookbackWindowDays(0)
                                        .build()
                                )
                                .operationType(
                                    EventDefinitionListResponse.ComboEventRules.OperationType.AND
                                )
                                .addRuleBranch(JsonValue.from(mapOf<String, Any>()))
                                .build()
                        )
                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .createdUserId(0)
                        .description("description")
                        .primaryObject("primaryObject")
                        .primaryObjectId("primaryObjectId")
                        .trackingType(EventDefinitionListResponse.TrackingType.VISITED_URL)
                        .build()
                )
                .total(0)
                .paging(
                    ForwardPaging.builder()
                        .next(NextPage.builder().after("").link("").build())
                        .build()
                )
                .build()

        assertThat(eventDefinitionListPageResponse.results())
            .containsExactly(
                EventDefinitionListResponse.builder()
                    .id("id")
                    .archived(true)
                    .addAssociation(
                        EventDefinitionListResponse.Association.builder()
                            .id(0)
                            .allowsCustomLabels(false)
                            .cardinality(
                                EventDefinitionListResponse.Association.Cardinality.ONE_TO_ONE
                            )
                            .category(
                                EventDefinitionListResponse.Association.Category.HUBSPOT_DEFINED
                            )
                            .fromObjectTypeId("")
                            .hasAllAssociatedObjects(false)
                            .hasCascadingDeletes(false)
                            .hasUserEnforcedMaxFromObjectIds(false)
                            .hasUserEnforcedMaxToObjectIds(false)
                            .hidden(false)
                            .inverseAllowsCustomLabels(false)
                            .inverseCardinality(
                                EventDefinitionListResponse.Association.InverseCardinality
                                    .ONE_TO_ONE
                            )
                            .inverseHasAllAssociatedObjects(false)
                            .inverseId(0)
                            .inverseName("")
                            .isInversePrimary(false)
                            .isPrimary(false)
                            .maxFromObjectIds(0)
                            .maxToObjectIds(0)
                            .name("")
                            .portalUniqueIdentifier("")
                            .toObjectTypeId("")
                            .fromObjectType(
                                EventDefinitionListResponse.Association.FromObjectType.CONTACT
                            )
                            .inverseLabel("")
                            .label("")
                            .toObjectType(
                                EventDefinitionListResponse.Association.ToObjectType.CONTACT
                            )
                            .build()
                    )
                    .fullyQualifiedName("fullyQualifiedName")
                    .labels(
                        EventDefinitionListResponse.Labels.builder()
                            .singular("singular")
                            .plural("plural")
                            .build()
                    )
                    .name("name")
                    .objectTypeId("objectTypeId")
                    .addProperty(
                        Property.builder()
                            .description("")
                            .fieldType("select")
                            .groupName("my_object_information")
                            .label("My object property")
                            .name("my_object_property")
                            .addOption(
                                Option.builder()
                                    .description("Choice number one")
                                    .displayOrder(1)
                                    .doubleData(0.0)
                                    .hidden(false)
                                    .label("Option A")
                                    .readOnly(false)
                                    .value("A")
                                    .build()
                            )
                            .addOption(
                                Option.builder()
                                    .description("Choice number two")
                                    .displayOrder(2)
                                    .doubleData(0.0)
                                    .hidden(false)
                                    .label("Option B")
                                    .readOnly(false)
                                    .value("B")
                                    .build()
                            )
                            .type("enumeration")
                            .archived(false)
                            .archivedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .calculated(false)
                            .calculationFormula("")
                            .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .createdUserId("")
                            .dataSensitivity(Property.DataSensitivity.NON_SENSITIVE)
                            .displayOrder(2)
                            .externalOptions(false)
                            .formField(false)
                            .hasUniqueValue(false)
                            .hidden(false)
                            .hubspotDefined(false)
                            .modificationMetadata(
                                PropertyModificationMetadata.builder()
                                    .archivable(true)
                                    .readOnlyDefinition(false)
                                    .readOnlyValue(false)
                                    .readOnlyOptions(false)
                                    .build()
                            )
                            .referencedObjectType("")
                            .addSensitiveDataCategory("string")
                            .showCurrencySymbol(false)
                            .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .updatedUserId("updatedUserId")
                            .build()
                    )
                    .comboEventRules(
                        EventDefinitionListResponse.ComboEventRules.builder()
                            .addComposingRule(
                                EventDefinitionListResponse.ComboEventRules.ComposingRule.builder()
                                    .count(0)
                                    .eventTypeId("eventTypeId")
                                    .addPropertyFilter(
                                        EventDefinitionListResponse.ComboEventRules.ComposingRule
                                            .PropertyFilter
                                            .builder()
                                            .filterType(
                                                EventDefinitionListResponse.ComboEventRules
                                                    .ComposingRule
                                                    .PropertyFilter
                                                    .FilterType
                                                    .PROPERTY
                                            )
                                            .operation(
                                                EventDefinitionListResponse.ComboEventRules
                                                    .ComposingRule
                                                    .PropertyFilter
                                                    .Operation
                                                    .EventsEventdefinitionsBoolPropertyOperation
                                                    .builder()
                                                    .includeObjectsWithNoValueSet(true)
                                                    .operationType("operationType")
                                                    .operator(
                                                        EventDefinitionListResponse.ComboEventRules
                                                            .ComposingRule
                                                            .PropertyFilter
                                                            .Operation
                                                            .EventsEventdefinitionsBoolPropertyOperation
                                                            .Operator
                                                            .IS_EQUAL_TO
                                                    )
                                                    .operatorName("operatorName")
                                                    .propertyType(
                                                        EventDefinitionListResponse.ComboEventRules
                                                            .ComposingRule
                                                            .PropertyFilter
                                                            .Operation
                                                            .EventsEventdefinitionsBoolPropertyOperation
                                                            .PropertyType
                                                            .BOOL
                                                    )
                                                    .value(true)
                                                    .defaultValue("defaultValue")
                                                    .build()
                                            )
                                            .property("property")
                                            .frameworkFilterId(0L)
                                            .build()
                                    )
                                    .lookbackWindowDays(0)
                                    .build()
                            )
                            .operationType(
                                EventDefinitionListResponse.ComboEventRules.OperationType.AND
                            )
                            .addRuleBranch(JsonValue.from(mapOf<String, Any>()))
                            .build()
                    )
                    .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .createdUserId(0)
                    .description("description")
                    .primaryObject("primaryObject")
                    .primaryObjectId("primaryObjectId")
                    .trackingType(EventDefinitionListResponse.TrackingType.VISITED_URL)
                    .build()
            )
        assertThat(eventDefinitionListPageResponse.total()).isEqualTo(0)
        assertThat(eventDefinitionListPageResponse.paging())
            .contains(
                ForwardPaging.builder().next(NextPage.builder().after("").link("").build()).build()
            )
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val eventDefinitionListPageResponse =
            EventDefinitionListPageResponse.builder()
                .addResult(
                    EventDefinitionListResponse.builder()
                        .id("id")
                        .archived(true)
                        .addAssociation(
                            EventDefinitionListResponse.Association.builder()
                                .id(0)
                                .allowsCustomLabels(false)
                                .cardinality(
                                    EventDefinitionListResponse.Association.Cardinality.ONE_TO_ONE
                                )
                                .category(
                                    EventDefinitionListResponse.Association.Category.HUBSPOT_DEFINED
                                )
                                .fromObjectTypeId("")
                                .hasAllAssociatedObjects(false)
                                .hasCascadingDeletes(false)
                                .hasUserEnforcedMaxFromObjectIds(false)
                                .hasUserEnforcedMaxToObjectIds(false)
                                .hidden(false)
                                .inverseAllowsCustomLabels(false)
                                .inverseCardinality(
                                    EventDefinitionListResponse.Association.InverseCardinality
                                        .ONE_TO_ONE
                                )
                                .inverseHasAllAssociatedObjects(false)
                                .inverseId(0)
                                .inverseName("")
                                .isInversePrimary(false)
                                .isPrimary(false)
                                .maxFromObjectIds(0)
                                .maxToObjectIds(0)
                                .name("")
                                .portalUniqueIdentifier("")
                                .toObjectTypeId("")
                                .fromObjectType(
                                    EventDefinitionListResponse.Association.FromObjectType.CONTACT
                                )
                                .inverseLabel("")
                                .label("")
                                .toObjectType(
                                    EventDefinitionListResponse.Association.ToObjectType.CONTACT
                                )
                                .build()
                        )
                        .fullyQualifiedName("fullyQualifiedName")
                        .labels(
                            EventDefinitionListResponse.Labels.builder()
                                .singular("singular")
                                .plural("plural")
                                .build()
                        )
                        .name("name")
                        .objectTypeId("objectTypeId")
                        .addProperty(
                            Property.builder()
                                .description("")
                                .fieldType("select")
                                .groupName("my_object_information")
                                .label("My object property")
                                .name("my_object_property")
                                .addOption(
                                    Option.builder()
                                        .description("Choice number one")
                                        .displayOrder(1)
                                        .doubleData(0.0)
                                        .hidden(false)
                                        .label("Option A")
                                        .readOnly(false)
                                        .value("A")
                                        .build()
                                )
                                .addOption(
                                    Option.builder()
                                        .description("Choice number two")
                                        .displayOrder(2)
                                        .doubleData(0.0)
                                        .hidden(false)
                                        .label("Option B")
                                        .readOnly(false)
                                        .value("B")
                                        .build()
                                )
                                .type("enumeration")
                                .archived(false)
                                .archivedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .calculated(false)
                                .calculationFormula("")
                                .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .createdUserId("")
                                .dataSensitivity(Property.DataSensitivity.NON_SENSITIVE)
                                .displayOrder(2)
                                .externalOptions(false)
                                .formField(false)
                                .hasUniqueValue(false)
                                .hidden(false)
                                .hubspotDefined(false)
                                .modificationMetadata(
                                    PropertyModificationMetadata.builder()
                                        .archivable(true)
                                        .readOnlyDefinition(false)
                                        .readOnlyValue(false)
                                        .readOnlyOptions(false)
                                        .build()
                                )
                                .referencedObjectType("")
                                .addSensitiveDataCategory("string")
                                .showCurrencySymbol(false)
                                .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .updatedUserId("updatedUserId")
                                .build()
                        )
                        .comboEventRules(
                            EventDefinitionListResponse.ComboEventRules.builder()
                                .addComposingRule(
                                    EventDefinitionListResponse.ComboEventRules.ComposingRule
                                        .builder()
                                        .count(0)
                                        .eventTypeId("eventTypeId")
                                        .addPropertyFilter(
                                            EventDefinitionListResponse.ComboEventRules
                                                .ComposingRule
                                                .PropertyFilter
                                                .builder()
                                                .filterType(
                                                    EventDefinitionListResponse.ComboEventRules
                                                        .ComposingRule
                                                        .PropertyFilter
                                                        .FilterType
                                                        .PROPERTY
                                                )
                                                .operation(
                                                    EventDefinitionListResponse.ComboEventRules
                                                        .ComposingRule
                                                        .PropertyFilter
                                                        .Operation
                                                        .EventsEventdefinitionsBoolPropertyOperation
                                                        .builder()
                                                        .includeObjectsWithNoValueSet(true)
                                                        .operationType("operationType")
                                                        .operator(
                                                            EventDefinitionListResponse
                                                                .ComboEventRules
                                                                .ComposingRule
                                                                .PropertyFilter
                                                                .Operation
                                                                .EventsEventdefinitionsBoolPropertyOperation
                                                                .Operator
                                                                .IS_EQUAL_TO
                                                        )
                                                        .operatorName("operatorName")
                                                        .propertyType(
                                                            EventDefinitionListResponse
                                                                .ComboEventRules
                                                                .ComposingRule
                                                                .PropertyFilter
                                                                .Operation
                                                                .EventsEventdefinitionsBoolPropertyOperation
                                                                .PropertyType
                                                                .BOOL
                                                        )
                                                        .value(true)
                                                        .defaultValue("defaultValue")
                                                        .build()
                                                )
                                                .property("property")
                                                .frameworkFilterId(0L)
                                                .build()
                                        )
                                        .lookbackWindowDays(0)
                                        .build()
                                )
                                .operationType(
                                    EventDefinitionListResponse.ComboEventRules.OperationType.AND
                                )
                                .addRuleBranch(JsonValue.from(mapOf<String, Any>()))
                                .build()
                        )
                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .createdUserId(0)
                        .description("description")
                        .primaryObject("primaryObject")
                        .primaryObjectId("primaryObjectId")
                        .trackingType(EventDefinitionListResponse.TrackingType.VISITED_URL)
                        .build()
                )
                .total(0)
                .paging(
                    ForwardPaging.builder()
                        .next(NextPage.builder().after("").link("").build())
                        .build()
                )
                .build()

        val roundtrippedEventDefinitionListPageResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(eventDefinitionListPageResponse),
                jacksonTypeRef<EventDefinitionListPageResponse>(),
            )

        assertThat(roundtrippedEventDefinitionListPageResponse)
            .isEqualTo(eventDefinitionListPageResponse)
    }
}
