// File generated from our OpenAPI spec by Stainless.

package com.hubspot_sdk.api.models.conversations

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.hubspot_sdk.api.core.JsonValue
import com.hubspot_sdk.api.core.jsonMapper
import com.hubspot_sdk.api.models.ForwardPaging
import com.hubspot_sdk.api.models.NextPage
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class CollectionResponsePublicMessageForwardPagingTest {

    @Test
    fun create() {
        val collectionResponsePublicMessageForwardPaging =
            CollectionResponsePublicMessageForwardPaging.builder()
                .addResult(
                    ConversationsPublicConversationsMessage.builder()
                        .id("id")
                        .archived(true)
                        .addAttachment(
                            PublicFile.builder()
                                .fileId("fileId")
                                .fileUsageType("fileUsageType")
                                .type(PublicFile.Type.FILE)
                                .name("name")
                                .url("url")
                                .build()
                        )
                        .channelAccountId("channelAccountId")
                        .channelId("channelId")
                        .client(
                            PublicClient.builder()
                                .clientType(PublicClient.ClientType.HUBSPOT)
                                .integrationAppId(0)
                                .build()
                        )
                        .conversationsThreadId("conversationsThreadId")
                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .createdBy("createdBy")
                        .direction(ConversationsPublicConversationsMessage.Direction.INCOMING)
                        .addRecipient(
                            PublicRecipient.builder()
                                .deliveryIdentifier(
                                    PublicDeliveryIdentifier.builder()
                                        .type("type")
                                        .value("value")
                                        .build()
                                )
                                .actorId("actorId")
                                .name("name")
                                .recipientField("recipientField")
                                .build()
                        )
                        .addSender(
                            PublicSender.builder()
                                .actorId("actorId")
                                .deliveryIdentifier(
                                    PublicDeliveryIdentifier.builder()
                                        .type("type")
                                        .value("value")
                                        .build()
                                )
                                .name("name")
                                .senderField("senderField")
                                .build()
                        )
                        .text("text")
                        .truncationStatus(
                            ConversationsPublicConversationsMessage.TruncationStatus.NOT_TRUNCATED
                        )
                        .type(ConversationsPublicConversationsMessage.Type.MESSAGE)
                        .inReplyToId("inReplyToId")
                        .richText("richText")
                        .status(
                            PublicMessageStatus.builder()
                                .statusType(PublicMessageStatus.StatusType.FAILED)
                                .failureDetails(
                                    PublicMessageFailureDetails.builder()
                                        .errorMessageTokens(
                                            PublicMessageFailureDetails.ErrorMessageTokens.builder()
                                                .putAdditionalProperty(
                                                    "foo",
                                                    JsonValue.from("string"),
                                                )
                                                .build()
                                        )
                                        .errorMessage("errorMessage")
                                        .build()
                                )
                                .build()
                        )
                        .subject("subject")
                        .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .build()
                )
                .paging(
                    ForwardPaging.builder()
                        .next(NextPage.builder().after("after").link("link").build())
                        .build()
                )
                .build()

        assertThat(collectionResponsePublicMessageForwardPaging.results())
            .containsExactly(
                PublicMessage.ofConversationsPublicConversations(
                    ConversationsPublicConversationsMessage.builder()
                        .id("id")
                        .archived(true)
                        .addAttachment(
                            PublicFile.builder()
                                .fileId("fileId")
                                .fileUsageType("fileUsageType")
                                .type(PublicFile.Type.FILE)
                                .name("name")
                                .url("url")
                                .build()
                        )
                        .channelAccountId("channelAccountId")
                        .channelId("channelId")
                        .client(
                            PublicClient.builder()
                                .clientType(PublicClient.ClientType.HUBSPOT)
                                .integrationAppId(0)
                                .build()
                        )
                        .conversationsThreadId("conversationsThreadId")
                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .createdBy("createdBy")
                        .direction(ConversationsPublicConversationsMessage.Direction.INCOMING)
                        .addRecipient(
                            PublicRecipient.builder()
                                .deliveryIdentifier(
                                    PublicDeliveryIdentifier.builder()
                                        .type("type")
                                        .value("value")
                                        .build()
                                )
                                .actorId("actorId")
                                .name("name")
                                .recipientField("recipientField")
                                .build()
                        )
                        .addSender(
                            PublicSender.builder()
                                .actorId("actorId")
                                .deliveryIdentifier(
                                    PublicDeliveryIdentifier.builder()
                                        .type("type")
                                        .value("value")
                                        .build()
                                )
                                .name("name")
                                .senderField("senderField")
                                .build()
                        )
                        .text("text")
                        .truncationStatus(
                            ConversationsPublicConversationsMessage.TruncationStatus.NOT_TRUNCATED
                        )
                        .type(ConversationsPublicConversationsMessage.Type.MESSAGE)
                        .inReplyToId("inReplyToId")
                        .richText("richText")
                        .status(
                            PublicMessageStatus.builder()
                                .statusType(PublicMessageStatus.StatusType.FAILED)
                                .failureDetails(
                                    PublicMessageFailureDetails.builder()
                                        .errorMessageTokens(
                                            PublicMessageFailureDetails.ErrorMessageTokens.builder()
                                                .putAdditionalProperty(
                                                    "foo",
                                                    JsonValue.from("string"),
                                                )
                                                .build()
                                        )
                                        .errorMessage("errorMessage")
                                        .build()
                                )
                                .build()
                        )
                        .subject("subject")
                        .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .build()
                )
            )
        assertThat(collectionResponsePublicMessageForwardPaging.paging())
            .contains(
                ForwardPaging.builder()
                    .next(NextPage.builder().after("after").link("link").build())
                    .build()
            )
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val collectionResponsePublicMessageForwardPaging =
            CollectionResponsePublicMessageForwardPaging.builder()
                .addResult(
                    ConversationsPublicConversationsMessage.builder()
                        .id("id")
                        .archived(true)
                        .addAttachment(
                            PublicFile.builder()
                                .fileId("fileId")
                                .fileUsageType("fileUsageType")
                                .type(PublicFile.Type.FILE)
                                .name("name")
                                .url("url")
                                .build()
                        )
                        .channelAccountId("channelAccountId")
                        .channelId("channelId")
                        .client(
                            PublicClient.builder()
                                .clientType(PublicClient.ClientType.HUBSPOT)
                                .integrationAppId(0)
                                .build()
                        )
                        .conversationsThreadId("conversationsThreadId")
                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .createdBy("createdBy")
                        .direction(ConversationsPublicConversationsMessage.Direction.INCOMING)
                        .addRecipient(
                            PublicRecipient.builder()
                                .deliveryIdentifier(
                                    PublicDeliveryIdentifier.builder()
                                        .type("type")
                                        .value("value")
                                        .build()
                                )
                                .actorId("actorId")
                                .name("name")
                                .recipientField("recipientField")
                                .build()
                        )
                        .addSender(
                            PublicSender.builder()
                                .actorId("actorId")
                                .deliveryIdentifier(
                                    PublicDeliveryIdentifier.builder()
                                        .type("type")
                                        .value("value")
                                        .build()
                                )
                                .name("name")
                                .senderField("senderField")
                                .build()
                        )
                        .text("text")
                        .truncationStatus(
                            ConversationsPublicConversationsMessage.TruncationStatus.NOT_TRUNCATED
                        )
                        .type(ConversationsPublicConversationsMessage.Type.MESSAGE)
                        .inReplyToId("inReplyToId")
                        .richText("richText")
                        .status(
                            PublicMessageStatus.builder()
                                .statusType(PublicMessageStatus.StatusType.FAILED)
                                .failureDetails(
                                    PublicMessageFailureDetails.builder()
                                        .errorMessageTokens(
                                            PublicMessageFailureDetails.ErrorMessageTokens.builder()
                                                .putAdditionalProperty(
                                                    "foo",
                                                    JsonValue.from("string"),
                                                )
                                                .build()
                                        )
                                        .errorMessage("errorMessage")
                                        .build()
                                )
                                .build()
                        )
                        .subject("subject")
                        .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .build()
                )
                .paging(
                    ForwardPaging.builder()
                        .next(NextPage.builder().after("after").link("link").build())
                        .build()
                )
                .build()

        val roundtrippedCollectionResponsePublicMessageForwardPaging =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(collectionResponsePublicMessageForwardPaging),
                jacksonTypeRef<CollectionResponsePublicMessageForwardPaging>(),
            )

        assertThat(roundtrippedCollectionResponsePublicMessageForwardPaging)
            .isEqualTo(collectionResponsePublicMessageForwardPaging)
    }
}
