// File generated from our OpenAPI spec by Stainless.

package com.hubspot_sdk.api.services.async.conversations

import com.hubspot_sdk.api.TestServerExtension
import com.hubspot_sdk.api.client.okhttp.HubspotOkHttpClientAsync
import com.hubspot_sdk.api.core.JsonValue
import com.hubspot_sdk.api.models.conversations.customchannels.CustomChannelCreateParams
import com.hubspot_sdk.api.models.conversations.customchannels.CustomChannelUpdateParams
import org.junit.jupiter.api.Disabled
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.extension.ExtendWith

@ExtendWith(TestServerExtension::class)
internal class CustomChannelServiceAsyncTest {

    @Disabled("Prism tests are disabled")
    @Test
    fun create() {
        val client =
            HubspotOkHttpClientAsync.builder()
                .baseUrl(TestServerExtension.BASE_URL)
                .accessToken("pat-na1-xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx")
                .build()
        val customChannelServiceAsync = client.conversations().customChannels()

        val customChannelFuture =
            customChannelServiceAsync.create(
                CustomChannelCreateParams.builder()
                    .capabilities(
                        CustomChannelCreateParams.Capabilities.builder()
                            .putAdditionalProperty("0", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("1", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("2", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("3", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("4", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("5", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("6", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("7", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("8", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("9", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("10", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("11", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("12", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("13", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("14", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("15", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("16", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("17", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("18", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("19", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("20", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("21", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("22", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("23", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("24", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("25", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("26", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("27", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("28", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("29", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("30", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("31", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("32", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("33", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("34", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("35", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("36", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("37", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("38", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("39", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("40", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("41", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("42", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("43", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("44", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("45", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("46", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("47", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("48", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("49", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("50", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("51", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("52", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("53", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("54", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("55", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("56", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("57", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("58", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("59", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("60", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("61", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("62", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("63", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("64", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("65", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("66", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("67", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("68", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("69", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("70", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("71", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("72", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("73", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("74", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("75", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("76", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("77", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("78", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("79", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("80", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("81", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("82", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("83", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("84", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("85", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("86", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("87", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("88", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("89", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("90", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("91", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("92", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("93", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("94", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("95", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("96", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("97", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("98", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("99", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("100", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("101", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("102", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("103", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("104", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("105", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("106", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("107", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("108", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("109", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("110", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("111", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("112", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("113", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("114", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("115", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("116", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("117", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("118", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("119", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("120", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("121", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("122", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("123", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("124", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("125", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("126", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("127", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("128", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("129", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("130", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("131", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("132", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("133", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("134", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("135", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("136", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("137", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("138", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("139", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("140", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("141", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("142", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("143", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("144", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("145", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("146", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("147", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("148", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("149", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("150", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("151", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("152", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("153", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("154", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("155", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("156", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("157", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("158", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("159", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("160", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("161", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("162", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("163", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("164", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("165", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("166", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("167", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("168", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("169", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("170", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("171", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("172", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("173", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("174", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("175", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("176", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("177", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("178", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("179", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("180", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("181", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("182", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("183", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("184", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("185", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("186", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("187", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("188", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("189", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("190", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("191", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("192", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("193", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("194", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("195", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("196", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("197", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("198", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("199", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("200", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("201", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("202", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("203", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("204", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("205", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("206", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("207", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("208", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("209", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("210", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("211", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("212", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("213", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("214", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("215", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("216", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("217", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("218", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("219", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("220", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("221", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("222", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("223", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("224", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("225", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("226", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("227", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("228", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("229", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("230", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("231", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("232", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("233", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("234", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("235", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("236", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("237", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("238", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("239", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("240", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("241", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("242", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("243", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("244", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("245", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("246", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("247", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("248", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("249", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("250", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("251", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("252", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("253", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("254", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("255", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("256", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("257", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("258", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("259", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("260", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("261", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("262", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("263", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("264", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("265", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("266", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("267", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("268", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("269", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("270", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("271", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("272", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("273", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("274", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("275", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("276", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("277", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("278", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("279", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("280", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("281", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("282", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("283", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("284", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("285", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("286", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("287", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("288", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("289", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("290", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("291", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("292", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("293", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("294", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("295", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("296", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("297", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("298", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("299", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("300", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("301", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("302", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("303", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("304", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("305", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("306", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("307", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("308", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("309", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("310", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("311", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("312", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("313", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("314", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("315", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("316", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("317", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("318", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("319", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("320", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("321", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("322", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("323", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("324", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("325", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("326", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("327", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("328", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("329", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("330", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("331", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("332", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("333", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("334", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("335", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("336", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("337", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("338", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("339", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("340", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("341", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("342", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("343", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("344", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("345", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("346", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("347", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("348", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("349", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("350", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("351", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("352", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("353", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("354", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("355", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("356", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("357", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("358", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("359", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("360", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("361", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("362", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("363", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("364", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("365", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("366", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("367", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("368", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("369", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("370", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("371", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("372", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("373", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("374", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("375", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("376", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("377", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("378", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("379", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("380", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("381", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("382", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("383", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("384", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("385", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("386", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("387", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("388", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("389", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("390", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("391", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("392", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("393", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("394", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("395", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("396", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("397", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("398", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("399", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("400", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("401", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("402", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("403", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("404", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("405", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("406", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("407", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("408", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("409", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("410", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("411", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("412", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("413", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("414", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("415", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("416", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("417", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("418", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("419", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("420", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("421", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("422", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("423", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("424", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("425", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("426", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("427", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("428", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("429", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("430", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("431", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("432", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("433", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("434", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("435", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("436", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("437", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("438", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("439", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("440", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("441", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("442", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("443", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("444", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("445", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("446", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("447", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("448", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("449", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("450", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("451", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("452", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("453", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("454", JsonValue.from(mapOf<String, Any>()))
                            .build()
                    )
                    .name("name")
                    .channelAccountConnectionRedirectUrl("channelAccountConnectionRedirectUrl")
                    .channelDescription("channelDescription")
                    .channelLogoUrl("channelLogoUrl")
                    .webhookUrl("webhookUrl")
                    .build()
            )

        val customChannel = customChannelFuture.get()
        customChannel.validate()
    }

    @Disabled("Prism tests are disabled")
    @Test
    fun update() {
        val client =
            HubspotOkHttpClientAsync.builder()
                .baseUrl(TestServerExtension.BASE_URL)
                .accessToken("pat-na1-xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx")
                .build()
        val customChannelServiceAsync = client.conversations().customChannels()

        val customChannelFuture =
            customChannelServiceAsync.update(
                CustomChannelUpdateParams.builder()
                    .channelId("channelId")
                    .capabilities(
                        CustomChannelUpdateParams.Capabilities.builder()
                            .putAdditionalProperty("0", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("1", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("2", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("3", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("4", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("5", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("6", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("7", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("8", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("9", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("10", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("11", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("12", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("13", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("14", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("15", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("16", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("17", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("18", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("19", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("20", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("21", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("22", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("23", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("24", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("25", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("26", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("27", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("28", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("29", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("30", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("31", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("32", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("33", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("34", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("35", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("36", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("37", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("38", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("39", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("40", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("41", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("42", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("43", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("44", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("45", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("46", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("47", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("48", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("49", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("50", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("51", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("52", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("53", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("54", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("55", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("56", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("57", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("58", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("59", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("60", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("61", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("62", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("63", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("64", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("65", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("66", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("67", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("68", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("69", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("70", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("71", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("72", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("73", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("74", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("75", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("76", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("77", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("78", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("79", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("80", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("81", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("82", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("83", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("84", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("85", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("86", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("87", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("88", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("89", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("90", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("91", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("92", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("93", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("94", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("95", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("96", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("97", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("98", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("99", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("100", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("101", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("102", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("103", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("104", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("105", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("106", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("107", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("108", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("109", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("110", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("111", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("112", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("113", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("114", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("115", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("116", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("117", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("118", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("119", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("120", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("121", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("122", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("123", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("124", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("125", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("126", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("127", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("128", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("129", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("130", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("131", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("132", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("133", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("134", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("135", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("136", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("137", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("138", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("139", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("140", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("141", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("142", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("143", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("144", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("145", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("146", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("147", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("148", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("149", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("150", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("151", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("152", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("153", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("154", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("155", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("156", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("157", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("158", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("159", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("160", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("161", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("162", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("163", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("164", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("165", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("166", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("167", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("168", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("169", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("170", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("171", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("172", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("173", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("174", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("175", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("176", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("177", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("178", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("179", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("180", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("181", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("182", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("183", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("184", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("185", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("186", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("187", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("188", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("189", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("190", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("191", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("192", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("193", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("194", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("195", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("196", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("197", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("198", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("199", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("200", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("201", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("202", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("203", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("204", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("205", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("206", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("207", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("208", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("209", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("210", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("211", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("212", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("213", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("214", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("215", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("216", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("217", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("218", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("219", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("220", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("221", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("222", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("223", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("224", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("225", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("226", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("227", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("228", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("229", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("230", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("231", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("232", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("233", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("234", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("235", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("236", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("237", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("238", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("239", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("240", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("241", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("242", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("243", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("244", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("245", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("246", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("247", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("248", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("249", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("250", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("251", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("252", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("253", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("254", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("255", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("256", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("257", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("258", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("259", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("260", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("261", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("262", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("263", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("264", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("265", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("266", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("267", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("268", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("269", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("270", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("271", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("272", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("273", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("274", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("275", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("276", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("277", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("278", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("279", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("280", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("281", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("282", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("283", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("284", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("285", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("286", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("287", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("288", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("289", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("290", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("291", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("292", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("293", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("294", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("295", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("296", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("297", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("298", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("299", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("300", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("301", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("302", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("303", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("304", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("305", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("306", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("307", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("308", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("309", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("310", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("311", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("312", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("313", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("314", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("315", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("316", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("317", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("318", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("319", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("320", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("321", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("322", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("323", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("324", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("325", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("326", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("327", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("328", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("329", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("330", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("331", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("332", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("333", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("334", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("335", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("336", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("337", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("338", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("339", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("340", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("341", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("342", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("343", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("344", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("345", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("346", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("347", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("348", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("349", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("350", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("351", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("352", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("353", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("354", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("355", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("356", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("357", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("358", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("359", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("360", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("361", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("362", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("363", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("364", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("365", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("366", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("367", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("368", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("369", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("370", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("371", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("372", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("373", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("374", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("375", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("376", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("377", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("378", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("379", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("380", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("381", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("382", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("383", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("384", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("385", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("386", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("387", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("388", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("389", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("390", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("391", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("392", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("393", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("394", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("395", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("396", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("397", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("398", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("399", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("400", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("401", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("402", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("403", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("404", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("405", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("406", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("407", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("408", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("409", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("410", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("411", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("412", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("413", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("414", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("415", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("416", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("417", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("418", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("419", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("420", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("421", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("422", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("423", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("424", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("425", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("426", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("427", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("428", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("429", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("430", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("431", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("432", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("433", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("434", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("435", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("436", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("437", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("438", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("439", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("440", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("441", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("442", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("443", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("444", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("445", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("446", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("447", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("448", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("449", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("450", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("451", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("452", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("453", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("454", JsonValue.from(mapOf<String, Any>()))
                            .build()
                    )
                    .channelDescription(JsonValue.from(mapOf<String, Any>()))
                    .channelLogoUrl(JsonValue.from(mapOf<String, Any>()))
                    .channelAccountConnectionRedirectUrl(JsonValue.from(mapOf<String, Any>()))
                    .name(JsonValue.from(mapOf<String, Any>()))
                    .webhookUrl(JsonValue.from(mapOf<String, Any>()))
                    .build()
            )

        val customChannel = customChannelFuture.get()
        customChannel.validate()
    }

    @Disabled("Prism tests are disabled")
    @Test
    fun list() {
        val client =
            HubspotOkHttpClientAsync.builder()
                .baseUrl(TestServerExtension.BASE_URL)
                .accessToken("pat-na1-xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx")
                .build()
        val customChannelServiceAsync = client.conversations().customChannels()

        val customChannelsFuture = customChannelServiceAsync.list()

        val customChannels = customChannelsFuture.get()
        customChannels.validate()
    }

    @Disabled("Prism tests are disabled")
    @Test
    fun delete() {
        val client =
            HubspotOkHttpClientAsync.builder()
                .baseUrl(TestServerExtension.BASE_URL)
                .accessToken("pat-na1-xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx")
                .build()
        val customChannelServiceAsync = client.conversations().customChannels()

        val future = customChannelServiceAsync.delete("channelId")

        val response = future.get()
    }

    @Disabled("Prism tests are disabled")
    @Test
    fun get() {
        val client =
            HubspotOkHttpClientAsync.builder()
                .baseUrl(TestServerExtension.BASE_URL)
                .accessToken("pat-na1-xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx")
                .build()
        val customChannelServiceAsync = client.conversations().customChannels()

        val customChannelFuture = customChannelServiceAsync.get("channelId")

        val customChannel = customChannelFuture.get()
        customChannel.validate()
    }
}
