// File generated from our OpenAPI spec by Stainless.

package com.hubspot_sdk.api.models.crm.extensions.cardsdev

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.hubspot_sdk.api.core.jsonMapper
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class IntegratorCardPayloadResponseTest {

    @Test
    fun create() {
        val integratorCardPayloadResponse =
            IntegratorCardPayloadResponse.builder()
                .responseVersion(IntegratorCardPayloadResponse.ResponseVersion.V1)
                .addSection(
                    IntegratorObjectResult.builder()
                        .id("id")
                        .addAction(
                            ActionHookActionBody.builder()
                                .httpMethod(ActionHookActionBody.HttpMethod.CONNECT)
                                .addPropertyNamesIncluded("string")
                                .type(ActionHookActionBody.Type.ACTION_HOOK)
                                .url("url")
                                .confirmation(
                                    ActionConfirmationBody.builder()
                                        .cancelButtonLabel("cancelButtonLabel")
                                        .confirmButtonLabel("confirmButtonLabel")
                                        .prompt("prompt")
                                        .build()
                                )
                                .label("label")
                                .build()
                        )
                        .title("title")
                        .addToken(
                            ObjectToken.builder()
                                .value("value")
                                .dataType(ObjectToken.DataType.BOOLEAN)
                                .label("label")
                                .name("name")
                                .build()
                        )
                        .linkUrl("linkUrl")
                        .build()
                )
                .totalCount(0)
                .allItemsLinkUrl("allItemsLinkUrl")
                .cardLabel("cardLabel")
                .topLevelActions(
                    TopLevelActions.builder()
                        .addSecondary(
                            ActionHookActionBody.builder()
                                .httpMethod(ActionHookActionBody.HttpMethod.CONNECT)
                                .addPropertyNamesIncluded("string")
                                .type(ActionHookActionBody.Type.ACTION_HOOK)
                                .url("url")
                                .confirmation(
                                    ActionConfirmationBody.builder()
                                        .cancelButtonLabel("cancelButtonLabel")
                                        .confirmButtonLabel("confirmButtonLabel")
                                        .prompt("prompt")
                                        .build()
                                )
                                .label("label")
                                .build()
                        )
                        .primary(
                            ActionHookActionBody.builder()
                                .httpMethod(ActionHookActionBody.HttpMethod.CONNECT)
                                .addPropertyNamesIncluded("string")
                                .type(ActionHookActionBody.Type.ACTION_HOOK)
                                .url("url")
                                .confirmation(
                                    ActionConfirmationBody.builder()
                                        .cancelButtonLabel("cancelButtonLabel")
                                        .confirmButtonLabel("confirmButtonLabel")
                                        .prompt("prompt")
                                        .build()
                                )
                                .label("label")
                                .build()
                        )
                        .settings(
                            IFrameActionBody.builder()
                                .height(0)
                                .addPropertyNamesIncluded("string")
                                .type(IFrameActionBody.Type.IFRAME)
                                .url("url")
                                .width(0)
                                .label("label")
                                .build()
                        )
                        .build()
                )
                .build()

        assertThat(integratorCardPayloadResponse.responseVersion())
            .isEqualTo(IntegratorCardPayloadResponse.ResponseVersion.V1)
        assertThat(integratorCardPayloadResponse.sections())
            .containsExactly(
                IntegratorObjectResult.builder()
                    .id("id")
                    .addAction(
                        ActionHookActionBody.builder()
                            .httpMethod(ActionHookActionBody.HttpMethod.CONNECT)
                            .addPropertyNamesIncluded("string")
                            .type(ActionHookActionBody.Type.ACTION_HOOK)
                            .url("url")
                            .confirmation(
                                ActionConfirmationBody.builder()
                                    .cancelButtonLabel("cancelButtonLabel")
                                    .confirmButtonLabel("confirmButtonLabel")
                                    .prompt("prompt")
                                    .build()
                            )
                            .label("label")
                            .build()
                    )
                    .title("title")
                    .addToken(
                        ObjectToken.builder()
                            .value("value")
                            .dataType(ObjectToken.DataType.BOOLEAN)
                            .label("label")
                            .name("name")
                            .build()
                    )
                    .linkUrl("linkUrl")
                    .build()
            )
        assertThat(integratorCardPayloadResponse.totalCount()).isEqualTo(0)
        assertThat(integratorCardPayloadResponse.allItemsLinkUrl()).contains("allItemsLinkUrl")
        assertThat(integratorCardPayloadResponse.cardLabel()).contains("cardLabel")
        assertThat(integratorCardPayloadResponse.topLevelActions())
            .contains(
                TopLevelActions.builder()
                    .addSecondary(
                        ActionHookActionBody.builder()
                            .httpMethod(ActionHookActionBody.HttpMethod.CONNECT)
                            .addPropertyNamesIncluded("string")
                            .type(ActionHookActionBody.Type.ACTION_HOOK)
                            .url("url")
                            .confirmation(
                                ActionConfirmationBody.builder()
                                    .cancelButtonLabel("cancelButtonLabel")
                                    .confirmButtonLabel("confirmButtonLabel")
                                    .prompt("prompt")
                                    .build()
                            )
                            .label("label")
                            .build()
                    )
                    .primary(
                        ActionHookActionBody.builder()
                            .httpMethod(ActionHookActionBody.HttpMethod.CONNECT)
                            .addPropertyNamesIncluded("string")
                            .type(ActionHookActionBody.Type.ACTION_HOOK)
                            .url("url")
                            .confirmation(
                                ActionConfirmationBody.builder()
                                    .cancelButtonLabel("cancelButtonLabel")
                                    .confirmButtonLabel("confirmButtonLabel")
                                    .prompt("prompt")
                                    .build()
                            )
                            .label("label")
                            .build()
                    )
                    .settings(
                        IFrameActionBody.builder()
                            .height(0)
                            .addPropertyNamesIncluded("string")
                            .type(IFrameActionBody.Type.IFRAME)
                            .url("url")
                            .width(0)
                            .label("label")
                            .build()
                    )
                    .build()
            )
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val integratorCardPayloadResponse =
            IntegratorCardPayloadResponse.builder()
                .responseVersion(IntegratorCardPayloadResponse.ResponseVersion.V1)
                .addSection(
                    IntegratorObjectResult.builder()
                        .id("id")
                        .addAction(
                            ActionHookActionBody.builder()
                                .httpMethod(ActionHookActionBody.HttpMethod.CONNECT)
                                .addPropertyNamesIncluded("string")
                                .type(ActionHookActionBody.Type.ACTION_HOOK)
                                .url("url")
                                .confirmation(
                                    ActionConfirmationBody.builder()
                                        .cancelButtonLabel("cancelButtonLabel")
                                        .confirmButtonLabel("confirmButtonLabel")
                                        .prompt("prompt")
                                        .build()
                                )
                                .label("label")
                                .build()
                        )
                        .title("title")
                        .addToken(
                            ObjectToken.builder()
                                .value("value")
                                .dataType(ObjectToken.DataType.BOOLEAN)
                                .label("label")
                                .name("name")
                                .build()
                        )
                        .linkUrl("linkUrl")
                        .build()
                )
                .totalCount(0)
                .allItemsLinkUrl("allItemsLinkUrl")
                .cardLabel("cardLabel")
                .topLevelActions(
                    TopLevelActions.builder()
                        .addSecondary(
                            ActionHookActionBody.builder()
                                .httpMethod(ActionHookActionBody.HttpMethod.CONNECT)
                                .addPropertyNamesIncluded("string")
                                .type(ActionHookActionBody.Type.ACTION_HOOK)
                                .url("url")
                                .confirmation(
                                    ActionConfirmationBody.builder()
                                        .cancelButtonLabel("cancelButtonLabel")
                                        .confirmButtonLabel("confirmButtonLabel")
                                        .prompt("prompt")
                                        .build()
                                )
                                .label("label")
                                .build()
                        )
                        .primary(
                            ActionHookActionBody.builder()
                                .httpMethod(ActionHookActionBody.HttpMethod.CONNECT)
                                .addPropertyNamesIncluded("string")
                                .type(ActionHookActionBody.Type.ACTION_HOOK)
                                .url("url")
                                .confirmation(
                                    ActionConfirmationBody.builder()
                                        .cancelButtonLabel("cancelButtonLabel")
                                        .confirmButtonLabel("confirmButtonLabel")
                                        .prompt("prompt")
                                        .build()
                                )
                                .label("label")
                                .build()
                        )
                        .settings(
                            IFrameActionBody.builder()
                                .height(0)
                                .addPropertyNamesIncluded("string")
                                .type(IFrameActionBody.Type.IFRAME)
                                .url("url")
                                .width(0)
                                .label("label")
                                .build()
                        )
                        .build()
                )
                .build()

        val roundtrippedIntegratorCardPayloadResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(integratorCardPayloadResponse),
                jacksonTypeRef<IntegratorCardPayloadResponse>(),
            )

        assertThat(roundtrippedIntegratorCardPayloadResponse)
            .isEqualTo(integratorCardPayloadResponse)
    }
}
