// File generated from our OpenAPI spec by Stainless.

package com.hubspot_sdk.api.models.cms.mediabridge

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.hubspot_sdk.api.core.jsonMapper
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class InboundDbObjectTypeTest {

    @Test
    fun create() {
        val inboundDbObjectType =
            InboundDbObjectType.builder()
                .id(0)
                .allowsSensitiveProperties(true)
                .createDatePropertyName("createDatePropertyName")
                .addDefaultSearchPropertyName("string")
                .deleted(true)
                .fullyQualifiedName("fullyQualifiedName")
                .hasCustomProperties(true)
                .hasDefaultProperties(true)
                .hasExternalObjectIds(true)
                .hasOwners(true)
                .hasPipelines(true)
                .indexedForFiltersAndReports(true)
                .lastModifiedPropertyName("lastModifiedPropertyName")
                .metaType(InboundDbObjectType.MetaType.HUBSPOT)
                .metaTypeId(0)
                .name("name")
                .objectTypeId("objectTypeId")
                .permissioningType("permissioningType")
                .pipelinePropertyName("pipelinePropertyName")
                .pipelineStagePropertyName("pipelineStagePropertyName")
                .addRequiredProperty("string")
                .restorable(true)
                .addScopeMapping(
                    ScopeMapping.builder()
                        .accessLevel("accessLevel")
                        .requestAction("requestAction")
                        .scopeName("scopeName")
                        .build()
                )
                .addSecondaryDisplayLabelPropertyName("string")
                .accessScopeName("accessScopeName")
                .createdAt(0L)
                .description("description")
                .integrationAppId(0)
                .janusGroup("janusGroup")
                .ownerPortalId(0)
                .pipelineCloseDatePropertyName("pipelineCloseDatePropertyName")
                .pipelineTimeToClosePropertyName("pipelineTimeToClosePropertyName")
                .pluralForm("pluralForm")
                .primaryDisplayLabelPropertyName("primaryDisplayLabelPropertyName")
                .readScopeName("readScopeName")
                .singularForm("singularForm")
                .status("status")
                .visibility("visibility")
                .writeScopeName("writeScopeName")
                .build()

        assertThat(inboundDbObjectType.id()).isEqualTo(0)
        assertThat(inboundDbObjectType.allowsSensitiveProperties()).isEqualTo(true)
        assertThat(inboundDbObjectType.createDatePropertyName()).isEqualTo("createDatePropertyName")
        assertThat(inboundDbObjectType.defaultSearchPropertyNames()).containsExactly("string")
        assertThat(inboundDbObjectType.deleted()).isEqualTo(true)
        assertThat(inboundDbObjectType.fullyQualifiedName()).isEqualTo("fullyQualifiedName")
        assertThat(inboundDbObjectType.hasCustomProperties()).isEqualTo(true)
        assertThat(inboundDbObjectType.hasDefaultProperties()).isEqualTo(true)
        assertThat(inboundDbObjectType.hasExternalObjectIds()).isEqualTo(true)
        assertThat(inboundDbObjectType.hasOwners()).isEqualTo(true)
        assertThat(inboundDbObjectType.hasPipelines()).isEqualTo(true)
        assertThat(inboundDbObjectType.indexedForFiltersAndReports()).isEqualTo(true)
        assertThat(inboundDbObjectType.lastModifiedPropertyName())
            .isEqualTo("lastModifiedPropertyName")
        assertThat(inboundDbObjectType.metaType()).isEqualTo(InboundDbObjectType.MetaType.HUBSPOT)
        assertThat(inboundDbObjectType.metaTypeId()).isEqualTo(0)
        assertThat(inboundDbObjectType.name()).isEqualTo("name")
        assertThat(inboundDbObjectType.objectTypeId()).isEqualTo("objectTypeId")
        assertThat(inboundDbObjectType.permissioningType()).isEqualTo("permissioningType")
        assertThat(inboundDbObjectType.pipelinePropertyName()).isEqualTo("pipelinePropertyName")
        assertThat(inboundDbObjectType.pipelineStagePropertyName())
            .isEqualTo("pipelineStagePropertyName")
        assertThat(inboundDbObjectType.requiredProperties()).containsExactly("string")
        assertThat(inboundDbObjectType.restorable()).isEqualTo(true)
        assertThat(inboundDbObjectType.scopeMappings())
            .containsExactly(
                ScopeMapping.builder()
                    .accessLevel("accessLevel")
                    .requestAction("requestAction")
                    .scopeName("scopeName")
                    .build()
            )
        assertThat(inboundDbObjectType.secondaryDisplayLabelPropertyNames())
            .containsExactly("string")
        assertThat(inboundDbObjectType.accessScopeName()).contains("accessScopeName")
        assertThat(inboundDbObjectType.createdAt()).contains(0L)
        assertThat(inboundDbObjectType.description()).contains("description")
        assertThat(inboundDbObjectType.integrationAppId()).contains(0)
        assertThat(inboundDbObjectType.janusGroup()).contains("janusGroup")
        assertThat(inboundDbObjectType.ownerPortalId()).contains(0)
        assertThat(inboundDbObjectType.pipelineCloseDatePropertyName())
            .contains("pipelineCloseDatePropertyName")
        assertThat(inboundDbObjectType.pipelineTimeToClosePropertyName())
            .contains("pipelineTimeToClosePropertyName")
        assertThat(inboundDbObjectType.pluralForm()).contains("pluralForm")
        assertThat(inboundDbObjectType.primaryDisplayLabelPropertyName())
            .contains("primaryDisplayLabelPropertyName")
        assertThat(inboundDbObjectType.readScopeName()).contains("readScopeName")
        assertThat(inboundDbObjectType.singularForm()).contains("singularForm")
        assertThat(inboundDbObjectType.status()).contains("status")
        assertThat(inboundDbObjectType.visibility()).contains("visibility")
        assertThat(inboundDbObjectType.writeScopeName()).contains("writeScopeName")
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val inboundDbObjectType =
            InboundDbObjectType.builder()
                .id(0)
                .allowsSensitiveProperties(true)
                .createDatePropertyName("createDatePropertyName")
                .addDefaultSearchPropertyName("string")
                .deleted(true)
                .fullyQualifiedName("fullyQualifiedName")
                .hasCustomProperties(true)
                .hasDefaultProperties(true)
                .hasExternalObjectIds(true)
                .hasOwners(true)
                .hasPipelines(true)
                .indexedForFiltersAndReports(true)
                .lastModifiedPropertyName("lastModifiedPropertyName")
                .metaType(InboundDbObjectType.MetaType.HUBSPOT)
                .metaTypeId(0)
                .name("name")
                .objectTypeId("objectTypeId")
                .permissioningType("permissioningType")
                .pipelinePropertyName("pipelinePropertyName")
                .pipelineStagePropertyName("pipelineStagePropertyName")
                .addRequiredProperty("string")
                .restorable(true)
                .addScopeMapping(
                    ScopeMapping.builder()
                        .accessLevel("accessLevel")
                        .requestAction("requestAction")
                        .scopeName("scopeName")
                        .build()
                )
                .addSecondaryDisplayLabelPropertyName("string")
                .accessScopeName("accessScopeName")
                .createdAt(0L)
                .description("description")
                .integrationAppId(0)
                .janusGroup("janusGroup")
                .ownerPortalId(0)
                .pipelineCloseDatePropertyName("pipelineCloseDatePropertyName")
                .pipelineTimeToClosePropertyName("pipelineTimeToClosePropertyName")
                .pluralForm("pluralForm")
                .primaryDisplayLabelPropertyName("primaryDisplayLabelPropertyName")
                .readScopeName("readScopeName")
                .singularForm("singularForm")
                .status("status")
                .visibility("visibility")
                .writeScopeName("writeScopeName")
                .build()

        val roundtrippedInboundDbObjectType =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(inboundDbObjectType),
                jacksonTypeRef<InboundDbObjectType>(),
            )

        assertThat(roundtrippedInboundDbObjectType).isEqualTo(inboundDbObjectType)
    }
}
