// File generated from our OpenAPI spec by Stainless.

package com.hubspot_sdk.api.services.blocking.events

import com.hubspot_sdk.api.TestServerExtension
import com.hubspot_sdk.api.client.okhttp.HubSpotOkHttpClient
import com.hubspot_sdk.api.core.JsonValue
import com.hubspot_sdk.api.models.events.send.BatchedBehavioralEventHttpCompletionRequest
import com.hubspot_sdk.api.models.events.send.BehavioralEventHttpCompletionRequest
import java.time.OffsetDateTime
import org.junit.jupiter.api.Disabled
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.extension.ExtendWith

@ExtendWith(TestServerExtension::class)
internal class SendServiceTest {

    @Disabled("Prism tests are disabled")
    @Test
    fun send() {
        val client =
            HubSpotOkHttpClient.builder()
                .baseUrl(TestServerExtension.BASE_URL)
                .accessToken("pat-na1-xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx")
                .build()
        val sendService = client.events().send()

        sendService.send(
            BehavioralEventHttpCompletionRequest.builder()
                .eventName("pe123456_account_login")
                .email("mark.s@lumon.industries")
                .objectId("089274502")
                .occurredAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .properties(
                    BehavioralEventHttpCompletionRequest.Properties.builder()
                        .putAdditionalProperty("0", JsonValue.from("{"))
                        .putAdditionalProperty("1", JsonValue.from("\""))
                        .putAdditionalProperty("2", JsonValue.from("h"))
                        .putAdditionalProperty("3", JsonValue.from("s"))
                        .putAdditionalProperty("4", JsonValue.from("_"))
                        .putAdditionalProperty("5", JsonValue.from("p"))
                        .putAdditionalProperty("6", JsonValue.from("a"))
                        .putAdditionalProperty("7", JsonValue.from("g"))
                        .putAdditionalProperty("8", JsonValue.from("e"))
                        .putAdditionalProperty("9", JsonValue.from("_"))
                        .putAdditionalProperty("10", JsonValue.from("i"))
                        .putAdditionalProperty("11", JsonValue.from("d"))
                        .putAdditionalProperty("12", JsonValue.from("\""))
                        .putAdditionalProperty("13", JsonValue.from(":"))
                        .putAdditionalProperty("14", JsonValue.from("\""))
                        .putAdditionalProperty("15", JsonValue.from("1"))
                        .putAdditionalProperty("16", JsonValue.from("2"))
                        .putAdditionalProperty("17", JsonValue.from("3"))
                        .putAdditionalProperty("18", JsonValue.from("4"))
                        .putAdditionalProperty("19", JsonValue.from("5"))
                        .putAdditionalProperty("20", JsonValue.from("6"))
                        .putAdditionalProperty("21", JsonValue.from("7"))
                        .putAdditionalProperty("22", JsonValue.from("8"))
                        .putAdditionalProperty("23", JsonValue.from("9"))
                        .putAdditionalProperty("24", JsonValue.from("0"))
                        .putAdditionalProperty("25", JsonValue.from("\""))
                        .putAdditionalProperty("26", JsonValue.from(","))
                        .putAdditionalProperty("27", JsonValue.from("\""))
                        .putAdditionalProperty("28", JsonValue.from("h"))
                        .putAdditionalProperty("29", JsonValue.from("s"))
                        .putAdditionalProperty("30", JsonValue.from("_"))
                        .putAdditionalProperty("31", JsonValue.from("e"))
                        .putAdditionalProperty("32", JsonValue.from("l"))
                        .putAdditionalProperty("33", JsonValue.from("e"))
                        .putAdditionalProperty("34", JsonValue.from("m"))
                        .putAdditionalProperty("35", JsonValue.from("e"))
                        .putAdditionalProperty("36", JsonValue.from("n"))
                        .putAdditionalProperty("37", JsonValue.from("t"))
                        .putAdditionalProperty("38", JsonValue.from("_"))
                        .putAdditionalProperty("39", JsonValue.from("i"))
                        .putAdditionalProperty("40", JsonValue.from("d"))
                        .putAdditionalProperty("41", JsonValue.from("\""))
                        .putAdditionalProperty("42", JsonValue.from(":"))
                        .putAdditionalProperty("43", JsonValue.from("\""))
                        .putAdditionalProperty("44", JsonValue.from("l"))
                        .putAdditionalProperty("45", JsonValue.from("o"))
                        .putAdditionalProperty("46", JsonValue.from("g"))
                        .putAdditionalProperty("47", JsonValue.from("i"))
                        .putAdditionalProperty("48", JsonValue.from("n"))
                        .putAdditionalProperty("49", JsonValue.from("-"))
                        .putAdditionalProperty("50", JsonValue.from("b"))
                        .putAdditionalProperty("51", JsonValue.from("u"))
                        .putAdditionalProperty("52", JsonValue.from("t"))
                        .putAdditionalProperty("53", JsonValue.from("t"))
                        .putAdditionalProperty("54", JsonValue.from("o"))
                        .putAdditionalProperty("55", JsonValue.from("n"))
                        .putAdditionalProperty("56", JsonValue.from("\""))
                        .putAdditionalProperty("57", JsonValue.from(","))
                        .putAdditionalProperty("58", JsonValue.from("\""))
                        .putAdditionalProperty("59", JsonValue.from("h"))
                        .putAdditionalProperty("60", JsonValue.from("s"))
                        .putAdditionalProperty("61", JsonValue.from("_"))
                        .putAdditionalProperty("62", JsonValue.from("p"))
                        .putAdditionalProperty("63", JsonValue.from("a"))
                        .putAdditionalProperty("64", JsonValue.from("g"))
                        .putAdditionalProperty("65", JsonValue.from("e"))
                        .putAdditionalProperty("66", JsonValue.from("_"))
                        .putAdditionalProperty("67", JsonValue.from("t"))
                        .putAdditionalProperty("68", JsonValue.from("i"))
                        .putAdditionalProperty("69", JsonValue.from("t"))
                        .putAdditionalProperty("70", JsonValue.from("l"))
                        .putAdditionalProperty("71", JsonValue.from("e"))
                        .putAdditionalProperty("72", JsonValue.from("\""))
                        .putAdditionalProperty("73", JsonValue.from(":"))
                        .putAdditionalProperty("74", JsonValue.from("\""))
                        .putAdditionalProperty("75", JsonValue.from("h"))
                        .putAdditionalProperty("76", JsonValue.from("o"))
                        .putAdditionalProperty("77", JsonValue.from("m"))
                        .putAdditionalProperty("78", JsonValue.from("e"))
                        .putAdditionalProperty("79", JsonValue.from("p"))
                        .putAdditionalProperty("80", JsonValue.from("a"))
                        .putAdditionalProperty("81", JsonValue.from("g"))
                        .putAdditionalProperty("82", JsonValue.from("e"))
                        .putAdditionalProperty("83", JsonValue.from("\""))
                        .putAdditionalProperty("84", JsonValue.from("}"))
                        .build()
                )
                .utk("utk")
                .uuid("uuid")
                .build()
        )
    }

    @Disabled("Prism tests are disabled")
    @Test
    fun sendBatch() {
        val client =
            HubSpotOkHttpClient.builder()
                .baseUrl(TestServerExtension.BASE_URL)
                .accessToken("pat-na1-xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx")
                .build()
        val sendService = client.events().send()

        sendService.sendBatch(
            BatchedBehavioralEventHttpCompletionRequest.builder()
                .addInput(
                    BehavioralEventHttpCompletionRequest.builder()
                        .eventName("pe123456_account_login")
                        .email("mark.s@lumon.industries")
                        .objectId("089274502")
                        .occurredAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .properties(
                            BehavioralEventHttpCompletionRequest.Properties.builder()
                                .putAdditionalProperty("0", JsonValue.from("{"))
                                .putAdditionalProperty("1", JsonValue.from("\""))
                                .putAdditionalProperty("2", JsonValue.from("h"))
                                .putAdditionalProperty("3", JsonValue.from("s"))
                                .putAdditionalProperty("4", JsonValue.from("_"))
                                .putAdditionalProperty("5", JsonValue.from("p"))
                                .putAdditionalProperty("6", JsonValue.from("a"))
                                .putAdditionalProperty("7", JsonValue.from("g"))
                                .putAdditionalProperty("8", JsonValue.from("e"))
                                .putAdditionalProperty("9", JsonValue.from("_"))
                                .putAdditionalProperty("10", JsonValue.from("i"))
                                .putAdditionalProperty("11", JsonValue.from("d"))
                                .putAdditionalProperty("12", JsonValue.from("\""))
                                .putAdditionalProperty("13", JsonValue.from(":"))
                                .putAdditionalProperty("14", JsonValue.from("\""))
                                .putAdditionalProperty("15", JsonValue.from("1"))
                                .putAdditionalProperty("16", JsonValue.from("2"))
                                .putAdditionalProperty("17", JsonValue.from("3"))
                                .putAdditionalProperty("18", JsonValue.from("4"))
                                .putAdditionalProperty("19", JsonValue.from("5"))
                                .putAdditionalProperty("20", JsonValue.from("6"))
                                .putAdditionalProperty("21", JsonValue.from("7"))
                                .putAdditionalProperty("22", JsonValue.from("8"))
                                .putAdditionalProperty("23", JsonValue.from("9"))
                                .putAdditionalProperty("24", JsonValue.from("0"))
                                .putAdditionalProperty("25", JsonValue.from("\""))
                                .putAdditionalProperty("26", JsonValue.from(","))
                                .putAdditionalProperty("27", JsonValue.from("\""))
                                .putAdditionalProperty("28", JsonValue.from("h"))
                                .putAdditionalProperty("29", JsonValue.from("s"))
                                .putAdditionalProperty("30", JsonValue.from("_"))
                                .putAdditionalProperty("31", JsonValue.from("e"))
                                .putAdditionalProperty("32", JsonValue.from("l"))
                                .putAdditionalProperty("33", JsonValue.from("e"))
                                .putAdditionalProperty("34", JsonValue.from("m"))
                                .putAdditionalProperty("35", JsonValue.from("e"))
                                .putAdditionalProperty("36", JsonValue.from("n"))
                                .putAdditionalProperty("37", JsonValue.from("t"))
                                .putAdditionalProperty("38", JsonValue.from("_"))
                                .putAdditionalProperty("39", JsonValue.from("i"))
                                .putAdditionalProperty("40", JsonValue.from("d"))
                                .putAdditionalProperty("41", JsonValue.from("\""))
                                .putAdditionalProperty("42", JsonValue.from(":"))
                                .putAdditionalProperty("43", JsonValue.from("\""))
                                .putAdditionalProperty("44", JsonValue.from("l"))
                                .putAdditionalProperty("45", JsonValue.from("o"))
                                .putAdditionalProperty("46", JsonValue.from("g"))
                                .putAdditionalProperty("47", JsonValue.from("i"))
                                .putAdditionalProperty("48", JsonValue.from("n"))
                                .putAdditionalProperty("49", JsonValue.from("-"))
                                .putAdditionalProperty("50", JsonValue.from("b"))
                                .putAdditionalProperty("51", JsonValue.from("u"))
                                .putAdditionalProperty("52", JsonValue.from("t"))
                                .putAdditionalProperty("53", JsonValue.from("t"))
                                .putAdditionalProperty("54", JsonValue.from("o"))
                                .putAdditionalProperty("55", JsonValue.from("n"))
                                .putAdditionalProperty("56", JsonValue.from("\""))
                                .putAdditionalProperty("57", JsonValue.from(","))
                                .putAdditionalProperty("58", JsonValue.from("\""))
                                .putAdditionalProperty("59", JsonValue.from("h"))
                                .putAdditionalProperty("60", JsonValue.from("s"))
                                .putAdditionalProperty("61", JsonValue.from("_"))
                                .putAdditionalProperty("62", JsonValue.from("p"))
                                .putAdditionalProperty("63", JsonValue.from("a"))
                                .putAdditionalProperty("64", JsonValue.from("g"))
                                .putAdditionalProperty("65", JsonValue.from("e"))
                                .putAdditionalProperty("66", JsonValue.from("_"))
                                .putAdditionalProperty("67", JsonValue.from("t"))
                                .putAdditionalProperty("68", JsonValue.from("i"))
                                .putAdditionalProperty("69", JsonValue.from("t"))
                                .putAdditionalProperty("70", JsonValue.from("l"))
                                .putAdditionalProperty("71", JsonValue.from("e"))
                                .putAdditionalProperty("72", JsonValue.from("\""))
                                .putAdditionalProperty("73", JsonValue.from(":"))
                                .putAdditionalProperty("74", JsonValue.from("\""))
                                .putAdditionalProperty("75", JsonValue.from("h"))
                                .putAdditionalProperty("76", JsonValue.from("o"))
                                .putAdditionalProperty("77", JsonValue.from("m"))
                                .putAdditionalProperty("78", JsonValue.from("e"))
                                .putAdditionalProperty("79", JsonValue.from("p"))
                                .putAdditionalProperty("80", JsonValue.from("a"))
                                .putAdditionalProperty("81", JsonValue.from("g"))
                                .putAdditionalProperty("82", JsonValue.from("e"))
                                .putAdditionalProperty("83", JsonValue.from("\""))
                                .putAdditionalProperty("84", JsonValue.from("}"))
                                .build()
                        )
                        .utk("utk")
                        .uuid("uuid")
                        .build()
                )
                .build()
        )
    }
}
