// File generated from our OpenAPI spec by Stainless.

package com.hubspot.sdk.models.automation.sequences

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.hubspot.sdk.core.jsonMapper
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class PublicSequenceResponseTest {

    @Test
    fun create() {
        val publicSequenceResponse =
            PublicSequenceResponse.builder()
                .id("id")
                .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .addDependency(
                    PublicSequenceStepDependencyResponse.builder()
                        .id("id")
                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .dependencyType(
                            PublicSequenceStepDependencyResponse.DependencyType.MANUAL_PAUSE
                        )
                        .reliesOnSequenceStepId("reliesOnSequenceStepId")
                        .reliesOnStepOrder(0)
                        .requiredBySequenceStepId("requiredBySequenceStepId")
                        .requiredByStepOrder(0)
                        .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .build()
                )
                .name("name")
                .addStep(
                    PublicSequenceStepResponse.builder()
                        .id("id")
                        .actionType(PublicSequenceStepResponse.ActionType.EMAIL)
                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .delayMillis(0)
                        .stepOrder(0)
                        .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .emailPattern(
                            PublicEmailPatternResponse.builder()
                                .id("id")
                                .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .templateId("templateId")
                                .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .threadEmailToStepOrder(0)
                                .build()
                        )
                        .taskPattern(
                            PublicTaskPatternResponse.builder()
                                .id("id")
                                .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .taskPriority(PublicTaskPatternResponse.TaskPriority.HIGH)
                                .taskType(PublicTaskPatternResponse.TaskType.CALL)
                                .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .notes("notes")
                                .queueId(0)
                                .subject("subject")
                                .templateId(0L)
                                .threadEmailToStepOrder(0)
                                .build()
                        )
                        .build()
                )
                .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .userId("userId")
                .folderId("folderId")
                .settings(
                    PublicSequenceSettingsResponse.builder()
                        .id("id")
                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .eligibleFollowUpDays(
                            PublicSequenceSettingsResponse.EligibleFollowUpDays.BUSINESS_DAYS
                        )
                        .individualTaskRemindersEnabled(true)
                        .sellingStrategy(
                            PublicSequenceSettingsResponse.SellingStrategy.ACCOUNT_BASED
                        )
                        .sendWindowEndMinute(0)
                        .sendWindowStartMinute(0)
                        .taskReminderMinute(0)
                        .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .build()
                )
                .build()

        assertThat(publicSequenceResponse.id()).isEqualTo("id")
        assertThat(publicSequenceResponse.createdAt())
            .isEqualTo(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
        assertThat(publicSequenceResponse.dependencies())
            .containsExactly(
                PublicSequenceStepDependencyResponse.builder()
                    .id("id")
                    .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .dependencyType(
                        PublicSequenceStepDependencyResponse.DependencyType.MANUAL_PAUSE
                    )
                    .reliesOnSequenceStepId("reliesOnSequenceStepId")
                    .reliesOnStepOrder(0)
                    .requiredBySequenceStepId("requiredBySequenceStepId")
                    .requiredByStepOrder(0)
                    .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .build()
            )
        assertThat(publicSequenceResponse.name()).isEqualTo("name")
        assertThat(publicSequenceResponse.steps())
            .containsExactly(
                PublicSequenceStepResponse.builder()
                    .id("id")
                    .actionType(PublicSequenceStepResponse.ActionType.EMAIL)
                    .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .delayMillis(0)
                    .stepOrder(0)
                    .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .emailPattern(
                        PublicEmailPatternResponse.builder()
                            .id("id")
                            .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .templateId("templateId")
                            .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .threadEmailToStepOrder(0)
                            .build()
                    )
                    .taskPattern(
                        PublicTaskPatternResponse.builder()
                            .id("id")
                            .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .taskPriority(PublicTaskPatternResponse.TaskPriority.HIGH)
                            .taskType(PublicTaskPatternResponse.TaskType.CALL)
                            .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .notes("notes")
                            .queueId(0)
                            .subject("subject")
                            .templateId(0L)
                            .threadEmailToStepOrder(0)
                            .build()
                    )
                    .build()
            )
        assertThat(publicSequenceResponse.updatedAt())
            .isEqualTo(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
        assertThat(publicSequenceResponse.userId()).isEqualTo("userId")
        assertThat(publicSequenceResponse.folderId()).contains("folderId")
        assertThat(publicSequenceResponse.settings())
            .contains(
                PublicSequenceSettingsResponse.builder()
                    .id("id")
                    .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .eligibleFollowUpDays(
                        PublicSequenceSettingsResponse.EligibleFollowUpDays.BUSINESS_DAYS
                    )
                    .individualTaskRemindersEnabled(true)
                    .sellingStrategy(PublicSequenceSettingsResponse.SellingStrategy.ACCOUNT_BASED)
                    .sendWindowEndMinute(0)
                    .sendWindowStartMinute(0)
                    .taskReminderMinute(0)
                    .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .build()
            )
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val publicSequenceResponse =
            PublicSequenceResponse.builder()
                .id("id")
                .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .addDependency(
                    PublicSequenceStepDependencyResponse.builder()
                        .id("id")
                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .dependencyType(
                            PublicSequenceStepDependencyResponse.DependencyType.MANUAL_PAUSE
                        )
                        .reliesOnSequenceStepId("reliesOnSequenceStepId")
                        .reliesOnStepOrder(0)
                        .requiredBySequenceStepId("requiredBySequenceStepId")
                        .requiredByStepOrder(0)
                        .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .build()
                )
                .name("name")
                .addStep(
                    PublicSequenceStepResponse.builder()
                        .id("id")
                        .actionType(PublicSequenceStepResponse.ActionType.EMAIL)
                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .delayMillis(0)
                        .stepOrder(0)
                        .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .emailPattern(
                            PublicEmailPatternResponse.builder()
                                .id("id")
                                .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .templateId("templateId")
                                .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .threadEmailToStepOrder(0)
                                .build()
                        )
                        .taskPattern(
                            PublicTaskPatternResponse.builder()
                                .id("id")
                                .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .taskPriority(PublicTaskPatternResponse.TaskPriority.HIGH)
                                .taskType(PublicTaskPatternResponse.TaskType.CALL)
                                .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .notes("notes")
                                .queueId(0)
                                .subject("subject")
                                .templateId(0L)
                                .threadEmailToStepOrder(0)
                                .build()
                        )
                        .build()
                )
                .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .userId("userId")
                .folderId("folderId")
                .settings(
                    PublicSequenceSettingsResponse.builder()
                        .id("id")
                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .eligibleFollowUpDays(
                            PublicSequenceSettingsResponse.EligibleFollowUpDays.BUSINESS_DAYS
                        )
                        .individualTaskRemindersEnabled(true)
                        .sellingStrategy(
                            PublicSequenceSettingsResponse.SellingStrategy.ACCOUNT_BASED
                        )
                        .sendWindowEndMinute(0)
                        .sendWindowStartMinute(0)
                        .taskReminderMinute(0)
                        .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .build()
                )
                .build()

        val roundtrippedPublicSequenceResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(publicSequenceResponse),
                jacksonTypeRef<PublicSequenceResponse>(),
            )

        assertThat(roundtrippedPublicSequenceResponse).isEqualTo(publicSequenceResponse)
    }
}
