// File generated from our OpenAPI spec by Stainless.

package com.hubspot_sdk.api.models.automation.workflows

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.hubspot_sdk.api.core.jsonMapper
import com.hubspot_sdk.api.models.PublicAndFilterBranch
import com.hubspot_sdk.api.models.PublicAssociationFilterBranch
import com.hubspot_sdk.api.models.PublicBoolPropertyOperation
import com.hubspot_sdk.api.models.PublicNotAllFilterBranch
import com.hubspot_sdk.api.models.PublicNotAnyFilterBranch
import com.hubspot_sdk.api.models.PublicNumOccurrencesRefineBy
import com.hubspot_sdk.api.models.PublicOrFilterBranch
import com.hubspot_sdk.api.models.PublicPropertyAssociationFilterBranch
import com.hubspot_sdk.api.models.PublicPropertyFilter
import com.hubspot_sdk.api.models.PublicRestrictedFilterBranch
import com.hubspot_sdk.api.models.PublicUnifiedEventsFilterBranch
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class ApiEventBasedEnrollmentCriteriaTest {

    @Test
    fun create() {
        val apiEventBasedEnrollmentCriteria =
            ApiEventBasedEnrollmentCriteria.builder()
                .addEventFilterBranch(
                    PublicUnifiedEventsFilterBranch.builder()
                        .eventTypeId("eventTypeId")
                        .addFilterBranch(
                            PublicOrFilterBranch.builder()
                                .addFilterBranch(
                                    PublicAndFilterBranch.builder()
                                        .addFilterBranch(
                                            PublicNotAllFilterBranch.builder()
                                                .addFilterBranch(
                                                    PublicNotAnyFilterBranch.builder()
                                                        .addFilterBranch(
                                                            PublicRestrictedFilterBranch.builder()
                                                                .addFilterBranch(
                                                                    PublicPropertyAssociationFilterBranch
                                                                        .builder()
                                                                        .addFilterBranch(
                                                                            PublicAssociationFilterBranch
                                                                                .builder()
                                                                                .associationCategory(
                                                                                    "associationCategory"
                                                                                )
                                                                                .associationTypeId(
                                                                                    0
                                                                                )
                                                                                .addFilterBranch(
                                                                                    PublicOrFilterBranch
                                                                                        .builder()
                                                                                        .filterBranches(
                                                                                            listOf()
                                                                                        )
                                                                                        .filterBranchOperator(
                                                                                            "filterBranchOperator"
                                                                                        )
                                                                                        .filterBranchType(
                                                                                            PublicOrFilterBranch
                                                                                                .FilterBranchType
                                                                                                .OR
                                                                                        )
                                                                                        .addFilter(
                                                                                            PublicPropertyFilter
                                                                                                .builder()
                                                                                                .filterType(
                                                                                                    PublicPropertyFilter
                                                                                                        .FilterType
                                                                                                        .PROPERTY
                                                                                                )
                                                                                                .operation(
                                                                                                    PublicBoolPropertyOperation
                                                                                                        .builder()
                                                                                                        .includeObjectsWithNoValueSet(
                                                                                                            true
                                                                                                        )
                                                                                                        .operationType(
                                                                                                            PublicBoolPropertyOperation
                                                                                                                .OperationType
                                                                                                                .BOOL
                                                                                                        )
                                                                                                        .operator(
                                                                                                            "operator"
                                                                                                        )
                                                                                                        .value(
                                                                                                            true
                                                                                                        )
                                                                                                        .build()
                                                                                                )
                                                                                                .property(
                                                                                                    "property"
                                                                                                )
                                                                                                .build()
                                                                                        )
                                                                                        .build()
                                                                                )
                                                                                .filterBranchOperator(
                                                                                    "filterBranchOperator"
                                                                                )
                                                                                .filterBranchType(
                                                                                    PublicAssociationFilterBranch
                                                                                        .FilterBranchType
                                                                                        .ASSOCIATION
                                                                                )
                                                                                .addFilter(
                                                                                    PublicPropertyFilter
                                                                                        .builder()
                                                                                        .filterType(
                                                                                            PublicPropertyFilter
                                                                                                .FilterType
                                                                                                .PROPERTY
                                                                                        )
                                                                                        .operation(
                                                                                            PublicBoolPropertyOperation
                                                                                                .builder()
                                                                                                .includeObjectsWithNoValueSet(
                                                                                                    true
                                                                                                )
                                                                                                .operationType(
                                                                                                    PublicBoolPropertyOperation
                                                                                                        .OperationType
                                                                                                        .BOOL
                                                                                                )
                                                                                                .operator(
                                                                                                    "operator"
                                                                                                )
                                                                                                .value(
                                                                                                    true
                                                                                                )
                                                                                                .build()
                                                                                        )
                                                                                        .property(
                                                                                            "property"
                                                                                        )
                                                                                        .build()
                                                                                )
                                                                                .objectTypeId(
                                                                                    "objectTypeId"
                                                                                )
                                                                                .operator(
                                                                                    "operator"
                                                                                )
                                                                                .build()
                                                                        )
                                                                        .filterBranchOperator(
                                                                            "filterBranchOperator"
                                                                        )
                                                                        .filterBranchType(
                                                                            PublicPropertyAssociationFilterBranch
                                                                                .FilterBranchType
                                                                                .PROPERTY_ASSOCIATION
                                                                        )
                                                                        .addFilter(
                                                                            PublicPropertyFilter
                                                                                .builder()
                                                                                .filterType(
                                                                                    PublicPropertyFilter
                                                                                        .FilterType
                                                                                        .PROPERTY
                                                                                )
                                                                                .operation(
                                                                                    PublicBoolPropertyOperation
                                                                                        .builder()
                                                                                        .includeObjectsWithNoValueSet(
                                                                                            true
                                                                                        )
                                                                                        .operationType(
                                                                                            PublicBoolPropertyOperation
                                                                                                .OperationType
                                                                                                .BOOL
                                                                                        )
                                                                                        .operator(
                                                                                            "operator"
                                                                                        )
                                                                                        .value(true)
                                                                                        .build()
                                                                                )
                                                                                .property(
                                                                                    "property"
                                                                                )
                                                                                .build()
                                                                        )
                                                                        .objectTypeId(
                                                                            "objectTypeId"
                                                                        )
                                                                        .operator("operator")
                                                                        .propertyWithObjectId(
                                                                            "propertyWithObjectId"
                                                                        )
                                                                        .build()
                                                                )
                                                                .filterBranchOperator(
                                                                    "filterBranchOperator"
                                                                )
                                                                .filterBranchType(
                                                                    PublicRestrictedFilterBranch
                                                                        .FilterBranchType
                                                                        .RESTRICTED
                                                                )
                                                                .addFilter(
                                                                    PublicPropertyFilter.builder()
                                                                        .filterType(
                                                                            PublicPropertyFilter
                                                                                .FilterType
                                                                                .PROPERTY
                                                                        )
                                                                        .operation(
                                                                            PublicBoolPropertyOperation
                                                                                .builder()
                                                                                .includeObjectsWithNoValueSet(
                                                                                    true
                                                                                )
                                                                                .operationType(
                                                                                    PublicBoolPropertyOperation
                                                                                        .OperationType
                                                                                        .BOOL
                                                                                )
                                                                                .operator(
                                                                                    "operator"
                                                                                )
                                                                                .value(true)
                                                                                .build()
                                                                        )
                                                                        .property("property")
                                                                        .build()
                                                                )
                                                                .build()
                                                        )
                                                        .filterBranchOperator(
                                                            "filterBranchOperator"
                                                        )
                                                        .filterBranchType(
                                                            PublicNotAnyFilterBranch
                                                                .FilterBranchType
                                                                .NOT_ANY
                                                        )
                                                        .addFilter(
                                                            PublicPropertyFilter.builder()
                                                                .filterType(
                                                                    PublicPropertyFilter.FilterType
                                                                        .PROPERTY
                                                                )
                                                                .operation(
                                                                    PublicBoolPropertyOperation
                                                                        .builder()
                                                                        .includeObjectsWithNoValueSet(
                                                                            true
                                                                        )
                                                                        .operationType(
                                                                            PublicBoolPropertyOperation
                                                                                .OperationType
                                                                                .BOOL
                                                                        )
                                                                        .operator("operator")
                                                                        .value(true)
                                                                        .build()
                                                                )
                                                                .property("property")
                                                                .build()
                                                        )
                                                        .build()
                                                )
                                                .filterBranchOperator("filterBranchOperator")
                                                .filterBranchType(
                                                    PublicNotAllFilterBranch.FilterBranchType
                                                        .NOT_ALL
                                                )
                                                .addFilter(
                                                    PublicPropertyFilter.builder()
                                                        .filterType(
                                                            PublicPropertyFilter.FilterType.PROPERTY
                                                        )
                                                        .operation(
                                                            PublicBoolPropertyOperation.builder()
                                                                .includeObjectsWithNoValueSet(true)
                                                                .operationType(
                                                                    PublicBoolPropertyOperation
                                                                        .OperationType
                                                                        .BOOL
                                                                )
                                                                .operator("operator")
                                                                .value(true)
                                                                .build()
                                                        )
                                                        .property("property")
                                                        .build()
                                                )
                                                .build()
                                        )
                                        .filterBranchOperator("filterBranchOperator")
                                        .filterBranchType(
                                            PublicAndFilterBranch.FilterBranchType.AND
                                        )
                                        .addFilter(
                                            PublicPropertyFilter.builder()
                                                .filterType(
                                                    PublicPropertyFilter.FilterType.PROPERTY
                                                )
                                                .operation(
                                                    PublicBoolPropertyOperation.builder()
                                                        .includeObjectsWithNoValueSet(true)
                                                        .operationType(
                                                            PublicBoolPropertyOperation
                                                                .OperationType
                                                                .BOOL
                                                        )
                                                        .operator("operator")
                                                        .value(true)
                                                        .build()
                                                )
                                                .property("property")
                                                .build()
                                        )
                                        .build()
                                )
                                .filterBranchOperator("filterBranchOperator")
                                .filterBranchType(PublicOrFilterBranch.FilterBranchType.OR)
                                .addFilter(
                                    PublicPropertyFilter.builder()
                                        .filterType(PublicPropertyFilter.FilterType.PROPERTY)
                                        .operation(
                                            PublicBoolPropertyOperation.builder()
                                                .includeObjectsWithNoValueSet(true)
                                                .operationType(
                                                    PublicBoolPropertyOperation.OperationType.BOOL
                                                )
                                                .operator("operator")
                                                .value(true)
                                                .build()
                                        )
                                        .property("property")
                                        .build()
                                )
                                .build()
                        )
                        .filterBranchOperator("filterBranchOperator")
                        .filterBranchType(
                            PublicUnifiedEventsFilterBranch.FilterBranchType.UNIFIED_EVENTS
                        )
                        .addFilter(
                            PublicPropertyFilter.builder()
                                .filterType(PublicPropertyFilter.FilterType.PROPERTY)
                                .operation(
                                    PublicBoolPropertyOperation.builder()
                                        .includeObjectsWithNoValueSet(true)
                                        .operationType(
                                            PublicBoolPropertyOperation.OperationType.BOOL
                                        )
                                        .operator("operator")
                                        .value(true)
                                        .build()
                                )
                                .property("property")
                                .build()
                        )
                        .operator(PublicUnifiedEventsFilterBranch.Operator.HAS_COMPLETED)
                        .coalescingRefineBy(
                            PublicNumOccurrencesRefineBy.builder()
                                .type(PublicNumOccurrencesRefineBy.Type.NUM_OCCURRENCES)
                                .maxOccurrences(0)
                                .minOccurrences(0)
                                .build()
                        )
                        .build()
                )
                .addListMembershipFilterBranch(
                    PublicOrFilterBranch.builder()
                        .filterBranches(listOf())
                        .filterBranchOperator("filterBranchOperator")
                        .filterBranchType(PublicOrFilterBranch.FilterBranchType.OR)
                        .addFilter(
                            PublicPropertyFilter.builder()
                                .filterType(PublicPropertyFilter.FilterType.PROPERTY)
                                .operation(
                                    PublicBoolPropertyOperation.builder()
                                        .includeObjectsWithNoValueSet(true)
                                        .operationType(
                                            PublicBoolPropertyOperation.OperationType.BOOL
                                        )
                                        .operator("operator")
                                        .value(true)
                                        .build()
                                )
                                .property("property")
                                .build()
                        )
                        .build()
                )
                .shouldReEnroll(true)
                .type(ApiEventBasedEnrollmentCriteria.Type.EVENT_BASED)
                .refinementCriteria(
                    PublicOrFilterBranch.builder()
                        .filterBranches(listOf())
                        .filterBranchOperator("filterBranchOperator")
                        .filterBranchType(PublicOrFilterBranch.FilterBranchType.OR)
                        .addFilter(
                            PublicPropertyFilter.builder()
                                .filterType(PublicPropertyFilter.FilterType.PROPERTY)
                                .operation(
                                    PublicBoolPropertyOperation.builder()
                                        .includeObjectsWithNoValueSet(true)
                                        .operationType(
                                            PublicBoolPropertyOperation.OperationType.BOOL
                                        )
                                        .operator("operator")
                                        .value(true)
                                        .build()
                                )
                                .property("property")
                                .build()
                        )
                        .build()
                )
                .build()

        assertThat(apiEventBasedEnrollmentCriteria.eventFilterBranches())
            .containsExactly(
                PublicUnifiedEventsFilterBranch.builder()
                    .eventTypeId("eventTypeId")
                    .addFilterBranch(
                        PublicOrFilterBranch.builder()
                            .addFilterBranch(
                                PublicAndFilterBranch.builder()
                                    .addFilterBranch(
                                        PublicNotAllFilterBranch.builder()
                                            .addFilterBranch(
                                                PublicNotAnyFilterBranch.builder()
                                                    .addFilterBranch(
                                                        PublicRestrictedFilterBranch.builder()
                                                            .addFilterBranch(
                                                                PublicPropertyAssociationFilterBranch
                                                                    .builder()
                                                                    .addFilterBranch(
                                                                        PublicAssociationFilterBranch
                                                                            .builder()
                                                                            .associationCategory(
                                                                                "associationCategory"
                                                                            )
                                                                            .associationTypeId(0)
                                                                            .addFilterBranch(
                                                                                PublicOrFilterBranch
                                                                                    .builder()
                                                                                    .filterBranches(
                                                                                        listOf()
                                                                                    )
                                                                                    .filterBranchOperator(
                                                                                        "filterBranchOperator"
                                                                                    )
                                                                                    .filterBranchType(
                                                                                        PublicOrFilterBranch
                                                                                            .FilterBranchType
                                                                                            .OR
                                                                                    )
                                                                                    .addFilter(
                                                                                        PublicPropertyFilter
                                                                                            .builder()
                                                                                            .filterType(
                                                                                                PublicPropertyFilter
                                                                                                    .FilterType
                                                                                                    .PROPERTY
                                                                                            )
                                                                                            .operation(
                                                                                                PublicBoolPropertyOperation
                                                                                                    .builder()
                                                                                                    .includeObjectsWithNoValueSet(
                                                                                                        true
                                                                                                    )
                                                                                                    .operationType(
                                                                                                        PublicBoolPropertyOperation
                                                                                                            .OperationType
                                                                                                            .BOOL
                                                                                                    )
                                                                                                    .operator(
                                                                                                        "operator"
                                                                                                    )
                                                                                                    .value(
                                                                                                        true
                                                                                                    )
                                                                                                    .build()
                                                                                            )
                                                                                            .property(
                                                                                                "property"
                                                                                            )
                                                                                            .build()
                                                                                    )
                                                                                    .build()
                                                                            )
                                                                            .filterBranchOperator(
                                                                                "filterBranchOperator"
                                                                            )
                                                                            .filterBranchType(
                                                                                PublicAssociationFilterBranch
                                                                                    .FilterBranchType
                                                                                    .ASSOCIATION
                                                                            )
                                                                            .addFilter(
                                                                                PublicPropertyFilter
                                                                                    .builder()
                                                                                    .filterType(
                                                                                        PublicPropertyFilter
                                                                                            .FilterType
                                                                                            .PROPERTY
                                                                                    )
                                                                                    .operation(
                                                                                        PublicBoolPropertyOperation
                                                                                            .builder()
                                                                                            .includeObjectsWithNoValueSet(
                                                                                                true
                                                                                            )
                                                                                            .operationType(
                                                                                                PublicBoolPropertyOperation
                                                                                                    .OperationType
                                                                                                    .BOOL
                                                                                            )
                                                                                            .operator(
                                                                                                "operator"
                                                                                            )
                                                                                            .value(
                                                                                                true
                                                                                            )
                                                                                            .build()
                                                                                    )
                                                                                    .property(
                                                                                        "property"
                                                                                    )
                                                                                    .build()
                                                                            )
                                                                            .objectTypeId(
                                                                                "objectTypeId"
                                                                            )
                                                                            .operator("operator")
                                                                            .build()
                                                                    )
                                                                    .filterBranchOperator(
                                                                        "filterBranchOperator"
                                                                    )
                                                                    .filterBranchType(
                                                                        PublicPropertyAssociationFilterBranch
                                                                            .FilterBranchType
                                                                            .PROPERTY_ASSOCIATION
                                                                    )
                                                                    .addFilter(
                                                                        PublicPropertyFilter
                                                                            .builder()
                                                                            .filterType(
                                                                                PublicPropertyFilter
                                                                                    .FilterType
                                                                                    .PROPERTY
                                                                            )
                                                                            .operation(
                                                                                PublicBoolPropertyOperation
                                                                                    .builder()
                                                                                    .includeObjectsWithNoValueSet(
                                                                                        true
                                                                                    )
                                                                                    .operationType(
                                                                                        PublicBoolPropertyOperation
                                                                                            .OperationType
                                                                                            .BOOL
                                                                                    )
                                                                                    .operator(
                                                                                        "operator"
                                                                                    )
                                                                                    .value(true)
                                                                                    .build()
                                                                            )
                                                                            .property("property")
                                                                            .build()
                                                                    )
                                                                    .objectTypeId("objectTypeId")
                                                                    .operator("operator")
                                                                    .propertyWithObjectId(
                                                                        "propertyWithObjectId"
                                                                    )
                                                                    .build()
                                                            )
                                                            .filterBranchOperator(
                                                                "filterBranchOperator"
                                                            )
                                                            .filterBranchType(
                                                                PublicRestrictedFilterBranch
                                                                    .FilterBranchType
                                                                    .RESTRICTED
                                                            )
                                                            .addFilter(
                                                                PublicPropertyFilter.builder()
                                                                    .filterType(
                                                                        PublicPropertyFilter
                                                                            .FilterType
                                                                            .PROPERTY
                                                                    )
                                                                    .operation(
                                                                        PublicBoolPropertyOperation
                                                                            .builder()
                                                                            .includeObjectsWithNoValueSet(
                                                                                true
                                                                            )
                                                                            .operationType(
                                                                                PublicBoolPropertyOperation
                                                                                    .OperationType
                                                                                    .BOOL
                                                                            )
                                                                            .operator("operator")
                                                                            .value(true)
                                                                            .build()
                                                                    )
                                                                    .property("property")
                                                                    .build()
                                                            )
                                                            .build()
                                                    )
                                                    .filterBranchOperator("filterBranchOperator")
                                                    .filterBranchType(
                                                        PublicNotAnyFilterBranch.FilterBranchType
                                                            .NOT_ANY
                                                    )
                                                    .addFilter(
                                                        PublicPropertyFilter.builder()
                                                            .filterType(
                                                                PublicPropertyFilter.FilterType
                                                                    .PROPERTY
                                                            )
                                                            .operation(
                                                                PublicBoolPropertyOperation
                                                                    .builder()
                                                                    .includeObjectsWithNoValueSet(
                                                                        true
                                                                    )
                                                                    .operationType(
                                                                        PublicBoolPropertyOperation
                                                                            .OperationType
                                                                            .BOOL
                                                                    )
                                                                    .operator("operator")
                                                                    .value(true)
                                                                    .build()
                                                            )
                                                            .property("property")
                                                            .build()
                                                    )
                                                    .build()
                                            )
                                            .filterBranchOperator("filterBranchOperator")
                                            .filterBranchType(
                                                PublicNotAllFilterBranch.FilterBranchType.NOT_ALL
                                            )
                                            .addFilter(
                                                PublicPropertyFilter.builder()
                                                    .filterType(
                                                        PublicPropertyFilter.FilterType.PROPERTY
                                                    )
                                                    .operation(
                                                        PublicBoolPropertyOperation.builder()
                                                            .includeObjectsWithNoValueSet(true)
                                                            .operationType(
                                                                PublicBoolPropertyOperation
                                                                    .OperationType
                                                                    .BOOL
                                                            )
                                                            .operator("operator")
                                                            .value(true)
                                                            .build()
                                                    )
                                                    .property("property")
                                                    .build()
                                            )
                                            .build()
                                    )
                                    .filterBranchOperator("filterBranchOperator")
                                    .filterBranchType(PublicAndFilterBranch.FilterBranchType.AND)
                                    .addFilter(
                                        PublicPropertyFilter.builder()
                                            .filterType(PublicPropertyFilter.FilterType.PROPERTY)
                                            .operation(
                                                PublicBoolPropertyOperation.builder()
                                                    .includeObjectsWithNoValueSet(true)
                                                    .operationType(
                                                        PublicBoolPropertyOperation.OperationType
                                                            .BOOL
                                                    )
                                                    .operator("operator")
                                                    .value(true)
                                                    .build()
                                            )
                                            .property("property")
                                            .build()
                                    )
                                    .build()
                            )
                            .filterBranchOperator("filterBranchOperator")
                            .filterBranchType(PublicOrFilterBranch.FilterBranchType.OR)
                            .addFilter(
                                PublicPropertyFilter.builder()
                                    .filterType(PublicPropertyFilter.FilterType.PROPERTY)
                                    .operation(
                                        PublicBoolPropertyOperation.builder()
                                            .includeObjectsWithNoValueSet(true)
                                            .operationType(
                                                PublicBoolPropertyOperation.OperationType.BOOL
                                            )
                                            .operator("operator")
                                            .value(true)
                                            .build()
                                    )
                                    .property("property")
                                    .build()
                            )
                            .build()
                    )
                    .filterBranchOperator("filterBranchOperator")
                    .filterBranchType(
                        PublicUnifiedEventsFilterBranch.FilterBranchType.UNIFIED_EVENTS
                    )
                    .addFilter(
                        PublicPropertyFilter.builder()
                            .filterType(PublicPropertyFilter.FilterType.PROPERTY)
                            .operation(
                                PublicBoolPropertyOperation.builder()
                                    .includeObjectsWithNoValueSet(true)
                                    .operationType(PublicBoolPropertyOperation.OperationType.BOOL)
                                    .operator("operator")
                                    .value(true)
                                    .build()
                            )
                            .property("property")
                            .build()
                    )
                    .operator(PublicUnifiedEventsFilterBranch.Operator.HAS_COMPLETED)
                    .coalescingRefineBy(
                        PublicNumOccurrencesRefineBy.builder()
                            .type(PublicNumOccurrencesRefineBy.Type.NUM_OCCURRENCES)
                            .maxOccurrences(0)
                            .minOccurrences(0)
                            .build()
                    )
                    .build()
            )
        assertThat(apiEventBasedEnrollmentCriteria.listMembershipFilterBranches())
            .containsExactly(
                ApiEventBasedEnrollmentCriteria.ListMembershipFilterBranch.ofPublicOr(
                    PublicOrFilterBranch.builder()
                        .filterBranches(listOf())
                        .filterBranchOperator("filterBranchOperator")
                        .filterBranchType(PublicOrFilterBranch.FilterBranchType.OR)
                        .addFilter(
                            PublicPropertyFilter.builder()
                                .filterType(PublicPropertyFilter.FilterType.PROPERTY)
                                .operation(
                                    PublicBoolPropertyOperation.builder()
                                        .includeObjectsWithNoValueSet(true)
                                        .operationType(
                                            PublicBoolPropertyOperation.OperationType.BOOL
                                        )
                                        .operator("operator")
                                        .value(true)
                                        .build()
                                )
                                .property("property")
                                .build()
                        )
                        .build()
                )
            )
        assertThat(apiEventBasedEnrollmentCriteria.shouldReEnroll()).isEqualTo(true)
        assertThat(apiEventBasedEnrollmentCriteria.type())
            .isEqualTo(ApiEventBasedEnrollmentCriteria.Type.EVENT_BASED)
        assertThat(apiEventBasedEnrollmentCriteria.refinementCriteria())
            .contains(
                ApiEventBasedEnrollmentCriteria.RefinementCriteria.ofPublicOrFilterBranch(
                    PublicOrFilterBranch.builder()
                        .filterBranches(listOf())
                        .filterBranchOperator("filterBranchOperator")
                        .filterBranchType(PublicOrFilterBranch.FilterBranchType.OR)
                        .addFilter(
                            PublicPropertyFilter.builder()
                                .filterType(PublicPropertyFilter.FilterType.PROPERTY)
                                .operation(
                                    PublicBoolPropertyOperation.builder()
                                        .includeObjectsWithNoValueSet(true)
                                        .operationType(
                                            PublicBoolPropertyOperation.OperationType.BOOL
                                        )
                                        .operator("operator")
                                        .value(true)
                                        .build()
                                )
                                .property("property")
                                .build()
                        )
                        .build()
                )
            )
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val apiEventBasedEnrollmentCriteria =
            ApiEventBasedEnrollmentCriteria.builder()
                .addEventFilterBranch(
                    PublicUnifiedEventsFilterBranch.builder()
                        .eventTypeId("eventTypeId")
                        .addFilterBranch(
                            PublicOrFilterBranch.builder()
                                .addFilterBranch(
                                    PublicAndFilterBranch.builder()
                                        .addFilterBranch(
                                            PublicNotAllFilterBranch.builder()
                                                .addFilterBranch(
                                                    PublicNotAnyFilterBranch.builder()
                                                        .addFilterBranch(
                                                            PublicRestrictedFilterBranch.builder()
                                                                .addFilterBranch(
                                                                    PublicPropertyAssociationFilterBranch
                                                                        .builder()
                                                                        .addFilterBranch(
                                                                            PublicAssociationFilterBranch
                                                                                .builder()
                                                                                .associationCategory(
                                                                                    "associationCategory"
                                                                                )
                                                                                .associationTypeId(
                                                                                    0
                                                                                )
                                                                                .addFilterBranch(
                                                                                    PublicOrFilterBranch
                                                                                        .builder()
                                                                                        .filterBranches(
                                                                                            listOf()
                                                                                        )
                                                                                        .filterBranchOperator(
                                                                                            "filterBranchOperator"
                                                                                        )
                                                                                        .filterBranchType(
                                                                                            PublicOrFilterBranch
                                                                                                .FilterBranchType
                                                                                                .OR
                                                                                        )
                                                                                        .addFilter(
                                                                                            PublicPropertyFilter
                                                                                                .builder()
                                                                                                .filterType(
                                                                                                    PublicPropertyFilter
                                                                                                        .FilterType
                                                                                                        .PROPERTY
                                                                                                )
                                                                                                .operation(
                                                                                                    PublicBoolPropertyOperation
                                                                                                        .builder()
                                                                                                        .includeObjectsWithNoValueSet(
                                                                                                            true
                                                                                                        )
                                                                                                        .operationType(
                                                                                                            PublicBoolPropertyOperation
                                                                                                                .OperationType
                                                                                                                .BOOL
                                                                                                        )
                                                                                                        .operator(
                                                                                                            "operator"
                                                                                                        )
                                                                                                        .value(
                                                                                                            true
                                                                                                        )
                                                                                                        .build()
                                                                                                )
                                                                                                .property(
                                                                                                    "property"
                                                                                                )
                                                                                                .build()
                                                                                        )
                                                                                        .build()
                                                                                )
                                                                                .filterBranchOperator(
                                                                                    "filterBranchOperator"
                                                                                )
                                                                                .filterBranchType(
                                                                                    PublicAssociationFilterBranch
                                                                                        .FilterBranchType
                                                                                        .ASSOCIATION
                                                                                )
                                                                                .addFilter(
                                                                                    PublicPropertyFilter
                                                                                        .builder()
                                                                                        .filterType(
                                                                                            PublicPropertyFilter
                                                                                                .FilterType
                                                                                                .PROPERTY
                                                                                        )
                                                                                        .operation(
                                                                                            PublicBoolPropertyOperation
                                                                                                .builder()
                                                                                                .includeObjectsWithNoValueSet(
                                                                                                    true
                                                                                                )
                                                                                                .operationType(
                                                                                                    PublicBoolPropertyOperation
                                                                                                        .OperationType
                                                                                                        .BOOL
                                                                                                )
                                                                                                .operator(
                                                                                                    "operator"
                                                                                                )
                                                                                                .value(
                                                                                                    true
                                                                                                )
                                                                                                .build()
                                                                                        )
                                                                                        .property(
                                                                                            "property"
                                                                                        )
                                                                                        .build()
                                                                                )
                                                                                .objectTypeId(
                                                                                    "objectTypeId"
                                                                                )
                                                                                .operator(
                                                                                    "operator"
                                                                                )
                                                                                .build()
                                                                        )
                                                                        .filterBranchOperator(
                                                                            "filterBranchOperator"
                                                                        )
                                                                        .filterBranchType(
                                                                            PublicPropertyAssociationFilterBranch
                                                                                .FilterBranchType
                                                                                .PROPERTY_ASSOCIATION
                                                                        )
                                                                        .addFilter(
                                                                            PublicPropertyFilter
                                                                                .builder()
                                                                                .filterType(
                                                                                    PublicPropertyFilter
                                                                                        .FilterType
                                                                                        .PROPERTY
                                                                                )
                                                                                .operation(
                                                                                    PublicBoolPropertyOperation
                                                                                        .builder()
                                                                                        .includeObjectsWithNoValueSet(
                                                                                            true
                                                                                        )
                                                                                        .operationType(
                                                                                            PublicBoolPropertyOperation
                                                                                                .OperationType
                                                                                                .BOOL
                                                                                        )
                                                                                        .operator(
                                                                                            "operator"
                                                                                        )
                                                                                        .value(true)
                                                                                        .build()
                                                                                )
                                                                                .property(
                                                                                    "property"
                                                                                )
                                                                                .build()
                                                                        )
                                                                        .objectTypeId(
                                                                            "objectTypeId"
                                                                        )
                                                                        .operator("operator")
                                                                        .propertyWithObjectId(
                                                                            "propertyWithObjectId"
                                                                        )
                                                                        .build()
                                                                )
                                                                .filterBranchOperator(
                                                                    "filterBranchOperator"
                                                                )
                                                                .filterBranchType(
                                                                    PublicRestrictedFilterBranch
                                                                        .FilterBranchType
                                                                        .RESTRICTED
                                                                )
                                                                .addFilter(
                                                                    PublicPropertyFilter.builder()
                                                                        .filterType(
                                                                            PublicPropertyFilter
                                                                                .FilterType
                                                                                .PROPERTY
                                                                        )
                                                                        .operation(
                                                                            PublicBoolPropertyOperation
                                                                                .builder()
                                                                                .includeObjectsWithNoValueSet(
                                                                                    true
                                                                                )
                                                                                .operationType(
                                                                                    PublicBoolPropertyOperation
                                                                                        .OperationType
                                                                                        .BOOL
                                                                                )
                                                                                .operator(
                                                                                    "operator"
                                                                                )
                                                                                .value(true)
                                                                                .build()
                                                                        )
                                                                        .property("property")
                                                                        .build()
                                                                )
                                                                .build()
                                                        )
                                                        .filterBranchOperator(
                                                            "filterBranchOperator"
                                                        )
                                                        .filterBranchType(
                                                            PublicNotAnyFilterBranch
                                                                .FilterBranchType
                                                                .NOT_ANY
                                                        )
                                                        .addFilter(
                                                            PublicPropertyFilter.builder()
                                                                .filterType(
                                                                    PublicPropertyFilter.FilterType
                                                                        .PROPERTY
                                                                )
                                                                .operation(
                                                                    PublicBoolPropertyOperation
                                                                        .builder()
                                                                        .includeObjectsWithNoValueSet(
                                                                            true
                                                                        )
                                                                        .operationType(
                                                                            PublicBoolPropertyOperation
                                                                                .OperationType
                                                                                .BOOL
                                                                        )
                                                                        .operator("operator")
                                                                        .value(true)
                                                                        .build()
                                                                )
                                                                .property("property")
                                                                .build()
                                                        )
                                                        .build()
                                                )
                                                .filterBranchOperator("filterBranchOperator")
                                                .filterBranchType(
                                                    PublicNotAllFilterBranch.FilterBranchType
                                                        .NOT_ALL
                                                )
                                                .addFilter(
                                                    PublicPropertyFilter.builder()
                                                        .filterType(
                                                            PublicPropertyFilter.FilterType.PROPERTY
                                                        )
                                                        .operation(
                                                            PublicBoolPropertyOperation.builder()
                                                                .includeObjectsWithNoValueSet(true)
                                                                .operationType(
                                                                    PublicBoolPropertyOperation
                                                                        .OperationType
                                                                        .BOOL
                                                                )
                                                                .operator("operator")
                                                                .value(true)
                                                                .build()
                                                        )
                                                        .property("property")
                                                        .build()
                                                )
                                                .build()
                                        )
                                        .filterBranchOperator("filterBranchOperator")
                                        .filterBranchType(
                                            PublicAndFilterBranch.FilterBranchType.AND
                                        )
                                        .addFilter(
                                            PublicPropertyFilter.builder()
                                                .filterType(
                                                    PublicPropertyFilter.FilterType.PROPERTY
                                                )
                                                .operation(
                                                    PublicBoolPropertyOperation.builder()
                                                        .includeObjectsWithNoValueSet(true)
                                                        .operationType(
                                                            PublicBoolPropertyOperation
                                                                .OperationType
                                                                .BOOL
                                                        )
                                                        .operator("operator")
                                                        .value(true)
                                                        .build()
                                                )
                                                .property("property")
                                                .build()
                                        )
                                        .build()
                                )
                                .filterBranchOperator("filterBranchOperator")
                                .filterBranchType(PublicOrFilterBranch.FilterBranchType.OR)
                                .addFilter(
                                    PublicPropertyFilter.builder()
                                        .filterType(PublicPropertyFilter.FilterType.PROPERTY)
                                        .operation(
                                            PublicBoolPropertyOperation.builder()
                                                .includeObjectsWithNoValueSet(true)
                                                .operationType(
                                                    PublicBoolPropertyOperation.OperationType.BOOL
                                                )
                                                .operator("operator")
                                                .value(true)
                                                .build()
                                        )
                                        .property("property")
                                        .build()
                                )
                                .build()
                        )
                        .filterBranchOperator("filterBranchOperator")
                        .filterBranchType(
                            PublicUnifiedEventsFilterBranch.FilterBranchType.UNIFIED_EVENTS
                        )
                        .addFilter(
                            PublicPropertyFilter.builder()
                                .filterType(PublicPropertyFilter.FilterType.PROPERTY)
                                .operation(
                                    PublicBoolPropertyOperation.builder()
                                        .includeObjectsWithNoValueSet(true)
                                        .operationType(
                                            PublicBoolPropertyOperation.OperationType.BOOL
                                        )
                                        .operator("operator")
                                        .value(true)
                                        .build()
                                )
                                .property("property")
                                .build()
                        )
                        .operator(PublicUnifiedEventsFilterBranch.Operator.HAS_COMPLETED)
                        .coalescingRefineBy(
                            PublicNumOccurrencesRefineBy.builder()
                                .type(PublicNumOccurrencesRefineBy.Type.NUM_OCCURRENCES)
                                .maxOccurrences(0)
                                .minOccurrences(0)
                                .build()
                        )
                        .build()
                )
                .addListMembershipFilterBranch(
                    PublicOrFilterBranch.builder()
                        .filterBranches(listOf())
                        .filterBranchOperator("filterBranchOperator")
                        .filterBranchType(PublicOrFilterBranch.FilterBranchType.OR)
                        .addFilter(
                            PublicPropertyFilter.builder()
                                .filterType(PublicPropertyFilter.FilterType.PROPERTY)
                                .operation(
                                    PublicBoolPropertyOperation.builder()
                                        .includeObjectsWithNoValueSet(true)
                                        .operationType(
                                            PublicBoolPropertyOperation.OperationType.BOOL
                                        )
                                        .operator("operator")
                                        .value(true)
                                        .build()
                                )
                                .property("property")
                                .build()
                        )
                        .build()
                )
                .shouldReEnroll(true)
                .type(ApiEventBasedEnrollmentCriteria.Type.EVENT_BASED)
                .refinementCriteria(
                    PublicOrFilterBranch.builder()
                        .filterBranches(listOf())
                        .filterBranchOperator("filterBranchOperator")
                        .filterBranchType(PublicOrFilterBranch.FilterBranchType.OR)
                        .addFilter(
                            PublicPropertyFilter.builder()
                                .filterType(PublicPropertyFilter.FilterType.PROPERTY)
                                .operation(
                                    PublicBoolPropertyOperation.builder()
                                        .includeObjectsWithNoValueSet(true)
                                        .operationType(
                                            PublicBoolPropertyOperation.OperationType.BOOL
                                        )
                                        .operator("operator")
                                        .value(true)
                                        .build()
                                )
                                .property("property")
                                .build()
                        )
                        .build()
                )
                .build()

        val roundtrippedApiEventBasedEnrollmentCriteria =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(apiEventBasedEnrollmentCriteria),
                jacksonTypeRef<ApiEventBasedEnrollmentCriteria>(),
            )

        assertThat(roundtrippedApiEventBasedEnrollmentCriteria)
            .isEqualTo(apiEventBasedEnrollmentCriteria)
    }
}
