// File generated from our OpenAPI spec by Stainless.

package com.hubspot_sdk.api.models.marketing.emails

import com.hubspot_sdk.api.core.JsonValue
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class EmailUpdateDraftParamsTest {

    @Test
    fun create() {
        EmailUpdateDraftParams.builder()
            .emailId("emailId")
            .emailUpdateRequest(
                EmailUpdateRequest.builder()
                    .activeDomain("activeDomain")
                    .archived(true)
                    .businessUnitId(0L)
                    .campaign("campaign")
                    .content(
                        PublicEmailContent.builder()
                            .flexAreas(
                                PublicEmailContent.FlexAreas.builder()
                                    .putAdditionalProperty(
                                        "foo",
                                        JsonValue.from(mapOf<String, Any>()),
                                    )
                                    .build()
                            )
                            .plainTextVersion("plainTextVersion")
                            .smartFields(
                                PublicEmailContent.SmartFields.builder()
                                    .putAdditionalProperty(
                                        "foo",
                                        JsonValue.from(mapOf<String, Any>()),
                                    )
                                    .build()
                            )
                            .styleSettings(
                                PublicEmailStyleSettings.builder()
                                    .backgroundColor("backgroundColor")
                                    .backgroundImage("backgroundImage")
                                    .backgroundImageType(
                                        PublicEmailStyleSettings.BackgroundImageType.REPEAT
                                    )
                                    .bodyBorderColor("bodyBorderColor")
                                    .bodyBorderColorChoice("bodyBorderColorChoice")
                                    .bodyBorderWidth(0.0)
                                    .bodyColor("bodyColor")
                                    .buttonStyleSettings(
                                        PublicButtonStyleSettings.builder()
                                            .backgroundColor(JsonValue.from(mapOf<String, Any>()))
                                            .cornerRadius(0)
                                            .fontStyle(
                                                PublicFontStyle.builder()
                                                    .bold(true)
                                                    .color("color")
                                                    .font("font")
                                                    .italic(true)
                                                    .size(0)
                                                    .underline(true)
                                                    .build()
                                            )
                                            .build()
                                    )
                                    .colorPickerFavorite1("colorPickerFavorite1")
                                    .colorPickerFavorite2("colorPickerFavorite2")
                                    .colorPickerFavorite3("colorPickerFavorite3")
                                    .colorPickerFavorite4("colorPickerFavorite4")
                                    .colorPickerFavorite5("colorPickerFavorite5")
                                    .colorPickerFavorite6("colorPickerFavorite6")
                                    .dividerStyleSettings(
                                        PublicDividerStyleSettings.builder()
                                            .color(JsonValue.from(mapOf<String, Any>()))
                                            .height(0)
                                            .lineType("lineType")
                                            .build()
                                    )
                                    .emailBodyPadding("emailBodyPadding")
                                    .emailBodyWidth("emailBodyWidth")
                                    .headingOneFont(
                                        PublicFontStyle.builder()
                                            .bold(true)
                                            .color("color")
                                            .font("font")
                                            .italic(true)
                                            .size(0)
                                            .underline(true)
                                            .build()
                                    )
                                    .headingTwoFont(
                                        PublicFontStyle.builder()
                                            .bold(true)
                                            .color("color")
                                            .font("font")
                                            .italic(true)
                                            .size(0)
                                            .underline(true)
                                            .build()
                                    )
                                    .linksFont(
                                        PublicFontStyle.builder()
                                            .bold(true)
                                            .color("color")
                                            .font("font")
                                            .italic(true)
                                            .size(0)
                                            .underline(true)
                                            .build()
                                    )
                                    .primaryAccentColor("primaryAccentColor")
                                    .primaryFont("primaryFont")
                                    .primaryFontColor("primaryFontColor")
                                    .primaryFontLineHeight("primaryFontLineHeight")
                                    .primaryFontSize(0.0)
                                    .secondaryAccentColor("secondaryAccentColor")
                                    .secondaryFont("secondaryFont")
                                    .secondaryFontColor("secondaryFontColor")
                                    .secondaryFontLineHeight("secondaryFontLineHeight")
                                    .secondaryFontSize(0.0)
                                    .build()
                            )
                            .templatePath("templatePath")
                            .themeSettingsValues(
                                PublicEmailContent.ThemeSettingsValues.builder()
                                    .putAdditionalProperty(
                                        "foo",
                                        JsonValue.from(mapOf<String, Any>()),
                                    )
                                    .build()
                            )
                            .widgetContainers(
                                PublicEmailContent.WidgetContainers.builder()
                                    .putAdditionalProperty(
                                        "foo",
                                        JsonValue.from(mapOf<String, Any>()),
                                    )
                                    .build()
                            )
                            .widgets(
                                PublicEmailContent.Widgets.builder()
                                    .putAdditionalProperty(
                                        "foo",
                                        JsonValue.from(mapOf<String, Any>()),
                                    )
                                    .build()
                            )
                            .build()
                    )
                    .folderIdV2(0L)
                    .from(
                        PublicEmailFromDetails.builder()
                            .customReplyTo("customReplyTo")
                            .fromName("fromName")
                            .replyTo("replyTo")
                            .build()
                    )
                    .jitterSendTime(true)
                    .language(EmailUpdateRequest.Language.AA)
                    .name("name")
                    .publishDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .rssData(
                        PublicRssEmailDetails.builder()
                            .blogEmailType("blogEmailType")
                            .blogImageMaxWidth(0)
                            .blogLayout(PublicRssEmailDetails.BlogLayout.FULL_POST)
                            .hubspotBlogId("hubspotBlogId")
                            .maxEntries(0)
                            .rssEntryTemplate("rssEntryTemplate")
                            .timing(
                                PublicRssEmailDetails.Timing.builder()
                                    .putAdditionalProperty(
                                        "foo",
                                        JsonValue.from(mapOf<String, Any>()),
                                    )
                                    .build()
                            )
                            .url("url")
                            .useHeadlineAsSubject(true)
                            .build()
                    )
                    .sendOnPublish(true)
                    .state(EmailUpdateRequest.State.AGENT_GENERATED)
                    .subcategory(EmailUpdateRequest.Subcategory.AB_LOSER_VARIANT)
                    .subject("subject")
                    .subscriptionDetails(
                        PublicEmailSubscriptionDetails.builder()
                            .officeLocationId("officeLocationId")
                            .preferencesGroupId("preferencesGroupId")
                            .subscriptionId("subscriptionId")
                            .subscriptionName("subscriptionName")
                            .build()
                    )
                    .testing(
                        PublicEmailTestingDetails.builder()
                            .isAbVariation(true)
                            .abSampleSizeDefault(
                                PublicEmailTestingDetails.AbSampleSizeDefault
                                    .AUTOMATED_LOSER_VARIANT
                            )
                            .abSamplingDefault(
                                PublicEmailTestingDetails.AbSamplingDefault.AUTOMATED_LOSER_VARIANT
                            )
                            .abStatus(PublicEmailTestingDetails.AbStatus.AUTOMATED_LOSER_VARIANT)
                            .abSuccessMetric(
                                PublicEmailTestingDetails.AbSuccessMetric.CLICKS_BY_DELIVERED
                            )
                            .abTestPercentage(0)
                            .hoursToWait(0)
                            .testId("testId")
                            .build()
                    )
                    .to(
                        PublicEmailToDetails.builder()
                            .contactIds(
                                PublicEmailRecipients.builder()
                                    .addExclude("string")
                                    .addInclude("string")
                                    .build()
                            )
                            .contactIlsLists(
                                PublicEmailRecipients.builder()
                                    .addExclude("string")
                                    .addInclude("string")
                                    .build()
                            )
                            .contactLists(
                                PublicEmailRecipients.builder()
                                    .addExclude("string")
                                    .addInclude("string")
                                    .build()
                            )
                            .limitSendFrequency(true)
                            .suppressGraymail(true)
                            .build()
                    )
                    .webversion(
                        PublicWebversionDetails.builder()
                            .domain("domain")
                            .enabled(true)
                            .expiresAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .isPageRedirected(true)
                            .metaDescription("metaDescription")
                            .pageExpiryEnabled(true)
                            .redirectToPageId("redirectToPageId")
                            .redirectToUrl("redirectToUrl")
                            .slug("slug")
                            .title("title")
                            .url("url")
                            .build()
                    )
                    .build()
            )
            .build()
    }

    @Test
    fun pathParams() {
        val params =
            EmailUpdateDraftParams.builder()
                .emailId("emailId")
                .emailUpdateRequest(EmailUpdateRequest.builder().build())
                .build()

        assertThat(params._pathParam(0)).isEqualTo("emailId")
        // out-of-bound path param
        assertThat(params._pathParam(1)).isEqualTo("")
    }

    @Test
    fun body() {
        val params =
            EmailUpdateDraftParams.builder()
                .emailId("emailId")
                .emailUpdateRequest(
                    EmailUpdateRequest.builder()
                        .activeDomain("activeDomain")
                        .archived(true)
                        .businessUnitId(0L)
                        .campaign("campaign")
                        .content(
                            PublicEmailContent.builder()
                                .flexAreas(
                                    PublicEmailContent.FlexAreas.builder()
                                        .putAdditionalProperty(
                                            "foo",
                                            JsonValue.from(mapOf<String, Any>()),
                                        )
                                        .build()
                                )
                                .plainTextVersion("plainTextVersion")
                                .smartFields(
                                    PublicEmailContent.SmartFields.builder()
                                        .putAdditionalProperty(
                                            "foo",
                                            JsonValue.from(mapOf<String, Any>()),
                                        )
                                        .build()
                                )
                                .styleSettings(
                                    PublicEmailStyleSettings.builder()
                                        .backgroundColor("backgroundColor")
                                        .backgroundImage("backgroundImage")
                                        .backgroundImageType(
                                            PublicEmailStyleSettings.BackgroundImageType.REPEAT
                                        )
                                        .bodyBorderColor("bodyBorderColor")
                                        .bodyBorderColorChoice("bodyBorderColorChoice")
                                        .bodyBorderWidth(0.0)
                                        .bodyColor("bodyColor")
                                        .buttonStyleSettings(
                                            PublicButtonStyleSettings.builder()
                                                .backgroundColor(
                                                    JsonValue.from(mapOf<String, Any>())
                                                )
                                                .cornerRadius(0)
                                                .fontStyle(
                                                    PublicFontStyle.builder()
                                                        .bold(true)
                                                        .color("color")
                                                        .font("font")
                                                        .italic(true)
                                                        .size(0)
                                                        .underline(true)
                                                        .build()
                                                )
                                                .build()
                                        )
                                        .colorPickerFavorite1("colorPickerFavorite1")
                                        .colorPickerFavorite2("colorPickerFavorite2")
                                        .colorPickerFavorite3("colorPickerFavorite3")
                                        .colorPickerFavorite4("colorPickerFavorite4")
                                        .colorPickerFavorite5("colorPickerFavorite5")
                                        .colorPickerFavorite6("colorPickerFavorite6")
                                        .dividerStyleSettings(
                                            PublicDividerStyleSettings.builder()
                                                .color(JsonValue.from(mapOf<String, Any>()))
                                                .height(0)
                                                .lineType("lineType")
                                                .build()
                                        )
                                        .emailBodyPadding("emailBodyPadding")
                                        .emailBodyWidth("emailBodyWidth")
                                        .headingOneFont(
                                            PublicFontStyle.builder()
                                                .bold(true)
                                                .color("color")
                                                .font("font")
                                                .italic(true)
                                                .size(0)
                                                .underline(true)
                                                .build()
                                        )
                                        .headingTwoFont(
                                            PublicFontStyle.builder()
                                                .bold(true)
                                                .color("color")
                                                .font("font")
                                                .italic(true)
                                                .size(0)
                                                .underline(true)
                                                .build()
                                        )
                                        .linksFont(
                                            PublicFontStyle.builder()
                                                .bold(true)
                                                .color("color")
                                                .font("font")
                                                .italic(true)
                                                .size(0)
                                                .underline(true)
                                                .build()
                                        )
                                        .primaryAccentColor("primaryAccentColor")
                                        .primaryFont("primaryFont")
                                        .primaryFontColor("primaryFontColor")
                                        .primaryFontLineHeight("primaryFontLineHeight")
                                        .primaryFontSize(0.0)
                                        .secondaryAccentColor("secondaryAccentColor")
                                        .secondaryFont("secondaryFont")
                                        .secondaryFontColor("secondaryFontColor")
                                        .secondaryFontLineHeight("secondaryFontLineHeight")
                                        .secondaryFontSize(0.0)
                                        .build()
                                )
                                .templatePath("templatePath")
                                .themeSettingsValues(
                                    PublicEmailContent.ThemeSettingsValues.builder()
                                        .putAdditionalProperty(
                                            "foo",
                                            JsonValue.from(mapOf<String, Any>()),
                                        )
                                        .build()
                                )
                                .widgetContainers(
                                    PublicEmailContent.WidgetContainers.builder()
                                        .putAdditionalProperty(
                                            "foo",
                                            JsonValue.from(mapOf<String, Any>()),
                                        )
                                        .build()
                                )
                                .widgets(
                                    PublicEmailContent.Widgets.builder()
                                        .putAdditionalProperty(
                                            "foo",
                                            JsonValue.from(mapOf<String, Any>()),
                                        )
                                        .build()
                                )
                                .build()
                        )
                        .folderIdV2(0L)
                        .from(
                            PublicEmailFromDetails.builder()
                                .customReplyTo("customReplyTo")
                                .fromName("fromName")
                                .replyTo("replyTo")
                                .build()
                        )
                        .jitterSendTime(true)
                        .language(EmailUpdateRequest.Language.AA)
                        .name("name")
                        .publishDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .rssData(
                            PublicRssEmailDetails.builder()
                                .blogEmailType("blogEmailType")
                                .blogImageMaxWidth(0)
                                .blogLayout(PublicRssEmailDetails.BlogLayout.FULL_POST)
                                .hubspotBlogId("hubspotBlogId")
                                .maxEntries(0)
                                .rssEntryTemplate("rssEntryTemplate")
                                .timing(
                                    PublicRssEmailDetails.Timing.builder()
                                        .putAdditionalProperty(
                                            "foo",
                                            JsonValue.from(mapOf<String, Any>()),
                                        )
                                        .build()
                                )
                                .url("url")
                                .useHeadlineAsSubject(true)
                                .build()
                        )
                        .sendOnPublish(true)
                        .state(EmailUpdateRequest.State.AGENT_GENERATED)
                        .subcategory(EmailUpdateRequest.Subcategory.AB_LOSER_VARIANT)
                        .subject("subject")
                        .subscriptionDetails(
                            PublicEmailSubscriptionDetails.builder()
                                .officeLocationId("officeLocationId")
                                .preferencesGroupId("preferencesGroupId")
                                .subscriptionId("subscriptionId")
                                .subscriptionName("subscriptionName")
                                .build()
                        )
                        .testing(
                            PublicEmailTestingDetails.builder()
                                .isAbVariation(true)
                                .abSampleSizeDefault(
                                    PublicEmailTestingDetails.AbSampleSizeDefault
                                        .AUTOMATED_LOSER_VARIANT
                                )
                                .abSamplingDefault(
                                    PublicEmailTestingDetails.AbSamplingDefault
                                        .AUTOMATED_LOSER_VARIANT
                                )
                                .abStatus(
                                    PublicEmailTestingDetails.AbStatus.AUTOMATED_LOSER_VARIANT
                                )
                                .abSuccessMetric(
                                    PublicEmailTestingDetails.AbSuccessMetric.CLICKS_BY_DELIVERED
                                )
                                .abTestPercentage(0)
                                .hoursToWait(0)
                                .testId("testId")
                                .build()
                        )
                        .to(
                            PublicEmailToDetails.builder()
                                .contactIds(
                                    PublicEmailRecipients.builder()
                                        .addExclude("string")
                                        .addInclude("string")
                                        .build()
                                )
                                .contactIlsLists(
                                    PublicEmailRecipients.builder()
                                        .addExclude("string")
                                        .addInclude("string")
                                        .build()
                                )
                                .contactLists(
                                    PublicEmailRecipients.builder()
                                        .addExclude("string")
                                        .addInclude("string")
                                        .build()
                                )
                                .limitSendFrequency(true)
                                .suppressGraymail(true)
                                .build()
                        )
                        .webversion(
                            PublicWebversionDetails.builder()
                                .domain("domain")
                                .enabled(true)
                                .expiresAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .isPageRedirected(true)
                                .metaDescription("metaDescription")
                                .pageExpiryEnabled(true)
                                .redirectToPageId("redirectToPageId")
                                .redirectToUrl("redirectToUrl")
                                .slug("slug")
                                .title("title")
                                .url("url")
                                .build()
                        )
                        .build()
                )
                .build()

        val body = params._body()

        assertThat(body)
            .isEqualTo(
                EmailUpdateRequest.builder()
                    .activeDomain("activeDomain")
                    .archived(true)
                    .businessUnitId(0L)
                    .campaign("campaign")
                    .content(
                        PublicEmailContent.builder()
                            .flexAreas(
                                PublicEmailContent.FlexAreas.builder()
                                    .putAdditionalProperty(
                                        "foo",
                                        JsonValue.from(mapOf<String, Any>()),
                                    )
                                    .build()
                            )
                            .plainTextVersion("plainTextVersion")
                            .smartFields(
                                PublicEmailContent.SmartFields.builder()
                                    .putAdditionalProperty(
                                        "foo",
                                        JsonValue.from(mapOf<String, Any>()),
                                    )
                                    .build()
                            )
                            .styleSettings(
                                PublicEmailStyleSettings.builder()
                                    .backgroundColor("backgroundColor")
                                    .backgroundImage("backgroundImage")
                                    .backgroundImageType(
                                        PublicEmailStyleSettings.BackgroundImageType.REPEAT
                                    )
                                    .bodyBorderColor("bodyBorderColor")
                                    .bodyBorderColorChoice("bodyBorderColorChoice")
                                    .bodyBorderWidth(0.0)
                                    .bodyColor("bodyColor")
                                    .buttonStyleSettings(
                                        PublicButtonStyleSettings.builder()
                                            .backgroundColor(JsonValue.from(mapOf<String, Any>()))
                                            .cornerRadius(0)
                                            .fontStyle(
                                                PublicFontStyle.builder()
                                                    .bold(true)
                                                    .color("color")
                                                    .font("font")
                                                    .italic(true)
                                                    .size(0)
                                                    .underline(true)
                                                    .build()
                                            )
                                            .build()
                                    )
                                    .colorPickerFavorite1("colorPickerFavorite1")
                                    .colorPickerFavorite2("colorPickerFavorite2")
                                    .colorPickerFavorite3("colorPickerFavorite3")
                                    .colorPickerFavorite4("colorPickerFavorite4")
                                    .colorPickerFavorite5("colorPickerFavorite5")
                                    .colorPickerFavorite6("colorPickerFavorite6")
                                    .dividerStyleSettings(
                                        PublicDividerStyleSettings.builder()
                                            .color(JsonValue.from(mapOf<String, Any>()))
                                            .height(0)
                                            .lineType("lineType")
                                            .build()
                                    )
                                    .emailBodyPadding("emailBodyPadding")
                                    .emailBodyWidth("emailBodyWidth")
                                    .headingOneFont(
                                        PublicFontStyle.builder()
                                            .bold(true)
                                            .color("color")
                                            .font("font")
                                            .italic(true)
                                            .size(0)
                                            .underline(true)
                                            .build()
                                    )
                                    .headingTwoFont(
                                        PublicFontStyle.builder()
                                            .bold(true)
                                            .color("color")
                                            .font("font")
                                            .italic(true)
                                            .size(0)
                                            .underline(true)
                                            .build()
                                    )
                                    .linksFont(
                                        PublicFontStyle.builder()
                                            .bold(true)
                                            .color("color")
                                            .font("font")
                                            .italic(true)
                                            .size(0)
                                            .underline(true)
                                            .build()
                                    )
                                    .primaryAccentColor("primaryAccentColor")
                                    .primaryFont("primaryFont")
                                    .primaryFontColor("primaryFontColor")
                                    .primaryFontLineHeight("primaryFontLineHeight")
                                    .primaryFontSize(0.0)
                                    .secondaryAccentColor("secondaryAccentColor")
                                    .secondaryFont("secondaryFont")
                                    .secondaryFontColor("secondaryFontColor")
                                    .secondaryFontLineHeight("secondaryFontLineHeight")
                                    .secondaryFontSize(0.0)
                                    .build()
                            )
                            .templatePath("templatePath")
                            .themeSettingsValues(
                                PublicEmailContent.ThemeSettingsValues.builder()
                                    .putAdditionalProperty(
                                        "foo",
                                        JsonValue.from(mapOf<String, Any>()),
                                    )
                                    .build()
                            )
                            .widgetContainers(
                                PublicEmailContent.WidgetContainers.builder()
                                    .putAdditionalProperty(
                                        "foo",
                                        JsonValue.from(mapOf<String, Any>()),
                                    )
                                    .build()
                            )
                            .widgets(
                                PublicEmailContent.Widgets.builder()
                                    .putAdditionalProperty(
                                        "foo",
                                        JsonValue.from(mapOf<String, Any>()),
                                    )
                                    .build()
                            )
                            .build()
                    )
                    .folderIdV2(0L)
                    .from(
                        PublicEmailFromDetails.builder()
                            .customReplyTo("customReplyTo")
                            .fromName("fromName")
                            .replyTo("replyTo")
                            .build()
                    )
                    .jitterSendTime(true)
                    .language(EmailUpdateRequest.Language.AA)
                    .name("name")
                    .publishDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .rssData(
                        PublicRssEmailDetails.builder()
                            .blogEmailType("blogEmailType")
                            .blogImageMaxWidth(0)
                            .blogLayout(PublicRssEmailDetails.BlogLayout.FULL_POST)
                            .hubspotBlogId("hubspotBlogId")
                            .maxEntries(0)
                            .rssEntryTemplate("rssEntryTemplate")
                            .timing(
                                PublicRssEmailDetails.Timing.builder()
                                    .putAdditionalProperty(
                                        "foo",
                                        JsonValue.from(mapOf<String, Any>()),
                                    )
                                    .build()
                            )
                            .url("url")
                            .useHeadlineAsSubject(true)
                            .build()
                    )
                    .sendOnPublish(true)
                    .state(EmailUpdateRequest.State.AGENT_GENERATED)
                    .subcategory(EmailUpdateRequest.Subcategory.AB_LOSER_VARIANT)
                    .subject("subject")
                    .subscriptionDetails(
                        PublicEmailSubscriptionDetails.builder()
                            .officeLocationId("officeLocationId")
                            .preferencesGroupId("preferencesGroupId")
                            .subscriptionId("subscriptionId")
                            .subscriptionName("subscriptionName")
                            .build()
                    )
                    .testing(
                        PublicEmailTestingDetails.builder()
                            .isAbVariation(true)
                            .abSampleSizeDefault(
                                PublicEmailTestingDetails.AbSampleSizeDefault
                                    .AUTOMATED_LOSER_VARIANT
                            )
                            .abSamplingDefault(
                                PublicEmailTestingDetails.AbSamplingDefault.AUTOMATED_LOSER_VARIANT
                            )
                            .abStatus(PublicEmailTestingDetails.AbStatus.AUTOMATED_LOSER_VARIANT)
                            .abSuccessMetric(
                                PublicEmailTestingDetails.AbSuccessMetric.CLICKS_BY_DELIVERED
                            )
                            .abTestPercentage(0)
                            .hoursToWait(0)
                            .testId("testId")
                            .build()
                    )
                    .to(
                        PublicEmailToDetails.builder()
                            .contactIds(
                                PublicEmailRecipients.builder()
                                    .addExclude("string")
                                    .addInclude("string")
                                    .build()
                            )
                            .contactIlsLists(
                                PublicEmailRecipients.builder()
                                    .addExclude("string")
                                    .addInclude("string")
                                    .build()
                            )
                            .contactLists(
                                PublicEmailRecipients.builder()
                                    .addExclude("string")
                                    .addInclude("string")
                                    .build()
                            )
                            .limitSendFrequency(true)
                            .suppressGraymail(true)
                            .build()
                    )
                    .webversion(
                        PublicWebversionDetails.builder()
                            .domain("domain")
                            .enabled(true)
                            .expiresAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .isPageRedirected(true)
                            .metaDescription("metaDescription")
                            .pageExpiryEnabled(true)
                            .redirectToPageId("redirectToPageId")
                            .redirectToUrl("redirectToUrl")
                            .slug("slug")
                            .title("title")
                            .url("url")
                            .build()
                    )
                    .build()
            )
    }

    @Test
    fun bodyWithoutOptionalFields() {
        val params =
            EmailUpdateDraftParams.builder()
                .emailId("emailId")
                .emailUpdateRequest(EmailUpdateRequest.builder().build())
                .build()

        val body = params._body()

        assertThat(body).isEqualTo(EmailUpdateRequest.builder().build())
    }
}
