// File generated from our OpenAPI spec by Stainless.

package com.hubspot_sdk.api.models.marketing.emails

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.hubspot_sdk.api.core.JsonValue
import com.hubspot_sdk.api.core.jsonMapper
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class EmailCreateRequestTest {

    @Test
    fun create() {
        val emailCreateRequest =
            EmailCreateRequest.builder()
                .name("My subject")
                .activeDomain("test.hs-sites.com")
                .archived(false)
                .businessUnitId(0L)
                .campaign("1b7f51a6-33c1-44d6-ba28-fe81f655dced")
                .content(
                    PublicEmailContent.builder()
                        .flexAreas(
                            PublicEmailContent.FlexAreas.builder()
                                .putAdditionalProperty("main", JsonValue.from(mapOf<String, Any>()))
                                .build()
                        )
                        .plainTextVersion(
                            "This is custom! View in browser ({{view_as_page_url}})\n\nHello {{ contact.firstname }},\n\nPlain text emails have minimal formatting so your reader can really focus on what you have to say. Introduce yourself and explain why you’re reaching out.\n\nEvery email should try to lead the reader to some kind of action. Use this space to describe why the reader should want to click on the link below. Put the link on its own line to really draw their eye to it.\n\nLink text\n\nNow it’s time to wrap up your email. Before your signature, thank the recipient for reading. You can also invite them to send this email to any of their colleagues who might be interested.\n\nAll the best,\n\nYour full name\n\nYour job title\n\nOther contact information\n\n{{site_settings.company_name}}, {{site_settings.company_street_address_1}}, {{site_settings.company_street_address_2}}, {{site_settings.company_city}}, {{site_settings.company_state}} {{site_settings.company_zip}}, {{site_settings.company_country}}, {{site_settings.company_phone}}\n\nUnsubscribe ({{unsubscribe_link_all}})\n\nManage preferences ({{unsubscribe_link}})"
                        )
                        .smartFields(
                            PublicEmailContent.SmartFields.builder()
                                .putAdditionalProperty("foo", JsonValue.from(mapOf<String, Any>()))
                                .build()
                        )
                        .styleSettings(
                            PublicEmailStyleSettings.builder()
                                .backgroundColor("backgroundColor")
                                .backgroundImage("backgroundImage")
                                .backgroundImageType("backgroundImageType")
                                .bodyBorderColor("bodyBorderColor")
                                .bodyBorderColorChoice("bodyBorderColorChoice")
                                .bodyBorderWidth(0.0)
                                .bodyColor("bodyColor")
                                .buttonStyleSettings(
                                    PublicButtonStyleSettings.builder()
                                        .backgroundColor(JsonValue.from(mapOf<String, Any>()))
                                        .cornerRadius(0)
                                        .fontStyle(
                                            PublicFontStyle.builder()
                                                .bold(true)
                                                .color("color")
                                                .font("font")
                                                .italic(true)
                                                .size(0)
                                                .underline(true)
                                                .build()
                                        )
                                        .build()
                                )
                                .colorPickerFavorite1("colorPickerFavorite1")
                                .colorPickerFavorite2("colorPickerFavorite2")
                                .colorPickerFavorite3("colorPickerFavorite3")
                                .colorPickerFavorite4("colorPickerFavorite4")
                                .colorPickerFavorite5("colorPickerFavorite5")
                                .colorPickerFavorite6("colorPickerFavorite6")
                                .dividerStyleSettings(
                                    PublicDividerStyleSettings.builder()
                                        .color(JsonValue.from(mapOf<String, Any>()))
                                        .height(0)
                                        .lineType("lineType")
                                        .build()
                                )
                                .emailBodyPadding("emailBodyPadding")
                                .emailBodyWidth("emailBodyWidth")
                                .headingOneFont(
                                    PublicFontStyle.builder()
                                        .bold(true)
                                        .color("color")
                                        .font("font")
                                        .italic(true)
                                        .size(0)
                                        .underline(true)
                                        .build()
                                )
                                .headingTwoFont(
                                    PublicFontStyle.builder()
                                        .bold(true)
                                        .color("color")
                                        .font("font")
                                        .italic(true)
                                        .size(0)
                                        .underline(true)
                                        .build()
                                )
                                .linksFont(
                                    PublicFontStyle.builder()
                                        .bold(true)
                                        .color("color")
                                        .font("font")
                                        .italic(true)
                                        .size(0)
                                        .underline(true)
                                        .build()
                                )
                                .primaryAccentColor("primaryAccentColor")
                                .primaryFont("primaryFont")
                                .primaryFontColor("primaryFontColor")
                                .primaryFontLineHeight("primaryFontLineHeight")
                                .primaryFontSize(0.0)
                                .secondaryAccentColor("secondaryAccentColor")
                                .secondaryFont("secondaryFont")
                                .secondaryFontColor("secondaryFontColor")
                                .secondaryFontLineHeight("secondaryFontLineHeight")
                                .secondaryFontSize(0.0)
                                .build()
                        )
                        .templatePath("templatePath")
                        .themeSettingsValues(
                            PublicEmailContent.ThemeSettingsValues.builder()
                                .putAdditionalProperty("foo", JsonValue.from(mapOf<String, Any>()))
                                .build()
                        )
                        .widgetContainers(
                            PublicEmailContent.WidgetContainers.builder()
                                .putAdditionalProperty("foo", JsonValue.from(mapOf<String, Any>()))
                                .build()
                        )
                        .widgets(
                            PublicEmailContent.Widgets.builder()
                                .putAdditionalProperty(
                                    "module-0-1-1",
                                    JsonValue.from(mapOf<String, Any>()),
                                )
                                .putAdditionalProperty(
                                    "module-1-1-1",
                                    JsonValue.from(mapOf<String, Any>()),
                                )
                                .putAdditionalProperty(
                                    "module_160676180617911",
                                    JsonValue.from(mapOf<String, Any>()),
                                )
                                .putAdditionalProperty(
                                    "preview_text",
                                    JsonValue.from(mapOf<String, Any>()),
                                )
                                .build()
                        )
                        .build()
                )
                .feedbackSurveyId("feedbackSurveyId")
                .folderIdV2(0L)
                .from(
                    PublicEmailFromDetails.builder()
                        .customReplyTo("customReplyTo")
                        .fromName("Bruce Wayne")
                        .replyTo("test@hubspot.com")
                        .build()
                )
                .jitterSendTime(true)
                .language(EmailCreateRequest.Language.AF)
                .publishDate(OffsetDateTime.parse("2023-11-30T18:44:20.387Z"))
                .rssData(
                    PublicRssEmailDetails.builder()
                        .blogEmailType("blogEmailType")
                        .blogImageMaxWidth(0)
                        .blogLayout("blogLayout")
                        .hubspotBlogId("hubspotBlogId")
                        .maxEntries(0)
                        .rssEntryTemplate("rssEntryTemplate")
                        .timing(
                            PublicRssEmailDetails.Timing.builder()
                                .putAdditionalProperty("foo", JsonValue.from(mapOf<String, Any>()))
                                .build()
                        )
                        .url("url")
                        .useHeadlineAsSubject(true)
                        .build()
                )
                .sendOnPublish(true)
                .state(EmailCreateRequest.State.DRAFT)
                .subcategory(EmailCreateRequest.Subcategory.BATCH)
                .subject("My subject")
                .subscriptionDetails(
                    PublicEmailSubscriptionDetails.builder()
                        .officeLocationId("5449392956")
                        .preferencesGroupId("preferencesGroupId")
                        .subscriptionId("subscriptionId")
                        .subscriptionName("subscriptionName")
                        .build()
                )
                .testing(
                    PublicEmailTestingDetails.builder()
                        .abSampleSizeDefault(
                            PublicEmailTestingDetails.AbSampleSizeDefault.AUTOMATED_LOSER_VARIANT
                        )
                        .abSamplingDefault(
                            PublicEmailTestingDetails.AbSamplingDefault.AUTOMATED_LOSER_VARIANT
                        )
                        .abStatus(PublicEmailTestingDetails.AbStatus.AUTOMATED_LOSER_VARIANT)
                        .abSuccessMetric(
                            PublicEmailTestingDetails.AbSuccessMetric.CLICKS_BY_DELIVERED
                        )
                        .abTestPercentage(0)
                        .hoursToWait(0)
                        .isAbVariation(true)
                        .testId("testId")
                        .build()
                )
                .to(
                    PublicEmailToDetails.builder()
                        .contactIds(
                            PublicEmailRecipients.builder()
                                .addExclude("string")
                                .addInclude("string")
                                .build()
                        )
                        .contactIlsLists(
                            PublicEmailRecipients.builder()
                                .addExclude("string")
                                .addInclude("string")
                                .build()
                        )
                        .contactLists(
                            PublicEmailRecipients.builder()
                                .addExclude("string")
                                .addInclude("string")
                                .build()
                        )
                        .limitSendFrequency(true)
                        .suppressGraymail(true)
                        .build()
                )
                .webversion(
                    PublicWebversionDetails.builder()
                        .domain("domain")
                        .enabled(true)
                        .expiresAt(OffsetDateTime.parse("2020-11-30T18:44:20.387Z"))
                        .isPageRedirected(true)
                        .metaDescription("")
                        .pageExpiryEnabled(true)
                        .redirectToPageId("redirectToPageId")
                        .redirectToUrl("http://www.example.org")
                        .slug("slug")
                        .title("title")
                        .url("url")
                        .build()
                )
                .build()

        assertThat(emailCreateRequest.name()).isEqualTo("My subject")
        assertThat(emailCreateRequest.activeDomain()).contains("test.hs-sites.com")
        assertThat(emailCreateRequest.archived()).contains(false)
        assertThat(emailCreateRequest.businessUnitId()).contains(0L)
        assertThat(emailCreateRequest.campaign()).contains("1b7f51a6-33c1-44d6-ba28-fe81f655dced")
        assertThat(emailCreateRequest.content())
            .contains(
                PublicEmailContent.builder()
                    .flexAreas(
                        PublicEmailContent.FlexAreas.builder()
                            .putAdditionalProperty("main", JsonValue.from(mapOf<String, Any>()))
                            .build()
                    )
                    .plainTextVersion(
                        "This is custom! View in browser ({{view_as_page_url}})\n\nHello {{ contact.firstname }},\n\nPlain text emails have minimal formatting so your reader can really focus on what you have to say. Introduce yourself and explain why you’re reaching out.\n\nEvery email should try to lead the reader to some kind of action. Use this space to describe why the reader should want to click on the link below. Put the link on its own line to really draw their eye to it.\n\nLink text\n\nNow it’s time to wrap up your email. Before your signature, thank the recipient for reading. You can also invite them to send this email to any of their colleagues who might be interested.\n\nAll the best,\n\nYour full name\n\nYour job title\n\nOther contact information\n\n{{site_settings.company_name}}, {{site_settings.company_street_address_1}}, {{site_settings.company_street_address_2}}, {{site_settings.company_city}}, {{site_settings.company_state}} {{site_settings.company_zip}}, {{site_settings.company_country}}, {{site_settings.company_phone}}\n\nUnsubscribe ({{unsubscribe_link_all}})\n\nManage preferences ({{unsubscribe_link}})"
                    )
                    .smartFields(
                        PublicEmailContent.SmartFields.builder()
                            .putAdditionalProperty("foo", JsonValue.from(mapOf<String, Any>()))
                            .build()
                    )
                    .styleSettings(
                        PublicEmailStyleSettings.builder()
                            .backgroundColor("backgroundColor")
                            .backgroundImage("backgroundImage")
                            .backgroundImageType("backgroundImageType")
                            .bodyBorderColor("bodyBorderColor")
                            .bodyBorderColorChoice("bodyBorderColorChoice")
                            .bodyBorderWidth(0.0)
                            .bodyColor("bodyColor")
                            .buttonStyleSettings(
                                PublicButtonStyleSettings.builder()
                                    .backgroundColor(JsonValue.from(mapOf<String, Any>()))
                                    .cornerRadius(0)
                                    .fontStyle(
                                        PublicFontStyle.builder()
                                            .bold(true)
                                            .color("color")
                                            .font("font")
                                            .italic(true)
                                            .size(0)
                                            .underline(true)
                                            .build()
                                    )
                                    .build()
                            )
                            .colorPickerFavorite1("colorPickerFavorite1")
                            .colorPickerFavorite2("colorPickerFavorite2")
                            .colorPickerFavorite3("colorPickerFavorite3")
                            .colorPickerFavorite4("colorPickerFavorite4")
                            .colorPickerFavorite5("colorPickerFavorite5")
                            .colorPickerFavorite6("colorPickerFavorite6")
                            .dividerStyleSettings(
                                PublicDividerStyleSettings.builder()
                                    .color(JsonValue.from(mapOf<String, Any>()))
                                    .height(0)
                                    .lineType("lineType")
                                    .build()
                            )
                            .emailBodyPadding("emailBodyPadding")
                            .emailBodyWidth("emailBodyWidth")
                            .headingOneFont(
                                PublicFontStyle.builder()
                                    .bold(true)
                                    .color("color")
                                    .font("font")
                                    .italic(true)
                                    .size(0)
                                    .underline(true)
                                    .build()
                            )
                            .headingTwoFont(
                                PublicFontStyle.builder()
                                    .bold(true)
                                    .color("color")
                                    .font("font")
                                    .italic(true)
                                    .size(0)
                                    .underline(true)
                                    .build()
                            )
                            .linksFont(
                                PublicFontStyle.builder()
                                    .bold(true)
                                    .color("color")
                                    .font("font")
                                    .italic(true)
                                    .size(0)
                                    .underline(true)
                                    .build()
                            )
                            .primaryAccentColor("primaryAccentColor")
                            .primaryFont("primaryFont")
                            .primaryFontColor("primaryFontColor")
                            .primaryFontLineHeight("primaryFontLineHeight")
                            .primaryFontSize(0.0)
                            .secondaryAccentColor("secondaryAccentColor")
                            .secondaryFont("secondaryFont")
                            .secondaryFontColor("secondaryFontColor")
                            .secondaryFontLineHeight("secondaryFontLineHeight")
                            .secondaryFontSize(0.0)
                            .build()
                    )
                    .templatePath("templatePath")
                    .themeSettingsValues(
                        PublicEmailContent.ThemeSettingsValues.builder()
                            .putAdditionalProperty("foo", JsonValue.from(mapOf<String, Any>()))
                            .build()
                    )
                    .widgetContainers(
                        PublicEmailContent.WidgetContainers.builder()
                            .putAdditionalProperty("foo", JsonValue.from(mapOf<String, Any>()))
                            .build()
                    )
                    .widgets(
                        PublicEmailContent.Widgets.builder()
                            .putAdditionalProperty(
                                "module-0-1-1",
                                JsonValue.from(mapOf<String, Any>()),
                            )
                            .putAdditionalProperty(
                                "module-1-1-1",
                                JsonValue.from(mapOf<String, Any>()),
                            )
                            .putAdditionalProperty(
                                "module_160676180617911",
                                JsonValue.from(mapOf<String, Any>()),
                            )
                            .putAdditionalProperty(
                                "preview_text",
                                JsonValue.from(mapOf<String, Any>()),
                            )
                            .build()
                    )
                    .build()
            )
        assertThat(emailCreateRequest.feedbackSurveyId()).contains("feedbackSurveyId")
        assertThat(emailCreateRequest.folderIdV2()).contains(0L)
        assertThat(emailCreateRequest.from())
            .contains(
                PublicEmailFromDetails.builder()
                    .customReplyTo("customReplyTo")
                    .fromName("Bruce Wayne")
                    .replyTo("test@hubspot.com")
                    .build()
            )
        assertThat(emailCreateRequest.jitterSendTime()).contains(true)
        assertThat(emailCreateRequest.language()).contains(EmailCreateRequest.Language.AF)
        assertThat(emailCreateRequest.publishDate())
            .contains(OffsetDateTime.parse("2023-11-30T18:44:20.387Z"))
        assertThat(emailCreateRequest.rssData())
            .contains(
                PublicRssEmailDetails.builder()
                    .blogEmailType("blogEmailType")
                    .blogImageMaxWidth(0)
                    .blogLayout("blogLayout")
                    .hubspotBlogId("hubspotBlogId")
                    .maxEntries(0)
                    .rssEntryTemplate("rssEntryTemplate")
                    .timing(
                        PublicRssEmailDetails.Timing.builder()
                            .putAdditionalProperty("foo", JsonValue.from(mapOf<String, Any>()))
                            .build()
                    )
                    .url("url")
                    .useHeadlineAsSubject(true)
                    .build()
            )
        assertThat(emailCreateRequest.sendOnPublish()).contains(true)
        assertThat(emailCreateRequest.state()).contains(EmailCreateRequest.State.DRAFT)
        assertThat(emailCreateRequest.subcategory()).contains(EmailCreateRequest.Subcategory.BATCH)
        assertThat(emailCreateRequest.subject()).contains("My subject")
        assertThat(emailCreateRequest.subscriptionDetails())
            .contains(
                PublicEmailSubscriptionDetails.builder()
                    .officeLocationId("5449392956")
                    .preferencesGroupId("preferencesGroupId")
                    .subscriptionId("subscriptionId")
                    .subscriptionName("subscriptionName")
                    .build()
            )
        assertThat(emailCreateRequest.testing())
            .contains(
                PublicEmailTestingDetails.builder()
                    .abSampleSizeDefault(
                        PublicEmailTestingDetails.AbSampleSizeDefault.AUTOMATED_LOSER_VARIANT
                    )
                    .abSamplingDefault(
                        PublicEmailTestingDetails.AbSamplingDefault.AUTOMATED_LOSER_VARIANT
                    )
                    .abStatus(PublicEmailTestingDetails.AbStatus.AUTOMATED_LOSER_VARIANT)
                    .abSuccessMetric(PublicEmailTestingDetails.AbSuccessMetric.CLICKS_BY_DELIVERED)
                    .abTestPercentage(0)
                    .hoursToWait(0)
                    .isAbVariation(true)
                    .testId("testId")
                    .build()
            )
        assertThat(emailCreateRequest.to())
            .contains(
                PublicEmailToDetails.builder()
                    .contactIds(
                        PublicEmailRecipients.builder()
                            .addExclude("string")
                            .addInclude("string")
                            .build()
                    )
                    .contactIlsLists(
                        PublicEmailRecipients.builder()
                            .addExclude("string")
                            .addInclude("string")
                            .build()
                    )
                    .contactLists(
                        PublicEmailRecipients.builder()
                            .addExclude("string")
                            .addInclude("string")
                            .build()
                    )
                    .limitSendFrequency(true)
                    .suppressGraymail(true)
                    .build()
            )
        assertThat(emailCreateRequest.webversion())
            .contains(
                PublicWebversionDetails.builder()
                    .domain("domain")
                    .enabled(true)
                    .expiresAt(OffsetDateTime.parse("2020-11-30T18:44:20.387Z"))
                    .isPageRedirected(true)
                    .metaDescription("")
                    .pageExpiryEnabled(true)
                    .redirectToPageId("redirectToPageId")
                    .redirectToUrl("http://www.example.org")
                    .slug("slug")
                    .title("title")
                    .url("url")
                    .build()
            )
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val emailCreateRequest =
            EmailCreateRequest.builder()
                .name("My subject")
                .activeDomain("test.hs-sites.com")
                .archived(false)
                .businessUnitId(0L)
                .campaign("1b7f51a6-33c1-44d6-ba28-fe81f655dced")
                .content(
                    PublicEmailContent.builder()
                        .flexAreas(
                            PublicEmailContent.FlexAreas.builder()
                                .putAdditionalProperty("main", JsonValue.from(mapOf<String, Any>()))
                                .build()
                        )
                        .plainTextVersion(
                            "This is custom! View in browser ({{view_as_page_url}})\n\nHello {{ contact.firstname }},\n\nPlain text emails have minimal formatting so your reader can really focus on what you have to say. Introduce yourself and explain why you’re reaching out.\n\nEvery email should try to lead the reader to some kind of action. Use this space to describe why the reader should want to click on the link below. Put the link on its own line to really draw their eye to it.\n\nLink text\n\nNow it’s time to wrap up your email. Before your signature, thank the recipient for reading. You can also invite them to send this email to any of their colleagues who might be interested.\n\nAll the best,\n\nYour full name\n\nYour job title\n\nOther contact information\n\n{{site_settings.company_name}}, {{site_settings.company_street_address_1}}, {{site_settings.company_street_address_2}}, {{site_settings.company_city}}, {{site_settings.company_state}} {{site_settings.company_zip}}, {{site_settings.company_country}}, {{site_settings.company_phone}}\n\nUnsubscribe ({{unsubscribe_link_all}})\n\nManage preferences ({{unsubscribe_link}})"
                        )
                        .smartFields(
                            PublicEmailContent.SmartFields.builder()
                                .putAdditionalProperty("foo", JsonValue.from(mapOf<String, Any>()))
                                .build()
                        )
                        .styleSettings(
                            PublicEmailStyleSettings.builder()
                                .backgroundColor("backgroundColor")
                                .backgroundImage("backgroundImage")
                                .backgroundImageType("backgroundImageType")
                                .bodyBorderColor("bodyBorderColor")
                                .bodyBorderColorChoice("bodyBorderColorChoice")
                                .bodyBorderWidth(0.0)
                                .bodyColor("bodyColor")
                                .buttonStyleSettings(
                                    PublicButtonStyleSettings.builder()
                                        .backgroundColor(JsonValue.from(mapOf<String, Any>()))
                                        .cornerRadius(0)
                                        .fontStyle(
                                            PublicFontStyle.builder()
                                                .bold(true)
                                                .color("color")
                                                .font("font")
                                                .italic(true)
                                                .size(0)
                                                .underline(true)
                                                .build()
                                        )
                                        .build()
                                )
                                .colorPickerFavorite1("colorPickerFavorite1")
                                .colorPickerFavorite2("colorPickerFavorite2")
                                .colorPickerFavorite3("colorPickerFavorite3")
                                .colorPickerFavorite4("colorPickerFavorite4")
                                .colorPickerFavorite5("colorPickerFavorite5")
                                .colorPickerFavorite6("colorPickerFavorite6")
                                .dividerStyleSettings(
                                    PublicDividerStyleSettings.builder()
                                        .color(JsonValue.from(mapOf<String, Any>()))
                                        .height(0)
                                        .lineType("lineType")
                                        .build()
                                )
                                .emailBodyPadding("emailBodyPadding")
                                .emailBodyWidth("emailBodyWidth")
                                .headingOneFont(
                                    PublicFontStyle.builder()
                                        .bold(true)
                                        .color("color")
                                        .font("font")
                                        .italic(true)
                                        .size(0)
                                        .underline(true)
                                        .build()
                                )
                                .headingTwoFont(
                                    PublicFontStyle.builder()
                                        .bold(true)
                                        .color("color")
                                        .font("font")
                                        .italic(true)
                                        .size(0)
                                        .underline(true)
                                        .build()
                                )
                                .linksFont(
                                    PublicFontStyle.builder()
                                        .bold(true)
                                        .color("color")
                                        .font("font")
                                        .italic(true)
                                        .size(0)
                                        .underline(true)
                                        .build()
                                )
                                .primaryAccentColor("primaryAccentColor")
                                .primaryFont("primaryFont")
                                .primaryFontColor("primaryFontColor")
                                .primaryFontLineHeight("primaryFontLineHeight")
                                .primaryFontSize(0.0)
                                .secondaryAccentColor("secondaryAccentColor")
                                .secondaryFont("secondaryFont")
                                .secondaryFontColor("secondaryFontColor")
                                .secondaryFontLineHeight("secondaryFontLineHeight")
                                .secondaryFontSize(0.0)
                                .build()
                        )
                        .templatePath("templatePath")
                        .themeSettingsValues(
                            PublicEmailContent.ThemeSettingsValues.builder()
                                .putAdditionalProperty("foo", JsonValue.from(mapOf<String, Any>()))
                                .build()
                        )
                        .widgetContainers(
                            PublicEmailContent.WidgetContainers.builder()
                                .putAdditionalProperty("foo", JsonValue.from(mapOf<String, Any>()))
                                .build()
                        )
                        .widgets(
                            PublicEmailContent.Widgets.builder()
                                .putAdditionalProperty(
                                    "module-0-1-1",
                                    JsonValue.from(mapOf<String, Any>()),
                                )
                                .putAdditionalProperty(
                                    "module-1-1-1",
                                    JsonValue.from(mapOf<String, Any>()),
                                )
                                .putAdditionalProperty(
                                    "module_160676180617911",
                                    JsonValue.from(mapOf<String, Any>()),
                                )
                                .putAdditionalProperty(
                                    "preview_text",
                                    JsonValue.from(mapOf<String, Any>()),
                                )
                                .build()
                        )
                        .build()
                )
                .feedbackSurveyId("feedbackSurveyId")
                .folderIdV2(0L)
                .from(
                    PublicEmailFromDetails.builder()
                        .customReplyTo("customReplyTo")
                        .fromName("Bruce Wayne")
                        .replyTo("test@hubspot.com")
                        .build()
                )
                .jitterSendTime(true)
                .language(EmailCreateRequest.Language.AF)
                .publishDate(OffsetDateTime.parse("2023-11-30T18:44:20.387Z"))
                .rssData(
                    PublicRssEmailDetails.builder()
                        .blogEmailType("blogEmailType")
                        .blogImageMaxWidth(0)
                        .blogLayout("blogLayout")
                        .hubspotBlogId("hubspotBlogId")
                        .maxEntries(0)
                        .rssEntryTemplate("rssEntryTemplate")
                        .timing(
                            PublicRssEmailDetails.Timing.builder()
                                .putAdditionalProperty("foo", JsonValue.from(mapOf<String, Any>()))
                                .build()
                        )
                        .url("url")
                        .useHeadlineAsSubject(true)
                        .build()
                )
                .sendOnPublish(true)
                .state(EmailCreateRequest.State.DRAFT)
                .subcategory(EmailCreateRequest.Subcategory.BATCH)
                .subject("My subject")
                .subscriptionDetails(
                    PublicEmailSubscriptionDetails.builder()
                        .officeLocationId("5449392956")
                        .preferencesGroupId("preferencesGroupId")
                        .subscriptionId("subscriptionId")
                        .subscriptionName("subscriptionName")
                        .build()
                )
                .testing(
                    PublicEmailTestingDetails.builder()
                        .abSampleSizeDefault(
                            PublicEmailTestingDetails.AbSampleSizeDefault.AUTOMATED_LOSER_VARIANT
                        )
                        .abSamplingDefault(
                            PublicEmailTestingDetails.AbSamplingDefault.AUTOMATED_LOSER_VARIANT
                        )
                        .abStatus(PublicEmailTestingDetails.AbStatus.AUTOMATED_LOSER_VARIANT)
                        .abSuccessMetric(
                            PublicEmailTestingDetails.AbSuccessMetric.CLICKS_BY_DELIVERED
                        )
                        .abTestPercentage(0)
                        .hoursToWait(0)
                        .isAbVariation(true)
                        .testId("testId")
                        .build()
                )
                .to(
                    PublicEmailToDetails.builder()
                        .contactIds(
                            PublicEmailRecipients.builder()
                                .addExclude("string")
                                .addInclude("string")
                                .build()
                        )
                        .contactIlsLists(
                            PublicEmailRecipients.builder()
                                .addExclude("string")
                                .addInclude("string")
                                .build()
                        )
                        .contactLists(
                            PublicEmailRecipients.builder()
                                .addExclude("string")
                                .addInclude("string")
                                .build()
                        )
                        .limitSendFrequency(true)
                        .suppressGraymail(true)
                        .build()
                )
                .webversion(
                    PublicWebversionDetails.builder()
                        .domain("domain")
                        .enabled(true)
                        .expiresAt(OffsetDateTime.parse("2020-11-30T18:44:20.387Z"))
                        .isPageRedirected(true)
                        .metaDescription("")
                        .pageExpiryEnabled(true)
                        .redirectToPageId("redirectToPageId")
                        .redirectToUrl("http://www.example.org")
                        .slug("slug")
                        .title("title")
                        .url("url")
                        .build()
                )
                .build()

        val roundtrippedEmailCreateRequest =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(emailCreateRequest),
                jacksonTypeRef<EmailCreateRequest>(),
            )

        assertThat(roundtrippedEmailCreateRequest).isEqualTo(emailCreateRequest)
    }
}
