// File generated from our OpenAPI spec by Stainless.

package com.hubspot_sdk.api.models.marketing.emails

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.hubspot_sdk.api.core.JsonValue
import com.hubspot_sdk.api.core.jsonMapper
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class PublicEmailContentTest {

    @Test
    fun create() {
        val publicEmailContent =
            PublicEmailContent.builder()
                .flexAreas(
                    PublicEmailContent.FlexAreas.builder()
                        .putAdditionalProperty("foo", JsonValue.from(mapOf<String, Any>()))
                        .build()
                )
                .plainTextVersion("plainTextVersion")
                .smartFields(
                    PublicEmailContent.SmartFields.builder()
                        .putAdditionalProperty("foo", JsonValue.from(mapOf<String, Any>()))
                        .build()
                )
                .styleSettings(
                    PublicEmailStyleSettings.builder()
                        .backgroundColor("backgroundColor")
                        .backgroundImage("backgroundImage")
                        .backgroundImageType(PublicEmailStyleSettings.BackgroundImageType.REPEAT)
                        .bodyBorderColor("bodyBorderColor")
                        .bodyBorderColorChoice("bodyBorderColorChoice")
                        .bodyBorderWidth(0.0)
                        .bodyColor("bodyColor")
                        .buttonStyleSettings(
                            PublicButtonStyleSettings.builder()
                                .backgroundColor(JsonValue.from(mapOf<String, Any>()))
                                .cornerRadius(0)
                                .fontStyle(
                                    PublicFontStyle.builder()
                                        .bold(true)
                                        .color("color")
                                        .font("font")
                                        .italic(true)
                                        .size(0)
                                        .underline(true)
                                        .build()
                                )
                                .build()
                        )
                        .colorPickerFavorite1("colorPickerFavorite1")
                        .colorPickerFavorite2("colorPickerFavorite2")
                        .colorPickerFavorite3("colorPickerFavorite3")
                        .colorPickerFavorite4("colorPickerFavorite4")
                        .colorPickerFavorite5("colorPickerFavorite5")
                        .colorPickerFavorite6("colorPickerFavorite6")
                        .dividerStyleSettings(
                            PublicDividerStyleSettings.builder()
                                .color(JsonValue.from(mapOf<String, Any>()))
                                .height(0)
                                .lineType("lineType")
                                .build()
                        )
                        .emailBodyPadding("emailBodyPadding")
                        .emailBodyWidth("emailBodyWidth")
                        .headingOneFont(
                            PublicFontStyle.builder()
                                .bold(true)
                                .color("color")
                                .font("font")
                                .italic(true)
                                .size(0)
                                .underline(true)
                                .build()
                        )
                        .headingTwoFont(
                            PublicFontStyle.builder()
                                .bold(true)
                                .color("color")
                                .font("font")
                                .italic(true)
                                .size(0)
                                .underline(true)
                                .build()
                        )
                        .linksFont(
                            PublicFontStyle.builder()
                                .bold(true)
                                .color("color")
                                .font("font")
                                .italic(true)
                                .size(0)
                                .underline(true)
                                .build()
                        )
                        .primaryAccentColor("primaryAccentColor")
                        .primaryFont("primaryFont")
                        .primaryFontColor("primaryFontColor")
                        .primaryFontLineHeight("primaryFontLineHeight")
                        .primaryFontSize(0.0)
                        .secondaryAccentColor("secondaryAccentColor")
                        .secondaryFont("secondaryFont")
                        .secondaryFontColor("secondaryFontColor")
                        .secondaryFontLineHeight("secondaryFontLineHeight")
                        .secondaryFontSize(0.0)
                        .build()
                )
                .templatePath("templatePath")
                .themeSettingsValues(
                    PublicEmailContent.ThemeSettingsValues.builder()
                        .putAdditionalProperty("foo", JsonValue.from(mapOf<String, Any>()))
                        .build()
                )
                .widgetContainers(
                    PublicEmailContent.WidgetContainers.builder()
                        .putAdditionalProperty("foo", JsonValue.from(mapOf<String, Any>()))
                        .build()
                )
                .widgets(
                    PublicEmailContent.Widgets.builder()
                        .putAdditionalProperty("foo", JsonValue.from(mapOf<String, Any>()))
                        .build()
                )
                .build()

        assertThat(publicEmailContent.flexAreas())
            .contains(
                PublicEmailContent.FlexAreas.builder()
                    .putAdditionalProperty("foo", JsonValue.from(mapOf<String, Any>()))
                    .build()
            )
        assertThat(publicEmailContent.plainTextVersion()).contains("plainTextVersion")
        assertThat(publicEmailContent.smartFields())
            .contains(
                PublicEmailContent.SmartFields.builder()
                    .putAdditionalProperty("foo", JsonValue.from(mapOf<String, Any>()))
                    .build()
            )
        assertThat(publicEmailContent.styleSettings())
            .contains(
                PublicEmailStyleSettings.builder()
                    .backgroundColor("backgroundColor")
                    .backgroundImage("backgroundImage")
                    .backgroundImageType(PublicEmailStyleSettings.BackgroundImageType.REPEAT)
                    .bodyBorderColor("bodyBorderColor")
                    .bodyBorderColorChoice("bodyBorderColorChoice")
                    .bodyBorderWidth(0.0)
                    .bodyColor("bodyColor")
                    .buttonStyleSettings(
                        PublicButtonStyleSettings.builder()
                            .backgroundColor(JsonValue.from(mapOf<String, Any>()))
                            .cornerRadius(0)
                            .fontStyle(
                                PublicFontStyle.builder()
                                    .bold(true)
                                    .color("color")
                                    .font("font")
                                    .italic(true)
                                    .size(0)
                                    .underline(true)
                                    .build()
                            )
                            .build()
                    )
                    .colorPickerFavorite1("colorPickerFavorite1")
                    .colorPickerFavorite2("colorPickerFavorite2")
                    .colorPickerFavorite3("colorPickerFavorite3")
                    .colorPickerFavorite4("colorPickerFavorite4")
                    .colorPickerFavorite5("colorPickerFavorite5")
                    .colorPickerFavorite6("colorPickerFavorite6")
                    .dividerStyleSettings(
                        PublicDividerStyleSettings.builder()
                            .color(JsonValue.from(mapOf<String, Any>()))
                            .height(0)
                            .lineType("lineType")
                            .build()
                    )
                    .emailBodyPadding("emailBodyPadding")
                    .emailBodyWidth("emailBodyWidth")
                    .headingOneFont(
                        PublicFontStyle.builder()
                            .bold(true)
                            .color("color")
                            .font("font")
                            .italic(true)
                            .size(0)
                            .underline(true)
                            .build()
                    )
                    .headingTwoFont(
                        PublicFontStyle.builder()
                            .bold(true)
                            .color("color")
                            .font("font")
                            .italic(true)
                            .size(0)
                            .underline(true)
                            .build()
                    )
                    .linksFont(
                        PublicFontStyle.builder()
                            .bold(true)
                            .color("color")
                            .font("font")
                            .italic(true)
                            .size(0)
                            .underline(true)
                            .build()
                    )
                    .primaryAccentColor("primaryAccentColor")
                    .primaryFont("primaryFont")
                    .primaryFontColor("primaryFontColor")
                    .primaryFontLineHeight("primaryFontLineHeight")
                    .primaryFontSize(0.0)
                    .secondaryAccentColor("secondaryAccentColor")
                    .secondaryFont("secondaryFont")
                    .secondaryFontColor("secondaryFontColor")
                    .secondaryFontLineHeight("secondaryFontLineHeight")
                    .secondaryFontSize(0.0)
                    .build()
            )
        assertThat(publicEmailContent.templatePath()).contains("templatePath")
        assertThat(publicEmailContent.themeSettingsValues())
            .contains(
                PublicEmailContent.ThemeSettingsValues.builder()
                    .putAdditionalProperty("foo", JsonValue.from(mapOf<String, Any>()))
                    .build()
            )
        assertThat(publicEmailContent.widgetContainers())
            .contains(
                PublicEmailContent.WidgetContainers.builder()
                    .putAdditionalProperty("foo", JsonValue.from(mapOf<String, Any>()))
                    .build()
            )
        assertThat(publicEmailContent.widgets())
            .contains(
                PublicEmailContent.Widgets.builder()
                    .putAdditionalProperty("foo", JsonValue.from(mapOf<String, Any>()))
                    .build()
            )
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val publicEmailContent =
            PublicEmailContent.builder()
                .flexAreas(
                    PublicEmailContent.FlexAreas.builder()
                        .putAdditionalProperty("foo", JsonValue.from(mapOf<String, Any>()))
                        .build()
                )
                .plainTextVersion("plainTextVersion")
                .smartFields(
                    PublicEmailContent.SmartFields.builder()
                        .putAdditionalProperty("foo", JsonValue.from(mapOf<String, Any>()))
                        .build()
                )
                .styleSettings(
                    PublicEmailStyleSettings.builder()
                        .backgroundColor("backgroundColor")
                        .backgroundImage("backgroundImage")
                        .backgroundImageType(PublicEmailStyleSettings.BackgroundImageType.REPEAT)
                        .bodyBorderColor("bodyBorderColor")
                        .bodyBorderColorChoice("bodyBorderColorChoice")
                        .bodyBorderWidth(0.0)
                        .bodyColor("bodyColor")
                        .buttonStyleSettings(
                            PublicButtonStyleSettings.builder()
                                .backgroundColor(JsonValue.from(mapOf<String, Any>()))
                                .cornerRadius(0)
                                .fontStyle(
                                    PublicFontStyle.builder()
                                        .bold(true)
                                        .color("color")
                                        .font("font")
                                        .italic(true)
                                        .size(0)
                                        .underline(true)
                                        .build()
                                )
                                .build()
                        )
                        .colorPickerFavorite1("colorPickerFavorite1")
                        .colorPickerFavorite2("colorPickerFavorite2")
                        .colorPickerFavorite3("colorPickerFavorite3")
                        .colorPickerFavorite4("colorPickerFavorite4")
                        .colorPickerFavorite5("colorPickerFavorite5")
                        .colorPickerFavorite6("colorPickerFavorite6")
                        .dividerStyleSettings(
                            PublicDividerStyleSettings.builder()
                                .color(JsonValue.from(mapOf<String, Any>()))
                                .height(0)
                                .lineType("lineType")
                                .build()
                        )
                        .emailBodyPadding("emailBodyPadding")
                        .emailBodyWidth("emailBodyWidth")
                        .headingOneFont(
                            PublicFontStyle.builder()
                                .bold(true)
                                .color("color")
                                .font("font")
                                .italic(true)
                                .size(0)
                                .underline(true)
                                .build()
                        )
                        .headingTwoFont(
                            PublicFontStyle.builder()
                                .bold(true)
                                .color("color")
                                .font("font")
                                .italic(true)
                                .size(0)
                                .underline(true)
                                .build()
                        )
                        .linksFont(
                            PublicFontStyle.builder()
                                .bold(true)
                                .color("color")
                                .font("font")
                                .italic(true)
                                .size(0)
                                .underline(true)
                                .build()
                        )
                        .primaryAccentColor("primaryAccentColor")
                        .primaryFont("primaryFont")
                        .primaryFontColor("primaryFontColor")
                        .primaryFontLineHeight("primaryFontLineHeight")
                        .primaryFontSize(0.0)
                        .secondaryAccentColor("secondaryAccentColor")
                        .secondaryFont("secondaryFont")
                        .secondaryFontColor("secondaryFontColor")
                        .secondaryFontLineHeight("secondaryFontLineHeight")
                        .secondaryFontSize(0.0)
                        .build()
                )
                .templatePath("templatePath")
                .themeSettingsValues(
                    PublicEmailContent.ThemeSettingsValues.builder()
                        .putAdditionalProperty("foo", JsonValue.from(mapOf<String, Any>()))
                        .build()
                )
                .widgetContainers(
                    PublicEmailContent.WidgetContainers.builder()
                        .putAdditionalProperty("foo", JsonValue.from(mapOf<String, Any>()))
                        .build()
                )
                .widgets(
                    PublicEmailContent.Widgets.builder()
                        .putAdditionalProperty("foo", JsonValue.from(mapOf<String, Any>()))
                        .build()
                )
                .build()

        val roundtrippedPublicEmailContent =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(publicEmailContent),
                jacksonTypeRef<PublicEmailContent>(),
            )

        assertThat(roundtrippedPublicEmailContent).isEqualTo(publicEmailContent)
    }
}
