// File generated from our OpenAPI spec by Stainless.

package com.hubspot_sdk.api.models.scheduler.meetings

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.hubspot_sdk.api.core.JsonValue
import com.hubspot_sdk.api.core.jsonMapper
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class ExternalMeetingsLinkSettingsTest {

    @Test
    fun create() {
        val externalMeetingsLinkSettings =
            ExternalMeetingsLinkSettings.builder()
                .availability(
                    ExternalMeetingsLinkSettings.Availability.builder()
                        .putAdditionalProperty(
                            "foo",
                            JsonValue.from(mapOf("end" to 0, "start" to 0)),
                        )
                        .build()
                )
                .addDuration(0L)
                .addFormField(
                    ExternalLinkFormField.builder()
                        .fieldType("fieldType")
                        .isCustom(true)
                        .isRequired(true)
                        .label("label")
                        .name("name")
                        .addOption(
                            ExternalOption.builder()
                                .description("description")
                                .displayOrder(0)
                                .doubleData(0.0)
                                .hidden(true)
                                .label("label")
                                .readOnly(true)
                                .value("value")
                                .build()
                        )
                        .type("type")
                        .build()
                )
                .legalConsentEnabled(true)
                .meetingBufferTime(0)
                .ownerPrioritized(true)
                .startTimeIncrementMinutes("startTimeIncrementMinutes")
                .weeksToAdvertise(0)
                .customAvailabilityEndDate(0L)
                .customAvailabilityStartDate(0L)
                .displayInfo(
                    ExternalLinkDisplayInfo.builder()
                        .avatar("avatar")
                        .companyAvatar("companyAvatar")
                        .headline("headline")
                        .publicDisplayAvatarOption("publicDisplayAvatarOption")
                        .build()
                )
                .guestSettings(
                    ExternalGuestSettings.builder().canAddGuests(true).maxGuestCount(0).build()
                )
                .language("language")
                .legalConsentOptions(
                    ExternalLegalConsentOptions.builder()
                        .addCommunicationConsentCheckbox(
                            ExternalCommunicationConsentCheckbox.builder()
                                .communicationTypeId("communicationTypeId")
                                .label("label")
                                .required(true)
                                .build()
                        )
                        .communicationConsentText("communicationConsentText")
                        .isLegitimateInterest(true)
                        .addLegitimateInterestSubscriptionType(0L)
                        .privacyPolicyText("privacyPolicyText")
                        .processingConsentCheckboxLabel("processingConsentCheckboxLabel")
                        .processingConsentFooterText("processingConsentFooterText")
                        .processingConsentText("processingConsentText")
                        .processingConsentType("processingConsentType")
                        .legitimateInterestLegalBasis(
                            ExternalLegalConsentOptions.LegitimateInterestLegalBasis
                                .LEGITIMATE_INTEREST_PQL
                        )
                        .build()
                )
                .locale("locale")
                .location("location")
                .redirectUrl("redirectUrl")
                .welcomeScreenInfo(
                    ExternalMeetingsWelcomeScreenInfo.builder()
                        .description("description")
                        .logoUrl("logoUrl")
                        .showWelcomeScreen(true)
                        .title("title")
                        .useCompanyLogo(true)
                        .build()
                )
                .build()

        assertThat(externalMeetingsLinkSettings.availability())
            .isEqualTo(
                ExternalMeetingsLinkSettings.Availability.builder()
                    .putAdditionalProperty("foo", JsonValue.from(mapOf("end" to 0, "start" to 0)))
                    .build()
            )
        assertThat(externalMeetingsLinkSettings.durations()).containsExactly(0L)
        assertThat(externalMeetingsLinkSettings.formFields())
            .containsExactly(
                ExternalLinkFormField.builder()
                    .fieldType("fieldType")
                    .isCustom(true)
                    .isRequired(true)
                    .label("label")
                    .name("name")
                    .addOption(
                        ExternalOption.builder()
                            .description("description")
                            .displayOrder(0)
                            .doubleData(0.0)
                            .hidden(true)
                            .label("label")
                            .readOnly(true)
                            .value("value")
                            .build()
                    )
                    .type("type")
                    .build()
            )
        assertThat(externalMeetingsLinkSettings.legalConsentEnabled()).isEqualTo(true)
        assertThat(externalMeetingsLinkSettings.meetingBufferTime()).isEqualTo(0)
        assertThat(externalMeetingsLinkSettings.ownerPrioritized()).isEqualTo(true)
        assertThat(externalMeetingsLinkSettings.startTimeIncrementMinutes())
            .isEqualTo("startTimeIncrementMinutes")
        assertThat(externalMeetingsLinkSettings.weeksToAdvertise()).isEqualTo(0)
        assertThat(externalMeetingsLinkSettings.customAvailabilityEndDate()).contains(0L)
        assertThat(externalMeetingsLinkSettings.customAvailabilityStartDate()).contains(0L)
        assertThat(externalMeetingsLinkSettings.displayInfo())
            .contains(
                ExternalLinkDisplayInfo.builder()
                    .avatar("avatar")
                    .companyAvatar("companyAvatar")
                    .headline("headline")
                    .publicDisplayAvatarOption("publicDisplayAvatarOption")
                    .build()
            )
        assertThat(externalMeetingsLinkSettings.guestSettings())
            .contains(ExternalGuestSettings.builder().canAddGuests(true).maxGuestCount(0).build())
        assertThat(externalMeetingsLinkSettings.language()).contains("language")
        assertThat(externalMeetingsLinkSettings.legalConsentOptions())
            .contains(
                ExternalLegalConsentOptions.builder()
                    .addCommunicationConsentCheckbox(
                        ExternalCommunicationConsentCheckbox.builder()
                            .communicationTypeId("communicationTypeId")
                            .label("label")
                            .required(true)
                            .build()
                    )
                    .communicationConsentText("communicationConsentText")
                    .isLegitimateInterest(true)
                    .addLegitimateInterestSubscriptionType(0L)
                    .privacyPolicyText("privacyPolicyText")
                    .processingConsentCheckboxLabel("processingConsentCheckboxLabel")
                    .processingConsentFooterText("processingConsentFooterText")
                    .processingConsentText("processingConsentText")
                    .processingConsentType("processingConsentType")
                    .legitimateInterestLegalBasis(
                        ExternalLegalConsentOptions.LegitimateInterestLegalBasis
                            .LEGITIMATE_INTEREST_PQL
                    )
                    .build()
            )
        assertThat(externalMeetingsLinkSettings.locale()).contains("locale")
        assertThat(externalMeetingsLinkSettings.location()).contains("location")
        assertThat(externalMeetingsLinkSettings.redirectUrl()).contains("redirectUrl")
        assertThat(externalMeetingsLinkSettings.welcomeScreenInfo())
            .contains(
                ExternalMeetingsWelcomeScreenInfo.builder()
                    .description("description")
                    .logoUrl("logoUrl")
                    .showWelcomeScreen(true)
                    .title("title")
                    .useCompanyLogo(true)
                    .build()
            )
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val externalMeetingsLinkSettings =
            ExternalMeetingsLinkSettings.builder()
                .availability(
                    ExternalMeetingsLinkSettings.Availability.builder()
                        .putAdditionalProperty(
                            "foo",
                            JsonValue.from(mapOf("end" to 0, "start" to 0)),
                        )
                        .build()
                )
                .addDuration(0L)
                .addFormField(
                    ExternalLinkFormField.builder()
                        .fieldType("fieldType")
                        .isCustom(true)
                        .isRequired(true)
                        .label("label")
                        .name("name")
                        .addOption(
                            ExternalOption.builder()
                                .description("description")
                                .displayOrder(0)
                                .doubleData(0.0)
                                .hidden(true)
                                .label("label")
                                .readOnly(true)
                                .value("value")
                                .build()
                        )
                        .type("type")
                        .build()
                )
                .legalConsentEnabled(true)
                .meetingBufferTime(0)
                .ownerPrioritized(true)
                .startTimeIncrementMinutes("startTimeIncrementMinutes")
                .weeksToAdvertise(0)
                .customAvailabilityEndDate(0L)
                .customAvailabilityStartDate(0L)
                .displayInfo(
                    ExternalLinkDisplayInfo.builder()
                        .avatar("avatar")
                        .companyAvatar("companyAvatar")
                        .headline("headline")
                        .publicDisplayAvatarOption("publicDisplayAvatarOption")
                        .build()
                )
                .guestSettings(
                    ExternalGuestSettings.builder().canAddGuests(true).maxGuestCount(0).build()
                )
                .language("language")
                .legalConsentOptions(
                    ExternalLegalConsentOptions.builder()
                        .addCommunicationConsentCheckbox(
                            ExternalCommunicationConsentCheckbox.builder()
                                .communicationTypeId("communicationTypeId")
                                .label("label")
                                .required(true)
                                .build()
                        )
                        .communicationConsentText("communicationConsentText")
                        .isLegitimateInterest(true)
                        .addLegitimateInterestSubscriptionType(0L)
                        .privacyPolicyText("privacyPolicyText")
                        .processingConsentCheckboxLabel("processingConsentCheckboxLabel")
                        .processingConsentFooterText("processingConsentFooterText")
                        .processingConsentText("processingConsentText")
                        .processingConsentType("processingConsentType")
                        .legitimateInterestLegalBasis(
                            ExternalLegalConsentOptions.LegitimateInterestLegalBasis
                                .LEGITIMATE_INTEREST_PQL
                        )
                        .build()
                )
                .locale("locale")
                .location("location")
                .redirectUrl("redirectUrl")
                .welcomeScreenInfo(
                    ExternalMeetingsWelcomeScreenInfo.builder()
                        .description("description")
                        .logoUrl("logoUrl")
                        .showWelcomeScreen(true)
                        .title("title")
                        .useCompanyLogo(true)
                        .build()
                )
                .build()

        val roundtrippedExternalMeetingsLinkSettings =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(externalMeetingsLinkSettings),
                jacksonTypeRef<ExternalMeetingsLinkSettings>(),
            )

        assertThat(roundtrippedExternalMeetingsLinkSettings).isEqualTo(externalMeetingsLinkSettings)
    }
}
