// File generated from our OpenAPI spec by Stainless.

package com.hubspot_sdk.api.models.scheduler.meetings

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.hubspot_sdk.api.core.JsonValue
import com.hubspot_sdk.api.core.jsonMapper
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class ExternalBookingInfoTest {

    @Test
    fun create() {
        val externalBookingInfo =
            ExternalBookingInfo.builder()
                .addAllUsersBusyTime(
                    ExternalUserBusyTimes.builder()
                        .addBusyTime(ExternalTimeRange.builder().end(0).start(0).build())
                        .isOffline(true)
                        .meetingsUser(
                            ExternalMeetingsUser.builder()
                                .id("id")
                                .calendarProvider("calendarProvider")
                                .isSalesStarter(true)
                                .userId("userId")
                                .userProfile(
                                    ExternalUserProfile.builder()
                                        .email("email")
                                        .firstName("firstName")
                                        .fullName("fullName")
                                        .lastName("lastName")
                                        .build()
                                )
                                .build()
                        )
                        .build()
                )
                .customParams(
                    ExternalMeetingsLinkSettings.builder()
                        .availability(
                            ExternalMeetingsLinkSettings.Availability.builder()
                                .putAdditionalProperty(
                                    "foo",
                                    JsonValue.from(mapOf("end" to 0, "start" to 0)),
                                )
                                .build()
                        )
                        .addDuration(0L)
                        .addFormField(
                            ExternalLinkFormField.builder()
                                .fieldType("fieldType")
                                .isCustom(true)
                                .isRequired(true)
                                .label("label")
                                .name("name")
                                .addOption(
                                    ExternalOption.builder()
                                        .description("description")
                                        .displayOrder(0)
                                        .doubleData(0.0)
                                        .hidden(true)
                                        .label("label")
                                        .readOnly(true)
                                        .value("value")
                                        .build()
                                )
                                .type("type")
                                .build()
                        )
                        .legalConsentEnabled(true)
                        .meetingBufferTime(0)
                        .ownerPrioritized(true)
                        .startTimeIncrementMinutes("startTimeIncrementMinutes")
                        .weeksToAdvertise(0)
                        .customAvailabilityEndDate(0L)
                        .customAvailabilityStartDate(0L)
                        .displayInfo(
                            ExternalLinkDisplayInfo.builder()
                                .avatar("avatar")
                                .companyAvatar("companyAvatar")
                                .headline("headline")
                                .publicDisplayAvatarOption("publicDisplayAvatarOption")
                                .build()
                        )
                        .guestSettings(
                            ExternalGuestSettings.builder()
                                .canAddGuests(true)
                                .maxGuestCount(0)
                                .build()
                        )
                        .language("language")
                        .legalConsentOptions(
                            ExternalLegalConsentOptions.builder()
                                .addCommunicationConsentCheckbox(
                                    ExternalCommunicationConsentCheckbox.builder()
                                        .communicationTypeId("communicationTypeId")
                                        .label("label")
                                        .required(true)
                                        .build()
                                )
                                .communicationConsentText("communicationConsentText")
                                .isLegitimateInterest(true)
                                .addLegitimateInterestSubscriptionType(0L)
                                .privacyPolicyText("privacyPolicyText")
                                .processingConsentCheckboxLabel("processingConsentCheckboxLabel")
                                .processingConsentFooterText("processingConsentFooterText")
                                .processingConsentText("processingConsentText")
                                .processingConsentType("processingConsentType")
                                .legitimateInterestLegalBasis(
                                    ExternalLegalConsentOptions.LegitimateInterestLegalBasis
                                        .CONSENT_WITH_NOTICE
                                )
                                .build()
                        )
                        .locale("locale")
                        .location("location")
                        .redirectUrl("redirectUrl")
                        .welcomeScreenInfo(
                            ExternalMeetingsWelcomeScreenInfo.builder()
                                .description("description")
                                .logoUrl("logoUrl")
                                .showWelcomeScreen(true)
                                .title("title")
                                .useCompanyLogo(true)
                                .build()
                        )
                        .build()
                )
                .isOffline(true)
                .linkId("linkId")
                .linkType(ExternalBookingInfo.LinkType.GROUP_CALENDAR)
                .brandingMetadata(
                    ExternalBrandingMetadata.builder()
                        .logoAltText("logoAltText")
                        .showMarketingAd(true)
                        .showSalesAd(true)
                        .accent2Color("accent2Color")
                        .accentColor("accentColor")
                        .companyAddressLine1("companyAddressLine1")
                        .companyAddressLine2("companyAddressLine2")
                        .companyAvatar("companyAvatar")
                        .companyCity("companyCity")
                        .companyCountry("companyCountry")
                        .companyDomain("companyDomain")
                        .companyName("companyName")
                        .companyState("companyState")
                        .companyZip("companyZip")
                        .logoHeight(0)
                        .logoUrl("logoUrl")
                        .logoWidth(0)
                        .primaryColor("primaryColor")
                        .secondaryColor("secondaryColor")
                        .build()
                )
                .linkAvailability(
                    ExternalLinkAvailability.builder()
                        .hasMore(true)
                        .linkAvailabilityByDuration(
                            ExternalLinkAvailability.LinkAvailabilityByDuration.builder()
                                .putAdditionalProperty(
                                    "foo",
                                    JsonValue.from(
                                        mapOf(
                                            "availabilities" to
                                                listOf(
                                                    mapOf(
                                                        "endMillisUtc" to 0,
                                                        "startMillisUtc" to 0,
                                                    )
                                                ),
                                            "meetingDurationMillis" to 0,
                                        )
                                    ),
                                )
                                .build()
                        )
                        .build()
                )
                .build()

        assertThat(externalBookingInfo.allUsersBusyTimes())
            .containsExactly(
                ExternalUserBusyTimes.builder()
                    .addBusyTime(ExternalTimeRange.builder().end(0).start(0).build())
                    .isOffline(true)
                    .meetingsUser(
                        ExternalMeetingsUser.builder()
                            .id("id")
                            .calendarProvider("calendarProvider")
                            .isSalesStarter(true)
                            .userId("userId")
                            .userProfile(
                                ExternalUserProfile.builder()
                                    .email("email")
                                    .firstName("firstName")
                                    .fullName("fullName")
                                    .lastName("lastName")
                                    .build()
                            )
                            .build()
                    )
                    .build()
            )
        assertThat(externalBookingInfo.customParams())
            .isEqualTo(
                ExternalMeetingsLinkSettings.builder()
                    .availability(
                        ExternalMeetingsLinkSettings.Availability.builder()
                            .putAdditionalProperty(
                                "foo",
                                JsonValue.from(mapOf("end" to 0, "start" to 0)),
                            )
                            .build()
                    )
                    .addDuration(0L)
                    .addFormField(
                        ExternalLinkFormField.builder()
                            .fieldType("fieldType")
                            .isCustom(true)
                            .isRequired(true)
                            .label("label")
                            .name("name")
                            .addOption(
                                ExternalOption.builder()
                                    .description("description")
                                    .displayOrder(0)
                                    .doubleData(0.0)
                                    .hidden(true)
                                    .label("label")
                                    .readOnly(true)
                                    .value("value")
                                    .build()
                            )
                            .type("type")
                            .build()
                    )
                    .legalConsentEnabled(true)
                    .meetingBufferTime(0)
                    .ownerPrioritized(true)
                    .startTimeIncrementMinutes("startTimeIncrementMinutes")
                    .weeksToAdvertise(0)
                    .customAvailabilityEndDate(0L)
                    .customAvailabilityStartDate(0L)
                    .displayInfo(
                        ExternalLinkDisplayInfo.builder()
                            .avatar("avatar")
                            .companyAvatar("companyAvatar")
                            .headline("headline")
                            .publicDisplayAvatarOption("publicDisplayAvatarOption")
                            .build()
                    )
                    .guestSettings(
                        ExternalGuestSettings.builder().canAddGuests(true).maxGuestCount(0).build()
                    )
                    .language("language")
                    .legalConsentOptions(
                        ExternalLegalConsentOptions.builder()
                            .addCommunicationConsentCheckbox(
                                ExternalCommunicationConsentCheckbox.builder()
                                    .communicationTypeId("communicationTypeId")
                                    .label("label")
                                    .required(true)
                                    .build()
                            )
                            .communicationConsentText("communicationConsentText")
                            .isLegitimateInterest(true)
                            .addLegitimateInterestSubscriptionType(0L)
                            .privacyPolicyText("privacyPolicyText")
                            .processingConsentCheckboxLabel("processingConsentCheckboxLabel")
                            .processingConsentFooterText("processingConsentFooterText")
                            .processingConsentText("processingConsentText")
                            .processingConsentType("processingConsentType")
                            .legitimateInterestLegalBasis(
                                ExternalLegalConsentOptions.LegitimateInterestLegalBasis
                                    .CONSENT_WITH_NOTICE
                            )
                            .build()
                    )
                    .locale("locale")
                    .location("location")
                    .redirectUrl("redirectUrl")
                    .welcomeScreenInfo(
                        ExternalMeetingsWelcomeScreenInfo.builder()
                            .description("description")
                            .logoUrl("logoUrl")
                            .showWelcomeScreen(true)
                            .title("title")
                            .useCompanyLogo(true)
                            .build()
                    )
                    .build()
            )
        assertThat(externalBookingInfo.isOffline()).isEqualTo(true)
        assertThat(externalBookingInfo.linkId()).isEqualTo("linkId")
        assertThat(externalBookingInfo.linkType())
            .isEqualTo(ExternalBookingInfo.LinkType.GROUP_CALENDAR)
        assertThat(externalBookingInfo.brandingMetadata())
            .contains(
                ExternalBrandingMetadata.builder()
                    .logoAltText("logoAltText")
                    .showMarketingAd(true)
                    .showSalesAd(true)
                    .accent2Color("accent2Color")
                    .accentColor("accentColor")
                    .companyAddressLine1("companyAddressLine1")
                    .companyAddressLine2("companyAddressLine2")
                    .companyAvatar("companyAvatar")
                    .companyCity("companyCity")
                    .companyCountry("companyCountry")
                    .companyDomain("companyDomain")
                    .companyName("companyName")
                    .companyState("companyState")
                    .companyZip("companyZip")
                    .logoHeight(0)
                    .logoUrl("logoUrl")
                    .logoWidth(0)
                    .primaryColor("primaryColor")
                    .secondaryColor("secondaryColor")
                    .build()
            )
        assertThat(externalBookingInfo.linkAvailability())
            .contains(
                ExternalLinkAvailability.builder()
                    .hasMore(true)
                    .linkAvailabilityByDuration(
                        ExternalLinkAvailability.LinkAvailabilityByDuration.builder()
                            .putAdditionalProperty(
                                "foo",
                                JsonValue.from(
                                    mapOf(
                                        "availabilities" to
                                            listOf(
                                                mapOf("endMillisUtc" to 0, "startMillisUtc" to 0)
                                            ),
                                        "meetingDurationMillis" to 0,
                                    )
                                ),
                            )
                            .build()
                    )
                    .build()
            )
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val externalBookingInfo =
            ExternalBookingInfo.builder()
                .addAllUsersBusyTime(
                    ExternalUserBusyTimes.builder()
                        .addBusyTime(ExternalTimeRange.builder().end(0).start(0).build())
                        .isOffline(true)
                        .meetingsUser(
                            ExternalMeetingsUser.builder()
                                .id("id")
                                .calendarProvider("calendarProvider")
                                .isSalesStarter(true)
                                .userId("userId")
                                .userProfile(
                                    ExternalUserProfile.builder()
                                        .email("email")
                                        .firstName("firstName")
                                        .fullName("fullName")
                                        .lastName("lastName")
                                        .build()
                                )
                                .build()
                        )
                        .build()
                )
                .customParams(
                    ExternalMeetingsLinkSettings.builder()
                        .availability(
                            ExternalMeetingsLinkSettings.Availability.builder()
                                .putAdditionalProperty(
                                    "foo",
                                    JsonValue.from(mapOf("end" to 0, "start" to 0)),
                                )
                                .build()
                        )
                        .addDuration(0L)
                        .addFormField(
                            ExternalLinkFormField.builder()
                                .fieldType("fieldType")
                                .isCustom(true)
                                .isRequired(true)
                                .label("label")
                                .name("name")
                                .addOption(
                                    ExternalOption.builder()
                                        .description("description")
                                        .displayOrder(0)
                                        .doubleData(0.0)
                                        .hidden(true)
                                        .label("label")
                                        .readOnly(true)
                                        .value("value")
                                        .build()
                                )
                                .type("type")
                                .build()
                        )
                        .legalConsentEnabled(true)
                        .meetingBufferTime(0)
                        .ownerPrioritized(true)
                        .startTimeIncrementMinutes("startTimeIncrementMinutes")
                        .weeksToAdvertise(0)
                        .customAvailabilityEndDate(0L)
                        .customAvailabilityStartDate(0L)
                        .displayInfo(
                            ExternalLinkDisplayInfo.builder()
                                .avatar("avatar")
                                .companyAvatar("companyAvatar")
                                .headline("headline")
                                .publicDisplayAvatarOption("publicDisplayAvatarOption")
                                .build()
                        )
                        .guestSettings(
                            ExternalGuestSettings.builder()
                                .canAddGuests(true)
                                .maxGuestCount(0)
                                .build()
                        )
                        .language("language")
                        .legalConsentOptions(
                            ExternalLegalConsentOptions.builder()
                                .addCommunicationConsentCheckbox(
                                    ExternalCommunicationConsentCheckbox.builder()
                                        .communicationTypeId("communicationTypeId")
                                        .label("label")
                                        .required(true)
                                        .build()
                                )
                                .communicationConsentText("communicationConsentText")
                                .isLegitimateInterest(true)
                                .addLegitimateInterestSubscriptionType(0L)
                                .privacyPolicyText("privacyPolicyText")
                                .processingConsentCheckboxLabel("processingConsentCheckboxLabel")
                                .processingConsentFooterText("processingConsentFooterText")
                                .processingConsentText("processingConsentText")
                                .processingConsentType("processingConsentType")
                                .legitimateInterestLegalBasis(
                                    ExternalLegalConsentOptions.LegitimateInterestLegalBasis
                                        .CONSENT_WITH_NOTICE
                                )
                                .build()
                        )
                        .locale("locale")
                        .location("location")
                        .redirectUrl("redirectUrl")
                        .welcomeScreenInfo(
                            ExternalMeetingsWelcomeScreenInfo.builder()
                                .description("description")
                                .logoUrl("logoUrl")
                                .showWelcomeScreen(true)
                                .title("title")
                                .useCompanyLogo(true)
                                .build()
                        )
                        .build()
                )
                .isOffline(true)
                .linkId("linkId")
                .linkType(ExternalBookingInfo.LinkType.GROUP_CALENDAR)
                .brandingMetadata(
                    ExternalBrandingMetadata.builder()
                        .logoAltText("logoAltText")
                        .showMarketingAd(true)
                        .showSalesAd(true)
                        .accent2Color("accent2Color")
                        .accentColor("accentColor")
                        .companyAddressLine1("companyAddressLine1")
                        .companyAddressLine2("companyAddressLine2")
                        .companyAvatar("companyAvatar")
                        .companyCity("companyCity")
                        .companyCountry("companyCountry")
                        .companyDomain("companyDomain")
                        .companyName("companyName")
                        .companyState("companyState")
                        .companyZip("companyZip")
                        .logoHeight(0)
                        .logoUrl("logoUrl")
                        .logoWidth(0)
                        .primaryColor("primaryColor")
                        .secondaryColor("secondaryColor")
                        .build()
                )
                .linkAvailability(
                    ExternalLinkAvailability.builder()
                        .hasMore(true)
                        .linkAvailabilityByDuration(
                            ExternalLinkAvailability.LinkAvailabilityByDuration.builder()
                                .putAdditionalProperty(
                                    "foo",
                                    JsonValue.from(
                                        mapOf(
                                            "availabilities" to
                                                listOf(
                                                    mapOf(
                                                        "endMillisUtc" to 0,
                                                        "startMillisUtc" to 0,
                                                    )
                                                ),
                                            "meetingDurationMillis" to 0,
                                        )
                                    ),
                                )
                                .build()
                        )
                        .build()
                )
                .build()

        val roundtrippedExternalBookingInfo =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(externalBookingInfo),
                jacksonTypeRef<ExternalBookingInfo>(),
            )

        assertThat(roundtrippedExternalBookingInfo).isEqualTo(externalBookingInfo)
    }
}
