// File generated from our OpenAPI spec by Stainless.

package com.hubspot_sdk.api.models

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.hubspot_sdk.api.core.JsonValue
import com.hubspot_sdk.api.core.jsonMapper
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class BatchResponsePropertyTest {

    @Test
    fun create() {
        val batchResponseProperty =
            BatchResponseProperty.builder()
                .completedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .addResult(
                    Property.builder()
                        .description("")
                        .fieldType("select")
                        .groupName("my_object_information")
                        .label("My object property")
                        .name("my_object_property")
                        .addOption(
                            Option.builder()
                                .hidden(false)
                                .label("Option A")
                                .value("A")
                                .description("Choice number one")
                                .displayOrder(1)
                                .build()
                        )
                        .addOption(
                            Option.builder()
                                .hidden(false)
                                .label("Option B")
                                .value("B")
                                .description("Choice number two")
                                .displayOrder(2)
                                .build()
                        )
                        .type("enumeration")
                        .archived(false)
                        .archivedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .calculated(false)
                        .calculationFormula("")
                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .createdUserId("")
                        .dataSensitivity(Property.DataSensitivity.NON_SENSITIVE)
                        .displayOrder(2)
                        .externalOptions(false)
                        .formField(false)
                        .hasUniqueValue(false)
                        .hidden(false)
                        .hubspotDefined(false)
                        .modificationMetadata(
                            PropertyModificationMetadata.builder()
                                .archivable(true)
                                .readOnlyDefinition(false)
                                .readOnlyValue(false)
                                .readOnlyOptions(false)
                                .build()
                        )
                        .referencedObjectType("")
                        .addSensitiveDataCategory("string")
                        .showCurrencySymbol(false)
                        .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .updatedUserId("updatedUserId")
                        .build()
                )
                .startedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .status(BatchResponseProperty.Status.PENDING)
                .links(
                    BatchResponseProperty.Links.builder()
                        .putAdditionalProperty("foo", JsonValue.from("string"))
                        .build()
                )
                .requestedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .build()

        assertThat(batchResponseProperty.completedAt())
            .isEqualTo(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
        assertThat(batchResponseProperty.results())
            .containsExactly(
                Property.builder()
                    .description("")
                    .fieldType("select")
                    .groupName("my_object_information")
                    .label("My object property")
                    .name("my_object_property")
                    .addOption(
                        Option.builder()
                            .hidden(false)
                            .label("Option A")
                            .value("A")
                            .description("Choice number one")
                            .displayOrder(1)
                            .build()
                    )
                    .addOption(
                        Option.builder()
                            .hidden(false)
                            .label("Option B")
                            .value("B")
                            .description("Choice number two")
                            .displayOrder(2)
                            .build()
                    )
                    .type("enumeration")
                    .archived(false)
                    .archivedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .calculated(false)
                    .calculationFormula("")
                    .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .createdUserId("")
                    .dataSensitivity(Property.DataSensitivity.NON_SENSITIVE)
                    .displayOrder(2)
                    .externalOptions(false)
                    .formField(false)
                    .hasUniqueValue(false)
                    .hidden(false)
                    .hubspotDefined(false)
                    .modificationMetadata(
                        PropertyModificationMetadata.builder()
                            .archivable(true)
                            .readOnlyDefinition(false)
                            .readOnlyValue(false)
                            .readOnlyOptions(false)
                            .build()
                    )
                    .referencedObjectType("")
                    .addSensitiveDataCategory("string")
                    .showCurrencySymbol(false)
                    .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .updatedUserId("updatedUserId")
                    .build()
            )
        assertThat(batchResponseProperty.startedAt())
            .isEqualTo(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
        assertThat(batchResponseProperty.status()).isEqualTo(BatchResponseProperty.Status.PENDING)
        assertThat(batchResponseProperty.links())
            .contains(
                BatchResponseProperty.Links.builder()
                    .putAdditionalProperty("foo", JsonValue.from("string"))
                    .build()
            )
        assertThat(batchResponseProperty.requestedAt())
            .contains(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val batchResponseProperty =
            BatchResponseProperty.builder()
                .completedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .addResult(
                    Property.builder()
                        .description("")
                        .fieldType("select")
                        .groupName("my_object_information")
                        .label("My object property")
                        .name("my_object_property")
                        .addOption(
                            Option.builder()
                                .hidden(false)
                                .label("Option A")
                                .value("A")
                                .description("Choice number one")
                                .displayOrder(1)
                                .build()
                        )
                        .addOption(
                            Option.builder()
                                .hidden(false)
                                .label("Option B")
                                .value("B")
                                .description("Choice number two")
                                .displayOrder(2)
                                .build()
                        )
                        .type("enumeration")
                        .archived(false)
                        .archivedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .calculated(false)
                        .calculationFormula("")
                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .createdUserId("")
                        .dataSensitivity(Property.DataSensitivity.NON_SENSITIVE)
                        .displayOrder(2)
                        .externalOptions(false)
                        .formField(false)
                        .hasUniqueValue(false)
                        .hidden(false)
                        .hubspotDefined(false)
                        .modificationMetadata(
                            PropertyModificationMetadata.builder()
                                .archivable(true)
                                .readOnlyDefinition(false)
                                .readOnlyValue(false)
                                .readOnlyOptions(false)
                                .build()
                        )
                        .referencedObjectType("")
                        .addSensitiveDataCategory("string")
                        .showCurrencySymbol(false)
                        .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .updatedUserId("updatedUserId")
                        .build()
                )
                .startedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .status(BatchResponseProperty.Status.PENDING)
                .links(
                    BatchResponseProperty.Links.builder()
                        .putAdditionalProperty("foo", JsonValue.from("string"))
                        .build()
                )
                .requestedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .build()

        val roundtrippedBatchResponseProperty =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(batchResponseProperty),
                jacksonTypeRef<BatchResponseProperty>(),
            )

        assertThat(roundtrippedBatchResponseProperty).isEqualTo(batchResponseProperty)
    }
}
