// File generated from our OpenAPI spec by Stainless.

package com.hubspot_sdk.api.models

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.hubspot_sdk.api.core.jsonMapper
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class PublicUnifiedEventsFilterBranchTest {

    @Test
    fun create() {
        val publicUnifiedEventsFilterBranch =
            PublicUnifiedEventsFilterBranch.builder()
                .eventTypeId("eventTypeId")
                .addFilterBranch(
                    PublicOrFilterBranch.builder()
                        .addFilterBranch(
                            PublicAndFilterBranch.builder()
                                .addFilterBranch(
                                    PublicNotAllFilterBranch.builder()
                                        .addFilterBranch(
                                            PublicNotAnyFilterBranch.builder()
                                                .addFilterBranch(
                                                    PublicRestrictedFilterBranch.builder()
                                                        .addFilterBranch(
                                                            PublicPropertyAssociationFilterBranch
                                                                .builder()
                                                                .addFilterBranch(
                                                                    PublicAssociationFilterBranch
                                                                        .builder()
                                                                        .associationCategory(
                                                                            "associationCategory"
                                                                        )
                                                                        .associationTypeId(0)
                                                                        .addFilterBranch(
                                                                            PublicOrFilterBranch
                                                                                .builder()
                                                                                .filterBranches(
                                                                                    listOf()
                                                                                )
                                                                                .filterBranchOperator(
                                                                                    "filterBranchOperator"
                                                                                )
                                                                                .filterBranchType(
                                                                                    PublicOrFilterBranch
                                                                                        .FilterBranchType
                                                                                        .OR
                                                                                )
                                                                                .addFilter(
                                                                                    PublicPropertyFilter
                                                                                        .builder()
                                                                                        .filterType(
                                                                                            PublicPropertyFilter
                                                                                                .FilterType
                                                                                                .PROPERTY
                                                                                        )
                                                                                        .operation(
                                                                                            PublicBoolPropertyOperation
                                                                                                .builder()
                                                                                                .includeObjectsWithNoValueSet(
                                                                                                    true
                                                                                                )
                                                                                                .operationType(
                                                                                                    PublicBoolPropertyOperation
                                                                                                        .OperationType
                                                                                                        .BOOL
                                                                                                )
                                                                                                .operator(
                                                                                                    "operator"
                                                                                                )
                                                                                                .value(
                                                                                                    true
                                                                                                )
                                                                                                .build()
                                                                                        )
                                                                                        .property(
                                                                                            "property"
                                                                                        )
                                                                                        .build()
                                                                                )
                                                                                .build()
                                                                        )
                                                                        .filterBranchOperator(
                                                                            "filterBranchOperator"
                                                                        )
                                                                        .filterBranchType(
                                                                            PublicAssociationFilterBranch
                                                                                .FilterBranchType
                                                                                .ASSOCIATION
                                                                        )
                                                                        .addFilter(
                                                                            PublicPropertyFilter
                                                                                .builder()
                                                                                .filterType(
                                                                                    PublicPropertyFilter
                                                                                        .FilterType
                                                                                        .PROPERTY
                                                                                )
                                                                                .operation(
                                                                                    PublicBoolPropertyOperation
                                                                                        .builder()
                                                                                        .includeObjectsWithNoValueSet(
                                                                                            true
                                                                                        )
                                                                                        .operationType(
                                                                                            PublicBoolPropertyOperation
                                                                                                .OperationType
                                                                                                .BOOL
                                                                                        )
                                                                                        .operator(
                                                                                            "operator"
                                                                                        )
                                                                                        .value(true)
                                                                                        .build()
                                                                                )
                                                                                .property(
                                                                                    "property"
                                                                                )
                                                                                .build()
                                                                        )
                                                                        .objectTypeId(
                                                                            "objectTypeId"
                                                                        )
                                                                        .operator("operator")
                                                                        .build()
                                                                )
                                                                .filterBranchOperator(
                                                                    "filterBranchOperator"
                                                                )
                                                                .filterBranchType(
                                                                    PublicPropertyAssociationFilterBranch
                                                                        .FilterBranchType
                                                                        .PROPERTY_ASSOCIATION
                                                                )
                                                                .addFilter(
                                                                    PublicPropertyFilter.builder()
                                                                        .filterType(
                                                                            PublicPropertyFilter
                                                                                .FilterType
                                                                                .PROPERTY
                                                                        )
                                                                        .operation(
                                                                            PublicBoolPropertyOperation
                                                                                .builder()
                                                                                .includeObjectsWithNoValueSet(
                                                                                    true
                                                                                )
                                                                                .operationType(
                                                                                    PublicBoolPropertyOperation
                                                                                        .OperationType
                                                                                        .BOOL
                                                                                )
                                                                                .operator(
                                                                                    "operator"
                                                                                )
                                                                                .value(true)
                                                                                .build()
                                                                        )
                                                                        .property("property")
                                                                        .build()
                                                                )
                                                                .objectTypeId("objectTypeId")
                                                                .operator("operator")
                                                                .propertyWithObjectId(
                                                                    "propertyWithObjectId"
                                                                )
                                                                .build()
                                                        )
                                                        .filterBranchOperator(
                                                            "filterBranchOperator"
                                                        )
                                                        .filterBranchType(
                                                            PublicRestrictedFilterBranch
                                                                .FilterBranchType
                                                                .RESTRICTED
                                                        )
                                                        .addFilter(
                                                            PublicPropertyFilter.builder()
                                                                .filterType(
                                                                    PublicPropertyFilter.FilterType
                                                                        .PROPERTY
                                                                )
                                                                .operation(
                                                                    PublicBoolPropertyOperation
                                                                        .builder()
                                                                        .includeObjectsWithNoValueSet(
                                                                            true
                                                                        )
                                                                        .operationType(
                                                                            PublicBoolPropertyOperation
                                                                                .OperationType
                                                                                .BOOL
                                                                        )
                                                                        .operator("operator")
                                                                        .value(true)
                                                                        .build()
                                                                )
                                                                .property("property")
                                                                .build()
                                                        )
                                                        .build()
                                                )
                                                .filterBranchOperator("filterBranchOperator")
                                                .filterBranchType(
                                                    PublicNotAnyFilterBranch.FilterBranchType
                                                        .NOT_ANY
                                                )
                                                .addFilter(
                                                    PublicPropertyFilter.builder()
                                                        .filterType(
                                                            PublicPropertyFilter.FilterType.PROPERTY
                                                        )
                                                        .operation(
                                                            PublicBoolPropertyOperation.builder()
                                                                .includeObjectsWithNoValueSet(true)
                                                                .operationType(
                                                                    PublicBoolPropertyOperation
                                                                        .OperationType
                                                                        .BOOL
                                                                )
                                                                .operator("operator")
                                                                .value(true)
                                                                .build()
                                                        )
                                                        .property("property")
                                                        .build()
                                                )
                                                .build()
                                        )
                                        .filterBranchOperator("filterBranchOperator")
                                        .filterBranchType(
                                            PublicNotAllFilterBranch.FilterBranchType.NOT_ALL
                                        )
                                        .addFilter(
                                            PublicPropertyFilter.builder()
                                                .filterType(
                                                    PublicPropertyFilter.FilterType.PROPERTY
                                                )
                                                .operation(
                                                    PublicBoolPropertyOperation.builder()
                                                        .includeObjectsWithNoValueSet(true)
                                                        .operationType(
                                                            PublicBoolPropertyOperation
                                                                .OperationType
                                                                .BOOL
                                                        )
                                                        .operator("operator")
                                                        .value(true)
                                                        .build()
                                                )
                                                .property("property")
                                                .build()
                                        )
                                        .build()
                                )
                                .filterBranchOperator("filterBranchOperator")
                                .filterBranchType(PublicAndFilterBranch.FilterBranchType.AND)
                                .addFilter(
                                    PublicPropertyFilter.builder()
                                        .filterType(PublicPropertyFilter.FilterType.PROPERTY)
                                        .operation(
                                            PublicBoolPropertyOperation.builder()
                                                .includeObjectsWithNoValueSet(true)
                                                .operationType(
                                                    PublicBoolPropertyOperation.OperationType.BOOL
                                                )
                                                .operator("operator")
                                                .value(true)
                                                .build()
                                        )
                                        .property("property")
                                        .build()
                                )
                                .build()
                        )
                        .filterBranchOperator("filterBranchOperator")
                        .filterBranchType(PublicOrFilterBranch.FilterBranchType.OR)
                        .addFilter(
                            PublicPropertyFilter.builder()
                                .filterType(PublicPropertyFilter.FilterType.PROPERTY)
                                .operation(
                                    PublicBoolPropertyOperation.builder()
                                        .includeObjectsWithNoValueSet(true)
                                        .operationType(
                                            PublicBoolPropertyOperation.OperationType.BOOL
                                        )
                                        .operator("operator")
                                        .value(true)
                                        .build()
                                )
                                .property("property")
                                .build()
                        )
                        .build()
                )
                .filterBranchOperator("filterBranchOperator")
                .filterBranchType(PublicUnifiedEventsFilterBranch.FilterBranchType.UNIFIED_EVENTS)
                .addFilter(
                    PublicPropertyFilter.builder()
                        .filterType(PublicPropertyFilter.FilterType.PROPERTY)
                        .operation(
                            PublicBoolPropertyOperation.builder()
                                .includeObjectsWithNoValueSet(true)
                                .operationType(PublicBoolPropertyOperation.OperationType.BOOL)
                                .operator("operator")
                                .value(true)
                                .build()
                        )
                        .property("property")
                        .build()
                )
                .operator(PublicUnifiedEventsFilterBranch.Operator.HAS_COMPLETED)
                .coalescingRefineBy(
                    PublicNumOccurrencesRefineBy.builder()
                        .type(PublicNumOccurrencesRefineBy.Type.NUM_OCCURRENCES)
                        .maxOccurrences(0)
                        .minOccurrences(0)
                        .build()
                )
                .build()

        assertThat(publicUnifiedEventsFilterBranch.eventTypeId()).isEqualTo("eventTypeId")
        assertThat(publicUnifiedEventsFilterBranch.filterBranches())
            .containsExactly(
                PublicUnifiedEventsFilterBranch.FilterBranch.ofPublicOr(
                    PublicOrFilterBranch.builder()
                        .addFilterBranch(
                            PublicAndFilterBranch.builder()
                                .addFilterBranch(
                                    PublicNotAllFilterBranch.builder()
                                        .addFilterBranch(
                                            PublicNotAnyFilterBranch.builder()
                                                .addFilterBranch(
                                                    PublicRestrictedFilterBranch.builder()
                                                        .addFilterBranch(
                                                            PublicPropertyAssociationFilterBranch
                                                                .builder()
                                                                .addFilterBranch(
                                                                    PublicAssociationFilterBranch
                                                                        .builder()
                                                                        .associationCategory(
                                                                            "associationCategory"
                                                                        )
                                                                        .associationTypeId(0)
                                                                        .addFilterBranch(
                                                                            PublicOrFilterBranch
                                                                                .builder()
                                                                                .filterBranches(
                                                                                    listOf()
                                                                                )
                                                                                .filterBranchOperator(
                                                                                    "filterBranchOperator"
                                                                                )
                                                                                .filterBranchType(
                                                                                    PublicOrFilterBranch
                                                                                        .FilterBranchType
                                                                                        .OR
                                                                                )
                                                                                .addFilter(
                                                                                    PublicPropertyFilter
                                                                                        .builder()
                                                                                        .filterType(
                                                                                            PublicPropertyFilter
                                                                                                .FilterType
                                                                                                .PROPERTY
                                                                                        )
                                                                                        .operation(
                                                                                            PublicBoolPropertyOperation
                                                                                                .builder()
                                                                                                .includeObjectsWithNoValueSet(
                                                                                                    true
                                                                                                )
                                                                                                .operationType(
                                                                                                    PublicBoolPropertyOperation
                                                                                                        .OperationType
                                                                                                        .BOOL
                                                                                                )
                                                                                                .operator(
                                                                                                    "operator"
                                                                                                )
                                                                                                .value(
                                                                                                    true
                                                                                                )
                                                                                                .build()
                                                                                        )
                                                                                        .property(
                                                                                            "property"
                                                                                        )
                                                                                        .build()
                                                                                )
                                                                                .build()
                                                                        )
                                                                        .filterBranchOperator(
                                                                            "filterBranchOperator"
                                                                        )
                                                                        .filterBranchType(
                                                                            PublicAssociationFilterBranch
                                                                                .FilterBranchType
                                                                                .ASSOCIATION
                                                                        )
                                                                        .addFilter(
                                                                            PublicPropertyFilter
                                                                                .builder()
                                                                                .filterType(
                                                                                    PublicPropertyFilter
                                                                                        .FilterType
                                                                                        .PROPERTY
                                                                                )
                                                                                .operation(
                                                                                    PublicBoolPropertyOperation
                                                                                        .builder()
                                                                                        .includeObjectsWithNoValueSet(
                                                                                            true
                                                                                        )
                                                                                        .operationType(
                                                                                            PublicBoolPropertyOperation
                                                                                                .OperationType
                                                                                                .BOOL
                                                                                        )
                                                                                        .operator(
                                                                                            "operator"
                                                                                        )
                                                                                        .value(true)
                                                                                        .build()
                                                                                )
                                                                                .property(
                                                                                    "property"
                                                                                )
                                                                                .build()
                                                                        )
                                                                        .objectTypeId(
                                                                            "objectTypeId"
                                                                        )
                                                                        .operator("operator")
                                                                        .build()
                                                                )
                                                                .filterBranchOperator(
                                                                    "filterBranchOperator"
                                                                )
                                                                .filterBranchType(
                                                                    PublicPropertyAssociationFilterBranch
                                                                        .FilterBranchType
                                                                        .PROPERTY_ASSOCIATION
                                                                )
                                                                .addFilter(
                                                                    PublicPropertyFilter.builder()
                                                                        .filterType(
                                                                            PublicPropertyFilter
                                                                                .FilterType
                                                                                .PROPERTY
                                                                        )
                                                                        .operation(
                                                                            PublicBoolPropertyOperation
                                                                                .builder()
                                                                                .includeObjectsWithNoValueSet(
                                                                                    true
                                                                                )
                                                                                .operationType(
                                                                                    PublicBoolPropertyOperation
                                                                                        .OperationType
                                                                                        .BOOL
                                                                                )
                                                                                .operator(
                                                                                    "operator"
                                                                                )
                                                                                .value(true)
                                                                                .build()
                                                                        )
                                                                        .property("property")
                                                                        .build()
                                                                )
                                                                .objectTypeId("objectTypeId")
                                                                .operator("operator")
                                                                .propertyWithObjectId(
                                                                    "propertyWithObjectId"
                                                                )
                                                                .build()
                                                        )
                                                        .filterBranchOperator(
                                                            "filterBranchOperator"
                                                        )
                                                        .filterBranchType(
                                                            PublicRestrictedFilterBranch
                                                                .FilterBranchType
                                                                .RESTRICTED
                                                        )
                                                        .addFilter(
                                                            PublicPropertyFilter.builder()
                                                                .filterType(
                                                                    PublicPropertyFilter.FilterType
                                                                        .PROPERTY
                                                                )
                                                                .operation(
                                                                    PublicBoolPropertyOperation
                                                                        .builder()
                                                                        .includeObjectsWithNoValueSet(
                                                                            true
                                                                        )
                                                                        .operationType(
                                                                            PublicBoolPropertyOperation
                                                                                .OperationType
                                                                                .BOOL
                                                                        )
                                                                        .operator("operator")
                                                                        .value(true)
                                                                        .build()
                                                                )
                                                                .property("property")
                                                                .build()
                                                        )
                                                        .build()
                                                )
                                                .filterBranchOperator("filterBranchOperator")
                                                .filterBranchType(
                                                    PublicNotAnyFilterBranch.FilterBranchType
                                                        .NOT_ANY
                                                )
                                                .addFilter(
                                                    PublicPropertyFilter.builder()
                                                        .filterType(
                                                            PublicPropertyFilter.FilterType.PROPERTY
                                                        )
                                                        .operation(
                                                            PublicBoolPropertyOperation.builder()
                                                                .includeObjectsWithNoValueSet(true)
                                                                .operationType(
                                                                    PublicBoolPropertyOperation
                                                                        .OperationType
                                                                        .BOOL
                                                                )
                                                                .operator("operator")
                                                                .value(true)
                                                                .build()
                                                        )
                                                        .property("property")
                                                        .build()
                                                )
                                                .build()
                                        )
                                        .filterBranchOperator("filterBranchOperator")
                                        .filterBranchType(
                                            PublicNotAllFilterBranch.FilterBranchType.NOT_ALL
                                        )
                                        .addFilter(
                                            PublicPropertyFilter.builder()
                                                .filterType(
                                                    PublicPropertyFilter.FilterType.PROPERTY
                                                )
                                                .operation(
                                                    PublicBoolPropertyOperation.builder()
                                                        .includeObjectsWithNoValueSet(true)
                                                        .operationType(
                                                            PublicBoolPropertyOperation
                                                                .OperationType
                                                                .BOOL
                                                        )
                                                        .operator("operator")
                                                        .value(true)
                                                        .build()
                                                )
                                                .property("property")
                                                .build()
                                        )
                                        .build()
                                )
                                .filterBranchOperator("filterBranchOperator")
                                .filterBranchType(PublicAndFilterBranch.FilterBranchType.AND)
                                .addFilter(
                                    PublicPropertyFilter.builder()
                                        .filterType(PublicPropertyFilter.FilterType.PROPERTY)
                                        .operation(
                                            PublicBoolPropertyOperation.builder()
                                                .includeObjectsWithNoValueSet(true)
                                                .operationType(
                                                    PublicBoolPropertyOperation.OperationType.BOOL
                                                )
                                                .operator("operator")
                                                .value(true)
                                                .build()
                                        )
                                        .property("property")
                                        .build()
                                )
                                .build()
                        )
                        .filterBranchOperator("filterBranchOperator")
                        .filterBranchType(PublicOrFilterBranch.FilterBranchType.OR)
                        .addFilter(
                            PublicPropertyFilter.builder()
                                .filterType(PublicPropertyFilter.FilterType.PROPERTY)
                                .operation(
                                    PublicBoolPropertyOperation.builder()
                                        .includeObjectsWithNoValueSet(true)
                                        .operationType(
                                            PublicBoolPropertyOperation.OperationType.BOOL
                                        )
                                        .operator("operator")
                                        .value(true)
                                        .build()
                                )
                                .property("property")
                                .build()
                        )
                        .build()
                )
            )
        assertThat(publicUnifiedEventsFilterBranch.filterBranchOperator())
            .isEqualTo("filterBranchOperator")
        assertThat(publicUnifiedEventsFilterBranch.filterBranchType())
            .isEqualTo(PublicUnifiedEventsFilterBranch.FilterBranchType.UNIFIED_EVENTS)
        assertThat(publicUnifiedEventsFilterBranch.filters())
            .containsExactly(
                PublicUnifiedEventsFilterBranch.Filter.ofPublicProperty(
                    PublicPropertyFilter.builder()
                        .filterType(PublicPropertyFilter.FilterType.PROPERTY)
                        .operation(
                            PublicBoolPropertyOperation.builder()
                                .includeObjectsWithNoValueSet(true)
                                .operationType(PublicBoolPropertyOperation.OperationType.BOOL)
                                .operator("operator")
                                .value(true)
                                .build()
                        )
                        .property("property")
                        .build()
                )
            )
        assertThat(publicUnifiedEventsFilterBranch.operator())
            .isEqualTo(PublicUnifiedEventsFilterBranch.Operator.HAS_COMPLETED)
        assertThat(publicUnifiedEventsFilterBranch.coalescingRefineBy())
            .contains(
                PublicUnifiedEventsFilterBranch.CoalescingRefineBy.ofPublicNumOccurrences(
                    PublicNumOccurrencesRefineBy.builder()
                        .type(PublicNumOccurrencesRefineBy.Type.NUM_OCCURRENCES)
                        .maxOccurrences(0)
                        .minOccurrences(0)
                        .build()
                )
            )
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val publicUnifiedEventsFilterBranch =
            PublicUnifiedEventsFilterBranch.builder()
                .eventTypeId("eventTypeId")
                .addFilterBranch(
                    PublicOrFilterBranch.builder()
                        .addFilterBranch(
                            PublicAndFilterBranch.builder()
                                .addFilterBranch(
                                    PublicNotAllFilterBranch.builder()
                                        .addFilterBranch(
                                            PublicNotAnyFilterBranch.builder()
                                                .addFilterBranch(
                                                    PublicRestrictedFilterBranch.builder()
                                                        .addFilterBranch(
                                                            PublicPropertyAssociationFilterBranch
                                                                .builder()
                                                                .addFilterBranch(
                                                                    PublicAssociationFilterBranch
                                                                        .builder()
                                                                        .associationCategory(
                                                                            "associationCategory"
                                                                        )
                                                                        .associationTypeId(0)
                                                                        .addFilterBranch(
                                                                            PublicOrFilterBranch
                                                                                .builder()
                                                                                .filterBranches(
                                                                                    listOf()
                                                                                )
                                                                                .filterBranchOperator(
                                                                                    "filterBranchOperator"
                                                                                )
                                                                                .filterBranchType(
                                                                                    PublicOrFilterBranch
                                                                                        .FilterBranchType
                                                                                        .OR
                                                                                )
                                                                                .addFilter(
                                                                                    PublicPropertyFilter
                                                                                        .builder()
                                                                                        .filterType(
                                                                                            PublicPropertyFilter
                                                                                                .FilterType
                                                                                                .PROPERTY
                                                                                        )
                                                                                        .operation(
                                                                                            PublicBoolPropertyOperation
                                                                                                .builder()
                                                                                                .includeObjectsWithNoValueSet(
                                                                                                    true
                                                                                                )
                                                                                                .operationType(
                                                                                                    PublicBoolPropertyOperation
                                                                                                        .OperationType
                                                                                                        .BOOL
                                                                                                )
                                                                                                .operator(
                                                                                                    "operator"
                                                                                                )
                                                                                                .value(
                                                                                                    true
                                                                                                )
                                                                                                .build()
                                                                                        )
                                                                                        .property(
                                                                                            "property"
                                                                                        )
                                                                                        .build()
                                                                                )
                                                                                .build()
                                                                        )
                                                                        .filterBranchOperator(
                                                                            "filterBranchOperator"
                                                                        )
                                                                        .filterBranchType(
                                                                            PublicAssociationFilterBranch
                                                                                .FilterBranchType
                                                                                .ASSOCIATION
                                                                        )
                                                                        .addFilter(
                                                                            PublicPropertyFilter
                                                                                .builder()
                                                                                .filterType(
                                                                                    PublicPropertyFilter
                                                                                        .FilterType
                                                                                        .PROPERTY
                                                                                )
                                                                                .operation(
                                                                                    PublicBoolPropertyOperation
                                                                                        .builder()
                                                                                        .includeObjectsWithNoValueSet(
                                                                                            true
                                                                                        )
                                                                                        .operationType(
                                                                                            PublicBoolPropertyOperation
                                                                                                .OperationType
                                                                                                .BOOL
                                                                                        )
                                                                                        .operator(
                                                                                            "operator"
                                                                                        )
                                                                                        .value(true)
                                                                                        .build()
                                                                                )
                                                                                .property(
                                                                                    "property"
                                                                                )
                                                                                .build()
                                                                        )
                                                                        .objectTypeId(
                                                                            "objectTypeId"
                                                                        )
                                                                        .operator("operator")
                                                                        .build()
                                                                )
                                                                .filterBranchOperator(
                                                                    "filterBranchOperator"
                                                                )
                                                                .filterBranchType(
                                                                    PublicPropertyAssociationFilterBranch
                                                                        .FilterBranchType
                                                                        .PROPERTY_ASSOCIATION
                                                                )
                                                                .addFilter(
                                                                    PublicPropertyFilter.builder()
                                                                        .filterType(
                                                                            PublicPropertyFilter
                                                                                .FilterType
                                                                                .PROPERTY
                                                                        )
                                                                        .operation(
                                                                            PublicBoolPropertyOperation
                                                                                .builder()
                                                                                .includeObjectsWithNoValueSet(
                                                                                    true
                                                                                )
                                                                                .operationType(
                                                                                    PublicBoolPropertyOperation
                                                                                        .OperationType
                                                                                        .BOOL
                                                                                )
                                                                                .operator(
                                                                                    "operator"
                                                                                )
                                                                                .value(true)
                                                                                .build()
                                                                        )
                                                                        .property("property")
                                                                        .build()
                                                                )
                                                                .objectTypeId("objectTypeId")
                                                                .operator("operator")
                                                                .propertyWithObjectId(
                                                                    "propertyWithObjectId"
                                                                )
                                                                .build()
                                                        )
                                                        .filterBranchOperator(
                                                            "filterBranchOperator"
                                                        )
                                                        .filterBranchType(
                                                            PublicRestrictedFilterBranch
                                                                .FilterBranchType
                                                                .RESTRICTED
                                                        )
                                                        .addFilter(
                                                            PublicPropertyFilter.builder()
                                                                .filterType(
                                                                    PublicPropertyFilter.FilterType
                                                                        .PROPERTY
                                                                )
                                                                .operation(
                                                                    PublicBoolPropertyOperation
                                                                        .builder()
                                                                        .includeObjectsWithNoValueSet(
                                                                            true
                                                                        )
                                                                        .operationType(
                                                                            PublicBoolPropertyOperation
                                                                                .OperationType
                                                                                .BOOL
                                                                        )
                                                                        .operator("operator")
                                                                        .value(true)
                                                                        .build()
                                                                )
                                                                .property("property")
                                                                .build()
                                                        )
                                                        .build()
                                                )
                                                .filterBranchOperator("filterBranchOperator")
                                                .filterBranchType(
                                                    PublicNotAnyFilterBranch.FilterBranchType
                                                        .NOT_ANY
                                                )
                                                .addFilter(
                                                    PublicPropertyFilter.builder()
                                                        .filterType(
                                                            PublicPropertyFilter.FilterType.PROPERTY
                                                        )
                                                        .operation(
                                                            PublicBoolPropertyOperation.builder()
                                                                .includeObjectsWithNoValueSet(true)
                                                                .operationType(
                                                                    PublicBoolPropertyOperation
                                                                        .OperationType
                                                                        .BOOL
                                                                )
                                                                .operator("operator")
                                                                .value(true)
                                                                .build()
                                                        )
                                                        .property("property")
                                                        .build()
                                                )
                                                .build()
                                        )
                                        .filterBranchOperator("filterBranchOperator")
                                        .filterBranchType(
                                            PublicNotAllFilterBranch.FilterBranchType.NOT_ALL
                                        )
                                        .addFilter(
                                            PublicPropertyFilter.builder()
                                                .filterType(
                                                    PublicPropertyFilter.FilterType.PROPERTY
                                                )
                                                .operation(
                                                    PublicBoolPropertyOperation.builder()
                                                        .includeObjectsWithNoValueSet(true)
                                                        .operationType(
                                                            PublicBoolPropertyOperation
                                                                .OperationType
                                                                .BOOL
                                                        )
                                                        .operator("operator")
                                                        .value(true)
                                                        .build()
                                                )
                                                .property("property")
                                                .build()
                                        )
                                        .build()
                                )
                                .filterBranchOperator("filterBranchOperator")
                                .filterBranchType(PublicAndFilterBranch.FilterBranchType.AND)
                                .addFilter(
                                    PublicPropertyFilter.builder()
                                        .filterType(PublicPropertyFilter.FilterType.PROPERTY)
                                        .operation(
                                            PublicBoolPropertyOperation.builder()
                                                .includeObjectsWithNoValueSet(true)
                                                .operationType(
                                                    PublicBoolPropertyOperation.OperationType.BOOL
                                                )
                                                .operator("operator")
                                                .value(true)
                                                .build()
                                        )
                                        .property("property")
                                        .build()
                                )
                                .build()
                        )
                        .filterBranchOperator("filterBranchOperator")
                        .filterBranchType(PublicOrFilterBranch.FilterBranchType.OR)
                        .addFilter(
                            PublicPropertyFilter.builder()
                                .filterType(PublicPropertyFilter.FilterType.PROPERTY)
                                .operation(
                                    PublicBoolPropertyOperation.builder()
                                        .includeObjectsWithNoValueSet(true)
                                        .operationType(
                                            PublicBoolPropertyOperation.OperationType.BOOL
                                        )
                                        .operator("operator")
                                        .value(true)
                                        .build()
                                )
                                .property("property")
                                .build()
                        )
                        .build()
                )
                .filterBranchOperator("filterBranchOperator")
                .filterBranchType(PublicUnifiedEventsFilterBranch.FilterBranchType.UNIFIED_EVENTS)
                .addFilter(
                    PublicPropertyFilter.builder()
                        .filterType(PublicPropertyFilter.FilterType.PROPERTY)
                        .operation(
                            PublicBoolPropertyOperation.builder()
                                .includeObjectsWithNoValueSet(true)
                                .operationType(PublicBoolPropertyOperation.OperationType.BOOL)
                                .operator("operator")
                                .value(true)
                                .build()
                        )
                        .property("property")
                        .build()
                )
                .operator(PublicUnifiedEventsFilterBranch.Operator.HAS_COMPLETED)
                .coalescingRefineBy(
                    PublicNumOccurrencesRefineBy.builder()
                        .type(PublicNumOccurrencesRefineBy.Type.NUM_OCCURRENCES)
                        .maxOccurrences(0)
                        .minOccurrences(0)
                        .build()
                )
                .build()

        val roundtrippedPublicUnifiedEventsFilterBranch =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(publicUnifiedEventsFilterBranch),
                jacksonTypeRef<PublicUnifiedEventsFilterBranch>(),
            )

        assertThat(roundtrippedPublicUnifiedEventsFilterBranch)
            .isEqualTo(publicUnifiedEventsFilterBranch)
    }
}
