// File generated from our OpenAPI spec by Stainless.

package com.hubspot_sdk.api.models

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.hubspot_sdk.api.core.JsonValue
import com.hubspot_sdk.api.core.jsonMapper
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class StandardErrorTest {

    @Test
    fun create() {
        val standardError =
            StandardError.builder()
                .category("category")
                .context(
                    StandardError.Context.builder()
                        .putAdditionalProperty("foo", JsonValue.from(listOf("string")))
                        .build()
                )
                .addError(
                    ErrorDetail.builder()
                        .message("message")
                        .code("code")
                        .context(
                            ErrorDetail.Context.builder()
                                .putAdditionalProperty("0", JsonValue.from(listOf("string")))
                                .putAdditionalProperty("1", JsonValue.from(listOf("string")))
                                .putAdditionalProperty("2", JsonValue.from(listOf("string")))
                                .putAdditionalProperty("3", JsonValue.from(listOf("string")))
                                .putAdditionalProperty("4", JsonValue.from(listOf("string")))
                                .putAdditionalProperty("5", JsonValue.from(listOf("string")))
                                .putAdditionalProperty("6", JsonValue.from(listOf("string")))
                                .putAdditionalProperty("7", JsonValue.from(listOf("string")))
                                .putAdditionalProperty("8", JsonValue.from(listOf("string")))
                                .putAdditionalProperty("9", JsonValue.from(listOf("string")))
                                .putAdditionalProperty("10", JsonValue.from(listOf("string")))
                                .putAdditionalProperty("11", JsonValue.from(listOf("string")))
                                .putAdditionalProperty("12", JsonValue.from(listOf("string")))
                                .putAdditionalProperty("13", JsonValue.from(listOf("string")))
                                .putAdditionalProperty("14", JsonValue.from(listOf("string")))
                                .putAdditionalProperty("15", JsonValue.from(listOf("string")))
                                .putAdditionalProperty("16", JsonValue.from(listOf("string")))
                                .putAdditionalProperty("17", JsonValue.from(listOf("string")))
                                .putAdditionalProperty("18", JsonValue.from(listOf("string")))
                                .putAdditionalProperty("19", JsonValue.from(listOf("string")))
                                .putAdditionalProperty("20", JsonValue.from(listOf("string")))
                                .putAdditionalProperty("21", JsonValue.from(listOf("string")))
                                .putAdditionalProperty("22", JsonValue.from(listOf("string")))
                                .putAdditionalProperty("23", JsonValue.from(listOf("string")))
                                .putAdditionalProperty("24", JsonValue.from(listOf("string")))
                                .putAdditionalProperty("25", JsonValue.from(listOf("string")))
                                .putAdditionalProperty("26", JsonValue.from(listOf("string")))
                                .putAdditionalProperty("27", JsonValue.from(listOf("string")))
                                .putAdditionalProperty("28", JsonValue.from(listOf("string")))
                                .putAdditionalProperty("29", JsonValue.from(listOf("string")))
                                .putAdditionalProperty("30", JsonValue.from(listOf("string")))
                                .putAdditionalProperty("31", JsonValue.from(listOf("string")))
                                .build()
                        )
                        .in_("in")
                        .subCategory("subCategory")
                        .build()
                )
                .links(
                    StandardError.Links.builder()
                        .putAdditionalProperty("foo", JsonValue.from("string"))
                        .build()
                )
                .message("message")
                .status("status")
                .id("id")
                .subCategory(JsonValue.from(mapOf<String, Any>()))
                .build()

        assertThat(standardError.category()).isEqualTo("category")
        assertThat(standardError.context())
            .isEqualTo(
                StandardError.Context.builder()
                    .putAdditionalProperty("foo", JsonValue.from(listOf("string")))
                    .build()
            )
        assertThat(standardError.errors())
            .containsExactly(
                ErrorDetail.builder()
                    .message("message")
                    .code("code")
                    .context(
                        ErrorDetail.Context.builder()
                            .putAdditionalProperty("0", JsonValue.from(listOf("string")))
                            .putAdditionalProperty("1", JsonValue.from(listOf("string")))
                            .putAdditionalProperty("2", JsonValue.from(listOf("string")))
                            .putAdditionalProperty("3", JsonValue.from(listOf("string")))
                            .putAdditionalProperty("4", JsonValue.from(listOf("string")))
                            .putAdditionalProperty("5", JsonValue.from(listOf("string")))
                            .putAdditionalProperty("6", JsonValue.from(listOf("string")))
                            .putAdditionalProperty("7", JsonValue.from(listOf("string")))
                            .putAdditionalProperty("8", JsonValue.from(listOf("string")))
                            .putAdditionalProperty("9", JsonValue.from(listOf("string")))
                            .putAdditionalProperty("10", JsonValue.from(listOf("string")))
                            .putAdditionalProperty("11", JsonValue.from(listOf("string")))
                            .putAdditionalProperty("12", JsonValue.from(listOf("string")))
                            .putAdditionalProperty("13", JsonValue.from(listOf("string")))
                            .putAdditionalProperty("14", JsonValue.from(listOf("string")))
                            .putAdditionalProperty("15", JsonValue.from(listOf("string")))
                            .putAdditionalProperty("16", JsonValue.from(listOf("string")))
                            .putAdditionalProperty("17", JsonValue.from(listOf("string")))
                            .putAdditionalProperty("18", JsonValue.from(listOf("string")))
                            .putAdditionalProperty("19", JsonValue.from(listOf("string")))
                            .putAdditionalProperty("20", JsonValue.from(listOf("string")))
                            .putAdditionalProperty("21", JsonValue.from(listOf("string")))
                            .putAdditionalProperty("22", JsonValue.from(listOf("string")))
                            .putAdditionalProperty("23", JsonValue.from(listOf("string")))
                            .putAdditionalProperty("24", JsonValue.from(listOf("string")))
                            .putAdditionalProperty("25", JsonValue.from(listOf("string")))
                            .putAdditionalProperty("26", JsonValue.from(listOf("string")))
                            .putAdditionalProperty("27", JsonValue.from(listOf("string")))
                            .putAdditionalProperty("28", JsonValue.from(listOf("string")))
                            .putAdditionalProperty("29", JsonValue.from(listOf("string")))
                            .putAdditionalProperty("30", JsonValue.from(listOf("string")))
                            .putAdditionalProperty("31", JsonValue.from(listOf("string")))
                            .build()
                    )
                    .in_("in")
                    .subCategory("subCategory")
                    .build()
            )
        assertThat(standardError.links())
            .isEqualTo(
                StandardError.Links.builder()
                    .putAdditionalProperty("foo", JsonValue.from("string"))
                    .build()
            )
        assertThat(standardError.message()).isEqualTo("message")
        assertThat(standardError.status()).isEqualTo("status")
        assertThat(standardError.id()).contains("id")
        assertThat(standardError._subCategory()).isEqualTo(JsonValue.from(mapOf<String, Any>()))
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val standardError =
            StandardError.builder()
                .category("category")
                .context(
                    StandardError.Context.builder()
                        .putAdditionalProperty("foo", JsonValue.from(listOf("string")))
                        .build()
                )
                .addError(
                    ErrorDetail.builder()
                        .message("message")
                        .code("code")
                        .context(
                            ErrorDetail.Context.builder()
                                .putAdditionalProperty("0", JsonValue.from(listOf("string")))
                                .putAdditionalProperty("1", JsonValue.from(listOf("string")))
                                .putAdditionalProperty("2", JsonValue.from(listOf("string")))
                                .putAdditionalProperty("3", JsonValue.from(listOf("string")))
                                .putAdditionalProperty("4", JsonValue.from(listOf("string")))
                                .putAdditionalProperty("5", JsonValue.from(listOf("string")))
                                .putAdditionalProperty("6", JsonValue.from(listOf("string")))
                                .putAdditionalProperty("7", JsonValue.from(listOf("string")))
                                .putAdditionalProperty("8", JsonValue.from(listOf("string")))
                                .putAdditionalProperty("9", JsonValue.from(listOf("string")))
                                .putAdditionalProperty("10", JsonValue.from(listOf("string")))
                                .putAdditionalProperty("11", JsonValue.from(listOf("string")))
                                .putAdditionalProperty("12", JsonValue.from(listOf("string")))
                                .putAdditionalProperty("13", JsonValue.from(listOf("string")))
                                .putAdditionalProperty("14", JsonValue.from(listOf("string")))
                                .putAdditionalProperty("15", JsonValue.from(listOf("string")))
                                .putAdditionalProperty("16", JsonValue.from(listOf("string")))
                                .putAdditionalProperty("17", JsonValue.from(listOf("string")))
                                .putAdditionalProperty("18", JsonValue.from(listOf("string")))
                                .putAdditionalProperty("19", JsonValue.from(listOf("string")))
                                .putAdditionalProperty("20", JsonValue.from(listOf("string")))
                                .putAdditionalProperty("21", JsonValue.from(listOf("string")))
                                .putAdditionalProperty("22", JsonValue.from(listOf("string")))
                                .putAdditionalProperty("23", JsonValue.from(listOf("string")))
                                .putAdditionalProperty("24", JsonValue.from(listOf("string")))
                                .putAdditionalProperty("25", JsonValue.from(listOf("string")))
                                .putAdditionalProperty("26", JsonValue.from(listOf("string")))
                                .putAdditionalProperty("27", JsonValue.from(listOf("string")))
                                .putAdditionalProperty("28", JsonValue.from(listOf("string")))
                                .putAdditionalProperty("29", JsonValue.from(listOf("string")))
                                .putAdditionalProperty("30", JsonValue.from(listOf("string")))
                                .putAdditionalProperty("31", JsonValue.from(listOf("string")))
                                .build()
                        )
                        .in_("in")
                        .subCategory("subCategory")
                        .build()
                )
                .links(
                    StandardError.Links.builder()
                        .putAdditionalProperty("foo", JsonValue.from("string"))
                        .build()
                )
                .message("message")
                .status("status")
                .id("id")
                .subCategory(JsonValue.from(mapOf<String, Any>()))
                .build()

        val roundtrippedStandardError =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(standardError),
                jacksonTypeRef<StandardError>(),
            )

        assertThat(roundtrippedStandardError).isEqualTo(standardError)
    }
}
