// File generated from our OpenAPI spec by Stainless.

package com.hubspot_sdk.api.models.automation.workflows

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.hubspot_sdk.api.core.jsonMapper
import com.hubspot_sdk.api.models.PublicAndFilterBranch
import com.hubspot_sdk.api.models.PublicAssociationFilterBranch
import com.hubspot_sdk.api.models.PublicBoolPropertyOperation
import com.hubspot_sdk.api.models.PublicNotAllFilterBranch
import com.hubspot_sdk.api.models.PublicNotAnyFilterBranch
import com.hubspot_sdk.api.models.PublicNumOccurrencesRefineBy
import com.hubspot_sdk.api.models.PublicOrFilterBranch
import com.hubspot_sdk.api.models.PublicPropertyAssociationFilterBranch
import com.hubspot_sdk.api.models.PublicPropertyFilter
import com.hubspot_sdk.api.models.PublicRestrictedFilterBranch
import com.hubspot_sdk.api.models.PublicUnifiedEventsFilterBranch
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class ApiListBranchTest {

    @Test
    fun create() {
        val apiListBranch =
            ApiListBranch.builder()
                .branchName("Branch name")
                .connection(
                    ApiConnection.builder()
                        .edgeType("edgeType")
                        .nextActionId("nextActionId")
                        .build()
                )
                .filterBranch(
                    PublicOrFilterBranch.builder()
                        .addFilterBranch(
                            PublicAndFilterBranch.builder()
                                .addFilterBranch(
                                    PublicNotAllFilterBranch.builder()
                                        .addFilterBranch(
                                            PublicNotAnyFilterBranch.builder()
                                                .addFilterBranch(
                                                    PublicRestrictedFilterBranch.builder()
                                                        .addFilterBranch(
                                                            PublicUnifiedEventsFilterBranch
                                                                .builder()
                                                                .eventTypeId("eventTypeId")
                                                                .addFilterBranch(
                                                                    PublicPropertyAssociationFilterBranch
                                                                        .builder()
                                                                        .addFilterBranch(
                                                                            PublicAssociationFilterBranch
                                                                                .builder()
                                                                                .associationCategory(
                                                                                    "associationCategory"
                                                                                )
                                                                                .associationTypeId(
                                                                                    0
                                                                                )
                                                                                .addFilterBranch(
                                                                                    PublicOrFilterBranch
                                                                                        .builder()
                                                                                        .filterBranches(
                                                                                            listOf()
                                                                                        )
                                                                                        .filterBranchOperator(
                                                                                            "filterBranchOperator"
                                                                                        )
                                                                                        .filterBranchType(
                                                                                            PublicOrFilterBranch
                                                                                                .FilterBranchType
                                                                                                .OR
                                                                                        )
                                                                                        .addFilter(
                                                                                            PublicPropertyFilter
                                                                                                .builder()
                                                                                                .filterType(
                                                                                                    PublicPropertyFilter
                                                                                                        .FilterType
                                                                                                        .PROPERTY
                                                                                                )
                                                                                                .operation(
                                                                                                    PublicBoolPropertyOperation
                                                                                                        .builder()
                                                                                                        .includeObjectsWithNoValueSet(
                                                                                                            true
                                                                                                        )
                                                                                                        .operationType(
                                                                                                            PublicBoolPropertyOperation
                                                                                                                .OperationType
                                                                                                                .BOOL
                                                                                                        )
                                                                                                        .operator(
                                                                                                            "operator"
                                                                                                        )
                                                                                                        .value(
                                                                                                            true
                                                                                                        )
                                                                                                        .build()
                                                                                                )
                                                                                                .property(
                                                                                                    "property"
                                                                                                )
                                                                                                .build()
                                                                                        )
                                                                                        .build()
                                                                                )
                                                                                .filterBranchOperator(
                                                                                    "filterBranchOperator"
                                                                                )
                                                                                .filterBranchType(
                                                                                    PublicAssociationFilterBranch
                                                                                        .FilterBranchType
                                                                                        .ASSOCIATION
                                                                                )
                                                                                .addFilter(
                                                                                    PublicPropertyFilter
                                                                                        .builder()
                                                                                        .filterType(
                                                                                            PublicPropertyFilter
                                                                                                .FilterType
                                                                                                .PROPERTY
                                                                                        )
                                                                                        .operation(
                                                                                            PublicBoolPropertyOperation
                                                                                                .builder()
                                                                                                .includeObjectsWithNoValueSet(
                                                                                                    true
                                                                                                )
                                                                                                .operationType(
                                                                                                    PublicBoolPropertyOperation
                                                                                                        .OperationType
                                                                                                        .BOOL
                                                                                                )
                                                                                                .operator(
                                                                                                    "operator"
                                                                                                )
                                                                                                .value(
                                                                                                    true
                                                                                                )
                                                                                                .build()
                                                                                        )
                                                                                        .property(
                                                                                            "property"
                                                                                        )
                                                                                        .build()
                                                                                )
                                                                                .objectTypeId(
                                                                                    "objectTypeId"
                                                                                )
                                                                                .operator(
                                                                                    "operator"
                                                                                )
                                                                                .build()
                                                                        )
                                                                        .filterBranchOperator(
                                                                            "filterBranchOperator"
                                                                        )
                                                                        .filterBranchType(
                                                                            PublicPropertyAssociationFilterBranch
                                                                                .FilterBranchType
                                                                                .PROPERTY_ASSOCIATION
                                                                        )
                                                                        .addFilter(
                                                                            PublicPropertyFilter
                                                                                .builder()
                                                                                .filterType(
                                                                                    PublicPropertyFilter
                                                                                        .FilterType
                                                                                        .PROPERTY
                                                                                )
                                                                                .operation(
                                                                                    PublicBoolPropertyOperation
                                                                                        .builder()
                                                                                        .includeObjectsWithNoValueSet(
                                                                                            true
                                                                                        )
                                                                                        .operationType(
                                                                                            PublicBoolPropertyOperation
                                                                                                .OperationType
                                                                                                .BOOL
                                                                                        )
                                                                                        .operator(
                                                                                            "operator"
                                                                                        )
                                                                                        .value(true)
                                                                                        .build()
                                                                                )
                                                                                .property(
                                                                                    "property"
                                                                                )
                                                                                .build()
                                                                        )
                                                                        .objectTypeId(
                                                                            "objectTypeId"
                                                                        )
                                                                        .operator("operator")
                                                                        .propertyWithObjectId(
                                                                            "propertyWithObjectId"
                                                                        )
                                                                        .build()
                                                                )
                                                                .filterBranchOperator(
                                                                    "filterBranchOperator"
                                                                )
                                                                .filterBranchType(
                                                                    PublicUnifiedEventsFilterBranch
                                                                        .FilterBranchType
                                                                        .UNIFIED_EVENTS
                                                                )
                                                                .addFilter(
                                                                    PublicPropertyFilter.builder()
                                                                        .filterType(
                                                                            PublicPropertyFilter
                                                                                .FilterType
                                                                                .PROPERTY
                                                                        )
                                                                        .operation(
                                                                            PublicBoolPropertyOperation
                                                                                .builder()
                                                                                .includeObjectsWithNoValueSet(
                                                                                    true
                                                                                )
                                                                                .operationType(
                                                                                    PublicBoolPropertyOperation
                                                                                        .OperationType
                                                                                        .BOOL
                                                                                )
                                                                                .operator(
                                                                                    "operator"
                                                                                )
                                                                                .value(true)
                                                                                .build()
                                                                        )
                                                                        .property("property")
                                                                        .build()
                                                                )
                                                                .operator(
                                                                    PublicUnifiedEventsFilterBranch
                                                                        .Operator
                                                                        .HAS_COMPLETED
                                                                )
                                                                .coalescingRefineBy(
                                                                    PublicNumOccurrencesRefineBy
                                                                        .builder()
                                                                        .type(
                                                                            PublicNumOccurrencesRefineBy
                                                                                .Type
                                                                                .NUM_OCCURRENCES
                                                                        )
                                                                        .maxOccurrences(0)
                                                                        .minOccurrences(0)
                                                                        .build()
                                                                )
                                                                .build()
                                                        )
                                                        .filterBranchOperator(
                                                            "filterBranchOperator"
                                                        )
                                                        .filterBranchType(
                                                            PublicRestrictedFilterBranch
                                                                .FilterBranchType
                                                                .RESTRICTED
                                                        )
                                                        .addFilter(
                                                            PublicPropertyFilter.builder()
                                                                .filterType(
                                                                    PublicPropertyFilter.FilterType
                                                                        .PROPERTY
                                                                )
                                                                .operation(
                                                                    PublicBoolPropertyOperation
                                                                        .builder()
                                                                        .includeObjectsWithNoValueSet(
                                                                            true
                                                                        )
                                                                        .operationType(
                                                                            PublicBoolPropertyOperation
                                                                                .OperationType
                                                                                .BOOL
                                                                        )
                                                                        .operator("operator")
                                                                        .value(true)
                                                                        .build()
                                                                )
                                                                .property("property")
                                                                .build()
                                                        )
                                                        .build()
                                                )
                                                .filterBranchOperator("filterBranchOperator")
                                                .filterBranchType(
                                                    PublicNotAnyFilterBranch.FilterBranchType
                                                        .NOT_ANY
                                                )
                                                .addFilter(
                                                    PublicPropertyFilter.builder()
                                                        .filterType(
                                                            PublicPropertyFilter.FilterType.PROPERTY
                                                        )
                                                        .operation(
                                                            PublicBoolPropertyOperation.builder()
                                                                .includeObjectsWithNoValueSet(true)
                                                                .operationType(
                                                                    PublicBoolPropertyOperation
                                                                        .OperationType
                                                                        .BOOL
                                                                )
                                                                .operator("operator")
                                                                .value(true)
                                                                .build()
                                                        )
                                                        .property("property")
                                                        .build()
                                                )
                                                .build()
                                        )
                                        .filterBranchOperator("filterBranchOperator")
                                        .filterBranchType(
                                            PublicNotAllFilterBranch.FilterBranchType.NOT_ALL
                                        )
                                        .addFilter(
                                            PublicPropertyFilter.builder()
                                                .filterType(
                                                    PublicPropertyFilter.FilterType.PROPERTY
                                                )
                                                .operation(
                                                    PublicBoolPropertyOperation.builder()
                                                        .includeObjectsWithNoValueSet(true)
                                                        .operationType(
                                                            PublicBoolPropertyOperation
                                                                .OperationType
                                                                .BOOL
                                                        )
                                                        .operator("operator")
                                                        .value(true)
                                                        .build()
                                                )
                                                .property("property")
                                                .build()
                                        )
                                        .build()
                                )
                                .filterBranchOperator("filterBranchOperator")
                                .filterBranchType(PublicAndFilterBranch.FilterBranchType.AND)
                                .addFilter(
                                    PublicPropertyFilter.builder()
                                        .filterType(PublicPropertyFilter.FilterType.PROPERTY)
                                        .operation(
                                            PublicBoolPropertyOperation.builder()
                                                .includeObjectsWithNoValueSet(true)
                                                .operationType(
                                                    PublicBoolPropertyOperation.OperationType.BOOL
                                                )
                                                .operator("operator")
                                                .value(true)
                                                .build()
                                        )
                                        .property("property")
                                        .build()
                                )
                                .build()
                        )
                        .filterBranchOperator("filterBranchOperator")
                        .filterBranchType(PublicOrFilterBranch.FilterBranchType.OR)
                        .addFilter(
                            PublicPropertyFilter.builder()
                                .filterType(PublicPropertyFilter.FilterType.PROPERTY)
                                .operation(
                                    PublicBoolPropertyOperation.builder()
                                        .includeObjectsWithNoValueSet(true)
                                        .operationType(
                                            PublicBoolPropertyOperation.OperationType.BOOL
                                        )
                                        .operator("operator")
                                        .value(true)
                                        .build()
                                )
                                .property("property")
                                .build()
                        )
                        .build()
                )
                .build()

        assertThat(apiListBranch.branchName()).contains("Branch name")
        assertThat(apiListBranch.connection())
            .contains(
                ApiConnection.builder().edgeType("edgeType").nextActionId("nextActionId").build()
            )
        assertThat(apiListBranch.filterBranch())
            .contains(
                ApiListBranch.FilterBranch.ofPublicOr(
                    PublicOrFilterBranch.builder()
                        .addFilterBranch(
                            PublicAndFilterBranch.builder()
                                .addFilterBranch(
                                    PublicNotAllFilterBranch.builder()
                                        .addFilterBranch(
                                            PublicNotAnyFilterBranch.builder()
                                                .addFilterBranch(
                                                    PublicRestrictedFilterBranch.builder()
                                                        .addFilterBranch(
                                                            PublicUnifiedEventsFilterBranch
                                                                .builder()
                                                                .eventTypeId("eventTypeId")
                                                                .addFilterBranch(
                                                                    PublicPropertyAssociationFilterBranch
                                                                        .builder()
                                                                        .addFilterBranch(
                                                                            PublicAssociationFilterBranch
                                                                                .builder()
                                                                                .associationCategory(
                                                                                    "associationCategory"
                                                                                )
                                                                                .associationTypeId(
                                                                                    0
                                                                                )
                                                                                .addFilterBranch(
                                                                                    PublicOrFilterBranch
                                                                                        .builder()
                                                                                        .filterBranches(
                                                                                            listOf()
                                                                                        )
                                                                                        .filterBranchOperator(
                                                                                            "filterBranchOperator"
                                                                                        )
                                                                                        .filterBranchType(
                                                                                            PublicOrFilterBranch
                                                                                                .FilterBranchType
                                                                                                .OR
                                                                                        )
                                                                                        .addFilter(
                                                                                            PublicPropertyFilter
                                                                                                .builder()
                                                                                                .filterType(
                                                                                                    PublicPropertyFilter
                                                                                                        .FilterType
                                                                                                        .PROPERTY
                                                                                                )
                                                                                                .operation(
                                                                                                    PublicBoolPropertyOperation
                                                                                                        .builder()
                                                                                                        .includeObjectsWithNoValueSet(
                                                                                                            true
                                                                                                        )
                                                                                                        .operationType(
                                                                                                            PublicBoolPropertyOperation
                                                                                                                .OperationType
                                                                                                                .BOOL
                                                                                                        )
                                                                                                        .operator(
                                                                                                            "operator"
                                                                                                        )
                                                                                                        .value(
                                                                                                            true
                                                                                                        )
                                                                                                        .build()
                                                                                                )
                                                                                                .property(
                                                                                                    "property"
                                                                                                )
                                                                                                .build()
                                                                                        )
                                                                                        .build()
                                                                                )
                                                                                .filterBranchOperator(
                                                                                    "filterBranchOperator"
                                                                                )
                                                                                .filterBranchType(
                                                                                    PublicAssociationFilterBranch
                                                                                        .FilterBranchType
                                                                                        .ASSOCIATION
                                                                                )
                                                                                .addFilter(
                                                                                    PublicPropertyFilter
                                                                                        .builder()
                                                                                        .filterType(
                                                                                            PublicPropertyFilter
                                                                                                .FilterType
                                                                                                .PROPERTY
                                                                                        )
                                                                                        .operation(
                                                                                            PublicBoolPropertyOperation
                                                                                                .builder()
                                                                                                .includeObjectsWithNoValueSet(
                                                                                                    true
                                                                                                )
                                                                                                .operationType(
                                                                                                    PublicBoolPropertyOperation
                                                                                                        .OperationType
                                                                                                        .BOOL
                                                                                                )
                                                                                                .operator(
                                                                                                    "operator"
                                                                                                )
                                                                                                .value(
                                                                                                    true
                                                                                                )
                                                                                                .build()
                                                                                        )
                                                                                        .property(
                                                                                            "property"
                                                                                        )
                                                                                        .build()
                                                                                )
                                                                                .objectTypeId(
                                                                                    "objectTypeId"
                                                                                )
                                                                                .operator(
                                                                                    "operator"
                                                                                )
                                                                                .build()
                                                                        )
                                                                        .filterBranchOperator(
                                                                            "filterBranchOperator"
                                                                        )
                                                                        .filterBranchType(
                                                                            PublicPropertyAssociationFilterBranch
                                                                                .FilterBranchType
                                                                                .PROPERTY_ASSOCIATION
                                                                        )
                                                                        .addFilter(
                                                                            PublicPropertyFilter
                                                                                .builder()
                                                                                .filterType(
                                                                                    PublicPropertyFilter
                                                                                        .FilterType
                                                                                        .PROPERTY
                                                                                )
                                                                                .operation(
                                                                                    PublicBoolPropertyOperation
                                                                                        .builder()
                                                                                        .includeObjectsWithNoValueSet(
                                                                                            true
                                                                                        )
                                                                                        .operationType(
                                                                                            PublicBoolPropertyOperation
                                                                                                .OperationType
                                                                                                .BOOL
                                                                                        )
                                                                                        .operator(
                                                                                            "operator"
                                                                                        )
                                                                                        .value(true)
                                                                                        .build()
                                                                                )
                                                                                .property(
                                                                                    "property"
                                                                                )
                                                                                .build()
                                                                        )
                                                                        .objectTypeId(
                                                                            "objectTypeId"
                                                                        )
                                                                        .operator("operator")
                                                                        .propertyWithObjectId(
                                                                            "propertyWithObjectId"
                                                                        )
                                                                        .build()
                                                                )
                                                                .filterBranchOperator(
                                                                    "filterBranchOperator"
                                                                )
                                                                .filterBranchType(
                                                                    PublicUnifiedEventsFilterBranch
                                                                        .FilterBranchType
                                                                        .UNIFIED_EVENTS
                                                                )
                                                                .addFilter(
                                                                    PublicPropertyFilter.builder()
                                                                        .filterType(
                                                                            PublicPropertyFilter
                                                                                .FilterType
                                                                                .PROPERTY
                                                                        )
                                                                        .operation(
                                                                            PublicBoolPropertyOperation
                                                                                .builder()
                                                                                .includeObjectsWithNoValueSet(
                                                                                    true
                                                                                )
                                                                                .operationType(
                                                                                    PublicBoolPropertyOperation
                                                                                        .OperationType
                                                                                        .BOOL
                                                                                )
                                                                                .operator(
                                                                                    "operator"
                                                                                )
                                                                                .value(true)
                                                                                .build()
                                                                        )
                                                                        .property("property")
                                                                        .build()
                                                                )
                                                                .operator(
                                                                    PublicUnifiedEventsFilterBranch
                                                                        .Operator
                                                                        .HAS_COMPLETED
                                                                )
                                                                .coalescingRefineBy(
                                                                    PublicNumOccurrencesRefineBy
                                                                        .builder()
                                                                        .type(
                                                                            PublicNumOccurrencesRefineBy
                                                                                .Type
                                                                                .NUM_OCCURRENCES
                                                                        )
                                                                        .maxOccurrences(0)
                                                                        .minOccurrences(0)
                                                                        .build()
                                                                )
                                                                .build()
                                                        )
                                                        .filterBranchOperator(
                                                            "filterBranchOperator"
                                                        )
                                                        .filterBranchType(
                                                            PublicRestrictedFilterBranch
                                                                .FilterBranchType
                                                                .RESTRICTED
                                                        )
                                                        .addFilter(
                                                            PublicPropertyFilter.builder()
                                                                .filterType(
                                                                    PublicPropertyFilter.FilterType
                                                                        .PROPERTY
                                                                )
                                                                .operation(
                                                                    PublicBoolPropertyOperation
                                                                        .builder()
                                                                        .includeObjectsWithNoValueSet(
                                                                            true
                                                                        )
                                                                        .operationType(
                                                                            PublicBoolPropertyOperation
                                                                                .OperationType
                                                                                .BOOL
                                                                        )
                                                                        .operator("operator")
                                                                        .value(true)
                                                                        .build()
                                                                )
                                                                .property("property")
                                                                .build()
                                                        )
                                                        .build()
                                                )
                                                .filterBranchOperator("filterBranchOperator")
                                                .filterBranchType(
                                                    PublicNotAnyFilterBranch.FilterBranchType
                                                        .NOT_ANY
                                                )
                                                .addFilter(
                                                    PublicPropertyFilter.builder()
                                                        .filterType(
                                                            PublicPropertyFilter.FilterType.PROPERTY
                                                        )
                                                        .operation(
                                                            PublicBoolPropertyOperation.builder()
                                                                .includeObjectsWithNoValueSet(true)
                                                                .operationType(
                                                                    PublicBoolPropertyOperation
                                                                        .OperationType
                                                                        .BOOL
                                                                )
                                                                .operator("operator")
                                                                .value(true)
                                                                .build()
                                                        )
                                                        .property("property")
                                                        .build()
                                                )
                                                .build()
                                        )
                                        .filterBranchOperator("filterBranchOperator")
                                        .filterBranchType(
                                            PublicNotAllFilterBranch.FilterBranchType.NOT_ALL
                                        )
                                        .addFilter(
                                            PublicPropertyFilter.builder()
                                                .filterType(
                                                    PublicPropertyFilter.FilterType.PROPERTY
                                                )
                                                .operation(
                                                    PublicBoolPropertyOperation.builder()
                                                        .includeObjectsWithNoValueSet(true)
                                                        .operationType(
                                                            PublicBoolPropertyOperation
                                                                .OperationType
                                                                .BOOL
                                                        )
                                                        .operator("operator")
                                                        .value(true)
                                                        .build()
                                                )
                                                .property("property")
                                                .build()
                                        )
                                        .build()
                                )
                                .filterBranchOperator("filterBranchOperator")
                                .filterBranchType(PublicAndFilterBranch.FilterBranchType.AND)
                                .addFilter(
                                    PublicPropertyFilter.builder()
                                        .filterType(PublicPropertyFilter.FilterType.PROPERTY)
                                        .operation(
                                            PublicBoolPropertyOperation.builder()
                                                .includeObjectsWithNoValueSet(true)
                                                .operationType(
                                                    PublicBoolPropertyOperation.OperationType.BOOL
                                                )
                                                .operator("operator")
                                                .value(true)
                                                .build()
                                        )
                                        .property("property")
                                        .build()
                                )
                                .build()
                        )
                        .filterBranchOperator("filterBranchOperator")
                        .filterBranchType(PublicOrFilterBranch.FilterBranchType.OR)
                        .addFilter(
                            PublicPropertyFilter.builder()
                                .filterType(PublicPropertyFilter.FilterType.PROPERTY)
                                .operation(
                                    PublicBoolPropertyOperation.builder()
                                        .includeObjectsWithNoValueSet(true)
                                        .operationType(
                                            PublicBoolPropertyOperation.OperationType.BOOL
                                        )
                                        .operator("operator")
                                        .value(true)
                                        .build()
                                )
                                .property("property")
                                .build()
                        )
                        .build()
                )
            )
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val apiListBranch =
            ApiListBranch.builder()
                .branchName("Branch name")
                .connection(
                    ApiConnection.builder()
                        .edgeType("edgeType")
                        .nextActionId("nextActionId")
                        .build()
                )
                .filterBranch(
                    PublicOrFilterBranch.builder()
                        .addFilterBranch(
                            PublicAndFilterBranch.builder()
                                .addFilterBranch(
                                    PublicNotAllFilterBranch.builder()
                                        .addFilterBranch(
                                            PublicNotAnyFilterBranch.builder()
                                                .addFilterBranch(
                                                    PublicRestrictedFilterBranch.builder()
                                                        .addFilterBranch(
                                                            PublicUnifiedEventsFilterBranch
                                                                .builder()
                                                                .eventTypeId("eventTypeId")
                                                                .addFilterBranch(
                                                                    PublicPropertyAssociationFilterBranch
                                                                        .builder()
                                                                        .addFilterBranch(
                                                                            PublicAssociationFilterBranch
                                                                                .builder()
                                                                                .associationCategory(
                                                                                    "associationCategory"
                                                                                )
                                                                                .associationTypeId(
                                                                                    0
                                                                                )
                                                                                .addFilterBranch(
                                                                                    PublicOrFilterBranch
                                                                                        .builder()
                                                                                        .filterBranches(
                                                                                            listOf()
                                                                                        )
                                                                                        .filterBranchOperator(
                                                                                            "filterBranchOperator"
                                                                                        )
                                                                                        .filterBranchType(
                                                                                            PublicOrFilterBranch
                                                                                                .FilterBranchType
                                                                                                .OR
                                                                                        )
                                                                                        .addFilter(
                                                                                            PublicPropertyFilter
                                                                                                .builder()
                                                                                                .filterType(
                                                                                                    PublicPropertyFilter
                                                                                                        .FilterType
                                                                                                        .PROPERTY
                                                                                                )
                                                                                                .operation(
                                                                                                    PublicBoolPropertyOperation
                                                                                                        .builder()
                                                                                                        .includeObjectsWithNoValueSet(
                                                                                                            true
                                                                                                        )
                                                                                                        .operationType(
                                                                                                            PublicBoolPropertyOperation
                                                                                                                .OperationType
                                                                                                                .BOOL
                                                                                                        )
                                                                                                        .operator(
                                                                                                            "operator"
                                                                                                        )
                                                                                                        .value(
                                                                                                            true
                                                                                                        )
                                                                                                        .build()
                                                                                                )
                                                                                                .property(
                                                                                                    "property"
                                                                                                )
                                                                                                .build()
                                                                                        )
                                                                                        .build()
                                                                                )
                                                                                .filterBranchOperator(
                                                                                    "filterBranchOperator"
                                                                                )
                                                                                .filterBranchType(
                                                                                    PublicAssociationFilterBranch
                                                                                        .FilterBranchType
                                                                                        .ASSOCIATION
                                                                                )
                                                                                .addFilter(
                                                                                    PublicPropertyFilter
                                                                                        .builder()
                                                                                        .filterType(
                                                                                            PublicPropertyFilter
                                                                                                .FilterType
                                                                                                .PROPERTY
                                                                                        )
                                                                                        .operation(
                                                                                            PublicBoolPropertyOperation
                                                                                                .builder()
                                                                                                .includeObjectsWithNoValueSet(
                                                                                                    true
                                                                                                )
                                                                                                .operationType(
                                                                                                    PublicBoolPropertyOperation
                                                                                                        .OperationType
                                                                                                        .BOOL
                                                                                                )
                                                                                                .operator(
                                                                                                    "operator"
                                                                                                )
                                                                                                .value(
                                                                                                    true
                                                                                                )
                                                                                                .build()
                                                                                        )
                                                                                        .property(
                                                                                            "property"
                                                                                        )
                                                                                        .build()
                                                                                )
                                                                                .objectTypeId(
                                                                                    "objectTypeId"
                                                                                )
                                                                                .operator(
                                                                                    "operator"
                                                                                )
                                                                                .build()
                                                                        )
                                                                        .filterBranchOperator(
                                                                            "filterBranchOperator"
                                                                        )
                                                                        .filterBranchType(
                                                                            PublicPropertyAssociationFilterBranch
                                                                                .FilterBranchType
                                                                                .PROPERTY_ASSOCIATION
                                                                        )
                                                                        .addFilter(
                                                                            PublicPropertyFilter
                                                                                .builder()
                                                                                .filterType(
                                                                                    PublicPropertyFilter
                                                                                        .FilterType
                                                                                        .PROPERTY
                                                                                )
                                                                                .operation(
                                                                                    PublicBoolPropertyOperation
                                                                                        .builder()
                                                                                        .includeObjectsWithNoValueSet(
                                                                                            true
                                                                                        )
                                                                                        .operationType(
                                                                                            PublicBoolPropertyOperation
                                                                                                .OperationType
                                                                                                .BOOL
                                                                                        )
                                                                                        .operator(
                                                                                            "operator"
                                                                                        )
                                                                                        .value(true)
                                                                                        .build()
                                                                                )
                                                                                .property(
                                                                                    "property"
                                                                                )
                                                                                .build()
                                                                        )
                                                                        .objectTypeId(
                                                                            "objectTypeId"
                                                                        )
                                                                        .operator("operator")
                                                                        .propertyWithObjectId(
                                                                            "propertyWithObjectId"
                                                                        )
                                                                        .build()
                                                                )
                                                                .filterBranchOperator(
                                                                    "filterBranchOperator"
                                                                )
                                                                .filterBranchType(
                                                                    PublicUnifiedEventsFilterBranch
                                                                        .FilterBranchType
                                                                        .UNIFIED_EVENTS
                                                                )
                                                                .addFilter(
                                                                    PublicPropertyFilter.builder()
                                                                        .filterType(
                                                                            PublicPropertyFilter
                                                                                .FilterType
                                                                                .PROPERTY
                                                                        )
                                                                        .operation(
                                                                            PublicBoolPropertyOperation
                                                                                .builder()
                                                                                .includeObjectsWithNoValueSet(
                                                                                    true
                                                                                )
                                                                                .operationType(
                                                                                    PublicBoolPropertyOperation
                                                                                        .OperationType
                                                                                        .BOOL
                                                                                )
                                                                                .operator(
                                                                                    "operator"
                                                                                )
                                                                                .value(true)
                                                                                .build()
                                                                        )
                                                                        .property("property")
                                                                        .build()
                                                                )
                                                                .operator(
                                                                    PublicUnifiedEventsFilterBranch
                                                                        .Operator
                                                                        .HAS_COMPLETED
                                                                )
                                                                .coalescingRefineBy(
                                                                    PublicNumOccurrencesRefineBy
                                                                        .builder()
                                                                        .type(
                                                                            PublicNumOccurrencesRefineBy
                                                                                .Type
                                                                                .NUM_OCCURRENCES
                                                                        )
                                                                        .maxOccurrences(0)
                                                                        .minOccurrences(0)
                                                                        .build()
                                                                )
                                                                .build()
                                                        )
                                                        .filterBranchOperator(
                                                            "filterBranchOperator"
                                                        )
                                                        .filterBranchType(
                                                            PublicRestrictedFilterBranch
                                                                .FilterBranchType
                                                                .RESTRICTED
                                                        )
                                                        .addFilter(
                                                            PublicPropertyFilter.builder()
                                                                .filterType(
                                                                    PublicPropertyFilter.FilterType
                                                                        .PROPERTY
                                                                )
                                                                .operation(
                                                                    PublicBoolPropertyOperation
                                                                        .builder()
                                                                        .includeObjectsWithNoValueSet(
                                                                            true
                                                                        )
                                                                        .operationType(
                                                                            PublicBoolPropertyOperation
                                                                                .OperationType
                                                                                .BOOL
                                                                        )
                                                                        .operator("operator")
                                                                        .value(true)
                                                                        .build()
                                                                )
                                                                .property("property")
                                                                .build()
                                                        )
                                                        .build()
                                                )
                                                .filterBranchOperator("filterBranchOperator")
                                                .filterBranchType(
                                                    PublicNotAnyFilterBranch.FilterBranchType
                                                        .NOT_ANY
                                                )
                                                .addFilter(
                                                    PublicPropertyFilter.builder()
                                                        .filterType(
                                                            PublicPropertyFilter.FilterType.PROPERTY
                                                        )
                                                        .operation(
                                                            PublicBoolPropertyOperation.builder()
                                                                .includeObjectsWithNoValueSet(true)
                                                                .operationType(
                                                                    PublicBoolPropertyOperation
                                                                        .OperationType
                                                                        .BOOL
                                                                )
                                                                .operator("operator")
                                                                .value(true)
                                                                .build()
                                                        )
                                                        .property("property")
                                                        .build()
                                                )
                                                .build()
                                        )
                                        .filterBranchOperator("filterBranchOperator")
                                        .filterBranchType(
                                            PublicNotAllFilterBranch.FilterBranchType.NOT_ALL
                                        )
                                        .addFilter(
                                            PublicPropertyFilter.builder()
                                                .filterType(
                                                    PublicPropertyFilter.FilterType.PROPERTY
                                                )
                                                .operation(
                                                    PublicBoolPropertyOperation.builder()
                                                        .includeObjectsWithNoValueSet(true)
                                                        .operationType(
                                                            PublicBoolPropertyOperation
                                                                .OperationType
                                                                .BOOL
                                                        )
                                                        .operator("operator")
                                                        .value(true)
                                                        .build()
                                                )
                                                .property("property")
                                                .build()
                                        )
                                        .build()
                                )
                                .filterBranchOperator("filterBranchOperator")
                                .filterBranchType(PublicAndFilterBranch.FilterBranchType.AND)
                                .addFilter(
                                    PublicPropertyFilter.builder()
                                        .filterType(PublicPropertyFilter.FilterType.PROPERTY)
                                        .operation(
                                            PublicBoolPropertyOperation.builder()
                                                .includeObjectsWithNoValueSet(true)
                                                .operationType(
                                                    PublicBoolPropertyOperation.OperationType.BOOL
                                                )
                                                .operator("operator")
                                                .value(true)
                                                .build()
                                        )
                                        .property("property")
                                        .build()
                                )
                                .build()
                        )
                        .filterBranchOperator("filterBranchOperator")
                        .filterBranchType(PublicOrFilterBranch.FilterBranchType.OR)
                        .addFilter(
                            PublicPropertyFilter.builder()
                                .filterType(PublicPropertyFilter.FilterType.PROPERTY)
                                .operation(
                                    PublicBoolPropertyOperation.builder()
                                        .includeObjectsWithNoValueSet(true)
                                        .operationType(
                                            PublicBoolPropertyOperation.OperationType.BOOL
                                        )
                                        .operator("operator")
                                        .value(true)
                                        .build()
                                )
                                .property("property")
                                .build()
                        )
                        .build()
                )
                .build()

        val roundtrippedApiListBranch =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(apiListBranch),
                jacksonTypeRef<ApiListBranch>(),
            )

        assertThat(roundtrippedApiListBranch).isEqualTo(apiListBranch)
    }
}
