// File generated from our OpenAPI spec by Stainless.

package com.hubspot_sdk.api.services.blocking.marketing

import com.hubspot_sdk.api.TestServerExtension
import com.hubspot_sdk.api.client.okhttp.HubspotOkHttpClient
import com.hubspot_sdk.api.core.JsonValue
import com.hubspot_sdk.api.models.marketing.PublicSingleSendEmail
import com.hubspot_sdk.api.models.marketing.PublicSingleSendRequestEgg
import org.junit.jupiter.api.Disabled
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.extension.ExtendWith

@ExtendWith(TestServerExtension::class)
internal class SingleSendServiceTest {

    @Disabled("Prism tests are disabled")
    @Test
    fun send() {
        val client =
            HubspotOkHttpClient.builder()
                .baseUrl(TestServerExtension.BASE_URL)
                .accessToken("pat-na1-xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx")
                .build()
        val singleSendService = client.marketing().singleSend()

        val emailSendStatusView =
            singleSendService.send(
                PublicSingleSendRequestEgg.builder()
                    .emailId(0L)
                    .message(
                        PublicSingleSendEmail.builder()
                            .to("to")
                            .addBcc("string")
                            .addCc("string")
                            .from("from")
                            .addReplyTo("string")
                            .sendId("sendId")
                            .build()
                    )
                    .contactProperties(
                        PublicSingleSendRequestEgg.ContactProperties.builder()
                            .putAdditionalProperty("0", JsonValue.from("{"))
                            .putAdditionalProperty("1", JsonValue.from("\""))
                            .putAdditionalProperty("2", JsonValue.from("l"))
                            .putAdditionalProperty("3", JsonValue.from("a"))
                            .putAdditionalProperty("4", JsonValue.from("s"))
                            .putAdditionalProperty("5", JsonValue.from("t"))
                            .putAdditionalProperty("6", JsonValue.from("n"))
                            .putAdditionalProperty("7", JsonValue.from("a"))
                            .putAdditionalProperty("8", JsonValue.from("m"))
                            .putAdditionalProperty("9", JsonValue.from("e"))
                            .putAdditionalProperty("10", JsonValue.from("\""))
                            .putAdditionalProperty("11", JsonValue.from(":"))
                            .putAdditionalProperty("12", JsonValue.from("\""))
                            .putAdditionalProperty("13", JsonValue.from("d"))
                            .putAdditionalProperty("14", JsonValue.from("o"))
                            .putAdditionalProperty("15", JsonValue.from("e"))
                            .putAdditionalProperty("16", JsonValue.from("\""))
                            .putAdditionalProperty("17", JsonValue.from(","))
                            .putAdditionalProperty("18", JsonValue.from("\""))
                            .putAdditionalProperty("19", JsonValue.from("f"))
                            .putAdditionalProperty("20", JsonValue.from("i"))
                            .putAdditionalProperty("21", JsonValue.from("r"))
                            .putAdditionalProperty("22", JsonValue.from("s"))
                            .putAdditionalProperty("23", JsonValue.from("t"))
                            .putAdditionalProperty("24", JsonValue.from("n"))
                            .putAdditionalProperty("25", JsonValue.from("a"))
                            .putAdditionalProperty("26", JsonValue.from("m"))
                            .putAdditionalProperty("27", JsonValue.from("e"))
                            .putAdditionalProperty("28", JsonValue.from("\""))
                            .putAdditionalProperty("29", JsonValue.from(":"))
                            .putAdditionalProperty("30", JsonValue.from("\""))
                            .putAdditionalProperty("31", JsonValue.from("j"))
                            .putAdditionalProperty("32", JsonValue.from("o"))
                            .putAdditionalProperty("33", JsonValue.from("h"))
                            .putAdditionalProperty("34", JsonValue.from("n"))
                            .putAdditionalProperty("35", JsonValue.from("\""))
                            .putAdditionalProperty("36", JsonValue.from("}"))
                            .build()
                    )
                    .customProperties(
                        PublicSingleSendRequestEgg.CustomProperties.builder()
                            .putAdditionalProperty("0", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("1", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("2", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("3", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("4", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("5", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("6", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("7", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("8", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("9", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("10", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("11", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("12", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("13", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("14", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("15", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("16", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("17", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("18", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("19", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("20", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("21", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("22", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("23", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("24", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("25", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("26", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("27", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("28", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("29", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("30", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("31", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("32", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("33", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("34", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("35", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("36", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("37", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("38", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("39", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("40", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("41", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("42", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("43", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("44", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("45", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("46", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("47", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("48", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("49", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("50", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("51", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("52", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("53", JsonValue.from(mapOf<String, Any>()))
                            .putAdditionalProperty("54", JsonValue.from(mapOf<String, Any>()))
                            .build()
                    )
                    .build()
            )

        emailSendStatusView.validate()
    }
}
