// File generated from our OpenAPI spec by Stainless.

package com.hubspot_sdk.api.models.crm.objects.schemas

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.hubspot_sdk.api.core.jsonMapper
import com.hubspot_sdk.api.models.ObjectTypeDefinitionLabels
import com.hubspot_sdk.api.models.Option
import com.hubspot_sdk.api.models.Property
import com.hubspot_sdk.api.models.PropertyModificationMetadata
import com.hubspot_sdk.api.models.events.eventdefinitions.AssociationDefinition
import java.time.OffsetDateTime
import kotlin.jvm.optionals.getOrNull
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class ObjectSchemaTest {

    @Test
    fun create() {
        val objectSchema =
            ObjectSchema.builder()
                .id("123456")
                .addAssociation(
                    AssociationDefinition.builder()
                        .id(0)
                        .allowsCustomLabels(false)
                        .cardinality(AssociationDefinition.Cardinality.ONE_TO_ONE)
                        .category(AssociationDefinition.Category.HUBSPOT_DEFINED)
                        .fromObjectTypeId("2-123456")
                        .hasAllAssociatedObjects(false)
                        .hasCascadingDeletes(false)
                        .hasUserEnforcedMaxFromObjectIds(false)
                        .hasUserEnforcedMaxToObjectIds(false)
                        .hidden(false)
                        .inverseAllowsCustomLabels(false)
                        .inverseCardinality(AssociationDefinition.InverseCardinality.ONE_TO_ONE)
                        .inverseHasAllAssociatedObjects(false)
                        .inverseId(0)
                        .inverseName("")
                        .isInversePrimary(false)
                        .isPrimary(false)
                        .maxFromObjectIds(0)
                        .maxToObjectIds(0)
                        .name("my_object_to_contact")
                        .portalUniqueIdentifier("")
                        .toObjectTypeId("0-1")
                        .fromObjectType(AssociationDefinition.FromObjectType.CONTACT)
                        .inverseLabel("")
                        .label("")
                        .toObjectType(AssociationDefinition.ToObjectType.CONTACT)
                        .build()
                )
                .labels(
                    ObjectTypeDefinitionLabels.builder()
                        .plural("My objects")
                        .singular("My object")
                        .build()
                )
                .name("my_object")
                .addProperty(
                    Property.builder()
                        .description("")
                        .fieldType("text")
                        .groupName("my_object_information")
                        .label("My object property")
                        .name("my_object_property")
                        .addOption(
                            Option.builder()
                                .hidden(false)
                                .label("Option A")
                                .value("A")
                                .description("Choice number one")
                                .displayOrder(1)
                                .build()
                        )
                        .addOption(
                            Option.builder()
                                .hidden(false)
                                .label("Option B")
                                .value("B")
                                .description("Choice number two")
                                .displayOrder(2)
                                .build()
                        )
                        .type("string")
                        .archived(false)
                        .archivedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .calculated(false)
                        .calculationFormula("")
                        .createdAt(OffsetDateTime.parse("2020-02-20T18:07:11.802Z"))
                        .createdUserId("")
                        .dataSensitivity(Property.DataSensitivity.NON_SENSITIVE)
                        .displayOrder(-1)
                        .externalOptions(false)
                        .formField(false)
                        .hasUniqueValue(false)
                        .hidden(false)
                        .hubspotDefined(false)
                        .modificationMetadata(
                            PropertyModificationMetadata.builder()
                                .archivable(true)
                                .readOnlyDefinition(false)
                                .readOnlyValue(false)
                                .readOnlyOptions(false)
                                .build()
                        )
                        .referencedObjectType("")
                        .addSensitiveDataCategory("string")
                        .showCurrencySymbol(false)
                        .updatedAt(OffsetDateTime.parse("2020-02-20T18:07:11.802Z"))
                        .updatedUserId("updatedUserId")
                        .build()
                )
                .addRequiredProperty("my_object_property")
                .archived(true)
                .createdAt(OffsetDateTime.parse("2020-02-20T18:07:11.390Z"))
                .createdByUserId(0)
                .description("description")
                .fullyQualifiedName("p7878787_my_object\"")
                .objectTypeId("objectTypeId")
                .primaryDisplayProperty("my_object_property")
                .addSearchableProperty("my_object_property")
                .addSecondaryDisplayProperty("string")
                .updatedAt(OffsetDateTime.parse("2020-02-20T18:09:07.555Z"))
                .updatedByUserId(0)
                .build()

        assertThat(objectSchema.id()).isEqualTo("123456")
        assertThat(objectSchema.associations())
            .containsExactly(
                AssociationDefinition.builder()
                    .id(0)
                    .allowsCustomLabels(false)
                    .cardinality(AssociationDefinition.Cardinality.ONE_TO_ONE)
                    .category(AssociationDefinition.Category.HUBSPOT_DEFINED)
                    .fromObjectTypeId("2-123456")
                    .hasAllAssociatedObjects(false)
                    .hasCascadingDeletes(false)
                    .hasUserEnforcedMaxFromObjectIds(false)
                    .hasUserEnforcedMaxToObjectIds(false)
                    .hidden(false)
                    .inverseAllowsCustomLabels(false)
                    .inverseCardinality(AssociationDefinition.InverseCardinality.ONE_TO_ONE)
                    .inverseHasAllAssociatedObjects(false)
                    .inverseId(0)
                    .inverseName("")
                    .isInversePrimary(false)
                    .isPrimary(false)
                    .maxFromObjectIds(0)
                    .maxToObjectIds(0)
                    .name("my_object_to_contact")
                    .portalUniqueIdentifier("")
                    .toObjectTypeId("0-1")
                    .fromObjectType(AssociationDefinition.FromObjectType.CONTACT)
                    .inverseLabel("")
                    .label("")
                    .toObjectType(AssociationDefinition.ToObjectType.CONTACT)
                    .build()
            )
        assertThat(objectSchema.labels())
            .isEqualTo(
                ObjectTypeDefinitionLabels.builder()
                    .plural("My objects")
                    .singular("My object")
                    .build()
            )
        assertThat(objectSchema.name()).isEqualTo("my_object")
        assertThat(objectSchema.properties())
            .containsExactly(
                Property.builder()
                    .description("")
                    .fieldType("text")
                    .groupName("my_object_information")
                    .label("My object property")
                    .name("my_object_property")
                    .addOption(
                        Option.builder()
                            .hidden(false)
                            .label("Option A")
                            .value("A")
                            .description("Choice number one")
                            .displayOrder(1)
                            .build()
                    )
                    .addOption(
                        Option.builder()
                            .hidden(false)
                            .label("Option B")
                            .value("B")
                            .description("Choice number two")
                            .displayOrder(2)
                            .build()
                    )
                    .type("string")
                    .archived(false)
                    .archivedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .calculated(false)
                    .calculationFormula("")
                    .createdAt(OffsetDateTime.parse("2020-02-20T18:07:11.802Z"))
                    .createdUserId("")
                    .dataSensitivity(Property.DataSensitivity.NON_SENSITIVE)
                    .displayOrder(-1)
                    .externalOptions(false)
                    .formField(false)
                    .hasUniqueValue(false)
                    .hidden(false)
                    .hubspotDefined(false)
                    .modificationMetadata(
                        PropertyModificationMetadata.builder()
                            .archivable(true)
                            .readOnlyDefinition(false)
                            .readOnlyValue(false)
                            .readOnlyOptions(false)
                            .build()
                    )
                    .referencedObjectType("")
                    .addSensitiveDataCategory("string")
                    .showCurrencySymbol(false)
                    .updatedAt(OffsetDateTime.parse("2020-02-20T18:07:11.802Z"))
                    .updatedUserId("updatedUserId")
                    .build()
            )
        assertThat(objectSchema.requiredProperties()).containsExactly("my_object_property")
        assertThat(objectSchema.archived()).contains(true)
        assertThat(objectSchema.createdAt())
            .contains(OffsetDateTime.parse("2020-02-20T18:07:11.390Z"))
        assertThat(objectSchema.createdByUserId()).contains(0)
        assertThat(objectSchema.description()).contains("description")
        assertThat(objectSchema.fullyQualifiedName()).contains("p7878787_my_object\"")
        assertThat(objectSchema.objectTypeId()).contains("objectTypeId")
        assertThat(objectSchema.primaryDisplayProperty()).contains("my_object_property")
        assertThat(objectSchema.searchableProperties().getOrNull())
            .containsExactly("my_object_property")
        assertThat(objectSchema.secondaryDisplayProperties().getOrNull()).containsExactly("string")
        assertThat(objectSchema.updatedAt())
            .contains(OffsetDateTime.parse("2020-02-20T18:09:07.555Z"))
        assertThat(objectSchema.updatedByUserId()).contains(0)
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val objectSchema =
            ObjectSchema.builder()
                .id("123456")
                .addAssociation(
                    AssociationDefinition.builder()
                        .id(0)
                        .allowsCustomLabels(false)
                        .cardinality(AssociationDefinition.Cardinality.ONE_TO_ONE)
                        .category(AssociationDefinition.Category.HUBSPOT_DEFINED)
                        .fromObjectTypeId("2-123456")
                        .hasAllAssociatedObjects(false)
                        .hasCascadingDeletes(false)
                        .hasUserEnforcedMaxFromObjectIds(false)
                        .hasUserEnforcedMaxToObjectIds(false)
                        .hidden(false)
                        .inverseAllowsCustomLabels(false)
                        .inverseCardinality(AssociationDefinition.InverseCardinality.ONE_TO_ONE)
                        .inverseHasAllAssociatedObjects(false)
                        .inverseId(0)
                        .inverseName("")
                        .isInversePrimary(false)
                        .isPrimary(false)
                        .maxFromObjectIds(0)
                        .maxToObjectIds(0)
                        .name("my_object_to_contact")
                        .portalUniqueIdentifier("")
                        .toObjectTypeId("0-1")
                        .fromObjectType(AssociationDefinition.FromObjectType.CONTACT)
                        .inverseLabel("")
                        .label("")
                        .toObjectType(AssociationDefinition.ToObjectType.CONTACT)
                        .build()
                )
                .labels(
                    ObjectTypeDefinitionLabels.builder()
                        .plural("My objects")
                        .singular("My object")
                        .build()
                )
                .name("my_object")
                .addProperty(
                    Property.builder()
                        .description("")
                        .fieldType("text")
                        .groupName("my_object_information")
                        .label("My object property")
                        .name("my_object_property")
                        .addOption(
                            Option.builder()
                                .hidden(false)
                                .label("Option A")
                                .value("A")
                                .description("Choice number one")
                                .displayOrder(1)
                                .build()
                        )
                        .addOption(
                            Option.builder()
                                .hidden(false)
                                .label("Option B")
                                .value("B")
                                .description("Choice number two")
                                .displayOrder(2)
                                .build()
                        )
                        .type("string")
                        .archived(false)
                        .archivedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .calculated(false)
                        .calculationFormula("")
                        .createdAt(OffsetDateTime.parse("2020-02-20T18:07:11.802Z"))
                        .createdUserId("")
                        .dataSensitivity(Property.DataSensitivity.NON_SENSITIVE)
                        .displayOrder(-1)
                        .externalOptions(false)
                        .formField(false)
                        .hasUniqueValue(false)
                        .hidden(false)
                        .hubspotDefined(false)
                        .modificationMetadata(
                            PropertyModificationMetadata.builder()
                                .archivable(true)
                                .readOnlyDefinition(false)
                                .readOnlyValue(false)
                                .readOnlyOptions(false)
                                .build()
                        )
                        .referencedObjectType("")
                        .addSensitiveDataCategory("string")
                        .showCurrencySymbol(false)
                        .updatedAt(OffsetDateTime.parse("2020-02-20T18:07:11.802Z"))
                        .updatedUserId("updatedUserId")
                        .build()
                )
                .addRequiredProperty("my_object_property")
                .archived(true)
                .createdAt(OffsetDateTime.parse("2020-02-20T18:07:11.390Z"))
                .createdByUserId(0)
                .description("description")
                .fullyQualifiedName("p7878787_my_object\"")
                .objectTypeId("objectTypeId")
                .primaryDisplayProperty("my_object_property")
                .addSearchableProperty("my_object_property")
                .addSecondaryDisplayProperty("string")
                .updatedAt(OffsetDateTime.parse("2020-02-20T18:09:07.555Z"))
                .updatedByUserId(0)
                .build()

        val roundtrippedObjectSchema =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(objectSchema),
                jacksonTypeRef<ObjectSchema>(),
            )

        assertThat(roundtrippedObjectSchema).isEqualTo(objectSchema)
    }
}
