// File generated from our OpenAPI spec by Stainless.

package com.hubspot_sdk.api.models.crm.objects.schemas

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.hubspot_sdk.api.core.jsonMapper
import com.hubspot_sdk.api.models.ObjectTypeDefinitionLabels
import com.hubspot_sdk.api.models.Option
import com.hubspot_sdk.api.models.Property
import com.hubspot_sdk.api.models.PropertyModificationMetadata
import com.hubspot_sdk.api.models.events.eventdefinitions.AssociationDefinition
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class SchemaListResponseTest {

    @Test
    fun create() {
        val schemaListResponse =
            SchemaListResponse.builder()
                .addResult(
                    ObjectSchema.builder()
                        .id("123456")
                        .addAssociation(
                            AssociationDefinition.builder()
                                .id(0)
                                .allowsCustomLabels(true)
                                .cardinality(AssociationDefinition.Cardinality.ONE_TO_MANY)
                                .category(AssociationDefinition.Category.HUBSPOT_DEFINED)
                                .fromObjectTypeId("2-123456")
                                .hasAllAssociatedObjects(true)
                                .hasCascadingDeletes(true)
                                .hasUserEnforcedMaxFromObjectIds(true)
                                .hasUserEnforcedMaxToObjectIds(true)
                                .hidden(true)
                                .inverseAllowsCustomLabels(true)
                                .inverseCardinality(
                                    AssociationDefinition.InverseCardinality.ONE_TO_MANY
                                )
                                .inverseHasAllAssociatedObjects(true)
                                .inverseId(0)
                                .inverseName("inverseName")
                                .isInversePrimary(true)
                                .isPrimary(true)
                                .maxFromObjectIds(0)
                                .maxToObjectIds(0)
                                .name("my_object_to_contact")
                                .portalUniqueIdentifier("portalUniqueIdentifier")
                                .toObjectTypeId("0-1")
                                .fromObjectType(AssociationDefinition.FromObjectType.ABANDONED_CART)
                                .inverseLabel("inverseLabel")
                                .label("label")
                                .toObjectType(AssociationDefinition.ToObjectType.ABANDONED_CART)
                                .build()
                        )
                        .labels(
                            ObjectTypeDefinitionLabels.builder()
                                .plural("My objects")
                                .singular("My object")
                                .build()
                        )
                        .name("my_object")
                        .addProperty(
                            Property.builder()
                                .description("description")
                                .fieldType("text")
                                .groupName("my_object_information")
                                .label("My object property")
                                .name("my_object_property")
                                .addOption(
                                    Option.builder()
                                        .hidden(false)
                                        .label("Option A")
                                        .value("A")
                                        .description("Choice number one")
                                        .displayOrder(1)
                                        .build()
                                )
                                .addOption(
                                    Option.builder()
                                        .hidden(false)
                                        .label("Option B")
                                        .value("B")
                                        .description("Choice number two")
                                        .displayOrder(2)
                                        .build()
                                )
                                .type("string")
                                .archived(false)
                                .archivedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .calculated(false)
                                .calculationFormula("calculationFormula")
                                .createdAt(OffsetDateTime.parse("2020-02-20T18:07:11.802Z"))
                                .createdUserId("createdUserId")
                                .dataSensitivity(Property.DataSensitivity.HIGHLY_SENSITIVE)
                                .displayOrder(-1)
                                .externalOptions(false)
                                .formField(true)
                                .hasUniqueValue(false)
                                .hidden(true)
                                .hubspotDefined(true)
                                .modificationMetadata(
                                    PropertyModificationMetadata.builder()
                                        .archivable(true)
                                        .readOnlyDefinition(false)
                                        .readOnlyValue(false)
                                        .readOnlyOptions(false)
                                        .build()
                                )
                                .referencedObjectType("referencedObjectType")
                                .addSensitiveDataCategory("string")
                                .showCurrencySymbol(true)
                                .updatedAt(OffsetDateTime.parse("2020-02-20T18:07:11.802Z"))
                                .updatedUserId("updatedUserId")
                                .build()
                        )
                        .addRequiredProperty("my_object_property")
                        .archived(true)
                        .createdAt(OffsetDateTime.parse("2020-02-20T18:07:11.390Z"))
                        .createdByUserId(0)
                        .description("description")
                        .fullyQualifiedName("p7878787_my_object\"")
                        .objectTypeId("objectTypeId")
                        .primaryDisplayProperty("my_object_property")
                        .addSearchableProperty("my_object_property")
                        .addSecondaryDisplayProperty("string")
                        .updatedAt(OffsetDateTime.parse("2020-02-20T18:09:07.555Z"))
                        .updatedByUserId(0)
                        .build()
                )
                .build()

        assertThat(schemaListResponse.results())
            .containsExactly(
                ObjectSchema.builder()
                    .id("123456")
                    .addAssociation(
                        AssociationDefinition.builder()
                            .id(0)
                            .allowsCustomLabels(true)
                            .cardinality(AssociationDefinition.Cardinality.ONE_TO_MANY)
                            .category(AssociationDefinition.Category.HUBSPOT_DEFINED)
                            .fromObjectTypeId("2-123456")
                            .hasAllAssociatedObjects(true)
                            .hasCascadingDeletes(true)
                            .hasUserEnforcedMaxFromObjectIds(true)
                            .hasUserEnforcedMaxToObjectIds(true)
                            .hidden(true)
                            .inverseAllowsCustomLabels(true)
                            .inverseCardinality(
                                AssociationDefinition.InverseCardinality.ONE_TO_MANY
                            )
                            .inverseHasAllAssociatedObjects(true)
                            .inverseId(0)
                            .inverseName("inverseName")
                            .isInversePrimary(true)
                            .isPrimary(true)
                            .maxFromObjectIds(0)
                            .maxToObjectIds(0)
                            .name("my_object_to_contact")
                            .portalUniqueIdentifier("portalUniqueIdentifier")
                            .toObjectTypeId("0-1")
                            .fromObjectType(AssociationDefinition.FromObjectType.ABANDONED_CART)
                            .inverseLabel("inverseLabel")
                            .label("label")
                            .toObjectType(AssociationDefinition.ToObjectType.ABANDONED_CART)
                            .build()
                    )
                    .labels(
                        ObjectTypeDefinitionLabels.builder()
                            .plural("My objects")
                            .singular("My object")
                            .build()
                    )
                    .name("my_object")
                    .addProperty(
                        Property.builder()
                            .description("description")
                            .fieldType("text")
                            .groupName("my_object_information")
                            .label("My object property")
                            .name("my_object_property")
                            .addOption(
                                Option.builder()
                                    .hidden(false)
                                    .label("Option A")
                                    .value("A")
                                    .description("Choice number one")
                                    .displayOrder(1)
                                    .build()
                            )
                            .addOption(
                                Option.builder()
                                    .hidden(false)
                                    .label("Option B")
                                    .value("B")
                                    .description("Choice number two")
                                    .displayOrder(2)
                                    .build()
                            )
                            .type("string")
                            .archived(false)
                            .archivedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .calculated(false)
                            .calculationFormula("calculationFormula")
                            .createdAt(OffsetDateTime.parse("2020-02-20T18:07:11.802Z"))
                            .createdUserId("createdUserId")
                            .dataSensitivity(Property.DataSensitivity.HIGHLY_SENSITIVE)
                            .displayOrder(-1)
                            .externalOptions(false)
                            .formField(true)
                            .hasUniqueValue(false)
                            .hidden(true)
                            .hubspotDefined(true)
                            .modificationMetadata(
                                PropertyModificationMetadata.builder()
                                    .archivable(true)
                                    .readOnlyDefinition(false)
                                    .readOnlyValue(false)
                                    .readOnlyOptions(false)
                                    .build()
                            )
                            .referencedObjectType("referencedObjectType")
                            .addSensitiveDataCategory("string")
                            .showCurrencySymbol(true)
                            .updatedAt(OffsetDateTime.parse("2020-02-20T18:07:11.802Z"))
                            .updatedUserId("updatedUserId")
                            .build()
                    )
                    .addRequiredProperty("my_object_property")
                    .archived(true)
                    .createdAt(OffsetDateTime.parse("2020-02-20T18:07:11.390Z"))
                    .createdByUserId(0)
                    .description("description")
                    .fullyQualifiedName("p7878787_my_object\"")
                    .objectTypeId("objectTypeId")
                    .primaryDisplayProperty("my_object_property")
                    .addSearchableProperty("my_object_property")
                    .addSecondaryDisplayProperty("string")
                    .updatedAt(OffsetDateTime.parse("2020-02-20T18:09:07.555Z"))
                    .updatedByUserId(0)
                    .build()
            )
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val schemaListResponse =
            SchemaListResponse.builder()
                .addResult(
                    ObjectSchema.builder()
                        .id("123456")
                        .addAssociation(
                            AssociationDefinition.builder()
                                .id(0)
                                .allowsCustomLabels(true)
                                .cardinality(AssociationDefinition.Cardinality.ONE_TO_MANY)
                                .category(AssociationDefinition.Category.HUBSPOT_DEFINED)
                                .fromObjectTypeId("2-123456")
                                .hasAllAssociatedObjects(true)
                                .hasCascadingDeletes(true)
                                .hasUserEnforcedMaxFromObjectIds(true)
                                .hasUserEnforcedMaxToObjectIds(true)
                                .hidden(true)
                                .inverseAllowsCustomLabels(true)
                                .inverseCardinality(
                                    AssociationDefinition.InverseCardinality.ONE_TO_MANY
                                )
                                .inverseHasAllAssociatedObjects(true)
                                .inverseId(0)
                                .inverseName("inverseName")
                                .isInversePrimary(true)
                                .isPrimary(true)
                                .maxFromObjectIds(0)
                                .maxToObjectIds(0)
                                .name("my_object_to_contact")
                                .portalUniqueIdentifier("portalUniqueIdentifier")
                                .toObjectTypeId("0-1")
                                .fromObjectType(AssociationDefinition.FromObjectType.ABANDONED_CART)
                                .inverseLabel("inverseLabel")
                                .label("label")
                                .toObjectType(AssociationDefinition.ToObjectType.ABANDONED_CART)
                                .build()
                        )
                        .labels(
                            ObjectTypeDefinitionLabels.builder()
                                .plural("My objects")
                                .singular("My object")
                                .build()
                        )
                        .name("my_object")
                        .addProperty(
                            Property.builder()
                                .description("description")
                                .fieldType("text")
                                .groupName("my_object_information")
                                .label("My object property")
                                .name("my_object_property")
                                .addOption(
                                    Option.builder()
                                        .hidden(false)
                                        .label("Option A")
                                        .value("A")
                                        .description("Choice number one")
                                        .displayOrder(1)
                                        .build()
                                )
                                .addOption(
                                    Option.builder()
                                        .hidden(false)
                                        .label("Option B")
                                        .value("B")
                                        .description("Choice number two")
                                        .displayOrder(2)
                                        .build()
                                )
                                .type("string")
                                .archived(false)
                                .archivedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .calculated(false)
                                .calculationFormula("calculationFormula")
                                .createdAt(OffsetDateTime.parse("2020-02-20T18:07:11.802Z"))
                                .createdUserId("createdUserId")
                                .dataSensitivity(Property.DataSensitivity.HIGHLY_SENSITIVE)
                                .displayOrder(-1)
                                .externalOptions(false)
                                .formField(true)
                                .hasUniqueValue(false)
                                .hidden(true)
                                .hubspotDefined(true)
                                .modificationMetadata(
                                    PropertyModificationMetadata.builder()
                                        .archivable(true)
                                        .readOnlyDefinition(false)
                                        .readOnlyValue(false)
                                        .readOnlyOptions(false)
                                        .build()
                                )
                                .referencedObjectType("referencedObjectType")
                                .addSensitiveDataCategory("string")
                                .showCurrencySymbol(true)
                                .updatedAt(OffsetDateTime.parse("2020-02-20T18:07:11.802Z"))
                                .updatedUserId("updatedUserId")
                                .build()
                        )
                        .addRequiredProperty("my_object_property")
                        .archived(true)
                        .createdAt(OffsetDateTime.parse("2020-02-20T18:07:11.390Z"))
                        .createdByUserId(0)
                        .description("description")
                        .fullyQualifiedName("p7878787_my_object\"")
                        .objectTypeId("objectTypeId")
                        .primaryDisplayProperty("my_object_property")
                        .addSearchableProperty("my_object_property")
                        .addSecondaryDisplayProperty("string")
                        .updatedAt(OffsetDateTime.parse("2020-02-20T18:09:07.555Z"))
                        .updatedByUserId(0)
                        .build()
                )
                .build()

        val roundtrippedSchemaListResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(schemaListResponse),
                jacksonTypeRef<SchemaListResponse>(),
            )

        assertThat(roundtrippedSchemaListResponse).isEqualTo(schemaListResponse)
    }
}
