// File generated from our OpenAPI spec by Stainless.

package com.hubspot_sdk.api.models.cms.mediabridge.integratorsettings

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.hubspot_sdk.api.core.JsonValue
import com.hubspot_sdk.api.core.jsonMapper
import com.hubspot_sdk.api.models.AssociationSpec
import com.hubspot_sdk.api.models.Option
import com.hubspot_sdk.api.models.Property
import com.hubspot_sdk.api.models.PropertyModificationMetadata
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class IntegratorSettingGetObjectDefinitionsByMediaTypeResponseTest {

    @Test
    fun create() {
        val integratorSettingGetObjectDefinitionsByMediaTypeResponse =
            IntegratorSettingGetObjectDefinitionsByMediaTypeResponse.builder()
                .objectTypeId("objectTypeId")
                .objectTypeName("objectTypeName")
                .addProperty(
                    IntegratorSettingGetObjectDefinitionsByMediaTypeResponse.Property.builder()
                        .objectTypeId("objectTypeId")
                        .property(
                            Property.builder()
                                .description("")
                                .fieldType("select")
                                .groupName("my_object_information")
                                .label("My object property")
                                .name("my_object_property")
                                .addOption(
                                    Option.builder()
                                        .description("Choice number one")
                                        .displayOrder(1)
                                        .doubleData(0.0)
                                        .hidden(false)
                                        .label("Option A")
                                        .readOnly(false)
                                        .value("A")
                                        .build()
                                )
                                .addOption(
                                    Option.builder()
                                        .description("Choice number two")
                                        .displayOrder(2)
                                        .doubleData(0.0)
                                        .hidden(false)
                                        .label("Option B")
                                        .readOnly(false)
                                        .value("B")
                                        .build()
                                )
                                .type("enumeration")
                                .archived(false)
                                .archivedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .calculated(false)
                                .calculationFormula("")
                                .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .createdUserId("")
                                .dataSensitivity(Property.DataSensitivity.NON_SENSITIVE)
                                .displayOrder(2)
                                .externalOptions(false)
                                .formField(false)
                                .hasUniqueValue(false)
                                .hidden(false)
                                .hubspotDefined(false)
                                .modificationMetadata(
                                    PropertyModificationMetadata.builder()
                                        .archivable(true)
                                        .readOnlyDefinition(false)
                                        .readOnlyValue(false)
                                        .readOnlyOptions(false)
                                        .build()
                                )
                                .referencedObjectType("")
                                .addSensitiveDataCategory("string")
                                .showCurrencySymbol(false)
                                .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .updatedUserId("updatedUserId")
                                .build()
                        )
                        .calculationExpression(
                            IntegratorSettingGetObjectDefinitionsByMediaTypeResponse.Property
                                .CalculationExpression
                                .CmsMediabridgeConstantBoolean
                                .builder()
                                .operator(
                                    IntegratorSettingGetObjectDefinitionsByMediaTypeResponse
                                        .Property
                                        .CalculationExpression
                                        .CmsMediabridgeConstantBoolean
                                        .Operator
                                        .CONSTANT_BOOLEAN
                                )
                                .addInput(JsonValue.from(mapOf<String, Any>()))
                                .propertyName("propertyName")
                                .value(true)
                                .build()
                        )
                        .calculationFormula("calculationFormula")
                        .definitionSource(
                            IntegratorSettingGetObjectDefinitionsByMediaTypeResponse.Property
                                .DefinitionSource
                                .builder()
                                .type(
                                    IntegratorSettingGetObjectDefinitionsByMediaTypeResponse
                                        .Property
                                        .DefinitionSource
                                        .Type
                                        .GLOBAL
                                )
                                .name("name")
                                .build()
                        )
                        .extensionData(
                            IntegratorSettingGetObjectDefinitionsByMediaTypeResponse.Property
                                .ExtensionData
                                .builder()
                                .extensionStatusMap(
                                    IntegratorSettingGetObjectDefinitionsByMediaTypeResponse
                                        .Property
                                        .ExtensionData
                                        .ExtensionStatusMap
                                        .builder()
                                        .putAdditionalProperty("foo", JsonValue.from("string"))
                                        .build()
                                )
                                .addTag("string")
                                .caseChangeTestExtensionData(
                                    IntegratorSettingGetObjectDefinitionsByMediaTypeResponse
                                        .Property
                                        .ExtensionData
                                        .CaseChangeTestExtensionData
                                        .builder()
                                        .mood("mood")
                                        .build()
                                )
                                .optionDecoratorsExtensionData(
                                    IntegratorSettingGetObjectDefinitionsByMediaTypeResponse
                                        .Property
                                        .ExtensionData
                                        .OptionDecoratorsExtensionData
                                        .builder()
                                        .optionDecorators(
                                            IntegratorSettingGetObjectDefinitionsByMediaTypeResponse
                                                .Property
                                                .ExtensionData
                                                .OptionDecoratorsExtensionData
                                                .OptionDecorators
                                                .builder()
                                                .putAdditionalProperty(
                                                    "foo",
                                                    JsonValue.from(mapOf("color" to "color")),
                                                )
                                                .build()
                                        )
                                        .optionDecoratorStyle("optionDecoratorStyle")
                                        .build()
                                )
                                .requiredPropertiesExtensionData(
                                    IntegratorSettingGetObjectDefinitionsByMediaTypeResponse
                                        .Property
                                        .ExtensionData
                                        .RequiredPropertiesExtensionData
                                        .builder()
                                        .isRequiredProperty(true)
                                        .build()
                                )
                                .softRequiredPropertiesExtensionData(
                                    IntegratorSettingGetObjectDefinitionsByMediaTypeResponse
                                        .Property
                                        .ExtensionData
                                        .SoftRequiredPropertiesExtensionData
                                        .builder()
                                        .isSoftRequiredProperty(true)
                                        .build()
                                )
                                .build()
                        )
                        .externalOptionsMetaData(
                            IntegratorSettingGetObjectDefinitionsByMediaTypeResponse.Property
                                .ExternalOptionsMetaData
                                .builder()
                                .filter(
                                    IntegratorSettingGetObjectDefinitionsByMediaTypeResponse
                                        .Property
                                        .ExternalOptionsMetaData
                                        .Filter
                                        .builder()
                                        .includeUnconfirmedUsers(true)
                                        .addPipelineId("string")
                                        .build()
                                )
                                .relatedObjectTypeId("relatedObjectTypeId")
                                .build()
                        )
                        .fulcrumPortalId(0)
                        .fulcrumTimestamp(0L)
                        .janusGroup("janusGroup")
                        .permission(
                            IntegratorSettingGetObjectDefinitionsByMediaTypeResponse.Property
                                .Permission
                                .builder()
                                .accessLevel("accessLevel")
                                .build()
                        )
                        .propertyDefinitionSource(
                            IntegratorSettingGetObjectDefinitionsByMediaTypeResponse.Property
                                .PropertyDefinitionSource
                                .builder()
                                .type("type")
                                .name("name")
                                .build()
                        )
                        .propertyRequirements(
                            IntegratorSettingGetObjectDefinitionsByMediaTypeResponse.Property
                                .PropertyRequirements
                                .builder()
                                .addGate("string")
                                .operator(
                                    IntegratorSettingGetObjectDefinitionsByMediaTypeResponse
                                        .Property
                                        .PropertyRequirements
                                        .Operator
                                        .AND
                                )
                                .addScopeName("string")
                                .addSetting("string")
                                .build()
                        )
                        .rollupExpression(
                            IntegratorSettingGetObjectDefinitionsByMediaTypeResponse.Property
                                .RollupExpression
                                .builder()
                                .addAssociationType(
                                    AssociationSpec.builder()
                                        .associationCategory(
                                            AssociationSpec.AssociationCategory.HUBSPOT_DEFINED
                                        )
                                        .associationTypeId(0)
                                        .build()
                                )
                                .rollupOperator("rollupOperator")
                                .sourceObjectTypeId("sourceObjectTypeId")
                                .sourcePropertyName("sourcePropertyName")
                                .conditionalExpression(
                                    IntegratorSettingGetObjectDefinitionsByMediaTypeResponse
                                        .Property
                                        .RollupExpression
                                        .ConditionalExpression
                                        .CmsMediabridgeConstantBoolean
                                        .builder()
                                        .operator(
                                            IntegratorSettingGetObjectDefinitionsByMediaTypeResponse
                                                .Property
                                                .RollupExpression
                                                .ConditionalExpression
                                                .CmsMediabridgeConstantBoolean
                                                .Operator
                                                .CONSTANT_BOOLEAN
                                        )
                                        .addInput(JsonValue.from(mapOf<String, Any>()))
                                        .propertyName("propertyName")
                                        .value(true)
                                        .build()
                                )
                                .conditionalFormula("conditionalFormula")
                                .emptyRollupValue("emptyRollupValue")
                                .sourceCompareByPropertyName("sourceCompareByPropertyName")
                                .build()
                        )
                        .build()
                )
                .addPropertyGroup(
                    IntegratorSettingGetObjectDefinitionsByMediaTypeResponse.PropertyGroup.builder()
                        .displayName("displayName")
                        .displayOrder(0)
                        .fulcrumPortalId(0)
                        .fulcrumTimestamp(0L)
                        .hubspotDefined(true)
                        .name("name")
                        .build()
                )
                .schema(
                    IntegratorSettingGetObjectDefinitionsByMediaTypeResponse.Schema.builder()
                        .id(0)
                        .allowsSensitiveProperties(true)
                        .createDatePropertyName("createDatePropertyName")
                        .addDefaultSearchPropertyName("string")
                        .deleted(true)
                        .fullyQualifiedName("fullyQualifiedName")
                        .hasCustomProperties(true)
                        .hasDefaultProperties(true)
                        .hasExternalObjectIds(true)
                        .hasOwners(true)
                        .hasPipelines(true)
                        .indexedForFiltersAndReports(true)
                        .lastModifiedPropertyName("lastModifiedPropertyName")
                        .metaType(
                            IntegratorSettingGetObjectDefinitionsByMediaTypeResponse.Schema.MetaType
                                .HUBSPOT
                        )
                        .metaTypeId(0)
                        .name("name")
                        .objectTypeId("objectTypeId")
                        .permissioningType("permissioningType")
                        .pipelinePropertyName("pipelinePropertyName")
                        .pipelineStagePropertyName("pipelineStagePropertyName")
                        .addRequiredProperty("string")
                        .restorable(true)
                        .addScopeMapping(
                            IntegratorSettingGetObjectDefinitionsByMediaTypeResponse.Schema
                                .ScopeMapping
                                .builder()
                                .accessLevel("accessLevel")
                                .requestAction("requestAction")
                                .scopeName("scopeName")
                                .build()
                        )
                        .addSecondaryDisplayLabelPropertyName("string")
                        .accessScopeName("accessScopeName")
                        .createdAt(0L)
                        .description("description")
                        .integrationAppId(0)
                        .janusGroup("janusGroup")
                        .ownerPortalId(0)
                        .pipelineCloseDatePropertyName("pipelineCloseDatePropertyName")
                        .pipelineTimeToClosePropertyName("pipelineTimeToClosePropertyName")
                        .pluralForm("pluralForm")
                        .primaryDisplayLabelPropertyName("primaryDisplayLabelPropertyName")
                        .readScopeName("readScopeName")
                        .singularForm("singularForm")
                        .status("status")
                        .visibility("visibility")
                        .writeScopeName("writeScopeName")
                        .build()
                )
                .build()

        assertThat(integratorSettingGetObjectDefinitionsByMediaTypeResponse.objectTypeId())
            .isEqualTo("objectTypeId")
        assertThat(integratorSettingGetObjectDefinitionsByMediaTypeResponse.objectTypeName())
            .isEqualTo("objectTypeName")
        assertThat(integratorSettingGetObjectDefinitionsByMediaTypeResponse.properties())
            .containsExactly(
                IntegratorSettingGetObjectDefinitionsByMediaTypeResponse.Property.builder()
                    .objectTypeId("objectTypeId")
                    .property(
                        Property.builder()
                            .description("")
                            .fieldType("select")
                            .groupName("my_object_information")
                            .label("My object property")
                            .name("my_object_property")
                            .addOption(
                                Option.builder()
                                    .description("Choice number one")
                                    .displayOrder(1)
                                    .doubleData(0.0)
                                    .hidden(false)
                                    .label("Option A")
                                    .readOnly(false)
                                    .value("A")
                                    .build()
                            )
                            .addOption(
                                Option.builder()
                                    .description("Choice number two")
                                    .displayOrder(2)
                                    .doubleData(0.0)
                                    .hidden(false)
                                    .label("Option B")
                                    .readOnly(false)
                                    .value("B")
                                    .build()
                            )
                            .type("enumeration")
                            .archived(false)
                            .archivedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .calculated(false)
                            .calculationFormula("")
                            .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .createdUserId("")
                            .dataSensitivity(Property.DataSensitivity.NON_SENSITIVE)
                            .displayOrder(2)
                            .externalOptions(false)
                            .formField(false)
                            .hasUniqueValue(false)
                            .hidden(false)
                            .hubspotDefined(false)
                            .modificationMetadata(
                                PropertyModificationMetadata.builder()
                                    .archivable(true)
                                    .readOnlyDefinition(false)
                                    .readOnlyValue(false)
                                    .readOnlyOptions(false)
                                    .build()
                            )
                            .referencedObjectType("")
                            .addSensitiveDataCategory("string")
                            .showCurrencySymbol(false)
                            .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .updatedUserId("updatedUserId")
                            .build()
                    )
                    .calculationExpression(
                        IntegratorSettingGetObjectDefinitionsByMediaTypeResponse.Property
                            .CalculationExpression
                            .CmsMediabridgeConstantBoolean
                            .builder()
                            .operator(
                                IntegratorSettingGetObjectDefinitionsByMediaTypeResponse.Property
                                    .CalculationExpression
                                    .CmsMediabridgeConstantBoolean
                                    .Operator
                                    .CONSTANT_BOOLEAN
                            )
                            .addInput(JsonValue.from(mapOf<String, Any>()))
                            .propertyName("propertyName")
                            .value(true)
                            .build()
                    )
                    .calculationFormula("calculationFormula")
                    .definitionSource(
                        IntegratorSettingGetObjectDefinitionsByMediaTypeResponse.Property
                            .DefinitionSource
                            .builder()
                            .type(
                                IntegratorSettingGetObjectDefinitionsByMediaTypeResponse.Property
                                    .DefinitionSource
                                    .Type
                                    .GLOBAL
                            )
                            .name("name")
                            .build()
                    )
                    .extensionData(
                        IntegratorSettingGetObjectDefinitionsByMediaTypeResponse.Property
                            .ExtensionData
                            .builder()
                            .extensionStatusMap(
                                IntegratorSettingGetObjectDefinitionsByMediaTypeResponse.Property
                                    .ExtensionData
                                    .ExtensionStatusMap
                                    .builder()
                                    .putAdditionalProperty("foo", JsonValue.from("string"))
                                    .build()
                            )
                            .addTag("string")
                            .caseChangeTestExtensionData(
                                IntegratorSettingGetObjectDefinitionsByMediaTypeResponse.Property
                                    .ExtensionData
                                    .CaseChangeTestExtensionData
                                    .builder()
                                    .mood("mood")
                                    .build()
                            )
                            .optionDecoratorsExtensionData(
                                IntegratorSettingGetObjectDefinitionsByMediaTypeResponse.Property
                                    .ExtensionData
                                    .OptionDecoratorsExtensionData
                                    .builder()
                                    .optionDecorators(
                                        IntegratorSettingGetObjectDefinitionsByMediaTypeResponse
                                            .Property
                                            .ExtensionData
                                            .OptionDecoratorsExtensionData
                                            .OptionDecorators
                                            .builder()
                                            .putAdditionalProperty(
                                                "foo",
                                                JsonValue.from(mapOf("color" to "color")),
                                            )
                                            .build()
                                    )
                                    .optionDecoratorStyle("optionDecoratorStyle")
                                    .build()
                            )
                            .requiredPropertiesExtensionData(
                                IntegratorSettingGetObjectDefinitionsByMediaTypeResponse.Property
                                    .ExtensionData
                                    .RequiredPropertiesExtensionData
                                    .builder()
                                    .isRequiredProperty(true)
                                    .build()
                            )
                            .softRequiredPropertiesExtensionData(
                                IntegratorSettingGetObjectDefinitionsByMediaTypeResponse.Property
                                    .ExtensionData
                                    .SoftRequiredPropertiesExtensionData
                                    .builder()
                                    .isSoftRequiredProperty(true)
                                    .build()
                            )
                            .build()
                    )
                    .externalOptionsMetaData(
                        IntegratorSettingGetObjectDefinitionsByMediaTypeResponse.Property
                            .ExternalOptionsMetaData
                            .builder()
                            .filter(
                                IntegratorSettingGetObjectDefinitionsByMediaTypeResponse.Property
                                    .ExternalOptionsMetaData
                                    .Filter
                                    .builder()
                                    .includeUnconfirmedUsers(true)
                                    .addPipelineId("string")
                                    .build()
                            )
                            .relatedObjectTypeId("relatedObjectTypeId")
                            .build()
                    )
                    .fulcrumPortalId(0)
                    .fulcrumTimestamp(0L)
                    .janusGroup("janusGroup")
                    .permission(
                        IntegratorSettingGetObjectDefinitionsByMediaTypeResponse.Property.Permission
                            .builder()
                            .accessLevel("accessLevel")
                            .build()
                    )
                    .propertyDefinitionSource(
                        IntegratorSettingGetObjectDefinitionsByMediaTypeResponse.Property
                            .PropertyDefinitionSource
                            .builder()
                            .type("type")
                            .name("name")
                            .build()
                    )
                    .propertyRequirements(
                        IntegratorSettingGetObjectDefinitionsByMediaTypeResponse.Property
                            .PropertyRequirements
                            .builder()
                            .addGate("string")
                            .operator(
                                IntegratorSettingGetObjectDefinitionsByMediaTypeResponse.Property
                                    .PropertyRequirements
                                    .Operator
                                    .AND
                            )
                            .addScopeName("string")
                            .addSetting("string")
                            .build()
                    )
                    .rollupExpression(
                        IntegratorSettingGetObjectDefinitionsByMediaTypeResponse.Property
                            .RollupExpression
                            .builder()
                            .addAssociationType(
                                AssociationSpec.builder()
                                    .associationCategory(
                                        AssociationSpec.AssociationCategory.HUBSPOT_DEFINED
                                    )
                                    .associationTypeId(0)
                                    .build()
                            )
                            .rollupOperator("rollupOperator")
                            .sourceObjectTypeId("sourceObjectTypeId")
                            .sourcePropertyName("sourcePropertyName")
                            .conditionalExpression(
                                IntegratorSettingGetObjectDefinitionsByMediaTypeResponse.Property
                                    .RollupExpression
                                    .ConditionalExpression
                                    .CmsMediabridgeConstantBoolean
                                    .builder()
                                    .operator(
                                        IntegratorSettingGetObjectDefinitionsByMediaTypeResponse
                                            .Property
                                            .RollupExpression
                                            .ConditionalExpression
                                            .CmsMediabridgeConstantBoolean
                                            .Operator
                                            .CONSTANT_BOOLEAN
                                    )
                                    .addInput(JsonValue.from(mapOf<String, Any>()))
                                    .propertyName("propertyName")
                                    .value(true)
                                    .build()
                            )
                            .conditionalFormula("conditionalFormula")
                            .emptyRollupValue("emptyRollupValue")
                            .sourceCompareByPropertyName("sourceCompareByPropertyName")
                            .build()
                    )
                    .build()
            )
        assertThat(integratorSettingGetObjectDefinitionsByMediaTypeResponse.propertyGroups())
            .containsExactly(
                IntegratorSettingGetObjectDefinitionsByMediaTypeResponse.PropertyGroup.builder()
                    .displayName("displayName")
                    .displayOrder(0)
                    .fulcrumPortalId(0)
                    .fulcrumTimestamp(0L)
                    .hubspotDefined(true)
                    .name("name")
                    .build()
            )
        assertThat(integratorSettingGetObjectDefinitionsByMediaTypeResponse.schema())
            .contains(
                IntegratorSettingGetObjectDefinitionsByMediaTypeResponse.Schema.builder()
                    .id(0)
                    .allowsSensitiveProperties(true)
                    .createDatePropertyName("createDatePropertyName")
                    .addDefaultSearchPropertyName("string")
                    .deleted(true)
                    .fullyQualifiedName("fullyQualifiedName")
                    .hasCustomProperties(true)
                    .hasDefaultProperties(true)
                    .hasExternalObjectIds(true)
                    .hasOwners(true)
                    .hasPipelines(true)
                    .indexedForFiltersAndReports(true)
                    .lastModifiedPropertyName("lastModifiedPropertyName")
                    .metaType(
                        IntegratorSettingGetObjectDefinitionsByMediaTypeResponse.Schema.MetaType
                            .HUBSPOT
                    )
                    .metaTypeId(0)
                    .name("name")
                    .objectTypeId("objectTypeId")
                    .permissioningType("permissioningType")
                    .pipelinePropertyName("pipelinePropertyName")
                    .pipelineStagePropertyName("pipelineStagePropertyName")
                    .addRequiredProperty("string")
                    .restorable(true)
                    .addScopeMapping(
                        IntegratorSettingGetObjectDefinitionsByMediaTypeResponse.Schema.ScopeMapping
                            .builder()
                            .accessLevel("accessLevel")
                            .requestAction("requestAction")
                            .scopeName("scopeName")
                            .build()
                    )
                    .addSecondaryDisplayLabelPropertyName("string")
                    .accessScopeName("accessScopeName")
                    .createdAt(0L)
                    .description("description")
                    .integrationAppId(0)
                    .janusGroup("janusGroup")
                    .ownerPortalId(0)
                    .pipelineCloseDatePropertyName("pipelineCloseDatePropertyName")
                    .pipelineTimeToClosePropertyName("pipelineTimeToClosePropertyName")
                    .pluralForm("pluralForm")
                    .primaryDisplayLabelPropertyName("primaryDisplayLabelPropertyName")
                    .readScopeName("readScopeName")
                    .singularForm("singularForm")
                    .status("status")
                    .visibility("visibility")
                    .writeScopeName("writeScopeName")
                    .build()
            )
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val integratorSettingGetObjectDefinitionsByMediaTypeResponse =
            IntegratorSettingGetObjectDefinitionsByMediaTypeResponse.builder()
                .objectTypeId("objectTypeId")
                .objectTypeName("objectTypeName")
                .addProperty(
                    IntegratorSettingGetObjectDefinitionsByMediaTypeResponse.Property.builder()
                        .objectTypeId("objectTypeId")
                        .property(
                            Property.builder()
                                .description("")
                                .fieldType("select")
                                .groupName("my_object_information")
                                .label("My object property")
                                .name("my_object_property")
                                .addOption(
                                    Option.builder()
                                        .description("Choice number one")
                                        .displayOrder(1)
                                        .doubleData(0.0)
                                        .hidden(false)
                                        .label("Option A")
                                        .readOnly(false)
                                        .value("A")
                                        .build()
                                )
                                .addOption(
                                    Option.builder()
                                        .description("Choice number two")
                                        .displayOrder(2)
                                        .doubleData(0.0)
                                        .hidden(false)
                                        .label("Option B")
                                        .readOnly(false)
                                        .value("B")
                                        .build()
                                )
                                .type("enumeration")
                                .archived(false)
                                .archivedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .calculated(false)
                                .calculationFormula("")
                                .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .createdUserId("")
                                .dataSensitivity(Property.DataSensitivity.NON_SENSITIVE)
                                .displayOrder(2)
                                .externalOptions(false)
                                .formField(false)
                                .hasUniqueValue(false)
                                .hidden(false)
                                .hubspotDefined(false)
                                .modificationMetadata(
                                    PropertyModificationMetadata.builder()
                                        .archivable(true)
                                        .readOnlyDefinition(false)
                                        .readOnlyValue(false)
                                        .readOnlyOptions(false)
                                        .build()
                                )
                                .referencedObjectType("")
                                .addSensitiveDataCategory("string")
                                .showCurrencySymbol(false)
                                .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .updatedUserId("updatedUserId")
                                .build()
                        )
                        .calculationExpression(
                            IntegratorSettingGetObjectDefinitionsByMediaTypeResponse.Property
                                .CalculationExpression
                                .CmsMediabridgeConstantBoolean
                                .builder()
                                .operator(
                                    IntegratorSettingGetObjectDefinitionsByMediaTypeResponse
                                        .Property
                                        .CalculationExpression
                                        .CmsMediabridgeConstantBoolean
                                        .Operator
                                        .CONSTANT_BOOLEAN
                                )
                                .addInput(JsonValue.from(mapOf<String, Any>()))
                                .propertyName("propertyName")
                                .value(true)
                                .build()
                        )
                        .calculationFormula("calculationFormula")
                        .definitionSource(
                            IntegratorSettingGetObjectDefinitionsByMediaTypeResponse.Property
                                .DefinitionSource
                                .builder()
                                .type(
                                    IntegratorSettingGetObjectDefinitionsByMediaTypeResponse
                                        .Property
                                        .DefinitionSource
                                        .Type
                                        .GLOBAL
                                )
                                .name("name")
                                .build()
                        )
                        .extensionData(
                            IntegratorSettingGetObjectDefinitionsByMediaTypeResponse.Property
                                .ExtensionData
                                .builder()
                                .extensionStatusMap(
                                    IntegratorSettingGetObjectDefinitionsByMediaTypeResponse
                                        .Property
                                        .ExtensionData
                                        .ExtensionStatusMap
                                        .builder()
                                        .putAdditionalProperty("foo", JsonValue.from("string"))
                                        .build()
                                )
                                .addTag("string")
                                .caseChangeTestExtensionData(
                                    IntegratorSettingGetObjectDefinitionsByMediaTypeResponse
                                        .Property
                                        .ExtensionData
                                        .CaseChangeTestExtensionData
                                        .builder()
                                        .mood("mood")
                                        .build()
                                )
                                .optionDecoratorsExtensionData(
                                    IntegratorSettingGetObjectDefinitionsByMediaTypeResponse
                                        .Property
                                        .ExtensionData
                                        .OptionDecoratorsExtensionData
                                        .builder()
                                        .optionDecorators(
                                            IntegratorSettingGetObjectDefinitionsByMediaTypeResponse
                                                .Property
                                                .ExtensionData
                                                .OptionDecoratorsExtensionData
                                                .OptionDecorators
                                                .builder()
                                                .putAdditionalProperty(
                                                    "foo",
                                                    JsonValue.from(mapOf("color" to "color")),
                                                )
                                                .build()
                                        )
                                        .optionDecoratorStyle("optionDecoratorStyle")
                                        .build()
                                )
                                .requiredPropertiesExtensionData(
                                    IntegratorSettingGetObjectDefinitionsByMediaTypeResponse
                                        .Property
                                        .ExtensionData
                                        .RequiredPropertiesExtensionData
                                        .builder()
                                        .isRequiredProperty(true)
                                        .build()
                                )
                                .softRequiredPropertiesExtensionData(
                                    IntegratorSettingGetObjectDefinitionsByMediaTypeResponse
                                        .Property
                                        .ExtensionData
                                        .SoftRequiredPropertiesExtensionData
                                        .builder()
                                        .isSoftRequiredProperty(true)
                                        .build()
                                )
                                .build()
                        )
                        .externalOptionsMetaData(
                            IntegratorSettingGetObjectDefinitionsByMediaTypeResponse.Property
                                .ExternalOptionsMetaData
                                .builder()
                                .filter(
                                    IntegratorSettingGetObjectDefinitionsByMediaTypeResponse
                                        .Property
                                        .ExternalOptionsMetaData
                                        .Filter
                                        .builder()
                                        .includeUnconfirmedUsers(true)
                                        .addPipelineId("string")
                                        .build()
                                )
                                .relatedObjectTypeId("relatedObjectTypeId")
                                .build()
                        )
                        .fulcrumPortalId(0)
                        .fulcrumTimestamp(0L)
                        .janusGroup("janusGroup")
                        .permission(
                            IntegratorSettingGetObjectDefinitionsByMediaTypeResponse.Property
                                .Permission
                                .builder()
                                .accessLevel("accessLevel")
                                .build()
                        )
                        .propertyDefinitionSource(
                            IntegratorSettingGetObjectDefinitionsByMediaTypeResponse.Property
                                .PropertyDefinitionSource
                                .builder()
                                .type("type")
                                .name("name")
                                .build()
                        )
                        .propertyRequirements(
                            IntegratorSettingGetObjectDefinitionsByMediaTypeResponse.Property
                                .PropertyRequirements
                                .builder()
                                .addGate("string")
                                .operator(
                                    IntegratorSettingGetObjectDefinitionsByMediaTypeResponse
                                        .Property
                                        .PropertyRequirements
                                        .Operator
                                        .AND
                                )
                                .addScopeName("string")
                                .addSetting("string")
                                .build()
                        )
                        .rollupExpression(
                            IntegratorSettingGetObjectDefinitionsByMediaTypeResponse.Property
                                .RollupExpression
                                .builder()
                                .addAssociationType(
                                    AssociationSpec.builder()
                                        .associationCategory(
                                            AssociationSpec.AssociationCategory.HUBSPOT_DEFINED
                                        )
                                        .associationTypeId(0)
                                        .build()
                                )
                                .rollupOperator("rollupOperator")
                                .sourceObjectTypeId("sourceObjectTypeId")
                                .sourcePropertyName("sourcePropertyName")
                                .conditionalExpression(
                                    IntegratorSettingGetObjectDefinitionsByMediaTypeResponse
                                        .Property
                                        .RollupExpression
                                        .ConditionalExpression
                                        .CmsMediabridgeConstantBoolean
                                        .builder()
                                        .operator(
                                            IntegratorSettingGetObjectDefinitionsByMediaTypeResponse
                                                .Property
                                                .RollupExpression
                                                .ConditionalExpression
                                                .CmsMediabridgeConstantBoolean
                                                .Operator
                                                .CONSTANT_BOOLEAN
                                        )
                                        .addInput(JsonValue.from(mapOf<String, Any>()))
                                        .propertyName("propertyName")
                                        .value(true)
                                        .build()
                                )
                                .conditionalFormula("conditionalFormula")
                                .emptyRollupValue("emptyRollupValue")
                                .sourceCompareByPropertyName("sourceCompareByPropertyName")
                                .build()
                        )
                        .build()
                )
                .addPropertyGroup(
                    IntegratorSettingGetObjectDefinitionsByMediaTypeResponse.PropertyGroup.builder()
                        .displayName("displayName")
                        .displayOrder(0)
                        .fulcrumPortalId(0)
                        .fulcrumTimestamp(0L)
                        .hubspotDefined(true)
                        .name("name")
                        .build()
                )
                .schema(
                    IntegratorSettingGetObjectDefinitionsByMediaTypeResponse.Schema.builder()
                        .id(0)
                        .allowsSensitiveProperties(true)
                        .createDatePropertyName("createDatePropertyName")
                        .addDefaultSearchPropertyName("string")
                        .deleted(true)
                        .fullyQualifiedName("fullyQualifiedName")
                        .hasCustomProperties(true)
                        .hasDefaultProperties(true)
                        .hasExternalObjectIds(true)
                        .hasOwners(true)
                        .hasPipelines(true)
                        .indexedForFiltersAndReports(true)
                        .lastModifiedPropertyName("lastModifiedPropertyName")
                        .metaType(
                            IntegratorSettingGetObjectDefinitionsByMediaTypeResponse.Schema.MetaType
                                .HUBSPOT
                        )
                        .metaTypeId(0)
                        .name("name")
                        .objectTypeId("objectTypeId")
                        .permissioningType("permissioningType")
                        .pipelinePropertyName("pipelinePropertyName")
                        .pipelineStagePropertyName("pipelineStagePropertyName")
                        .addRequiredProperty("string")
                        .restorable(true)
                        .addScopeMapping(
                            IntegratorSettingGetObjectDefinitionsByMediaTypeResponse.Schema
                                .ScopeMapping
                                .builder()
                                .accessLevel("accessLevel")
                                .requestAction("requestAction")
                                .scopeName("scopeName")
                                .build()
                        )
                        .addSecondaryDisplayLabelPropertyName("string")
                        .accessScopeName("accessScopeName")
                        .createdAt(0L)
                        .description("description")
                        .integrationAppId(0)
                        .janusGroup("janusGroup")
                        .ownerPortalId(0)
                        .pipelineCloseDatePropertyName("pipelineCloseDatePropertyName")
                        .pipelineTimeToClosePropertyName("pipelineTimeToClosePropertyName")
                        .pluralForm("pluralForm")
                        .primaryDisplayLabelPropertyName("primaryDisplayLabelPropertyName")
                        .readScopeName("readScopeName")
                        .singularForm("singularForm")
                        .status("status")
                        .visibility("visibility")
                        .writeScopeName("writeScopeName")
                        .build()
                )
                .build()

        val roundtrippedIntegratorSettingGetObjectDefinitionsByMediaTypeResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(
                    integratorSettingGetObjectDefinitionsByMediaTypeResponse
                ),
                jacksonTypeRef<IntegratorSettingGetObjectDefinitionsByMediaTypeResponse>(),
            )

        assertThat(roundtrippedIntegratorSettingGetObjectDefinitionsByMediaTypeResponse)
            .isEqualTo(integratorSettingGetObjectDefinitionsByMediaTypeResponse)
    }
}
