// File generated from our OpenAPI spec by Stainless.

package com.hubspot.models.marketing.campaigns

import com.fasterxml.jackson.annotation.JsonAnyGetter
import com.fasterxml.jackson.annotation.JsonAnySetter
import com.fasterxml.jackson.annotation.JsonCreator
import com.fasterxml.jackson.annotation.JsonProperty
import com.hubspot.core.ExcludeMissing
import com.hubspot.core.JsonField
import com.hubspot.core.JsonMissing
import com.hubspot.core.JsonValue
import com.hubspot.core.checkRequired
import com.hubspot.errors.HubSpotInvalidDataException
import java.util.Collections
import java.util.Objects

class MetricsCounters
@JsonCreator(mode = JsonCreator.Mode.DISABLED)
private constructor(
    private val influencedContacts: JsonField<Int>,
    private val newContactsFirstTouch: JsonField<Int>,
    private val newContactsLastTouch: JsonField<Int>,
    private val sessions: JsonField<Int>,
    private val additionalProperties: MutableMap<String, JsonValue>,
) {

    @JsonCreator
    private constructor(
        @JsonProperty("influencedContacts")
        @ExcludeMissing
        influencedContacts: JsonField<Int> = JsonMissing.of(),
        @JsonProperty("newContactsFirstTouch")
        @ExcludeMissing
        newContactsFirstTouch: JsonField<Int> = JsonMissing.of(),
        @JsonProperty("newContactsLastTouch")
        @ExcludeMissing
        newContactsLastTouch: JsonField<Int> = JsonMissing.of(),
        @JsonProperty("sessions") @ExcludeMissing sessions: JsonField<Int> = JsonMissing.of(),
    ) : this(
        influencedContacts,
        newContactsFirstTouch,
        newContactsLastTouch,
        sessions,
        mutableMapOf(),
    )

    /**
     * The number of contacts influenced by the campaign.
     *
     * @throws HubSpotInvalidDataException if the JSON field has an unexpected type or is
     *   unexpectedly missing or null (e.g. if the server responded with an unexpected value).
     */
    fun influencedContacts(): Int = influencedContacts.getRequired("influencedContacts")

    /**
     * The number of new contacts attributed to the campaign as the first touchpoint.
     *
     * @throws HubSpotInvalidDataException if the JSON field has an unexpected type or is
     *   unexpectedly missing or null (e.g. if the server responded with an unexpected value).
     */
    fun newContactsFirstTouch(): Int = newContactsFirstTouch.getRequired("newContactsFirstTouch")

    /**
     * The number of new contacts attributed to the campaign as the last touchpoint.
     *
     * @throws HubSpotInvalidDataException if the JSON field has an unexpected type or is
     *   unexpectedly missing or null (e.g. if the server responded with an unexpected value).
     */
    fun newContactsLastTouch(): Int = newContactsLastTouch.getRequired("newContactsLastTouch")

    /**
     * The total number of sessions generated by the campaign.
     *
     * @throws HubSpotInvalidDataException if the JSON field has an unexpected type or is
     *   unexpectedly missing or null (e.g. if the server responded with an unexpected value).
     */
    fun sessions(): Int = sessions.getRequired("sessions")

    /**
     * Returns the raw JSON value of [influencedContacts].
     *
     * Unlike [influencedContacts], this method doesn't throw if the JSON field has an unexpected
     * type.
     */
    @JsonProperty("influencedContacts")
    @ExcludeMissing
    fun _influencedContacts(): JsonField<Int> = influencedContacts

    /**
     * Returns the raw JSON value of [newContactsFirstTouch].
     *
     * Unlike [newContactsFirstTouch], this method doesn't throw if the JSON field has an unexpected
     * type.
     */
    @JsonProperty("newContactsFirstTouch")
    @ExcludeMissing
    fun _newContactsFirstTouch(): JsonField<Int> = newContactsFirstTouch

    /**
     * Returns the raw JSON value of [newContactsLastTouch].
     *
     * Unlike [newContactsLastTouch], this method doesn't throw if the JSON field has an unexpected
     * type.
     */
    @JsonProperty("newContactsLastTouch")
    @ExcludeMissing
    fun _newContactsLastTouch(): JsonField<Int> = newContactsLastTouch

    /**
     * Returns the raw JSON value of [sessions].
     *
     * Unlike [sessions], this method doesn't throw if the JSON field has an unexpected type.
     */
    @JsonProperty("sessions") @ExcludeMissing fun _sessions(): JsonField<Int> = sessions

    @JsonAnySetter
    private fun putAdditionalProperty(key: String, value: JsonValue) {
        additionalProperties.put(key, value)
    }

    @JsonAnyGetter
    @ExcludeMissing
    fun _additionalProperties(): Map<String, JsonValue> =
        Collections.unmodifiableMap(additionalProperties)

    fun toBuilder() = Builder().from(this)

    companion object {

        /**
         * Returns a mutable builder for constructing an instance of [MetricsCounters].
         *
         * The following fields are required:
         * ```java
         * .influencedContacts()
         * .newContactsFirstTouch()
         * .newContactsLastTouch()
         * .sessions()
         * ```
         */
        @JvmStatic fun builder() = Builder()
    }

    /** A builder for [MetricsCounters]. */
    class Builder internal constructor() {

        private var influencedContacts: JsonField<Int>? = null
        private var newContactsFirstTouch: JsonField<Int>? = null
        private var newContactsLastTouch: JsonField<Int>? = null
        private var sessions: JsonField<Int>? = null
        private var additionalProperties: MutableMap<String, JsonValue> = mutableMapOf()

        @JvmSynthetic
        internal fun from(metricsCounters: MetricsCounters) = apply {
            influencedContacts = metricsCounters.influencedContacts
            newContactsFirstTouch = metricsCounters.newContactsFirstTouch
            newContactsLastTouch = metricsCounters.newContactsLastTouch
            sessions = metricsCounters.sessions
            additionalProperties = metricsCounters.additionalProperties.toMutableMap()
        }

        /** The number of contacts influenced by the campaign. */
        fun influencedContacts(influencedContacts: Int) =
            influencedContacts(JsonField.of(influencedContacts))

        /**
         * Sets [Builder.influencedContacts] to an arbitrary JSON value.
         *
         * You should usually call [Builder.influencedContacts] with a well-typed [Int] value
         * instead. This method is primarily for setting the field to an undocumented or not yet
         * supported value.
         */
        fun influencedContacts(influencedContacts: JsonField<Int>) = apply {
            this.influencedContacts = influencedContacts
        }

        /** The number of new contacts attributed to the campaign as the first touchpoint. */
        fun newContactsFirstTouch(newContactsFirstTouch: Int) =
            newContactsFirstTouch(JsonField.of(newContactsFirstTouch))

        /**
         * Sets [Builder.newContactsFirstTouch] to an arbitrary JSON value.
         *
         * You should usually call [Builder.newContactsFirstTouch] with a well-typed [Int] value
         * instead. This method is primarily for setting the field to an undocumented or not yet
         * supported value.
         */
        fun newContactsFirstTouch(newContactsFirstTouch: JsonField<Int>) = apply {
            this.newContactsFirstTouch = newContactsFirstTouch
        }

        /** The number of new contacts attributed to the campaign as the last touchpoint. */
        fun newContactsLastTouch(newContactsLastTouch: Int) =
            newContactsLastTouch(JsonField.of(newContactsLastTouch))

        /**
         * Sets [Builder.newContactsLastTouch] to an arbitrary JSON value.
         *
         * You should usually call [Builder.newContactsLastTouch] with a well-typed [Int] value
         * instead. This method is primarily for setting the field to an undocumented or not yet
         * supported value.
         */
        fun newContactsLastTouch(newContactsLastTouch: JsonField<Int>) = apply {
            this.newContactsLastTouch = newContactsLastTouch
        }

        /** The total number of sessions generated by the campaign. */
        fun sessions(sessions: Int) = sessions(JsonField.of(sessions))

        /**
         * Sets [Builder.sessions] to an arbitrary JSON value.
         *
         * You should usually call [Builder.sessions] with a well-typed [Int] value instead. This
         * method is primarily for setting the field to an undocumented or not yet supported value.
         */
        fun sessions(sessions: JsonField<Int>) = apply { this.sessions = sessions }

        fun additionalProperties(additionalProperties: Map<String, JsonValue>) = apply {
            this.additionalProperties.clear()
            putAllAdditionalProperties(additionalProperties)
        }

        fun putAdditionalProperty(key: String, value: JsonValue) = apply {
            additionalProperties.put(key, value)
        }

        fun putAllAdditionalProperties(additionalProperties: Map<String, JsonValue>) = apply {
            this.additionalProperties.putAll(additionalProperties)
        }

        fun removeAdditionalProperty(key: String) = apply { additionalProperties.remove(key) }

        fun removeAllAdditionalProperties(keys: Set<String>) = apply {
            keys.forEach(::removeAdditionalProperty)
        }

        /**
         * Returns an immutable instance of [MetricsCounters].
         *
         * Further updates to this [Builder] will not mutate the returned instance.
         *
         * The following fields are required:
         * ```java
         * .influencedContacts()
         * .newContactsFirstTouch()
         * .newContactsLastTouch()
         * .sessions()
         * ```
         *
         * @throws IllegalStateException if any required field is unset.
         */
        fun build(): MetricsCounters =
            MetricsCounters(
                checkRequired("influencedContacts", influencedContacts),
                checkRequired("newContactsFirstTouch", newContactsFirstTouch),
                checkRequired("newContactsLastTouch", newContactsLastTouch),
                checkRequired("sessions", sessions),
                additionalProperties.toMutableMap(),
            )
    }

    private var validated: Boolean = false

    fun validate(): MetricsCounters = apply {
        if (validated) {
            return@apply
        }

        influencedContacts()
        newContactsFirstTouch()
        newContactsLastTouch()
        sessions()
        validated = true
    }

    fun isValid(): Boolean =
        try {
            validate()
            true
        } catch (e: HubSpotInvalidDataException) {
            false
        }

    /**
     * Returns a score indicating how many valid values are contained in this object recursively.
     *
     * Used for best match union deserialization.
     */
    @JvmSynthetic
    internal fun validity(): Int =
        (if (influencedContacts.asKnown().isPresent) 1 else 0) +
            (if (newContactsFirstTouch.asKnown().isPresent) 1 else 0) +
            (if (newContactsLastTouch.asKnown().isPresent) 1 else 0) +
            (if (sessions.asKnown().isPresent) 1 else 0)

    override fun equals(other: Any?): Boolean {
        if (this === other) {
            return true
        }

        return other is MetricsCounters &&
            influencedContacts == other.influencedContacts &&
            newContactsFirstTouch == other.newContactsFirstTouch &&
            newContactsLastTouch == other.newContactsLastTouch &&
            sessions == other.sessions &&
            additionalProperties == other.additionalProperties
    }

    private val hashCode: Int by lazy {
        Objects.hash(
            influencedContacts,
            newContactsFirstTouch,
            newContactsLastTouch,
            sessions,
            additionalProperties,
        )
    }

    override fun hashCode(): Int = hashCode

    override fun toString() =
        "MetricsCounters{influencedContacts=$influencedContacts, newContactsFirstTouch=$newContactsFirstTouch, newContactsLastTouch=$newContactsLastTouch, sessions=$sessions, additionalProperties=$additionalProperties}"
}
